import {
  GETIR_10_DOMAIN_TYPE,
  GETIR_FOOD_DOMAIN_TYPE,
  GETIR_MARKET_DOMAIN_TYPE,
  GETIR_VOYAGER_DOMAIN_TYPE,
  GETIR_MARKET_CHECKOUT_ERROR_CODE,
} from '@shared/shared/constants';

export const FAILED_ORDER_CODES = [
  GETIR_MARKET_CHECKOUT_ERROR_CODE.OTHER,
  GETIR_MARKET_CHECKOUT_ERROR_CODE.UNKNOWN_ERROR,
  GETIR_MARKET_CHECKOUT_ERROR_CODE.MINIMUM_AMOUNT_ERROR,
  GETIR_MARKET_CHECKOUT_ERROR_CODE.COURIER_UNAVAILABLE_ERROR,
  GETIR_MARKET_CHECKOUT_ERROR_CODE.COURIER_UNAVAILABLE_SLOTTED_ERROR,
  GETIR_MARKET_CHECKOUT_ERROR_CODE.PAYMENT_FAILED,
];

export const FINANCIAL_ERROR_CODES = [
  GETIR_MARKET_CHECKOUT_ERROR_CODE.OTHER,
  GETIR_MARKET_CHECKOUT_ERROR_CODE.UNKNOWN_ERROR,
  GETIR_MARKET_CHECKOUT_ERROR_CODE.MINIMUM_AMOUNT_ERROR,
  GETIR_MARKET_CHECKOUT_ERROR_CODE.PAYMENT_FAILED,
];

export const DOMAIN_TYPE_Z_INDEX_IDENTIFIERS = {
  [GETIR_10_DOMAIN_TYPE]: 'G10',
  [GETIR_MARKET_DOMAIN_TYPE]: 'G30',
  [GETIR_FOOD_DOMAIN_TYPE]: 'FOOD',
  [GETIR_VOYAGER_DOMAIN_TYPE]: 'VOYAGER',
};
