export const LIVE_MAP_EVENTS = {
  FILTERED: 'Market LiveMap - Filtered',
  WAREHOUSE: {
    SEARCH: 'Market LiveMap - Warehouse Searched',
    NAME: 'Warehouse',
  },
  MARKER: { CLICK: 'Market LiveMap - Marker Clicked' },
  BUTTON_CLICK: 'Market LiveMap - Button Clicked',
  EVENT_PANEL: {
    WAREHOUSE_DETAIL_CLICK: 'Panel Warehouse Detail',
    COURIER_ORDER_CLICK: 'Panel Order',
    CANCEL_CLICK: 'Panel Cancel',
    COURIER_DETAIL_CLICK: 'Panel Courier Detail',
  },
  COURIER_COUNTS_TABLE: {
    BUSY_WAREHOUSE_CLICK: 'Busy Wh',
    city: 'City Courier',
    country: 'Country Courier',
    WAREHOUSE_UNDER_COURIER_PLAN_CLICK: 'Wh Under Courier P.',
    COLLAPSE: 'Collapse',
    NAME: 'Courier Stats Panel',
  },
  ORDER_STATS_PANEL: { COLLAPSE: 'Collapse', NAME: 'Order Stats Panel' },
  COURIER_TYPES: {
    NAME: 'Courier Type',
    showEBicycleCouriers: 'Courier T. - E-Bike',
    showEMotorcycleCouriers: 'Courier T. - E-Moto',
    showMotoCouriers: 'Courier T. - Moto',
    showCarCouriers: 'Courier T. - Car',
    showMiTuCouriers: 'Courier T. - Mitu',
    showOnFootCouriers: 'Courier T. - On Foot',
    showECarCouriers: 'Courier T. - Test',
    showBusyCouriers: 'Courier T. - Busy',
    DELETE: 'Courier T. - Delete',
  },
  POLYGON_TYPES_BY_ENUM: {
    '1-1': 'G10 - Sub region',
    '3-1': 'GM - Sub region',
    '4-1': 'GW - Sub region',
    '1-9': 'G10 - Ext. Sub region',
    '3-9': 'GM - Ext. Sub region',
    '4-9': 'Gw - Ext. Sub region',
  },
};
