import { CLIENT_APP_ACTION_TYPE } from '@shared/containers/Marketing/ClientAppActions/constants';

export const BANNER_STATUS = {
  INACTIVE: 1,
  ACTIVE: 2,
};

export const PROCESS_STATUS = {
  CREATED: 1,
  PRE_PROCESS: 2, // IN PROGRESS
  READY: 3,
  IN_PROCESS: 4, // SENDING
  FINISHED: 5,
  CANCEL: 6,
  FAIL: 7,
};

export const FILE_UPLOAD_STATE_KEY = { BANNER_CONTENT_IMAGE: 'bannerContentImage' };

export const BANNER_ACTIONS = {
  DETAIL: 'DETAIL',
  DUPLICATE: 'DUPLICATE',
  CANCEL: 'CANCEL',
};

export const BANNER_TYPE = {
  DEFAULT: 1,
  PROMO_PAGE: 2,
  ADVERT: 3,
};

export const COMPONENT_TYPE = {
  MINI: 1,
  STANDARD: 2,
  MAXI: 3,
  DYNAMIC_CARD: 4,
  GAME_COMPONENT: 5,
};

export const BANNER_COMPONENT_IMAGE_SIZE = {
  [COMPONENT_TYPE.MAXI]: { width: 1125, height: 702 },
  [COMPONENT_TYPE.STANDARD]: { width: 1124, height: 562 },
  [COMPONENT_TYPE.MINI]: { width: 1029, height: 258 },
  [COMPONENT_TYPE.DYNAMIC_CARD]: { width: 192, height: 192 },
};

export const INACTIVE_ACTIONS = [
  CLIENT_APP_ACTION_TYPE.OPEN_APP,
  CLIENT_APP_ACTION_TYPE.ADD_TO_BASKET,
  CLIENT_APP_ACTION_TYPE.PHONE_CALL,
  CLIENT_APP_ACTION_TYPE.LOYALTY_DETAIL,
  CLIENT_APP_ACTION_TYPE.RESTAURANT_LIST,
  CLIENT_APP_ACTION_TYPE.RESTAURANT_PRODUCT,
  CLIENT_APP_ACTION_TYPE.RESTAURANT_FILTER,
  CLIENT_APP_ACTION_TYPE.FOOD_ORDER_LIST,
  CLIENT_APP_ACTION_TYPE.ARTISAN_LOYALTY_DETAIL,
  CLIENT_APP_ACTION_TYPE.GIVEAWAY_EVENT,
  CLIENT_APP_ACTION_TYPE.WATER_PRODUCT_LIST,
  CLIENT_APP_ACTION_TYPE.WATER_PRODUCT,
  CLIENT_APP_ACTION_TYPE.N11_REDIRECT_URL,
];
