import {
  targetListValues,
  promoTypes,
  typeListValues,
  redirectToListValues,
  platformListValues,
  buttonActionTypeListValues,
} from '../../../constants';

export const defaultValues = {
  target: targetListValues.GETIRWATER_MARKETPLACE,
  promoType: promoTypes.DISCOUNT,
  titleTr: '',
  titleEn: '',
  descriptionTr: '',
  descriptionEn: '',
  accessibilityLabelTr: '',
  accessibilityLabelEn: '',
  bannerActionType: typeListValues.PROMO_DETAIL,
  bannerRedirectTo: redirectToListValues.PROMO_DETAIL,
  buttonActionType: buttonActionTypeListValues.BRAND_PAGE,
  priority: 5000,
  isShowOnlyLocalNumbers: true,
  isBannerEnabled: false,
  status: false,
  color: '#000000',
  platforms: [platformListValues.IOS, platformListValues.Android],
};

export const validationSchema = {
  target: [{ required: true }],
  promoType: [{ required: true }],
  code: [{ required: true }],
  maxOrderCount: [{ required: false }],
  campaignPriority: [{ required: true }],
  color: [{ required: true }],
  titleTr: [{ required: true }],
  titleEn: [{ required: true }],
  getDynamicTitleValidator: isButtonActionEnabled => {
    const rules = [{ required: isButtonActionEnabled, max: 20 }];
    return {
      titleTr: rules,
      titleEn: rules,
    };
  },
  getDynamicRedirectToValidator: isButtonActionEnabled => [{ required: isButtonActionEnabled }],
  distributionTypes: [{ required: true }],
  descriptionTr: [{ required: true }],
  descriptionEn: [{ required: true }],
  accessibilityLabelTr: [{ required: true }],
  accessibilityLabelEn: [{ required: true }],
  pictureUrlTR: [{ required: true }],
  pictureUrlEN: [{ required: true }],
  thumbnailUrlTR: [{ required: true }],
  thumbnailUrlEN: [{ required: true }],
  promoUrlTr: [{ required: false }],
  promoUrlEn: [{ required: false }],
  promoContentHTMLTr: [{ required: true }],
  promoContentHTMLEn: [{ required: true }],
  promoPageTitleTr: [{ required: true }],
  promoPageTitleEn: [{ required: true }],
  promoContentUrlTr: [{ required: false }],
  promoContentUrlEn: [{ required: false }],
  promoContentSectionTitleTr: [{ required: true }],
  promoContentSectionTitleEn: [{ required: true }],
  products: [{ required: true }],
  maxItemCount: [{ required: false }],
  discountTotalAmount: [{ required: true }],
  minOrderAmount: [{ required: false }],
  maxOrderAmount: [{ required: false }],
  totalUsageLimit: [{ required: false }],
  excludeProducts: [{ required: true }],
  dailyUsageLimit: [{ required: false }],
  brandIds: [{ required: true }],
  minNumberOfPreviousGWaterMPOrder: [{ required: false }],
  maxNumberOfPreviousGWaterMPOrder: [{ required: false }],
  minNumberOfPreviousG10Order: [{ required: false }],
  maxNumberOfPreviousG10Order: [{ required: false }],
  paymentMethods: [{ required: true }],
  exceptForPromotionAbusives: [{ required: false }],
  platforms: [{ required: true }],
  isShowOnlyLocalNumbers: [{ required: false }],
  startDate: [{ required: true }],
  endDate: [{ required: true }],
  cityIds: [{ required: true }],
  vendorIds: [{ required: true }],
};
