import { createUseStyles } from 'react-jss';

export default createUseStyles({
  collapseContainer: {
    top: '30px',
    right: 0,
    position: 'fixed',
    width: '301px',
    borderRadius: '5px',
    backgroundColor: '#f5f5f5',
  },
  courierCountsContainer: {
    width: '300px',
    borderRadius: '5px',
    right: 0,
    position: 'fixed',
    top: '75px',
    zIndex: '200',
  },
  courierCountsWrapper: {
    background: '#f5f5f5',
    overflow: 'scroll',
    overflowX: 'hidden',
    maxHeight: '501px !important',
    '& > table tr td:first-child': {
      width: '37%',
      textAlign: 'left',
      paddingLeft: '5px',
    },
    '& > table tr td': {
      width: '24px',
      fontSize: '11px',
      textAlign: 'right',
    },
    '& > table tr td:nth-child(3)': { color: 'green' },
    '& > table tr td:nth-child(4)': { color: '#5D3EBC' },
    '& > table tr td.busy': { color: 'red' },
    '& > table tr td.util': { color: '#1BD5DE' },
  },
  rowName: {
    fontWeight: 'bold',
    fontSize: '12px',
  },
  warehouseName: {
    maxWidth: '60px',
    overflowX: 'hidden',
    '&:hover': { overflowX: 'scroll' },
  },
  searchBox: {
    border: '1px solid #eaeff0',
    width: 'calc(100% - 1rem)',
    margin: '0.25rem',
    fontSize: '12px',
    borderRadius: '5px',
  },
  parentTableRow: { borderBottom: '1px solid #eaeff0' },
  expandedRow: {
    padding: '0.25rem',
    border: '1px solid #ccc',
  },
  expandedTable: {
    width: '100%',
    minHeight: 'auto',
    maxHeight: '140px',
    overflowY: 'scroll',
    display: 'block',
    '& > tbody': { width: '100%' },
  },
  domainFilterButtons: {
    borderRadius: '8px',
    fontSize: '11px',
  },
  domainFilterWrapper: {
    width: '100%',
    display: 'flex',
    padding: '2px',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  vehicleFilterWrapper: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    borderTop: '1px solid #eaeff0',
    '& > span': { fontSize: '11px' },
  },
  vehicleFilterButtonsWrapper: {
    width: '100%',
    display: 'flex',
    padding: '2px',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  vehicleFilterButtons: {
    borderRadius: '8px',
    fontSize: '11px',
  },
  courierFilterWrapper: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    borderTop: '1px solid #eaeff0',
    '& > span': { fontSize: '11px' },
  },
  courierFilterButtonsWrapper: {
    width: '100%',
    display: 'flex',
    padding: '2px',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  courierFilterButtons: {
    borderRadius: '8px',
    fontSize: '11px',
  },
  filtersSpan: {
    textAlign: 'left',
    fontSize: '10px',
    display: 'block',
    fontWeight: 'bold',
    padding: '5px',
    borderBottom: '1px solid #eaeff0',
  },
  subFilterText: {
    textAlign: 'center',
    fontSize: '11px',
    display: 'block',
    paddingLeft: '7px',
  },
  customizeHr: { margin: '0 !important' },
});
