import { createUseStyles } from 'react-jss';

export default createUseStyles(() => {
  return {
    justifyContentStart: { justifyContent: 'flex-start' },
    justifyContentEnd: { justifyContent: 'flex-end' },
    boldCenterBlack: {
      fontWeight: 'bold',
      textAlign: 'center',
      color: 'black',
    },
    categorySelect: {
      width: '200px',
      height: '32px !important',
    },
    filterWrapper: {
      width: '21vh !important',
      display: 'flex',
      flexDirection: 'column',
      marginBottom: '5px',
    },
    priceDiv: {
      margin: '0',
      width: '170px',
      fontWeight: 600,
      fontSize: '1.3vh',
    },
    discountedDiv: {
      margin: '0',
      width: '150px',
      fontWeight: 600,
    },
    guardrailFailContent: {
      display: 'flex',
      justifyContent: 'center',
      flexDirection: 'column',
      alignItems: 'center',
    },
    widthHeightvh: {
      width: '15px',
      height: '15px',
    },
    setStruckPriceDiv: {
      margin: '0',
      width: '150px',
      fontWeight: 600,
    },
    elasticTable: {
      '& .ant-table-title': { height: '75px' },
      '& .ant-btn': { transition: 'all 0.01s cubic-bezier(0.645, 0.045, 0.355, 1) !important' },
    },
    excelExportFilter: {
      position: 'absolute',
      right: '115px',
      top: '18px',
    },
    excelExport: {
      position: 'absolute',
      right: '50px',
      top: '11px',
    },
    badgeWrapperLeft: { width: '80%' },
    productSelect: { width: '270px' },
    productSelectImg: { width: '15px', height: '15px' },
    productNameSpan: {
      whiteSpace: 'pre-wrap',
      overflowWrap: 'break-word',
      cursor: 'pointer',
      display: 'flex',
      height: 'fit-content',
      width: '27vh',
    },
    productNameLeadProduct: { fontSize: '8px', height: '60px' },
    productName: { fontSize: '1.2vh' },
    popoverFamilyDetail: { width: '400px' },
    badgeWrapper: {
      display: 'flex',
      alignSelf: 'center',
      minWidth: '80px',
      justifyContent: 'flex-end',
      marginLeft: '10px',
      '& .ant-divider-vertical': { margin: '0 3px !important', height: '35px' },
    },
    bundledProduct: { marginRight: '2px' },
    bundledDiscountedWrapper: {
      flexDirection: 'row !important',
      width: '25%',
      display: 'flex',
      justifyContent: 'flex-end',
      alignSelf: 'center',
      marginLeft: '5px',
    },
    extraCompetitors: {
      fontSize: '8px',
      color: 'rgb(120, 73, 247)',
      fontWeight: '600',
    },
    currentPriceImg: { width: '15px', height: '15px' },
    currentPriceDiv: { fontSize: '8px', color: 'grey', paddingLeft: '3px' },
    productColumn: { fontSize: '10px', fontWeight: 'normal' },
    downloadOutlined: { color: 'green', fontSize: '20px !important' },
    reloadOutlined: { color: 'red', fontSize: '20px !important' },
    downArrowCol: {
      display: 'flex',
      alignItems: 'flex-start',
      paddingTop: '4px',
    },
    newPriceDiv: { fontSize: '12px !important' },
    columnDiv: { minWidth: '60px', whiteSpace: 'nowrap' },
    discountedPriceColumn: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'flex-start',
      minWidth: '45px',
      whiteSpace: 'nowrap',
      paddingLeft: '17px !important',
    },
    applyButton: {
      display: 'flex',
      justifyContent: 'center',
      marginTop: '10px',
    },
    productCardContainer: { display: 'flex', justifyContent: 'space-around' },
    productCardCol: { maxWidth: '60%' },
    productCardRow: { marginBottom: '5px' },
    productCardColItem: { maxWidth: '60%' },
    productCardTag: {
      maxHeight: '23px',
      minWidth: '100px',
      maxWidth: '100%',
      color: 'rgb(120, 73, 247) !important',
      fontWeight: '600',
      textDecoration: 'underline',
      textUnderlineOffset: '5px',
    },
    productCardUl: { padding: '0px', paddingLeft: '20px' },
    productCardDivider: { margin: '5px 0' },
    producCardModal: {
      width: '45% !important',
      height: '1000px',
      '& .ant-modal-content': { height: 'auto', overflow: 'scroll' },
      '& .ant-divider-horizontal.ant-divider-with-text': {
        '&::after': { borderTop: '1px solid #6c757d !important' },
        '&::before': { borderTop: '1px solid #6c757d !important' },
      },
    },
    productCardName: {
      cursor: 'pointer',
      fontWeight: '600',
    },
    productCardProfile: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    productCardLink: { color: '#58666E' },
    priceIndexImage: { height: '20px', width: '20px' },
    productNameCompetitorImage: {
      height: '15px',
      marginRight: '4px',
      width: '17px',
      marginLeft: '8px',
    },
    productNameOtherImage: {
      height: '15px',
      marginRight: '4px',
      width: '15px',
    },
    priceIndexRow: {
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
    },
    competitorInfoBadge: { alignSelf: 'center' },
    competitorInfoBadgeLastChild: { alignSelf: 'center' },
    matchedProductCardImg: { maxHeight: '120px', marginTop: '20px' },
    familyProductCardImg: { maxHeight: '90px', marginTop: '30px' },
    familyProductCardImgSmall: { height: '60px !important', marginTop: '10px' },
    productCardMatchedCol: {
      display: 'flex',
      flexFlow: 'wrap',
      justifyContent: 'space-around',
      width: '100%',
    },
    matchedProductCard: {
      width: '20%',
      marginLeft: '5px',
      height: 'auto',
      borderRadius: '30px',
      boxShadow: 'rgb(25 25 25 / 25%) 0px 0px 5px',
      margin: '15px',
      '& .ant-card-meta': {
        position: 'absolute',
        bottom: '40px',
        left: '0px',
        right: '0px',
        marginLeft: 'auto',
        marginRight: 'auto',
      },
      '& .ant-card-cover': {
        minHeight: '120px !important',
        '& .ant-ribbon': {
          height: 'auto !important',
          padding: '0 15px !important',
        },
      },
      '& .ant-image-mask': { maxHeight: '150px !important' },
      '& .ant-card-body': {
        padding: '20px !important',
        display: 'flex',
        textAlign: 'center',
        marginBottom: '15px',
        height: '150px',
      },
      '& .ant-card-meta-title': {
        whiteSpace: 'normal !important',
        minHeight: '60px',
        fontSize: '10px !important',
        overflowWrap: 'anywhere',
        marginRight: '5px',
        marginLeft: '5px',
      },
      '& .ant-image': {
        display: 'flex',
        justifyContent: 'center',
        padding: '10px',
      },
    },
    downArrowCard: {
      justifyContent: 'flex-end',
      right: '-10px',
      alignSelf: 'center',
    },
    csvImporter: { '& .anticon-cloud-upload': { color: 'green', fontSize: '20px' } },
    csvImporterWrapper: {
      position: 'absolute',
      right: '90px !important',
      top: '11px',
    },
    indexDiv: { fontWeight: '600' },
    subcategoryPriceChange: { flexFlow: 'nowrap', marginTop: '5px' },
    simulateButtonWrapper: {
      display: 'flex',
      alignSelf: 'center',
      position: 'absolute',
      right: '180px',
    },
    purpleGetirColor: {
      borderRadius: '8px',
      width: '140px !important',
      color: 'rgb(120, 73, 247) !important',
      fontWeight: '600',
      border: '1px solid rgb(180, 163, 227) !important',
      fontSize: '1.4vh !important',
      '&:hover': {
        color: 'rgb(255, 228, 48) !important',
        backgroundColor: 'rgb(120, 73, 247) !important',
        borderColor: 'rgb(180, 163, 227)',
        fontWeight: '800',
        fontSize: '1.4vh !important',
      },
    },
    clearButtonWrapper: {
      alignSelf: 'center',
      position: 'absolute',
      right: '30px',
    },
    simulationModal: {
      width: '140vh !important',
      '& .ant-modal-content': { overflow: 'scroll' },
    },
    simulateCard: {
      width: '45%',
      marginLeft: '5px',
      height: 'auto',
      borderRadius: '30px',
      boxShadow: 'rgb(25 25 25 / 25%) 0px 0px 5px',
      margin: '15px',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      '& .ant-card-cover': { minHeight: '100px !important', width: '60%' },
      '& .ant-card-body': {
        padding: '10px',
        display: 'flex',
        textAlign: 'center',
        width: '80%',
        justifyContent: 'center',
      },
      '& .ant-card-meta': { width: '100%' },
      '& .ant-card-meta-title': {
        whiteSpace: 'normal !important',
        minHeight: '30px',
      },
      '& .ant-image': {
        display: 'flex',
        justifyContent: 'center',
        height: '100%',
        padding: '15px 30px',
        maxHeight: '100px',
      },
    },
    simulateRow: { justifyContent: 'space-evenly' },
    simulateArrow: {
      display: 'flex',
      flexDirection: 'column',
      alignSelf: 'center',
    },
    csvModal: { width: '550px' },
    indexDescriptionDivider: { width: '100%' },
    spin: { margin: '20px', padding: '30px 50px', textAlign: 'center' },
    allProductPriceChange: { fontWeight: 'bold', textAlign: 'center' },
    tagWrapper: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'flex-start',
    },
    recommendedPrice: {
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: 'translate(-50%, -50%)',
      fontWeight: '600',
    },
    recommendedWrapper: { display: 'flex', justifyContent: 'center' },
    recommendedButton: { display: 'flex' },
    recommendedIcon: {
      fontSize: '20px',
      marginLeft: '5px',
    },
    competitorName: {
      color: 'rgb(120, 73, 247)',
      fontWeight: 'bold',
      fontSize: 'smaller',
      textAlign: 'center',
      marginLeft: '3px',
    },
    inelasticStatus: {
      fontWeight: 'bold',
      fontSize: 'smaller',
      textAlign: 'center',
      whiteSpace: 'nowrap',
    },
    activeRule: {
      display: 'flex',
      justifyContent: 'center',
      flexDirection: 'column',
      minHeight: '45px',
      whiteSpace: 'nowrap',
    },
    guardrailFailTags: { margin: '5px', width: '100%' },
    guardrailTagWrapper: {
      minWidth: '350px',
      display: 'flex',
      justifyContent: 'flex-end',
    },
    guardrailTag: {
      lineHeight: '30px !important',
      fontSize: '15px !important',
    },
    guardrailFailIcon: { width: '65px' },
    guardrailDivider: { margin: '0 0 24px 0 !important' },
    activeRuleContent: {
      display: 'flex',
      alignSelf: 'center',
      alignItems: 'center',
    },
    listItem: { display: 'flex', justifyContent: 'flex-start' },
    listItemTag: { minWidth: '160px !important' },
    productLink: { color: 'rgb(120, 73, 247) !important' },
    barcodeLink: {
      padding: '5px',
      marginLeft: '5px',
      color: 'rgb(120, 73, 247) !important',
      '&:hover': {
        color: 'rgb(255, 228, 48) !important',
        backgroundColor: 'rgb(120, 73, 247) !important',
        borderColor: 'rgb(180, 163, 227)',
      },
    },
    barcode: {
      fontSize: '13px',
      padding: 0,
    },
    guardrailDetailRow: {
      width: '100%',
      display: 'flex',
      justifyContent: 'space-around',
    },
    guardrailDetailCol: {
      display: 'flex',
      justifyContent: 'center',
      flexDirection: 'column',
      alignItems: 'center',
      paddingTop: '22px',
    },
    guardrailDetailColTitle: { width: '100%', alignItems: 'center' },
    guardrailDetailDivider: {
      fontWeight: 600,
      textDecoration: 'underline',
      textUnderlineOffset: '5px',
    },
    guardrailDetailPrice: {
      display: 'flex',
      width: '100%',
      justifyContent: 'center',
      fontSize: 'xx-large',
      fontWeight: 600,
      margin: '40px 0',
    },
    guardrailDetailImage: {
      width: '10vh',
      height: '55px',
    },
    guardrailRightIcon: {
      alignSelf: 'center',
      marginTop: '10px',
      textAlign: 'center',
    },
    replaceIcon: {
      width: '20px',
      height: '20px',
    },
    replaceButton: {
      fontSize: '1.3vh',
      padding: '5px',
    },
    replaceButtonRow: {
      justifyContent: 'center',
      flexDirection: 'row',
    },
    newPriceInput: { marginBottom: '1px' },
    newPriceCheckbox: {
      display: 'flex',
      alignSelf: 'center',
      marginLeft: '10px',
      '& .ant-checkbox-disabled .ant-checkbox-inner': { backgroundColor: '#f5f5f5 !important' },
      '& .ant-checkbox-checked .ant-checkbox-inner': {
        backgroundColor: 'rgb(120, 73, 247)',
        borderColor: 'rgb(120, 73, 247)',
        '&:hover, &:active, &:focus': { borderColor: 'rgb(120, 73, 247)' },
      },
    },
    applyAllRecommendedCheckbox: {
      marginLeft: '17px',
      '& .ant-checkbox-disabled .ant-checkbox-inner': { backgroundColor: '#f5f5f5 !important' },
      '& .ant-checkbox-checked .ant-checkbox-inner': {
        backgroundColor: 'rgb(120, 73, 247)',
        borderColor: 'rgb(120, 73, 247)',
        '&:hover, &:active, &:focus': { borderColor: 'rgb(120, 73, 247)' },
      },
    },
    struckPriceBundleDetail: {
      fontSize: '8px',
      textDecoration: 'line-through',
      color: 'grey',
    },
    struckPrice: {
      textDecoration: 'line-through',
      color: 'grey',
      fontSize: '1.2vh !important',
    },
    productNameCol: { alignSelf: 'center' },
    indexFilterContainer: {
      alignItems: 'center',
      justifyContent: 'space-around',
      '& .ant-select': {
        width: '80%',
        height: '30px !important',
      },
    },
    tableRowContainer: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    tableCol: { marginTop: '30px' },
    tableContainer: {
      margin: '20px',
      '& .ant-table-row-expand-icon': {
        '&::after': {
          top: '3px !important',
          left: '7px !important',
        },
      },
    },
    overallDiv: {
      fontWeight: 'bold',
      textAlign: 'left',
      color: 'black',
    },
    highDiv: {
      fontWeight: 'bold',
      textAlign: 'center',
      color: 'black',
    },
    labeledDiv: {
      fontWeight: 'bolder',
      textAlign: 'center',
      color: '#ab47bc',
    },
    selectCompetitorImage: { width: '20px' },
    renderDivider: { margin: '4px 0' },
    renderContainer: {
      display: 'flex',
      flexWrap: 'nowrap',
      padding: 8,
    },
    matchedCheckboxGroup: { marginLeft: '15px !important' },
    drawer: {
      display: 'flex',
      alignItems: 'center',
      '& .ant-drawer-content-wrapper': { height: '50% !important' },
    },
    rowButtonDrawer: {
      display: 'flex',
      justifyContent: 'flex-end',
      marginTop: '15px',
    },
    actionTreeCancel: {
      height: '20px',
      maxWidth: '20px',
    },
    tooltipTitle: { width: '150px' },
    tooltipImage: { width: '25px' },
    tooltipImageSec: { maxWidth: '40px' },
    matchedSpan: {
      fontWeight: 'bolder',
      textAlign: 'center',
      color: '#ab47bc',
    },
    guardrailFailMinMax: {
      display: 'flex',
      whiteSpace: 'nowrap',
    },
    matchesText: { minWidth: '35px' },
    matchesContainer: { display: 'flex' },
    recommendedPriceLine: { fontSize: '12px' },
    summaryPriceNew: { display: 'flex', justifyContent: 'center' },
    newPriceCol: { minWidth: '10vh' },
    competitorCurrentPrice: { color: 'rgba(0, 0, 0, 0.85)', fontSize: '11px' },
    exclamationIconWrapper: { marginLeft: '95px', display: 'flex' },
    exclamationIconWrapperFinalAlert: { display: 'flex' },
    indirectDDetailProductCol: {
      padding: '2px !important',
      display: 'flex',
      flexFlow: 'wrap',
      '& .ant-tag': { fontSize: '8px !important', marginLeft: '4px' },
    },
    barcodeTags: {
      backgroundColor: 'rgb(120, 73, 247)',
      borderColor: 'rgb(120, 73, 247)',
    },
    productCardProfileImage: { display: 'flex', justifyContent: 'flex-end' },
    tableTitleButtons: {
      display: 'flex',
      alignItems: 'center',
      height: '53%',
      alignContent: 'center',
    },
    excelFilter: { marginRight: '5px', display: 'flex' },
    additionalFilterWrapper: {
      position: 'absolute',
      right: '330px',
      display: 'flex',
      alignSelf: 'center',
    },
    checkboxSpan: { fontSize: '12px !important' },
    checkboxGroupForm: {
      display: 'flex',
      flexDirection: 'row !important',
      '& .ant-checkbox-wrapper': { fontSize: '12px !important' },
      '& .ant-form-item-label': { paddingTop: '3px' },
      '& .ant-form-item-control-input': { alignSelf: 'flex-end' },
      '& .ant-checkbox': { '&:hover, &:active, &:focus': { borderColor: 'rgb(120, 73, 247)' } },
      '& .ant-checkbox-checked .ant-checkbox-inner': {
        backgroundColor: 'rgb(120, 73, 247)',
        borderColor: 'rgb(120, 73, 247)',
        '&:hover, &:active, &:focus': { borderColor: 'rgb(120, 73, 247)' },
      },
    },
    checkboxGroupMatchedForm: {
      display: 'flex',
      flexDirection: 'row !important',
      '& .ant-checkbox-wrapper': { fontSize: '12px !important' },
      '& .ant-form-item-label': { paddingTop: '3px' },
      '& .ant-form-item-control-input': { alignSelf: 'flex-end' },
      '& .ant-checkbox': { '&:hover, &:active, &:focus': { borderColor: 'rgb(120, 73, 247)' } },
      '& .ant-checkbox-inner::after': { backgroundColor: 'rgb(120, 73, 247) !important' },
      '& .ant-checkbox-checked .ant-checkbox-inner': {
        borderColor: 'rgb(120, 73, 247)',
        backgroundColor: 'rgb(120, 73, 247)',
        '&:hover, &:active, &:focus': { borderColor: 'rgb(120, 73, 247)' },
      },
    },
    matchedProductCheckbox: {
      display: 'flex',
      flexDirection: 'row !important',
    },
    filterDrawer: {
      display: 'flex',
      alignItems: 'center',
      '& .ant-drawer-content': { borderRadius: '8px' },
      '& .ant-drawer-content-wrapper': {
        width: '27vh !important',
        height: '70%',
        margin: '10px !important',
        borderRadius: '30px',
        boxShadow: 'rgb(25 25 25 / 25%) 0px 0px 5px',
      },
      '& .ant-drawer-body': { padding: '5px !important' },
      '& .ant-drawer-title': { fontSize: '12px !important' },
      '& .ant-checkbox-group': {
        display: 'flex',
        flexDirection: 'column !important',
      },
      '& .ant-checkbox-wrapper': { marginLeft: '0px !important' },
      '& .ant-drawer-mask': { opacity: '0 !important' },
      '& .ant-btn': { transition: 'all 0.01s cubic-bezier(0.645, 0.045, 0.355, 1) !important' },
    },
    badgeImageWrapper: { display: 'flex' },
    clearFilterButton: {
      display: 'flex',
      justifyContent: 'center',
      marginTop: '15px',
    },
    bundleStatusIcon: { height: '20px' },
    bundleStatusTrue: {
      boxShadow:
        '0 0 3px green, 0 0 10px green, 0 0 20px green, 0 0 10px green, 0 0 20px green, 0 0 20px green !important',
      transition: 'box-shadow 0.6s ease-in-out',
    },
    bundleStatusFalse: {
      boxShadow:
        '0 0 3px red, 0 0 10px red, 0 0 20px red, 0 0 10px red, 0 0 20px red, 0 0 20px red !important',
      margin: '10px !important',
      transition: 'box-shadow 0.6s ease-in-out',
    },
    bundleDetailModal: {
      display: 'flex',
      justifyContent: 'space-around',
      flexFlow: 'wrap',
    },
    bundleDetailCardIndex: {
      display: 'flex',
      justifyContent: 'center',
      padding: '15px 0px',
      color: 'rgb(120, 73, 247)',
      fontWeight: '600',
    },
    bundleProductCard: {
      width: '40%',
      height: '300px',
      borderRadius: '30px',
      paddingBottom: '55px',
      margin: '20px 15px !important',
      '& .ant-row': { margin: '0px !important' },
      '& .ant-divider': { margin: '0px !important' },
      '& .ant-card-meta': {
        position: 'absolute',
        bottom: '40px',
        left: '0px',
        top: '70px',
        right: '0px',
        marginLeft: 'auto',
        marginRight: 'auto',
      },
      '& .ant-image-mask': { maxHeight: '150px !important' },
      '& .ant-card-body': {
        padding: '20px !important',
        display: 'flex',
        textAlign: 'center',
        marginBottom: '15px',
        height: '150px',
      },
      '& .ant-card-meta-title': {
        whiteSpace: 'normal !important',
        minHeight: '60px',
        fontSize: '12px !important',
        overflowWrap: 'anywhere',
        marginRight: '5px',
        marginLeft: '5px',
      },
      '& .ant-image': {
        display: 'flex',
        justifyContent: 'center',
        padding: '10px',
      },
    },
    bundleDetailColDivider: { height: '100%' },
    bundleIndexStatusTrue: { color: 'green' },
    bundleIndexStatusFalse: { color: 'red' },
    productLinkBundle: {
      fontSize: '10px',
      color: 'rgb(120, 73, 247) !important',
    },
    competitorCurrentPriceBundle: {
      color: 'rgba(0, 0, 0, 0.85)',
      fontSize: '11px',
    },
    productCardNameBundle: {
      cursor: 'pointer',
      fontWeight: '600',
      marginBottom: '10px',
      height: '60px',
      overflow: 'hidden',
    },
    bundleDetailProductCol: { padding: '2px !important' },
    bundleDetailDivider: { padding: '0 !important' },
    matchTags: {
      fontSize: '8px !important',
      fontWeight: '600',
      width: '50px',
      borderRadius: '8px',
    },
    productNameTagWrapper: {
      display: 'flex',
      alignItems: 'center',
      marginLeft: '10px',
    },
    matchTagWrapper: { width: '50%' },
    familyLeadProduct: {
      display: 'flex',
      justifyContent: 'flex-start',
      marginLeft: '25px',
    },
    familyDetail: {
      display: 'flex',
      flexDirection: 'column',
      alignSelf: 'center',
      marginLeft: '30px !important',
    },
    familyProductCardSmall: {
      marginLeft: '5px',
      height: '160px !important',
      borderRadius: '30px',
      boxShadow: 'rgb(25 25 25 / 25%) 0px 0px 5px',
      margin: '15px',
      '& .ant-card-meta': {
        position: 'absolute',
        bottom: '10px',
        left: '0px',
        right: '0px',
        marginLeft: 'auto',
        marginRight: 'auto',
        marginTop: '5px',
      },
      '& .ant-card-cover': {
        minHeight: '120px !important',
        '& .ant-ribbon': {
          height: 'auto !important',
          padding: '3px 15px !important',
        },
      },
      '& .ant-image-mask': { maxHeight: '150px !important' },
      '& .ant-card-body': {
        padding: '20px !important',
        display: 'flex',
        textAlign: 'center',
        marginBottom: '15px',
        height: '150px',
      },
      '& .ant-card-meta-title': {
        whiteSpace: 'normal !important',
        maxHeight: '60px',
        fontSize: '13px !important',
        overflowWrap: 'anywhere',
        marginRight: '5px',
        marginLeft: '5px',
      },
      '& .ant-image': {
        display: 'flex',
        justifyContent: 'center',
        padding: '10px',
      },
    },
    familyProductCard: {
      marginLeft: '5px',
      height: 'auto',
      borderRadius: '30px',
      boxShadow: 'rgb(25 25 25 / 25%) 0px 0px 5px',
      margin: '15px',
      '& .ant-card-meta': {
        position: 'absolute',
        bottom: '40px',
        left: '0px',
        right: '0px',
        marginLeft: 'auto',
        marginRight: 'auto',
      },
      '& .ant-card-cover': {
        minHeight: '120px !important',
        '& .ant-ribbon': {
          height: 'auto !important',
          padding: '3px 15px !important',
        },
      },
      '& .ant-image-mask': { maxHeight: '150px !important' },
      '& .ant-card-body': {
        padding: '20px !important',
        display: 'flex',
        textAlign: 'center',
        marginBottom: '15px',
        height: '150px',
      },
      '& .ant-card-meta-title': {
        whiteSpace: 'normal !important',
        minHeight: '60px',
        fontSize: '13px !important',
        overflowWrap: 'anywhere',
        marginRight: '5px',
        marginLeft: '5px',
      },
      '& .ant-image': {
        display: 'flex',
        justifyContent: 'center',
        padding: '10px',
      },
    },
    familyDetailRow: {
      display: 'flex',
      alignItems: 'center',
      marginBottom: '20px',
    },
    familyDetailTitle: {
      width: '150px',
      paddingTop: '1px',
      display: 'flex',
      justifyContent: 'flex-start',
      fontSize: '14px',
      marginRight: '15px',
      fontWeight: '600',
      textDecoration: 'underline !important',
      textUnderlineOffset: '5px',
      color: 'rgb(120, 73, 247) !important',
    },
    familyDetailValue: {
      display: 'flex',
      justifyContent: 'center',
      fontSize: 'x-large',
      fontWeight: 600,
    },
    familyLeadProductPrice: { display: 'flex', justifyContent: 'space-around' },
    flexEndButton: { display: 'flex', justifyContent: 'flex-end' },
    csvButtonWrapper: {
      height: '53% !important',
      display: 'flex',
      alignItems: 'center',
    },
  };
});
