import { createUseStyles } from 'react-jss';

export default createUseStyles({
  mapWrapper: {
    height: '400px',
    maxHeight: 'calc(100vh - 200px)',
    border: '1px solid #edf1f2',
    borderTop: 'none',
  },
  customerInfo: {
    padding: '10px',
    marginBottom: '10px',
    background: '#ffffff',
    fontSize: '12px',
    borderBottom: '1px solid #edf1f2',
  },
  actionsMenu: { textAlign: 'right' },
  mapTitle: { fontSize: '12px' },
  titleContent: {
    backgroundColor: '#f6f8f8',
    padding: '5px',
    border: '1px solid #edf1f2',
    borderBottom: 'none',
  },
  batchedOrdersTimelineMultiOrder: {
    minHeight: '120px',
    marginBottom: '24px',
    display: 'flex',
    alignItems: 'center',
    overflowX: 'hidden',
    scrollBehavior: 'smooth',
  },
  batchedOrdersTimelineSingleOrder: {
    minHeight: '120px',
    marginBottom: '24px',
    display: 'flex',
    alignItems: 'center',
    overflowX: 'hidden',
    justifyContent: 'center',
  },
  progress: {
    backgroundColor: 'rgba(28, 52, 84, 0.26)',
    borderRadius: '4px',
    height: '24px',
    width: '54px',
    display: 'block',
    color: '#ffffff',
    fontWeight: 700,
    fontSize: '12px',
    lineHeight: '22px',
    textAlign: 'center',
  },
  progressBar: {
    backgroundColor: 'rgba(25, 59, 103, 0.05)',
    height: '24px',
    width: '56px',
    marginTop: '10px',
    position: 'absolute',
    left: '-50%',
    marginLeft: '12px',
  },
  avatarLeftCorner: {
    position: 'absolute',
    top: '-10px',
    left: '12px',
  },
  timelineTitleContent: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  timelineTitle: {
    fontSize: '16px',
    fontWeight: 700,
    lineHeight: '22px',
    color: '#5D3EBC',
  },
  scrollButtonGroup: {
    position: 'absolute',
    top: 0,
    right: '25px',
  },
  scrollButton: {
    borderRadius: '8px',
    padding: '5px 8px',
    backgroundColor: 'rgba(25, 59, 103, 0.05)',
  },
  tableTitleContent: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '12px',
    paddingLeft: '10px',
    paddingRight: '20px',
  },
  tableTitle: {
    fontSize: '16px',
    fontWeight: 700,
    lineHeight: '22px',
    color: '#5D3EBC',
  },
  slot: {
    float: 'right',
    color: '#192434',
  },
  slotDate: {
    color: 'rgba(27, 43, 65, 0.69)',
    fontSize: '14px',
  },
  triangle: {
    width: 0,
    height: 0,
    borderLeft: '3px solid transparent',
    borderRight: '3px solid transparent',
    position: 'absolute',
    left: '50%',
    top: '100%',
    marginLeft: '9px',
    borderTop: '6px solid',
  },
  boldFont: { fontWeight: 'bold' },
  normalFont: { fontWeight: 'normal' },
});
