export enum ROLE_REQUEST_STATUSES {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  CANCELED ='CANCELED',
}

export enum ROLE_REQUEST_STATES {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  USER_CANCELED = 'USER_CANCELED',
  SYSTEM_CANCELED = 'SYSTEM_CANCELED',
  CANCELLED_BY_GRANTING_ROLE_ACCESS = 'CANCELLED_BY_GRANTING_ROLE_ACCESS',
}
