import {
  BANNED_FOR_COURIER_GETIR_MARKET_POLYGON_TYPE,
  BANNED_FOR_PRODUCT_DISPLAY_GETIR_MARKET_POLYGON_TYPE,
  BANNED_FOR_PROMO_GETIR_MARKET_POLYGON_TYPE,
  TOTALLY_BANNED_GETIR_MARKET_POLYGON_TYPE,
  REGULAR_WAREHOUSE_TYPE,
  SC_GROCER_WAREHOUSE_TYPE,
  STORE_CONVERSION_WAREHOUSE_TYPE,
  OTHER_WAREHOUSE_TYPE,
  WAREHOUSE_ACTIVE_STATE,
  GETIR_DOMAIN_TYPE_CODES,
  GETIR_GORILLAS_DOMAIN_TYPE,
} from '@shared/shared/constants';

export const banPolygonTypes = [
  BANNED_FOR_PRODUCT_DISPLAY_GETIR_MARKET_POLYGON_TYPE,
  BANNED_FOR_PROMO_GETIR_MARKET_POLYGON_TYPE,
  TOTALLY_BANNED_GETIR_MARKET_POLYGON_TYPE,
  BANNED_FOR_COURIER_GETIR_MARKET_POLYGON_TYPE,
];

export const warehouseTypes = [
  REGULAR_WAREHOUSE_TYPE,
  SC_GROCER_WAREHOUSE_TYPE,
  STORE_CONVERSION_WAREHOUSE_TYPE,
  OTHER_WAREHOUSE_TYPE,
];

export const WAREHOUSE_STATE = WAREHOUSE_ACTIVE_STATE;

export const GETIR_DOMAIN_TYPES = [...GETIR_DOMAIN_TYPE_CODES, GETIR_GORILLAS_DOMAIN_TYPE];
