export const mockedMarketProductAllPrice = [
  {
    id: 15240,
    price: 15,
    vat: 0.08,
    productId: '607d6e19f4b0ce87b4c531f7',
    struckPrice: {
      isEnabled: true,
      price: null,
      isShownUnderSpecialOffers: true,
      financial: {
        supplierSupportRate: 0,
        thirdPartySupportRate: 0,
        isFreeProduct: false,
      },
    },
    isBundled: false,
    currencyId: null,
    listPrice: 10,
    depositPrice: 18.77,
    wholesalePrice: 6.804,
    wholesaleVat: 8,
    unitPriceProperties: {
      unit: 'lt',
      perUnit: 0.5,
      quantity: 1,
    },
    wholesaleFinancials: {
      listPrice: 10,
      wholesaleVat: 8,
      wholesaleBonuses: [
        {
          bonus: 1,
          bonusType: 1,
          bonusAsAmount: 1,
          bonusAsPercent: 10,
        },
        {
          bonus: 2,
          bonusType: 1,
          bonusAsAmount: 0.1,
          bonusAsPercent: 1,
        },
        {
          bonus: 3,
          bonusType: 1,
          bonusAsAmount: 0.1,
          bonusAsPercent: 1,
        },
        {
          bonus: 4,
          bonusType: 1,
          bonusAsAmount: 0.1,
          bonusAsPercent: 1,
        },
        {
          bonus: 5,
          bonusType: 2,
          bonusAsAmount: 2,
          bonusAsPercent: 20,
        },
        {
          bonus: 6,
          bonusType: 1,
          bonusAsAmount: 0.1,
          bonusAsPercent: 1,
        },
        {
          bonus: 7,
          bonusType: 1,
          bonusAsAmount: 0.2,
          bonusAsPercent: 2,
        },
        {
          bonus: 8,
          bonusType: 1,
          bonusAsAmount: 0.1,
          bonusAsPercent: 1,
        },
      ],
      totalPriceReduction: 0,
      netInvoicePriceWithVat: 10.8,
      netNetBuyingPriceWithVat: 6.804,
      netInvoicePriceWithoutVat: 10,
      netNetBuyingPriceWithoutVat: 6.3,
    },
    struckPriceFinancial: null,
    ecoContributionPrice: 0.52,
    bundlePricing: [],
    domainPricings: [],
    warehousePricing: null,
    wastePricing: null,
  },
];

export const mockedUpdatingMarketProductPrice = [{
  id: 15240,
  price: 15,
  vat: 0.08,
  productId: '607d6e19f4b0ce87b4c531f7',
  struckPrice: {
    isEnabled: true,
    price: null,
    isShownUnderSpecialOffers: true,
    financial: {
      supplierSupportRate: 0,
      thirdPartySupportRate: 0,
      isFreeProduct: false,
    },
  },
  isBundled: false,
  currencyId: null,
  listPrice: 11,
  depositPrice: 18.77,
  wholesalePrice: 6.804,
  wholesaleVat: 9,
  unitPriceProperties: {
    unit: 'lt',
    perUnit: 0.5,
    quantity: 1,
  },
  wholesaleFinancials: {
    listPrice: 10,
    wholesaleVat: 8,
    wholesaleBonuses: [
      {
        bonus: 1,
        bonusType: 1,
        bonusAsAmount: 1,
        bonusAsPercent: 10,
      },
      {
        bonus: 2,
        bonusType: 1,
        bonusAsAmount: 0.1,
        bonusAsPercent: 1,
      },
      {
        bonus: 3,
        bonusType: 1,
        bonusAsAmount: 0.1,
        bonusAsPercent: 1,
      },
      {
        bonus: 4,
        bonusType: 1,
        bonusAsAmount: 0.1,
        bonusAsPercent: 1,
      },
      {
        bonus: 5,
        bonusType: 2,
        bonusAsAmount: 2,
        bonusAsPercent: 20,
      },
      {
        bonus: 6,
        bonusType: 1,
        bonusAsAmount: 0.1,
        bonusAsPercent: 1,
      },
      {
        bonus: 7,
        bonusType: 1,
        bonusAsAmount: 0.2,
        bonusAsPercent: 2,
      },
      {
        bonus: 8,
        bonusType: 1,
        bonusAsAmount: 0.1,
        bonusAsPercent: 1,
      },
    ],
    totalPriceReduction: 0,
    netInvoicePriceWithVat: 10.8,
    netNetBuyingPriceWithVat: 6.804,
    netInvoicePriceWithoutVat: 10,
    netNetBuyingPriceWithoutVat: 6.3,
  },
  struckPriceFinancial: null,
  ecoContributionPrice: 0.75,
  bundlePricing: [],
  domainPricings: [],
  warehousePricing: null,
  wastePricing: null,
}];

export const mockedGetMarketProductAllPrice = {
  id: 37778,
  uid: 'fa8df87a-4ab8-492c-aaad-637fb15e849f',
  createdAt: '2023-07-25T12:27:50.505Z',
  createdBy: 'MIGRATION',
  updatedAt: '2024-11-08T10:51:16.332Z',
  updatedBy: '61adf4f43bd3b137f5c8184f',
  deletedAt: null,
  deletedBy: null,
  productId: '647df18fadc0f6d6cc0a4397',
  vat: 0.01,
  isBundled: true,
  unitPriceProperties: {},
  ecoContributionPrice: null,
  depositPrice: null,
  barcodes: [
    'E2E Test Product Bundle',
  ],
  manufacturerId: '58230c01d9a3db0004e6336f',
  cogs: null,
  netCogs: null,
  kviScore: null,
  kviLabel: null,
  countryId: 1,
  familyId: null,
  country: {
    id: 1,
    countryCode: 'TR',
    country: '55999ad00000010000000000',
  },
  supplierBuyingFinancials: [
    {
      id: 40362,
      uid: 'e803c1cc-3028-4892-a64d-c9b5fcec4e59',
      createdAt: '2023-07-25T12:29:16.586Z',
      createdBy: 'MIGRATION',
      updatedAt: '2023-07-25T12:29:16.586Z',
      updatedBy: null,
      deletedAt: null,
      deletedBy: null,
      supplierId: '58230c01d9a3db0004e6336f',
      supplierAccountCodes: [
        '320.01.00161',
      ],
      wholesalePrice: 24,
      wholesaleVat: 1,
      listPrice: 23.7624,
      totalPriceReduction: 0,
      netInvoicePriceWithVat: 24,
      netInvoicePriceWithoutVat: 23.7624,
      netNetBuyingPriceWithVat: 24,
      netNetBuyingPriceWithoutVat: 23.7624,
      wholesaleBonuses: null,
      paymentDueDay: 12,
      supplierSAPCode: null,
      isActive: true,
      isPreferred: false,
      priceMetadataId: 37778,
    },
  ],
  subProductPrices: [],
  family: null,
  availableDomainsForDiscountedPrices: [
    1,
    3,
  ],
};
