import {
  GETIR_10_DOMAIN_TYPE,
  GETIR_MARKET_DOMAIN_TYPE,
  GETIR_VOYAGER_DOMAIN_TYPE as GETIR_WATER_DOMAIN_TYPE,
} from '@shared/shared/constants';

export const WAREHOUSE_BREAKDOWN_DOMAIN_TYPES = [GETIR_10_DOMAIN_TYPE, GETIR_MARKET_DOMAIN_TYPE, GETIR_WATER_DOMAIN_TYPE];
