import { createUseStyles } from 'react-jss';

import { colors, transitions } from '@app/pages/MarketProductChainManagement/styleVariables';

export default createUseStyles({
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    padding: '24px',
    maxWidth: '100%',
    margin: '0 auto',
    boxSizing: 'border-box',
    background: colors.backgroundLight,
    transition: transitions.default,
    '& > *': {
      width: '100%',
      borderRadius: '8px',
      overflow: 'hidden',
      background: colors.backgroundWhite,
      borderColor: colors.borderGray,
      boxShadow: `0 1px 3px ${colors.boxShadowLight}`,
      transition: transitions.default,
    },
    willChange: 'transform',
    backfaceVisibility: 'hidden',
    perspective: 1000,
    transform: 'translate3d(0, 0, 0)',
  },
  filterContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0',
    padding: '0',
    background: 'transparent',
    boxShadow: 'none',
    marginBottom: '24px',
    '& > *': {
      width: '100%',
      overflow: 'hidden',
      background: colors.backgroundWhite,
      borderColor: colors.borderGray,
      boxShadow: `0 1px 3px ${colors.boxShadowLight}`,
    },
    '& > *:first-child': {
      borderRadius: '8px 8px 0 0',
      borderBottom: 'none',
    },
    '& > *:last-child': {
      borderRadius: '0 0 8px 8px',
      borderTop: `1px solid ${colors.borderGray}`,
    },
  },
  titleWrapper: {
    display: 'flex',
    flexDirection: 'column',
    transform: 'translate3d(0, 0, 0)',
    willChange: 'transform',
  },
  tabs: {
    '& .ant-tabs-tab': {
      padding: '12px 8px',
      transform: 'translate3d(0, 0, 0)',
      willChange: 'transform',
      backfaceVisibility: 'hidden',
    },
    '& .ant-tabs-nav-wrap': {
      padding: '0px 24px',
      transform: 'translate3d(0, 0, 0)',
    },
    '& .ant-tabs-nav': {
      borderBottom: `1px solid ${colors.borderGray}`,
      margin: 0,
      transform: 'translate3d(0, 0, 0)',
      willChange: 'transform',
    },
    '& .ant-tabs-ink-bar': {
      height: '3px',
      borderRadius: '2px 2px 0 0',
      willChange: 'transform',
      transform: 'translate3d(0, 0, 0)',
      transition: 'transform 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    },
  },
  table: {
    '& .ant-table': {
      background: colors.backgroundWhite,
      transition: transitions.default,
    },
    '& .ant-table-thead > tr > th': {
      background: colors.tableHeaderBackground,
      color: colors.textDark,
      fontSize: '14px',
      fontWeight: 500,
      transition: transitions.default,
    },
    '& .ant-table-tbody > tr > td': {
      color: colors.textDark,
      fontSize: '14px',
      padding: '12px',
      transition: transitions.default,
      '&:hover': { background: colors.backgroundLight },
    },
    '& .ant-table-row': {
      transition: transitions.default,
      '&:hover': {
        transform: 'translateY(-1px)',
        boxShadow: `0 2px 4px ${colors.boxShadowLight}`,
      },
    },
    '& .ant-pagination': {
      padding: '16px 24px',
      background: colors.backgroundWhite,
      borderTop: `1px solid ${colors.borderGray}`,
      transition: transitions.default,
    },
    '& .ant-table-measure-row': { visibility: 'collapse' },
    '& .ant-table-cell-fix-left': {
      background: colors.tableHeaderBackground,
      transform: 'translate3d(0, 0, 0)',
      willChange: 'transform',
    },
    '& .ant-table-thead > tr > th.ant-table-cell-fix-left': {
      background: colors.tableHeaderBackgroundFixed,
      transform: 'translate3d(0, 0, 0)',
    },
  },
  button: {
    display: 'flex',
    justifyContent: 'center',
    gap: '8px',
    transform: 'translate3d(0, 0, 0)',
    willChange: 'transform',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
  },
  linkButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    color: colors.textDark,
    background: 'none',
    fontSize: '12px',
    padding: '0px',
    transform: 'translate3d(0, 0, 0)',
    willChange: 'transform',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
  },
  menu: {
    background: colors.backgroundWhite,
    boxShadow: `0 2px 8px ${colors.boxShadowLight}`,
    borderRadius: '8px',
    padding: '4px',
    transition: transitions.default,
    animation: '$menuFadeIn 0.2s ease-out',
    '& .ant-dropdown-menu-item': {
      padding: '12px 16px',
      borderRadius: '4px',
      transition: transitions.fast,
      '&:hover': { background: colors.backgroundLight },
    },
  },
  '@keyframes menuFadeIn': {
    from: {
      opacity: 0,
      transform: 'translateY(-8px)',
    },
    to: {
      opacity: 1,
      transform: 'translateY(0)',
    },
  },
  image: {
    height: '18px',
    width: '18px',
    transform: 'translate3d(0, 0, 0)',
    willChange: 'transform',
  },
  actionsColumn: {
    display: 'flex',
    justifyContent: 'flex-end',
    transform: 'translate3d(0, 0, 0)',
    willChange: 'transform',
  },
  redActionLine: {
    color: colors.dangerRed,
    transform: 'translate3d(0, 0, 0)',
  },
  smallMenu: {
    boxShadow: `0px 2px 6px -1px ${colors.boxShadowLight}, 0px 8px 24px -4px ${colors.boxShadowDark}`,
    borderRadius: '8px',
    padding: '4px',
    width: '150px',
    transform: 'translate3d(0, 0, 0)',
    willChange: 'transform, opacity',
    backfaceVisibility: 'hidden',
    '& .ant-dropdown-menu-item': {
      padding: '12px',
      transform: 'translate3d(0, 0, 0)',
      transition: 'background-color 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    },
  },
  errorResult: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '50vh',
    animation: '$fadeIn 0.5s cubic-bezier(0.4, 0, 0.2, 1)',
    willChange: 'transform, opacity',
    backfaceVisibility: 'hidden',
    transform: 'translate3d(0, 0, 0)',
  },
  '@keyframes fadeIn': {
    '0%': {
      opacity: 0.25,
      transform: 'translate3d(0, 10px, 0)',
    },
    '100%': {
      opacity: 1,
      transform: 'translate3d(0, 0, 0)',
    },
  },
});
