export const CHAIN_ACTION_TYPES = {
  GET_CHAIN_LIST_REQUEST: 'GET_CHAIN_LIST_REQUEST',
  GET_CHAIN_LIST_SUCCESS: 'GET_CHAIN_LIST_SUCCESS',
  GET_CHAIN_LIST_FAILURE: 'GET_CHAIN_LIST_FAILURE',
} as const;
