export const clientAppActionType = {
  0: { en: 'Close', tr: 'Kapat' },
  1: { en: 'None', tr: 'Hiçbiri' },
  2: { en: 'Redirect to URL', tr: "URL'e Yönlendir" },
  3: { en: 'In-App Redirection', tr: 'Uygulama İçi Yönlendirme' },
  4: { en: 'Redirect to Game URL', tr: "Game URL'e Yönlendir" },
  5: { en: 'Show Product ', tr: 'Ürüne Giden' },
  6: { en: 'Show Category', tr: 'Kategoriye Giden' },
  7: { en: 'Search in Application', tr: 'Uygulamada Arama Yapan' },
  8: { en: 'Show Multiple Products', tr: 'Ürün Listesi Açan' },
  10: { en: 'Open Application', tr: 'Uygulama Açan' },
  11: { en: 'Add To Basket', tr: 'Sepete Ürün Ekleyen' },
  13: { en: 'Phone Call', tr: 'Telefon ile Arama Yaptıran' },
  15: { en: 'Open Promotion', tr: 'Kampanyaya Giden' },
  17: { en: 'Open Announcement', tr: 'Duyuruya Giden' },
  30: { en: 'Redirect to Restaurant Detail', tr: 'Restoran Detayına Yönlendirme' },
  31: { en: 'Redirect to Restaurant Promo List', tr: 'Restoran Promo Listesine Yönlendirme' },
  33: { en: 'Loyalty Detail Page', tr: 'Müdavim Detay Sayfası' },
  34: { en: 'Redirect to Restaurant List', tr: 'Restoran Listesine Yönlendirme' },
  // 35: { en: 'Wallet', tr: 'Wallet' },
  36: { en: 'Redirect to Restaurant Product', tr: 'Restoran Ürününe Yönlendirme' },
  37: { en: 'Filter restaurant by cuisines', tr: 'Mutfağa göre restoranları listele' },
  38: { en: 'Routes to previous order list', tr: 'Son sipariş listesine yönlendir' },
  40: { en: 'Getir Food Deeplink', tr: 'Getir Food Deeplink' },
  55: { en: 'Open giveaway page', tr: 'Çekiliş sayfasına yönlendir' },
  60: { en: 'GetirLocals Merchant Detail', tr: 'GetirÇarşı İşletme Detayı' },
  // 61: { en: 'SHOPS', tr: 'SHOPS' },
  63: { en: 'Artisan Loyalty Detail', tr: 'Esnaf bağlılık detayı.' },
  64: { en: 'Market Open Slotted Delivery Option Bottom Sheet', tr: 'Slotlu Teslimatlarda Teslimat Seçimi' },
  66: { en: 'GetirLocals Filtered Merchant List', tr: 'GetirÇarşı Filtreli İşletme Listesi' },
  67: { en: 'GetirLocals Chain Merchant Detail', tr: 'GetirÇarşı Zincir İşletme Detayı' },
  // 64: { en: 'SHOP_LIST', tr: 'SHOP_LIST' },
  // 65: { en: 'SHOP_WITH_PRODUCT', tr: 'SHOP_WITH_PRODUCT' },
  81: { en: 'Getir water product list', tr: 'Getir su ürün listesi' },
  82: { en: 'Getir water product detail', tr: 'Getir su ürün detayı' },
  1202: { en: 'N11 URL Redirect', tr: 'N11 URL\'e Yönlendir' },
  1104: { en: 'Opens GetirJobs Post Detail page', tr: 'Getirİş ilan detayına giden' },
  888: { en: 'Show Promo Eligible Products', tr: 'Promolu ürün listesi açan' },
  57: { en: 'Show Listing Promo List', tr: 'Promo Listesini Açan' },
  1215: { en: 'Redirect to GetirFinans BNPL Communication SDK', tr: 'GetirFinans BNPL İletişim SDK Açan' },
};
