import { createActions } from 'reduxsauce';

import { REDUX_KEY } from '@shared/shared/constants';

export const { Types, Creators } = createActions({
  getVehicleDetails: { vehicleId: null },
  getVehicleDetailsSuccess: { data: [] },
  getVehicleDetailsFailure: { error: null },
  getVehicleType: {},
  getVehicleTypeSuccess: { data: [] },
  getVehicleTypeFailure: { error: null },
  updateVehicleRequest: {
    plate: '',
    constraintId: '',
    warehouse: '',
    franchise: '',
    city: '',
    licenceOwner: '',
    licenceImage: '',
    licenceSerial: '',
    firstRegistrationDate: '',
    registrationDate: '',
    tradeName: '',
    brand: '',
    chasis: '',
    kind: '',
    color: '',
    engineNumber: '',
    identityNumber: '',
    inspectionValidityDate: '',
    tags: [],
    ownershipType: null,
    licenceNumber: '',
    modelYear: '',
    id: '',
  },
  updateVehicleRequestSuccess: { data: [] },
  updateVehicleRequestFailure: { error: null },
  getVehicleLogsRequest: { body: null },
  getVehicleLogsSuccess: { data: [] },
  getVehicleLogsFailure: { error: null },
  initPage: null,
  destroyPage: null,
}, { prefix: `${REDUX_KEY.VEHICLE.DETAIL}_` });
