export const ROLE_MODAL_TYPES = {
  ADD: 1,
  UPDATE: 2,
};

export const PAGE_DETAIL_TAB_PANE_KEY = {
  PAGE_COMPONENTS_LIST: 'PAGE_COMPONENTS_LIST',
  PAGE_OWNERS_LIST: 'PAGE_OWNERS_LIST',
  ROLE_LIST: 'ROLE_LIST',
  PANEL_DOC_LIST: 'PANEL_DOC_LIST',
};
