export const OPTIONAL_CONTROL = {
  TOTAL_ORDER_COUNT: 1,
  STOCK_LEVEL: 2,
  AGGRESSION_LEVEL: 3,
  LOCATION_BASED_CONTROL: 4,
  HOUR_SCHEDULER: 5,
  SEGMENT: 6,
  GETIR_MARKET_SUB_CATEGORY_CONTROL: 7,
  ARTISAN_STORE_CONTROL: 8,
  ARTISAN_VERTICAL_CONTROL: 9,
  ARTISAN_SERVICE_AREA_STORE_CONTROL: 10,
  VERSION_CONTROL: 11,
};

export const VERSION_CONTROL_FIELD_NAMES = {
  FIELD_NAME: 'versionControl',
  IOS_VERSION: 'iosVersion',
  ANDROID_VERSION: 'androidVersion',
};
