import { createUseStyles } from 'react-jss';

import { colors } from '@app/pages/MarketProductChainManagement/styleVariables';

export default createUseStyles({
  pageWrapper: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    padding: '0 0 24px 0',
  },
  contentCard: {
    borderRadius: '12px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.05)',
    overflow: 'hidden',
  },
  tabs: {
    '& .ant-tabs-nav': {
      marginBottom: '24px',
      '&::before': { border: 'none' },
    },
    '& .ant-tabs-tab': {
      padding: '12px 20px',
      fontSize: '15px',
      fontWeight: 500,
    },
    '& .ant-tabs-tab.ant-tabs-tab-active .ant-tabs-tab-btn': {
      color: '#1d1d1f',
      fontWeight: 600,
    },
    '& .ant-tabs-ink-bar': {
      backgroundColor: '#7a6b99',
      height: '3px',
    },
  },
  tabCount: {
    fontSize: '14px',
    color: 'rgba(0, 0, 0, 0.45)',
    marginLeft: '4px',
  },
  tabContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  filterCard: {
    background: '#f5f5f7',
    borderRadius: '12px',
    marginBottom: '24px',
    padding: '24px 28px',
  },
  table: {
    '& .ant-table': {
      backgroundColor: '#ffffff',
      borderRadius: '12px',
      overflow: 'hidden',
    },
    '& .ant-table-thead > tr > th': {
      backgroundColor: '#f5f5f7',
      borderBottom: '1px solid #d2d2d7',
      color: '#1d1d1f',
      fontSize: '14px',
      fontWeight: 500,
      padding: '12px 16px',
      textTransform: 'capitalize',
      '&::before': { display: 'none' },
    },
    '& .ant-table-tbody > tr > td': {
      borderBottom: '1px solid #f5f5f7',
      padding: '12px 16px',
      fontSize: '14px',
      color: '#1d1d1f',
      transition: 'background-color 0.2s ease',
    },
    '& .ant-table-tbody > tr:hover > td': { backgroundColor: '#f5f5f7' },
    '& .ant-table-pagination': {
      margin: '24px 0 0',
      '& .ant-pagination-item': {
        borderRadius: '8px',
        border: '1px solid #d2d2d7',
        transition: 'all 0.2s ease',
        '&-active': {
          borderColor: '#7a6b99',
          backgroundColor: '#7a6b99',
          '& a': { color: '#ffffff' },
        },
        '& a': {
          color: '#1d1d1f',
          '&:hover': { color: '#7a6b99' },
        },
      },
      '& .ant-pagination-prev, & .ant-pagination-next': {
        '& button': {
          borderRadius: '8px',
          border: '1px solid #d2d2d7',
          color: '#1d1d1f',
          transition: 'all 0.2s ease',
          '&:hover': {
            borderColor: '#7a6b99',
            color: '#7a6b99',
          },
        },
      },
      '& .ant-pagination-options': {
        '& .ant-select:not(.ant-select-disabled):hover .ant-select-selector': { borderColor: '#7a6b99' },
        '& .ant-select-focused:not(.ant-select-disabled) .ant-select-selector': {
          borderColor: '#7a6b99',
          boxShadow: '0 0 0 2px rgba(122, 107, 153, 0.1)',
        },
        '& .ant-select-selector': {
          borderRadius: '8px',
          transition: 'all 0.2s ease',
        },
        '& .ant-pagination-options-quick-jumper': {
          '& input': {
            borderRadius: '8px',
            transition: 'all 0.2s ease',
            '&:hover': { borderColor: '#7a6b99' },
            '&:focus': {
              borderColor: '#7a6b99',
              boxShadow: '0 0 0 2px rgba(122, 107, 153, 0.1)',
            },
          },
        },
      },
    },
  },
  copyWrapper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    position: 'relative',
    padding: '1px 1px',
    borderRadius: '3px',
    transition: 'background-color 0.2s ease',
    '&:hover': { backgroundColor: 'rgba(0, 0, 0, 0.03)' },
  },
  idText: {
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    maxWidth: 'calc(100% - 16px)',
    display: 'block',
    fontSize: '12px',
  },
  cellContent: {
    whiteSpace: 'normal',
    wordBreak: 'break-word',
    overflow: 'hidden',
    lineHeight: '1.4',
    padding: '2px 0',
  },
  domainTag: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2px 8px',
    borderRadius: '4px',
    fontSize: '12px',
    fontWeight: 500,
    backgroundColor: 'rgba(122, 107, 153, 0.1)',
    color: '#7a6b99',
    border: '1px solid rgba(122, 107, 153, 0.2)',
    maxWidth: '100%',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  emptyDomain: {
    color: '#999',
    fontStyle: 'italic',
    fontSize: '12px',
  },
  copyIcon: {
    color: '#999',
    fontSize: '12px',
    cursor: 'pointer',
    padding: '1px',
    opacity: 0.6,
    transition: 'all 0.2s ease',
    '&:hover': {
      color: '#1890ff',
      opacity: 1,
    },
  },
  actionsColumn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '12px',
  },
  actionSwitch: {
    marginRight: '4px',
    '& .ant-switch-checked': { backgroundColor: '#52c41a' },
  },
  detailButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '4px',
    color: '#7a6b99',
    fontWeight: 500,
    padding: '5px 10px',
    height: '32px',
    borderRadius: '8px',
    background: 'rgba(122, 107, 153, 0.05)',
    border: '1px solid rgba(122, 107, 153, 0.2)',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    boxShadow: 'none',

    '&:hover': {
      background: 'rgba(122, 107, 153, 0.1)',
      borderColor: 'rgba(122, 107, 153, 0.3)',
      color: '#7a6b99',
    },

    '&:active': {
      background: 'rgba(122, 107, 153, 0.15)',
      transform: 'translateY(1px)',
    },
  },
  enabledSwitchWrapper: {
    height: 'auto',
    display: 'flex',
    padding: 0,
    margin: 0,
    marginTop: '8px',
  },
  enabledSwitchContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    gap: '16px',
    padding: 0,
    margin: 0,
  },
  enabledSwitchLabel: {
    fontSize: '13px',
    color: 'rgba(0, 0, 0, 0.7)',
    fontWeight: 'normal',
    lineHeight: '1',
    marginBottom: '2px',
  },
  formItem: {
    marginBottom: '8px',
    height: '100%',
    '& .ant-form-item-label': {
      padding: 0,
      marginBottom: 4,
    },
    '& .ant-input, & .ant-select-selector': {
      borderRadius: 8,
      border: '1px solid #d2d2d7',
      transition: 'all 0.2s ease',
      backgroundColor: '#ffffff',
      height: 40,
      display: 'flex',
      alignItems: 'center',
      '&:hover': { borderColor: '#86868b' },
      '&:focus, &:active': {
        borderColor: '#7a6b99',
        boxShadow: '0 0 0 2px rgba(122, 107, 153, 0.1)',
      },
    },
    '& .ant-select-selector': {
      '& .ant-select-selection-search-input': { height: 38 },
      '& .ant-select-selection-item': {
        display: 'flex',
        alignItems: 'center',
      },
    },
    '& .ant-input': { '&::placeholder': { color: '#86868b' } },
  },
  // Kategori filtreleri stilleri
  filterSectionTitle: {
    fontSize: '15px',
    fontWeight: 500,
    color: '#1d1d1f',
    marginBottom: '16px',
    paddingBottom: '8px',
    borderBottom: '1px solid #e5e5ea',
  },
  categoryFilterSection: {
    position: 'relative',
    marginBottom: '32px',
    padding: '0 0 10px 0',
    background: 'rgba(122, 107, 153, 0.03)',
    borderRadius: '8px',
    borderLeft: '2px solid rgba(122, 107, 153, 0.2)',
    paddingLeft: '10px',
  },
  categoryConnector: {
    position: 'absolute',
    top: '55%',
    right: '-12px',
    width: '24px',
    height: '1px',
    background: 'rgba(122, 107, 153, 0.3)',
    zIndex: 1,
    '&:after': {
      content: '""',
      position: 'absolute',
      right: 0,
      top: '-3px',
      width: 0,
      height: 0,
      borderStyle: 'solid',
      borderWidth: '3px 0 3px 5px',
      borderColor: 'transparent transparent transparent rgba(122, 107, 153, 0.5)',
    },
  },
  categoryL3Item: { position: 'relative', marginBottom: '4px' },
  categoryL4Item: { position: 'relative' },
  categoryWrapper: { position: 'relative' },
  categoryHint: {
    fontSize: '11px',
    color: '#86868b',
    marginTop: '4px',
    fontStyle: 'italic',
    display: 'block',
    lineHeight: '1.2',
  },
  categoryHintDisabled: { color: '#c1c1c6' },
  categoryHintEnabled: { color: '#7a6b99', fontWeight: 500 },
  disabledInput: {
    opacity: 0.7,
    '& .ant-select-selector': {
      backgroundColor: '#f5f5f7 !important',
      borderColor: '#e5e5ea !important',
    },
  },
});
