import { createUseStyles } from 'react-jss';

import { colors } from '@app/pages/MarketProductChainManagement/styleVariables';

export default createUseStyles({
  rowWrapper: {
    background: colors.backgroundLight,
    padding: '16px',
    display: 'grid',
    gridTemplateColumns: 'repeat(1, 1fr)',
    gap: '16px',
    boxSizing: 'border-box',
    animation: '$fadeIn 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
    willChange: 'transform, opacity',
    transform: 'translate3d(0, 0, 0)',
    backfaceVisibility: 'hidden',
    '@media (min-width: 576px)': { gridTemplateColumns: 'repeat(2, 1fr)' },
    '@media (min-width: 768px)': {
      gridTemplateColumns: 'repeat(4, 1fr)',
      '&.reducedItems': { '& > *:nth-last-child(-n+2)': { gridColumn: 'span 2' } },
    },
  },
  cardContainer: {
    background: colors.backgroundWhite,
    height: '84px',
    padding: '12px 16px',
    borderRadius: '12px',
    boxSizing: 'border-box',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    overflow: 'hidden',
    willChange: 'transform, box-shadow',
    transform: 'translate3d(0, 0, 0)',
    backfaceVisibility: 'hidden',
  },
  contentWrapper: {
    position: 'relative',
    width: '100%',
    height: '100%',
    willChange: 'contents',
  },
  skeletonLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    opacity: 0,
    transform: 'translate3d(0, 10px, 0)',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    willChange: 'transform, opacity',
    backfaceVisibility: 'hidden',
    '& .ant-skeleton': {
      width: '100%',
      display: 'flex',
      alignItems: 'center',
      height: '100%',
      transform: 'translate3d(0, 0, 0)',
    },
    '& .ant-skeleton-avatar': {
      background: colors.backgroundImage,
      flexShrink: 0,
      marginRight: '12px',
      willChange: 'transform',
      transform: 'translate3d(0, 0, 0)',
    },
    '& .ant-skeleton-content': {
      flex: 1,
      transform: 'translate3d(0, 0, 0)',
      '& .ant-skeleton-input': {
        height: '16px',
        marginTop: 0,
        marginBottom: '8px',
        willChange: 'transform',
        transform: 'translate3d(0, 0, 0)',
        '&:last-child': { marginBottom: 0 },
      },
    },
  },
  contentLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    opacity: 1,
    transform: 'translate3d(0, 0, 0)',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    willChange: 'transform, opacity',
    backfaceVisibility: 'hidden',
  },
  loading: {
    '& $skeletonLayer': {
      opacity: 1,
      transform: 'translate3d(0, 0, 0)',
    },
    '& $contentLayer': {
      opacity: 0,
      transform: 'translate3d(0, -10px, 0)',
    },
  },
  imageWrapper: {
    width: '32px',
    height: '32px',
    background: colors.backgroundImage,
    borderRadius: '50%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: '12px',
    flexShrink: 0,
    willChange: 'transform',
    transform: 'translate3d(0, 0, 0)',
  },
  title: {
    color: colors.textLight,
    fontSize: '12px',
    fontWeight: 400,
    lineHeight: '16px',
    transform: 'translate3d(0, 0, 0)',
  },
  content: {
    color: colors.textDark,
    fontSize: '14px',
    fontWeight: 700,
    lineHeight: '18px',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    transform: 'translate3d(0, 0, 0)',
  },
  '@keyframes fadeIn': {
    '0%': {
      opacity: 0.25,
      transform: 'translate3d(0, 10px, 0)',
    },
    '100%': {
      opacity: 1,
      transform: 'translate3d(0, 0, 0)',
    },
  },
});
