export const MOCKED_WAREHOUSES = [
  {
    _id: '5f106c400d13cdb987c60368',
    location: {
      type: 'Point',
      coordinates: [
        29.0058214,
        41.0767667,
      ],
      acc: -1,
      time: '2020-07-16T15:03:28.251Z',
    },
    domainTypes: [
      2,
      6,
    ],
    pickers: [],
    couriers: [
      '604a3b0c3c5d5f030c80c23e',
      '605b7c1d7c2fed5f2bd5b4c9',
      '5ffc407bc9ca4905b5fc850b',
      '60abe455d06550da00be9650',
      '60d1905eb758247d8a971fb0',
    ],
    state: 300,
    status: 200,
    aggressionLevel: 4,
    name: 'sadece yemek',
    shortName: 'sadece yemek',
    warehouseType: 10,
    country: {
      _id: '55999ad00000010000000000',
      name: {
        de: 'Türkei',
        en: 'Turkey',
        fr: 'Turquie',
        nl: 'Turkije',
        tr: 'Türkiye',
        es: 'Turquía',
        it: 'Turchia',
        pt: 'Turquia',
        'en-US': 'Turkey',
      },
      center: {
        type: 'Point',
        coordinates: [
          35,
          39,
        ],
        acc: -1,
        time: '2019-12-13T21:00:00.000Z',
      },
      timezones: [
        { timezone: 'Europe/Istanbul' },
      ],
      flag: '🇹🇷',
      defaultLanguageCode: 'tr',
      languageSortOrder: [
        'tr',
        'en',
      ],
      languages: {
        tr: { name: 'Türkçe' },
        en: { name: 'English' },
      },
    },
    city: {
      _id: '55999ad00000010001000000',
      country: '55999ad00000010000000000',
      name: {
        en: 'Istanbul',
        tr: 'İstanbul',
      },
      center: {
        type: 'Point',
        coordinates: [
          29,
          41,
        ],
        acc: -1,
        time: '2019-12-13T21:00:00.000Z',
        zoomRatio: 11,
      },
      timezone: 'Europe/Istanbul',
      plate: '34',
    },
    region: {
      _id: '55999ad00000010001000001',
      country: '55999ad00000010000000000',
      city: '55999ad00000010001000000',
      name: {
        tr: 'Levent',
        en: 'Levent',
      },
      oldCode: 1000,
    },
    address: 'Levent metro istasyonu',
    mainStore: '5c38f601ca872900018db2d9',
    franchise: '5e0d8a1df0f1d572ab399aaa',
    createdAt: '2020-07-16T15:03:28.259Z',
    updatedAt: '2023-03-22T11:16:25.325Z',
    countryCode: 'TR',
    mainWarehouses: [
      '5c38f601ca872900018db2d9',
    ],
    id: '5f106c400d13cdb987c60368',
  },
];

export const MOCKED_DATA = {
  total: {
    total: {
      total: {
        planned: 4,
        total: 132,
        free: 42,
        busy: 22,
        onOrder: 32,
        canceled: 32,
        utilized: 50,
        utilizableTotal: 88,
        utilization: 56.81818181818182,
        byVehicleType: {
          200: {
            activeLocalsCouriers: 23,
            activeNonLocalsCouriers: 2,
            planned: 2,
            total: 100,
            free: 33,
            busy: 15,
            onOrder: 25,
            canceled: 25,
            utilized: 41,
            utilizableTotal: 74,
            utilization: 55.4054054054054,
          },
          400: {
            activeLocalsCouriers: 7,
            activeNonLocalsCouriers: 0,
            planned: 2,
            total: 32,
            free: 9,
            busy: 7,
            onOrder: 7,
            canceled: 7,
            utilized: 9,
            utilizableTotal: 14,
            utilization: 64.28571428571429,
          },
        },
        activeLocalsCouriers: 30,
        activeNonLocalsCouriers: 2,
        activeLocalsCouriersByVehicleType: {
          200: 22,
          400: 4,
        },
        activeNonLocalsCouriersByVehicleType: { 200: 2 },
      },
      warehouses: [
        {
          warehouseId: '5f106c400d13cdb987c60368',
          planned: 0,
          total: 1,
          free: 0,
          busy: 1,
          onOrder: 0,
          canceled: 0,
          utilized: 0,
          utilizableTotal: 0,
          utilization: null,
          byVehicleType: {
            200: {
              activeLocalsCouriers: 0,
              activeNonLocalsCouriers: 0,
              planned: 0,
              total: 1,
              free: 0,
              busy: 1,
              onOrder: 0,
              canceled: 0,
              utilized: 0,
              utilizableTotal: 0,
              utilization: null,
            },
            400: {
              activeLocalsCouriers: 0,
              activeNonLocalsCouriers: 0,
              planned: 0,
              total: 0,
              free: 0,
              busy: 0,
              onOrder: 0,
              canceled: 0,
              utilized: 0,
              utilizableTotal: 0,
              utilization: 0,
            },
          },
          activeLocalsCouriers: 0,
          activeNonLocalsCouriers: 0,
          activeLocalsCouriersByVehicleType: {},
          activeNonLocalsCouriersByVehicleType: {},
        },
      ],
    },
    domainType: {
      2: {
        warehousesMap: {
          '5f106c400d13cdb987c60368': {
            planned: 0,
            total: 1,
            free: 0,
            busy: 1,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: null,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 1,
                free: 0,
                busy: 1,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: null,
                isGFLOrder: true,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: true,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
        },
        total: {
          planned: 4,
          total: 23,
          free: 5,
          busy: 6,
          onOrder: 2,
          canceled: 8,
          utilized: 7,
          utilizableTotal: 10,
          utilization: 70,
          byVehicleType: {
            200: {
              activeLocalsCouriers: 2,
              activeNonLocalsCouriers: 0,
              planned: 2,
              total: 13,
              free: 4,
              busy: 4,
              onOrder: 2,
              canceled: 3,
              utilized: 3,
              utilizableTotal: 5,
              utilization: 60,
            },
            400: {
              activeLocalsCouriers: 0,
              activeNonLocalsCouriers: 0,
              planned: 2,
              total: 10,
              free: 1,
              busy: 2,
              onOrder: 0,
              canceled: 5,
              utilized: 4,
              utilizableTotal: 5,
              utilization: 80,
            },
          },
          activeLocalsCouriers: 2,
          activeNonLocalsCouriers: 0,
          activeLocalsCouriersByVehicleType: { 200: 2 },
          activeNonLocalsCouriersByVehicleType: {},
        },
      },
      6: {
        warehousesMap: {
          '6093cc112410f30974d6a65a': {
            planned: 0,
            total: 10,
            free: 1,
            busy: 4,
            onOrder: 3,
            canceled: 1,
            utilized: 4,
            utilizableTotal: 5,
            utilization: 80,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 5,
                free: 0,
                busy: 3,
                onOrder: 0,
                canceled: 1,
                utilized: 1,
                utilizableTotal: 1,
                utilization: 100,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 3,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 5,
                free: 1,
                busy: 1,
                onOrder: 3,
                canceled: 0,
                utilized: 3,
                utilizableTotal: 4,
                utilization: 75,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 3,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: { 400: 3 },
            activeNonLocalsCouriersByVehicleType: {},
          },
          '6093db3c2410f3d8ebd6a65b': {
            planned: 0,
            total: 0,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '60d5b4e176ebb4e8c8b4a697': {
            planned: 0,
            total: 0,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '60dd83175264cc125a67f041': {
            planned: 0,
            total: 0,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '60edf860e931398cdb0ae97c': {
            planned: 0,
            total: 2,
            free: 1,
            busy: 0,
            onOrder: 1,
            canceled: 0,
            utilized: 1,
            utilizableTotal: 2,
            utilization: 50,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 1,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 2,
                free: 1,
                busy: 0,
                onOrder: 1,
                canceled: 0,
                utilized: 1,
                utilizableTotal: 2,
                utilization: 50,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 1,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: { 400: 1 },
            activeNonLocalsCouriersByVehicleType: {},
          },
          '611f56a07727335cd2cec60b': {
            planned: 0,
            total: 1,
            free: 1,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 1,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 1,
                free: 1,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 1,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '6137afbeffd3741e046c575f': {
            planned: 0,
            total: 11,
            free: 3,
            busy: 0,
            onOrder: 6,
            canceled: 2,
            utilized: 8,
            utilizableTotal: 11,
            utilization: 72.72727272727273,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 6,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 11,
                free: 3,
                busy: 0,
                onOrder: 6,
                canceled: 2,
                utilized: 8,
                utilizableTotal: 11,
                utilization: 72.72727272727273,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 6,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: { 200: 6 },
            activeNonLocalsCouriersByVehicleType: {},
          },
          '613a0abd97ae43bbf6d070be': {
            planned: 0,
            total: 12,
            free: 6,
            busy: 0,
            onOrder: 5,
            canceled: 1,
            utilized: 6,
            utilizableTotal: 12,
            utilization: 50,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 4,
                activeNonLocalsCouriers: 1,
                planned: 0,
                total: 12,
                free: 6,
                busy: 0,
                onOrder: 5,
                canceled: 1,
                utilized: 6,
                utilizableTotal: 12,
                utilization: 50,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 4,
            activeNonLocalsCouriers: 1,
            activeLocalsCouriersByVehicleType: { 200: 4 },
            activeNonLocalsCouriersByVehicleType: { 200: 1 },
          },
          '61a0cfc5c066ae7b8d147415': {
            planned: 0,
            total: 1,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 1,
            utilized: 1,
            utilizableTotal: 1,
            utilization: 100,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 1,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 1,
                utilized: 1,
                utilizableTotal: 1,
                utilization: 100,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '61af6c97cb539007458c5387': {
            planned: 0,
            total: 2,
            free: 2,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 2,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 2,
                free: 2,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 2,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '61b3028dcb539049039acdbf': {
            planned: 0,
            total: 0,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '61d41c5688e570230fb75aeb': {
            planned: 0,
            total: 0,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '61dd297d0e8a06241d35b508': {
            planned: 0,
            total: 31,
            free: 11,
            busy: 0,
            onOrder: 10,
            canceled: 10,
            utilized: 20,
            utilizableTotal: 31,
            utilization: 64.51612903225806,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 10,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 31,
                free: 11,
                busy: 0,
                onOrder: 10,
                canceled: 10,
                utilized: 20,
                utilizableTotal: 31,
                utilization: 64.51612903225806,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 10,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: { 200: 10 },
            activeNonLocalsCouriersByVehicleType: {},
          },
          '61e5502bf3bcaca1c02eb896': {
            planned: 0,
            total: 1,
            free: 0,
            busy: 1,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: null,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 1,
                free: 0,
                busy: 1,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: null,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '62a75d968ddbb4d58f7db53b': {
            planned: 0,
            total: 0,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '62a8bb53a80b101ff47de3a0': {
            planned: 0,
            total: 2,
            free: 1,
            busy: 1,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 1,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 1,
                free: 0,
                busy: 1,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: null,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 1,
                free: 1,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 1,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '62b7104a479b3342d660ef54': {
            planned: 0,
            total: 0,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '62b9ae42bcf044ed82b126f0': {
            planned: 0,
            total: 0,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '62ff26f1d6d3a4d74d7301c2': {
            planned: 0,
            total: 0,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '633da0b52e03899212d74a5e': {
            planned: 0,
            total: 0,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '637b93c4ed91317aecebafd7': {
            planned: 0,
            total: 0,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '637b943ced9131a6d1ebb223': {
            planned: 0,
            total: 0,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '63982759577d3ebd63047d55': {
            planned: 0,
            total: 1,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 1,
            utilized: 1,
            utilizableTotal: 1,
            utilization: 100,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 1,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 1,
                utilized: 1,
                utilizableTotal: 1,
                utilization: 100,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '63a301614c77c38f2d58a83d': {
            planned: 0,
            total: 6,
            free: 2,
            busy: 3,
            onOrder: 0,
            canceled: 1,
            utilized: 1,
            utilizableTotal: 3,
            utilization: 33.33333333333333,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 6,
                free: 2,
                busy: 3,
                onOrder: 0,
                canceled: 1,
                utilized: 1,
                utilizableTotal: 3,
                utilization: 33.33333333333333,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '63a405024c77c33ea55a7059': {
            planned: 0,
            total: 1,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: null,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 1,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: null,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '63b472a4fda518e631341c17': {
            planned: 0,
            total: 0,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '63d7a27a0869ac607b54bccf': {
            planned: 0,
            total: 2,
            free: 2,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 2,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 2,
                free: 2,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 2,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '6411cbf489887765f100e105': {
            planned: 0,
            total: 1,
            free: 1,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 1,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 1,
                free: 1,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 1,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '641497b64f0eb9c573010130': {
            planned: 0,
            total: 1,
            free: 1,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 1,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 1,
                free: 1,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 1,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '641aee61a76dda799bc268fa': {
            planned: 0,
            total: 0,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '644933d4d24e5818046185bb': {
            planned: 0,
            total: 0,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '6459ef1339c3cb1efa45df31': {
            planned: 0,
            total: 1,
            free: 1,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 1,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 1,
                free: 1,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 1,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
                isGFLOrder: false,
                onGFLOrder: 0,
                onGLOrder: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
        },
        total: {
          planned: 0,
          total: 86,
          free: 33,
          busy: 9,
          onOrder: 25,
          canceled: 17,
          utilized: 42,
          utilizableTotal: 75,
          utilization: 56.00000000000001,
          byVehicleType: {
            200: {
              activeLocalsCouriers: 20,
              activeNonLocalsCouriers: 1,
              planned: 0,
              total: 76,
              free: 29,
              busy: 7,
              onOrder: 21,
              canceled: 17,
              utilized: 38,
              utilizableTotal: 67,
              utilization: 56.71641791044776,
            },
            400: {
              activeLocalsCouriers: 4,
              activeNonLocalsCouriers: 0,
              planned: 0,
              total: 10,
              free: 4,
              busy: 2,
              onOrder: 4,
              canceled: 0,
              utilized: 4,
              utilizableTotal: 8,
              utilization: 50,
            },
          },
          activeLocalsCouriers: 24,
          activeNonLocalsCouriers: 1,
          activeLocalsCouriersByVehicleType: {
            200: 20,
            400: 4,
          },
          activeNonLocalsCouriersByVehicleType: { 200: 1 },
        },
      },
    },
  },
  byCountryCodes: {
    TR: {
      total: {
        total: {
          planned: 4,
          total: 116,
          free: 38,
          busy: 17,
          onOrder: 28,
          canceled: 29,
          utilized: 50,
          utilizableTotal: 88,
          utilization: 56.81818181818182,
          byVehicleType: {
            200: {
              activeLocalsCouriers: 22,
              activeNonLocalsCouriers: 2,
              planned: 2,
              total: 95,
              free: 33,
              busy: 13,
              onOrder: 24,
              canceled: 23,
              utilized: 41,
              utilizableTotal: 74,
              utilization: 55.4054054054054,
            },
            400: {
              activeLocalsCouriers: 4,
              activeNonLocalsCouriers: 0,
              planned: 2,
              total: 21,
              free: 5,
              busy: 4,
              onOrder: 4,
              canceled: 6,
              utilized: 9,
              utilizableTotal: 14,
              utilization: 64.28571428571429,
            },
          },
          activeLocalsCouriers: 26,
          activeNonLocalsCouriers: 2,
          activeLocalsCouriersByVehicleType: {
            200: 22,
            400: 4,
          },
          activeNonLocalsCouriersByVehicleType: { 200: 2 },
        },
        warehouses: [
          {
            warehouseId: '5f106c400d13cdb987c60368',
            planned: 0,
            total: 1,
            free: 0,
            busy: 1,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: null,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 1,
                free: 0,
                busy: 1,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: null,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
        ],
      },
      domainType: {
        2: {
          total: {
            planned: 4,
            total: 23,
            free: 5,
            busy: 6,
            onOrder: 2,
            canceled: 8,
            utilized: 7,
            utilizableTotal: 10,
            utilization: 70,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 2,
                activeNonLocalsCouriers: 0,
                planned: 2,
                total: 13,
                free: 4,
                busy: 4,
                onOrder: 2,
                canceled: 3,
                utilized: 3,
                utilizableTotal: 5,
                utilization: 60,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 2,
                total: 10,
                free: 1,
                busy: 2,
                onOrder: 0,
                canceled: 5,
                utilized: 4,
                utilizableTotal: 5,
                utilization: 80,
              },
            },
            activeLocalsCouriers: 2,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: { 200: 2 },
            activeNonLocalsCouriersByVehicleType: {},
          },
          warehousesMap: {
            '5f106c400d13cdb987c60368': {
              planned: 0,
              total: 1,
              free: 0,
              busy: 1,
              onOrder: 0,
              canceled: 0,
              utilized: 0,
              utilizableTotal: 0,
              utilization: null,
              byVehicleType: {
                200: {
                  activeLocalsCouriers: 0,
                  activeNonLocalsCouriers: 0,
                  planned: 0,
                  total: 1,
                  free: 0,
                  busy: 1,
                  onOrder: 0,
                  canceled: 0,
                  utilized: 0,
                  utilizableTotal: 0,
                  utilization: null,
                },
                400: {
                  activeLocalsCouriers: 0,
                  activeNonLocalsCouriers: 0,
                  planned: 0,
                  total: 0,
                  free: 0,
                  busy: 0,
                  onOrder: 0,
                  canceled: 0,
                  utilized: 0,
                  utilizableTotal: 0,
                  utilization: 0,
                },
              },
              activeLocalsCouriers: 0,
              activeNonLocalsCouriers: 0,
              activeLocalsCouriersByVehicleType: {},
              activeNonLocalsCouriersByVehicleType: {},
            },
          },
        },
      },
    },
  },
  '55999ad00000010001000000': {
    total: {
      total: {
        planned: 4,
        total: 59,
        free: 13,
        busy: 12,
        onOrder: 15,
        canceled: 16,
        utilized: 26,
        utilizableTotal: 39,
        utilization: 66.66666666666666,
        byVehicleType: {
          200: {
            activeLocalsCouriers: 10,
            activeNonLocalsCouriers: 2,
            planned: 2,
            total: 43,
            free: 12,
            busy: 8,
            onOrder: 12,
            canceled: 10,
            utilized: 18,
            utilizableTotal: 30,
            utilization: 60,
          },
          400: {
            activeLocalsCouriers: 3,
            activeNonLocalsCouriers: 0,
            planned: 2,
            total: 16,
            free: 1,
            busy: 4,
            onOrder: 3,
            canceled: 6,
            utilized: 8,
            utilizableTotal: 9,
            utilization: 88.88888888888889,
          },
        },
        activeLocalsCouriers: 13,
        activeNonLocalsCouriers: 2,
        activeLocalsCouriersByVehicleType: {
          200: 10,
          400: 3,
        },
        activeNonLocalsCouriersByVehicleType: { 200: 2 },
      },
      warehouses: [
        {
          warehouseId: '5f106c400d13cdb987c60368',
          planned: 0,
          total: 1,
          free: 0,
          busy: 1,
          onOrder: 0,
          canceled: 0,
          utilized: 0,
          utilizableTotal: 0,
          utilization: null,
          byVehicleType: {
            200: {
              activeLocalsCouriers: 0,
              activeNonLocalsCouriers: 0,
              planned: 0,
              total: 1,
              free: 0,
              busy: 1,
              onOrder: 0,
              canceled: 0,
              utilized: 0,
              utilizableTotal: 0,
              utilization: null,
            },
            400: {
              activeLocalsCouriers: 0,
              activeNonLocalsCouriers: 0,
              planned: 0,
              total: 0,
              free: 0,
              busy: 0,
              onOrder: 0,
              canceled: 0,
              utilized: 0,
              utilizableTotal: 0,
              utilization: 0,
            },
          },
          activeLocalsCouriers: 0,
          activeNonLocalsCouriers: 0,
          activeLocalsCouriersByVehicleType: {},
          activeNonLocalsCouriersByVehicleType: {},
        },
      ],
    },
    domainType: {
      2: {
        total: {
          planned: 4,
          total: 16,
          free: 2,
          busy: 5,
          onOrder: 0,
          canceled: 7,
          utilized: 6,
          utilizableTotal: 7,
          utilization: 85.71428571428571,
          byVehicleType: {
            200: {
              activeLocalsCouriers: 0,
              activeNonLocalsCouriers: 0,
              planned: 2,
              total: 7,
              free: 2,
              busy: 3,
              onOrder: 0,
              canceled: 2,
              utilized: 2,
              utilizableTotal: 3,
              utilization: 66.66666666666666,
            },
            400: {
              activeLocalsCouriers: 0,
              activeNonLocalsCouriers: 0,
              planned: 2,
              total: 9,
              free: 0,
              busy: 2,
              onOrder: 0,
              canceled: 5,
              utilized: 4,
              utilizableTotal: 4,
              utilization: 100,
            },
          },
          activeLocalsCouriers: 0,
          activeNonLocalsCouriers: 0,
          activeLocalsCouriersByVehicleType: {},
          activeNonLocalsCouriersByVehicleType: {},
        },
        warehousesMap: {
          '5f106c400d13cdb987c60368': {
            planned: 0,
            total: 1,
            free: 0,
            busy: 1,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: null,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 1,
                free: 0,
                busy: 1,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: null,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
        },
      },
      3: {
        total: {
          planned: 0,
          total: 7,
          free: 0,
          busy: 2,
          onOrder: 1,
          canceled: 4,
          utilized: 0,
          utilizableTotal: 0,
          utilization: 0,
          byVehicleType: {
            200: {
              activeLocalsCouriers: 0,
              activeNonLocalsCouriers: 1,
              planned: 0,
              total: 6,
              free: 0,
              busy: 2,
              onOrder: 1,
              canceled: 3,
              utilized: 0,
              utilizableTotal: 0,
              utilization: 0,
            },
            400: {
              activeLocalsCouriers: 0,
              activeNonLocalsCouriers: 0,
              planned: 0,
              total: 1,
              free: 0,
              busy: 0,
              onOrder: 0,
              canceled: 1,
              utilized: 0,
              utilizableTotal: 0,
              utilization: 0,
            },
          },
          activeLocalsCouriers: 0,
          activeNonLocalsCouriers: 1,
          activeLocalsCouriersByVehicleType: {},
          activeNonLocalsCouriersByVehicleType: { 200: 1 },
        },
        warehousesMap: {
          '55646fc47051560c00cc8398': {
            planned: 0,
            total: 5,
            free: 0,
            busy: 0,
            onOrder: 1,
            canceled: 4,
            utilized: 0,
            utilizableTotal: 0,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 1,
                planned: 0,
                total: 4,
                free: 0,
                busy: 0,
                onOrder: 1,
                canceled: 3,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 1,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 1,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 1,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: { 200: 1 },
          },
          '5e8b2deb5b63c6e3b1b13d40': {
            planned: 0,
            total: 0,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '5db97c5252caa9bcc6603143': {
            planned: 0,
            total: 0,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '5f297238b5656f1cd6358c54': {
            planned: 0,
            total: 1,
            free: 0,
            busy: 1,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 1,
                free: 0,
                busy: 1,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '602fa06d94f5a2adb186b98f': {
            planned: 0,
            total: 1,
            free: 0,
            busy: 1,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 1,
                free: 0,
                busy: 1,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
        },
      },
      6: {
        total: {
          planned: 0,
          total: 36,
          free: 11,
          busy: 5,
          onOrder: 14,
          canceled: 5,
          utilized: 19,
          utilizableTotal: 30,
          utilization: 63.33333333333333,
          byVehicleType: {
            200: {
              activeLocalsCouriers: 10,
              activeNonLocalsCouriers: 1,
              planned: 0,
              total: 30,
              free: 10,
              busy: 3,
              onOrder: 11,
              canceled: 5,
              utilized: 16,
              utilizableTotal: 26,
              utilization: 61.53846153846154,
            },
            400: {
              activeLocalsCouriers: 3,
              activeNonLocalsCouriers: 0,
              planned: 0,
              total: 6,
              free: 1,
              busy: 2,
              onOrder: 3,
              canceled: 0,
              utilized: 3,
              utilizableTotal: 4,
              utilization: 75,
            },
          },
          activeLocalsCouriers: 13,
          activeNonLocalsCouriers: 1,
          activeLocalsCouriersByVehicleType: {
            200: 10,
            400: 3,
          },
          activeNonLocalsCouriersByVehicleType: { 200: 1 },
        },
        warehousesMap: {
          '6093cc112410f30974d6a65a': {
            planned: 0,
            total: 10,
            free: 1,
            busy: 4,
            onOrder: 3,
            canceled: 1,
            utilized: 4,
            utilizableTotal: 5,
            utilization: 80,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 5,
                free: 0,
                busy: 3,
                onOrder: 0,
                canceled: 1,
                utilized: 1,
                utilizableTotal: 1,
                utilization: 100,
              },
              400: {
                activeLocalsCouriers: 3,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 5,
                free: 1,
                busy: 1,
                onOrder: 3,
                canceled: 0,
                utilized: 3,
                utilizableTotal: 4,
                utilization: 75,
              },
            },
            activeLocalsCouriers: 3,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: { 400: 3 },
            activeNonLocalsCouriersByVehicleType: {},
          },
          '611f56a07727335cd2cec60b': {
            planned: 0,
            total: 1,
            free: 1,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 1,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 1,
                free: 1,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 1,
                utilization: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '6137afbeffd3741e046c575f': {
            planned: 0,
            total: 11,
            free: 3,
            busy: 0,
            onOrder: 6,
            canceled: 2,
            utilized: 8,
            utilizableTotal: 11,
            utilization: 72.72727272727273,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 6,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 11,
                free: 3,
                busy: 0,
                onOrder: 6,
                canceled: 2,
                utilized: 8,
                utilizableTotal: 11,
                utilization: 72.72727272727273,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
            },
            activeLocalsCouriers: 6,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: { 200: 6 },
            activeNonLocalsCouriersByVehicleType: {},
          },
          '613a0abd97ae43bbf6d070be': {
            planned: 0,
            total: 12,
            free: 6,
            busy: 0,
            onOrder: 5,
            canceled: 1,
            utilized: 6,
            utilizableTotal: 12,
            utilization: 50,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 4,
                activeNonLocalsCouriers: 1,
                planned: 0,
                total: 12,
                free: 6,
                busy: 0,
                onOrder: 5,
                canceled: 1,
                utilized: 6,
                utilizableTotal: 12,
                utilization: 50,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
            },
            activeLocalsCouriers: 4,
            activeNonLocalsCouriers: 1,
            activeLocalsCouriersByVehicleType: { 200: 4 },
            activeNonLocalsCouriersByVehicleType: { 200: 1 },
          },
          '61a0cfc5c066ae7b8d147415': {
            planned: 0,
            total: 1,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 1,
            utilized: 1,
            utilizableTotal: 1,
            utilization: 100,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 1,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 1,
                utilized: 1,
                utilizableTotal: 1,
                utilization: 100,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '61d41c5688e570230fb75aeb': {
            planned: 0,
            total: 0,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '61e5502bf3bcaca1c02eb896': {
            planned: 0,
            total: 1,
            free: 0,
            busy: 1,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: null,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 1,
                free: 0,
                busy: 1,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: null,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '62a75d968ddbb4d58f7db53b': {
            planned: 0,
            total: 0,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '62b7104a479b3342d660ef54': {
            planned: 0,
            total: 0,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '62b9ae42bcf044ed82b126f0': {
            planned: 0,
            total: 0,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
          '633da0b52e03899212d74a5e': {
            planned: 0,
            total: 0,
            free: 0,
            busy: 0,
            onOrder: 0,
            canceled: 0,
            utilized: 0,
            utilizableTotal: 0,
            utilization: 0,
            byVehicleType: {
              200: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
              400: {
                activeLocalsCouriers: 0,
                activeNonLocalsCouriers: 0,
                planned: 0,
                total: 0,
                free: 0,
                busy: 0,
                onOrder: 0,
                canceled: 0,
                utilized: 0,
                utilizableTotal: 0,
                utilization: 0,
              },
            },
            activeLocalsCouriers: 0,
            activeNonLocalsCouriers: 0,
            activeLocalsCouriersByVehicleType: {},
            activeNonLocalsCouriersByVehicleType: {},
          },
        },
      },
    },
  },
};

export const MOCKED_FORMATTED_DATA = {
  '55999ad00000010001000000': {
    200: {
      activeLocalsCouriers: 0,
      activeNonLocalsCouriers: 0,
      planned: 0,
      total: 1,
      free: 0,
      busy: 1,
      onGLOrder: 0,
      canceled: 0,
      utilized: 0,
      utilizableTotal: 0,
      utilization: 0,
      isGFLOrder: 1,
      onGFLOrder: 0,
    },
    400: {
      activeLocalsCouriers: 0,
      activeNonLocalsCouriers: 0,
      planned: 0,
      total: 0,
      free: 0,
      busy: 0,
      onGLOrder: 0,
      canceled: 0,
      utilized: 0,
      utilizableTotal: 0,
      utilization: 0,
      isGFLOrder: 1,
      onGFLOrder: 0,
    },
    warehouses: {
      '5f106c400d13cdb987c60368': {
        200: {
          activeLocalsCouriers: 0,
          activeNonLocalsCouriers: 0,
          planned: 0,
          total: 1,
          free: 0,
          busy: 1,
          onGFLOrder: 0,
          canceled: 0,
          utilized: 0,
          utilizableTotal: 0,
          utilization: 0,
          isGFLOrder: 1,
          onGLOrder: 0,
        },
        400: {
          activeLocalsCouriers: 0,
          activeNonLocalsCouriers: 0,
          planned: 0,
          total: 0,
          free: 0,
          busy: 0,
          onGFLOrder: 0,
          canceled: 0,
          utilized: 0,
          utilizableTotal: 0,
          utilization: 0,
          isGFLOrder: 1,
          onGLOrder: 0,
        },
      },
    },
  },
};

export const MOCKED_LOCALS_WAREHOUSE = {
  domainTypes: [
    2,
    6,
  ],
};
