import { CLIENT_APP_ACTION_TYPE } from '@shared/containers/Marketing/ClientAppActions/constants';
import {
  GETIR_BITAKSI_DOMAIN_TYPE, GETIR_DRIVE_DOMAIN_TYPE, GETIR_FINANCE_DOMAIN_TYPE,
  GETIR_FOOD_DOMAIN_TYPE, GETIR_GORILLAS_DOMAIN_TYPE, GETIR_JOB_DOMAIN_TYPE, GETIR_LOCALS_DOMAIN_TYPE,
  GETIR_MALL_DOMAIN_TYPE,
  GETIR_N11_DOMAIN_TYPE, GETIR_N11_QUICK_DOMAIN_TYPE, GETIR_SELECT_DOMAIN_TYPE,
  GETIR_VOYAGER_DOMAIN_TYPE, GETIR_WATER_MARKETPLACE_DOMAIN_TYPE, GORILLAS_INTEGRATION_TYPE,
} from '@shared/shared/constants';

export const NOTIFICATION_IMAGE_VALIDATION = {
  maxWidth: 2000,
  minWidth: 300,
  minHeight: 300,
  imageRatios: ['2:1'],
  maxImageSizeInMB: 1,
};

export const NOTIFICATION_STATUS = {
  ACTIVE: 1,
  INACTIVE: 2,
};

export const NOTIFICATION_PROCESS_STATUS = {
  CREATED: 1,
  PRE_PROCESS: 2, // WARMING
  READY: 3,
  IN_PROCESS: 4,
  PAUSE: 5,
  CANCEL: 6,
  DAILY_COMPLETED: 7,
  FAIL: 9,
  GLOBAL_PAUSE: 10,
  DAILY_FINISHED: 11,
  FINISHED: 12,
};

export const NOTIFICATION_ACTION = {
  DETAIL: 'DETAIL',
  CANCEL: 'CANCEL',
  PAUSE: 'PAUSE',
  RESUME: 'RESUME',
  DUPLICATE: 'DUPLICATE',
  DELETE: 'DELETE',
  DOWNLOAD_LIST: 'DOWNLOAD_LIST',
};

export const FOOD_PROMO_SEARCH_FIELDS = {
  sortField: 'validityPeriod.validFrom',
  sortType: '1',
  limit: 10,
  page: '1',
};

export const PUSH_NOTIFICATION_RULES = {
  WITHOUT_DAILY_LIMIT: 1,
  WITHOUT_SERVICE_LIMIT: 2,
  WITHOUT_FREQUENCY_LIMIT: 3,
};

export const NOTIFICATION_GLOBAL_STATUS = {
  ACTIVE: 1,
  PASSIVE: 2,
};

export const NOTIFICATION_SEND_TYPE = {
  ONE_SHOT: 1,
  PARTIAL: 2,
  DAILY: 3,
};

export const USER_INFORMATION_PROGRESS = {
  IN_PROGRESS: 1,
  COMPLETE: 2,
};

export const NOTIFICATION_OPTION_TYPES = {
  PROMO: 1,
  GENERIC: 3,
  AI: 4,
};

export const FILE_UPLOAD_TYPE = {
  DRAFT: 'template',
  EXCLUDED_DRAFT: 'excludedTemplate',
};

export const INACTIVE_ACTIONS = [
  CLIENT_APP_ACTION_TYPE.OPEN_APP,

  CLIENT_APP_ACTION_TYPE.CLOSE,
  CLIENT_APP_ACTION_TYPE.ADD_TO_BASKET,
  CLIENT_APP_ACTION_TYPE.PHONE_CALL,
  CLIENT_APP_ACTION_TYPE.LOYALTY_DETAIL,
  CLIENT_APP_ACTION_TYPE.RESTAURANT_LIST,
  CLIENT_APP_ACTION_TYPE.RESTAURANT_PRODUCT,
  CLIENT_APP_ACTION_TYPE.RESTAURANT_FILTER,
  CLIENT_APP_ACTION_TYPE.FOOD_ORDER_LIST,
  CLIENT_APP_ACTION_TYPE.ARTISAN_LOYALTY_DETAIL,
  CLIENT_APP_ACTION_TYPE.GIVEAWAY_EVENT,
  CLIENT_APP_ACTION_TYPE.WATER_PRODUCT_LIST,
  CLIENT_APP_ACTION_TYPE.WATER_PRODUCT,
];

export const MERCHANT_LIST = {
  SHOW_ALL_CHAIN_MERCHANTS: 1,
  SHOW_SPECIFIC_CHAIN_MERCHANTS: 2,
  SHOW_SPECIFIC_MERCHANT_TYPE: 3,
};

export const SENDING_MINIMUM_DATE_DIFF_MINUTE = 15;

export const MINUTE_IN_HOUR = 60;

export const TEMPLATE_FIELDS = [FILE_UPLOAD_TYPE.DRAFT, FILE_UPLOAD_TYPE.EXCLUDED_DRAFT];

export const NOTIF_REGION = { NO_REGION: 1, ALL_SERVICE_AREAS: 2, ONLY_SELECTED_SERVICE_AREA: 3 };

export const STATE_STORE_TYPE = { FULFILL: 'fulfill', APPEND: 'append' };

export const NOTIFICATION_DATE_FORMAT = 'YYYY/MM/DD HH:mm';

export const NOTIF_CENTER_HOURLY_TTL = {
  DEFAULT: 336, // 14 Days,
  MAX: 720, // 30 Days,
  MIN: 1,
};

export const DAYS_OF_WEEKS = {
  SUNDAY: 1,
  MONDAY: 2,
  TUESDAY: 3,
  WEDNESDAY: 4,
  THURSDAY: 5,
  FRIDAY: 6,
  SATURDAY: 7,
};

export const CONTROLLER = {
  STOCK_LEVEL_CONTROLLER: 1,
  AGGRESSION_LEVEL_CONTROLLER: 2,
  LOCATION_BASED_CONTROLLER: 3,
};

export const AI_MARKETING_UNSUPPORTED_DOMAIN_LIST = [
  GETIR_FOOD_DOMAIN_TYPE,
  GETIR_VOYAGER_DOMAIN_TYPE,
  GETIR_MALL_DOMAIN_TYPE,
  GETIR_LOCALS_DOMAIN_TYPE,
  GETIR_BITAKSI_DOMAIN_TYPE,
  GETIR_WATER_MARKETPLACE_DOMAIN_TYPE,
  GETIR_JOB_DOMAIN_TYPE,
  GETIR_DRIVE_DOMAIN_TYPE,
  GETIR_N11_DOMAIN_TYPE,
  GETIR_N11_QUICK_DOMAIN_TYPE,
  GETIR_FINANCE_DOMAIN_TYPE,
  GETIR_SELECT_DOMAIN_TYPE,
  GETIR_GORILLAS_DOMAIN_TYPE,
  GORILLAS_INTEGRATION_TYPE,
];
