import { REDUX_STORE_KEYS } from '@app/pages/MarketProductChainManagement/constants';

export const STORE_KEY = REDUX_STORE_KEYS.DARK_STORE_CENTRAL_WAREHOUSES_TABLE;

export const PREFIX = `marketProductChain/${STORE_KEY}`;

export const ACTION_TYPES = {
  FETCH_CENTRAL_WAREHOUSES_REQUEST: `${PREFIX}/FETCH_CENTRAL_WAREHOUSES_REQUEST`,
  FETCH_CENTRAL_WAREHOUSES_SUCCESS: `${PREFIX}/FETCH_CENTRAL_WAREHOUSES_SUCCESS`,
  FETCH_CENTRAL_WAREHOUSES_FAILURE: `${PREFIX}/FETCH_CENTRAL_WAREHOUSES_FAILURE`,

  FETCH_DOMAIN_TYPES_REQUEST: `${PREFIX}/FETCH_DOMAIN_TYPES_REQUEST`,
  FETCH_DOMAIN_TYPES_SUCCESS: `${PREFIX}/FETCH_DOMAIN_TYPES_SUCCESS`,
  FETCH_DOMAIN_TYPES_FAILURE: `${PREFIX}/FETCH_DOMAIN_TYPES_FAILURE`,

  FETCH_CITIES_REQUEST: `${PREFIX}/FETCH_CITIES_REQUEST`,
  FETCH_CITIES_SUCCESS: `${PREFIX}/FETCH_CITIES_SUCCESS`,
  FETCH_CITIES_FAILURE: `${PREFIX}/FETCH_CITIES_FAILURE`,

  FETCH_DEMOGRAPHIES_REQUEST: `${PREFIX}/FETCH_DEMOGRAPHIES_REQUEST`,
  FETCH_DEMOGRAPHIES_SUCCESS: `${PREFIX}/FETCH_DEMOGRAPHIES_SUCCESS`,
  FETCH_DEMOGRAPHIES_FAILURE: `${PREFIX}/FETCH_DEMOGRAPHIES_FAILURE`,

  UPDATE_FILTERS: `${PREFIX}/UPDATE_FILTERS`,
  UPDATE_PAGINATION: `${PREFIX}/UPDATE_PAGINATION`,
  UPDATE_SORT: `${PREFIX}/UPDATE_SORT`,

  REFRESH_CENTRAL_WAREHOUSES_REQUEST: `${PREFIX}/REFRESH_CENTRAL_WAREHOUSES_REQUEST`,
} as const;
