export const ACTIVE_TAB = '1';
export const COMPLETE_TAB = '2';

export const NOTIFICATION_STATUS = {
  PENDING_NOTIFICATION: 100,
  RUNNING_NOTIFICATION: 200,
  COMPLETED_NOTIFICATION: 300,
  FAILED_NOTIFICATION: 400,
};
