import { createActions } from 'reduxsauce';

import { REDUX_KEY } from '@shared/shared/constants';

export const { Types, Creators } = createActions(
  {
    getBasketDetailRequest: { basketOrderId: null },
    getBasketDetailSuccess: { data: {} },
    getBasketDetailFailure: { error: null },
    getOrderDetailRequest: { orderDetailId: null },
    getOrderDetailSuccess: { data: {} },
    getOrderDetailFailure: { error: null },
    getOrderCancelSourcesRequest: { orderDetailId: null },
    getOrderCancelSourcesSuccess: { data: {} },
    getOrderCancelSourcesFailure: { error: null },
    getOrderCancelOptionRequest: { orderDetailId: null },
    getOrderCancelOptionSuccess: { data: [] },
    getOrderCancelOptionFailure: { error: null },
    orderCancelRequest: { body: null, requestSource: null, cancelSource: null },
    orderCancelSuccess: { data: [] },
    orderCancelFailure: { error: null },
    exportFinancialInfoRequest: { financialInfo: {} },
    exportFinancialInfoSuccess: {},
    exportFinancialInfoFailure: { error: null },
    getOrderChangeOptionsRequest: { orderDetailId: null },
    getOrderChangeOptionsSuccess: { data: [] },
    getOrderChangeOptionsFailure: { error: null },
    getAvailableChangeTypesForOrderRequest: { foodOrderId: null },
    getAvailableChangeTypesForOrderSuccess: { data: {} },
    getAvailableChangeTypesForOrderFailure: { error: null },
    addChangeReasonAtOrderRequest: { body: null, foodOrderId: null },
    addChangeReasonAtOrderSuccess: { data: [] },
    addChangeReasonAtOrderFailure: { error: null },
    updateChangeReasonAtOrderRequest: { body: null, foodOrderId: null },
    updateChangeReasonAtOrderSuccess: { data: [] },
    updateChangeReasonAtOrderFailure: { error: null },
    getMainReasonsRequest: null,
    getMainReasonsSuccess: { data: [] },
    getMainReasonsFailure: { error: null },
    getSubReasonsRequest: { id: null },
    getSubReasonsSuccess: { data: [] },
    getSubReasonsFailure: { error: null },
    getSubReasonRequest: { id: null },
    getSubReasonSuccess: { data: {} },
    getSubReasonFailure: { error: null },
    getRefundSourcesRequest: { foodOrderId: '' },
    getRefundSourcesSuccess: { data: [] },
    getRefundSourcesFailure: { error: null },
    getClientTrustScoreRequest: { body: null },
    getClientTrustScoreSuccess: { data: null },
    getClientTrustScoreFailure: { error: null },
    setInquiryRequest: { body: null },
    setInquirySuccess: null,
    setInquiryFailure: { error: null },
    getUserByIdRequest: { id: null },
    getUserByIdSuccess: { data: {} },
    getUserByIdFailure: { error: null },
    getOrderInsightInquiryRequest: { foodOrderId: '' },
    getOrderInsightInquirySuccess: { data: [] },
    getOrderInsightInquiryFailure: { error: null },
    getOrderNoteRequest: { data: null },
    getOrderNoteSuccess: { data: [] },
    getOrderNoteFailure: { error: null },
    createOrderNoteRequest: { data: null },
    createOrderNoteSuccess: { data: [] },
    createOrderNoteFailure: { error: null },
    createForbiddenMatchRequest: { client: '', description: '', person: '' },
    createForbiddenMatchSuccess: { data: [] },
    createForbiddenMatchFailure: { error: null },
    getOrderCourierJsonRequest: { foodBasketIds: null },
    getOrderCourierJsonSuccess: { data: {} },
    getOrderCourierJsonFailure: { error: null },
    getOrderFinancialsRequest: { orderDetailId: null },
    getOrderFinancialsSuccess: { data: {} },
    getOrderFinancialsFailure: { error: null },
    getAgreementDataRequest: { foodOrderId: null, clientId: null },
    getAgreementDataSuccess: { data: {} },
    getAgreementDataFailure: { error: null },
    getCourierRouteRequest: { foodOrderId: null },
    getCourierRouteSuccess: { data: {} },
    getCourierRouteFailure: { error: null },
    initPage: null,
    destroyPage: null,
  },
  { prefix: `${REDUX_KEY.FOOD_ORDER.DETAIL}_` },
);
