import { targetListValues } from '../../../constants';

export const defaultValues = { target: targetListValues.GETIRWATER_MARKETPLACE };

export const validationSchema = {
  target: [{ required: true }],
  announementPriority: [{ required: true }],
  titleTr: [{ required: true }],
  titleEn: [{ required: true }],
  isButtonEnabled: [{ required: true }],
  buttonTextTr: [{ required: true }],
  buttonTextEn: [{ required: true }],
  buttonActionType: [{ required: true }],
  buttonRedirectTo: [{ required: true }],
  descriptionTr: [{ required: false }],
  descriptionEn: [{ required: false }],
  accessibilityLabelTr: [{ required: false }],
  accessibilityLabelEn: [{ required: false }],
  picturePreviewURLTr: [{ required: false }],
  picturePreviewURLEn: [{ required: false }],
  promoUrlTr: [{ required: false }],
  promoUrlEn: [{ required: false }],
  promoContentHTMLTr: [{ required: false }],
  promoContentHTMLEn: [{ required: false }],
  promoPageTitleTr: [{ required: false }],
  promoPageTitleEn: [{ required: false }],
  promoContentUrlTr: [{ required: false }],
  promoContentUrlEn: [{ required: false }],
  promoContentSectionTitleTr: [{ required: false }],
  promoContentSectionTitleEn: [{ required: false }],
  brandIds: [{ required: true }],
  paymentMethods: [{ required: true }],
  platforms: [{ required: true }],
  startDate: [{ required: true }],
  endDate: [{ required: true }],
  cityIdList: [{ required: true }],
  vendorIds: [{ required: true }],
  startDate_0: [{ required: true }],
  endDate_0: [{ required: true }],
};
