import { createActions } from 'reduxsauce';

import { REDUX_KEY } from '@shared/shared/constants';

const prefix = `${REDUX_KEY.PERSON.DETAIL}_`;

export const { Types, Creators } = createActions(
  {
    getPersonDetailRequest: { personId: undefined },
    getPersonDetailSuccess: { data: {} },
    getPersonDetailFailure: null,
    updatePersonDetailRequest: {
      personId: undefined,
      updateData: undefined,
      onlyPerson: undefined,
    },
    updatePersonDetailSuccess: null,
    updatePersonDetailFailure: null,
    updatePersonalDetailRequest: {
      personId: undefined,
      updateData: undefined,
      oldPersonalGsm: undefined,
      oldCountryCode: undefined,
      isActivated: undefined,
    },
    updatePersonalDetailSuccess: null,
    updatePersonalDetailFailure: null,
    addPersonTrainingRequest: {
      person: undefined,
      trainingObj: undefined,
    },
    addPersonTrainingSuccess: null,
    addPersonTrainingFailure: null,
    disableLoginOfCouriersRequest: {
      id: undefined,
      courierDisableReason: undefined,
      isLoginDisabled: undefined,
    },
    disableLoginOfCouriersSuccess: null,
    disableLoginOfCouriersFailure: null,
    getPersonNotesRequest: { data: { to: undefined, toType: undefined } },
    getPersonNotesSuccess: { data: [] },
    getPersonNotesFailure: null,
    createPersonNoteRequest: {
      data: {
        from: {
          _id: undefined,
          name: undefined,
        },
        to: undefined,
        toType: undefined,
        message: undefined,
      },
    },
    createPersonNoteSuccess: null,
    createPersonNoteFailure: null,
    updatePersonNoteRequest: {
      data: {
        noteId: undefined,
        updatedBy: {
          _id: undefined,
          name: undefined,
        },
        message: undefined,
      },
    },
    updatePersonNoteSuccess: null,
    updatePersonNoteFailure: null,
    addMarketEmployerRequest: {
      person: undefined,
      franchise: undefined,
      workType: undefined,
      contractId: undefined,
      franchiseAreaId: undefined,
    },
    addMarketEmployerSuccess: null,
    addMarketEmployerFailure: null,
    editMarketEmployerRequest: {
      person: undefined,
      marketEmployers: [{
        franchise: undefined,
        workType: undefined,
        contractId: undefined,
        franchiseAreaId: undefined,
      }],
    },
    editMarketEmployerSuccess: null,
    editMarketEmployerFailure: null,
    removeMarketEmployerRequest: {
      person: undefined,
      franchise: undefined,
    },
    removeMarketEmployerSuccess: null,
    removeMarketEmployerFailure: null,
    changePasswordRequest: {
      id: undefined,
      password: undefined,
    },
    changePasswordSuccess: null,
    changePasswordFailure: null,
    getCouriersRequest: { courierIds: undefined, fields: undefined },
    getCouriersSuccess: { data: [] },
    getCouriersFailure: { error: null },
    getPickersRequest: { pickerIds: undefined, fields: undefined },
    getPickersSuccess: { data: [] },
    getPickersFailure: { error: null },
    createCourierForPersonRequest: { id: undefined, courierTypes: undefined },
    createCourierForPersonSuccess: null,
    createCourierForPersonFailure: null,
    createPickerForPersonRequest: { id: undefined, pickerTypes: undefined },
    createPickerForPersonSuccess: null,
    createPickerForPersonFailure: null,
    changeAvatarRequest: {
      id: undefined,
      name: undefined,
      data: undefined,
    },
    changeAvatarSuccess: null,
    changeAvatarFailure: null,
    activatePersonRequest: {
      id: undefined,
      gsm: undefined,
      countryCode: undefined,
      shouldAddEmployeeDiscount: undefined,
    },
    activatePersonSuccess: null,
    activatePersonFailure: null,
    deactivatePersonRequest: {
      id: undefined,
      gsm: undefined,
      countryCode: undefined,
    },
    deactivatePersonSuccess: null,
    deactivatePersonFailure: null,
    addEmployeeDiscountRequest: {
      gsm: undefined,
      countryCode: undefined,
    },
    addEmployeeDiscountSuccess: null,
    addEmployeeDiscountFailure: null,
    getPersonContractRequest: { countryCode: undefined },
    getPersonContractSuccess: { data: {} },
    getPersonContractFailure: null,
    getGetirUpTrainingsRequest: { personId: undefined },
    getGetirUpTrainingsSuccess: { data: [] },
    getGetirUpTrainingsFailure: null,
    getFranchisesAreasRequest: { franchiseIds: undefined },
    getFranchisesAreasSuccess: { data: [] },
    getFranchisesAreasFailure: null,

    initPage: null,
    destroyPage: null,
  },
  { prefix },
);
