import { createUseStyles } from 'react-jss';

import { colors, transitions } from '@app/pages/MarketProductChainManagement/styleVariables';

const useStyles = createUseStyles({
  '@global': {
    '@keyframes fadeIn': {
      from: {
        opacity: '0',
        transform: 'translateY(8px)',
      },
      to: {
        opacity: '1',
        transform: 'translateY(0)',
      },
    },
    '@keyframes fadeInScale': {
      '0%': {
        opacity: '0',
        transform: 'translateY(4px) scale(0.98)',
      },
      '60%': {
        opacity: '0.8',
        transform: 'translateY(2px) scale(0.99)',
      },
      '100%': {
        opacity: '1',
        transform: 'translateY(0) scale(1)',
      },
    },
    '@keyframes collapseExpand': {
      from: {
        opacity: '0',
        transform: 'scaleY(0.8)',
      },
      to: {
        opacity: '1',
        transform: 'scaleY(1)',
      },
    },
    '.ant-select-dropdown': { zIndex: '1060 !important' },
    '.ant-collapse .ant-collapse-content': {
      transition: 'max-height 0.3s ease-out, opacity 0.4s ease-out, transform 0.25s ease-out !important',
      overflow: 'hidden !important',
      opacity: '0 !important',
      maxHeight: '0 !important',
      transform: 'scaleY(0) translateZ(0) !important',
      transformOrigin: 'top !important',
      willChange: 'max-height, opacity, transform !important',
    },
    '.ant-collapse .ant-collapse-content-active': {
      transition: 'max-height 0.3s ease-out, opacity 0.4s ease-out 0.1s, transform 0.25s ease-out !important',
      overflow: 'visible !important',
      opacity: '1 !important',
      maxHeight: '2000px !important',
      transform: 'scaleY(1) translateZ(0) !important',
      transformOrigin: 'top !important',
      willChange: 'max-height, opacity, transform !important',
    },
    '.ant-collapse .ant-collapse-content-inactive': {
      transition: 'max-height 0.2s ease-in, opacity 0.15s ease-in, transform 0.2s ease-in !important',
      overflow: 'hidden !important',
      opacity: '0 !important',
      maxHeight: '0 !important',
      transform: 'scaleY(0) translateZ(0) !important',
      transformOrigin: 'top !important',
      willChange: 'max-height, opacity, transform !important',
    },
    '.ant-motion-collapse': {
      transition: 'max-height 0.3s ease-out, opacity 0.25s ease-out, transform 0.25s ease-out !important',
      overflow: 'hidden !important',
      willChange: 'max-height, opacity, transform !important',
      transform: 'scaleY(0) translateZ(0) !important',
      transformOrigin: 'top !important',
    },
    '.ant-motion-collapse-appear': {
      transition: 'max-height 0.3s ease-out, opacity 0.25s ease-out, transform 0.25s ease-out !important',
      overflow: 'visible !important',
      opacity: '1 !important',
      maxHeight: '2000px !important',
      transform: 'scaleY(1) translateZ(0) !important',
      transformOrigin: 'top !important',
      willChange: 'max-height, opacity, transform !important',
    },
    '.ant-motion-collapse-leave': {
      transition: 'max-height 0.2s ease-in, opacity 0.15s ease-in, transform 0.2s ease-in !important',
      overflow: 'hidden !important',
      opacity: '0 !important',
      maxHeight: '0 !important',
      transform: 'scaleY(0) translateZ(0) !important',
      transformOrigin: 'top !important',
      willChange: 'max-height, opacity, transform !important',
    },
  },
  matchDarkStoreContent: {
    padding: '24px',
    minHeight: '300px',
    '& .ant-select-arrow': { right: '20px', top: '20px' },
  },
  infoBox: {
    backgroundColor: colors.backgroundWhite,
    border: `1px solid ${colors.purple}`,
    borderRadius: '12px',
    display: 'flex',
    gap: '16px',
    alignItems: 'flex-start',
    marginBottom: '24px',
  },
  infoIconWrapper: {
    backgroundColor: colors.purple,
    padding: '20px',
    borderTopLeftRadius: '8px',
    borderBottomLeftRadius: '8px',
  },
  infoIcon: {
    color: colors.backgroundWhite,
    fontSize: '24px',
    flexShrink: 0,
  },
  infoText: {
    color: colors.purple,
    fontSize: '14px',
    lineHeight: '20px',
    padding: '12px',
    flex: 1,
  },
  selectInfo: {
    backgroundColor: colors.backgroundWhite,
    padding: '24px',
    borderRadius: '8px',
    marginBottom: '24px',
  },
  selectInfoTitle: {
    fontSize: '16px',
    color: colors.purple,
    fontWeight: 700,
    marginBottom: '16px',
  },
  radioGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    marginBottom: '24px',
  },
  selectWrapper: {
    width: '100%',
    marginTop: '16px',
    '& .ant-select .ant-select-arrow': { right: '20px' },
  },
  continueButton: {
    marginTop: '24px',
    display: 'flex',
    justifyContent: 'flex-end',
  },
  stepHeader: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '24px',
    backgroundColor: colors.backgroundWhite,
    padding: '24px',
    borderRadius: '8px',
  },
  filterDisplay: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
    maxHeight: '250px',
    overflowY: 'auto',
    marginRight: '16px',
    '& > div:first-child': {
      backgroundColor: colors.backgroundLight,
      padding: '8px 12px',
      borderRadius: '6px',
      color: colors.textDark,
      fontSize: '14px',
      fontWeight: 500,
      display: 'flex',
      alignItems: 'center',
      '& span': {
        color: colors.textDark,
        marginLeft: '4px',
      },
    },
  },
  filterTag: {
    margin: '0 4px',
    padding: '8px',
    borderRadius: 8,
    background: colors.lightPurple,
    color: colors.purple,
    border: 'none',
    '& .anticon-close': {
      color: colors.purple,
      fontSize: 12,
    },
    '&:hover': {
      background: colors.lightPurple,
      '& .anticon-close': { color: colors.purple },
    },
  },
  actionButtons: {
    display: 'flex',
    gap: '12px',
    '& img': { paddingRight: '4px' },
  },
  collapseContainer: {
    '& h3': {
      fontSize: '16px',
      fontWeight: 500,
      color: colors.textDark,
      marginBottom: '16px',
    },
    '& .ant-collapse': {
      backgroundColor: 'transparent',
      border: 'none',
      '& > .ant-collapse-item > .ant-collapse-header .ant-collapse-arrow': { verticalAlign: '-25px', marginLeft: '12px' },
      '& .ant-collapse-content': {
        transition: 'max-height 0.3s ease-out, opacity 0.4s ease-out, transform 0.25s ease-out',
        overflow: 'hidden',
        opacity: '0',
        maxHeight: '0',
        transform: 'scaleY(0) translateZ(0)',
        transformOrigin: 'top',
        willChange: 'max-height, opacity, transform',
      },
      '& .ant-collapse-content-active': {
        transition: 'max-height 0.3s ease-out, opacity 0.4s ease-out 0.1s, transform 0.25s ease-out',
        overflow: 'visible',
        opacity: '1',
        maxHeight: '2000px',
        transform: 'scaleY(1) translateZ(0)',
        transformOrigin: 'top',
        willChange: 'max-height, opacity, transform',
      },
      '& .ant-motion-collapse': {
        transition: 'max-height 0.3s ease-out, opacity 0.25s ease-out, transform 0.25s ease-out',
        overflow: 'hidden',
        willChange: 'max-height, opacity, transform',
        transform: 'scaleY(0) translateZ(0)',
        transformOrigin: 'top',
      },
      '& .ant-collapse-item': {
        border: `1px solid ${colors.borderGray}`,
        borderRadius: '8px',
        marginBottom: '8px',
        position: 'relative',
        zIndex: 5,
        isolation: 'isolate',
        '& .ant-collapse-header': {
          padding: '16px',
          flexDirection: 'row-reverse !important',
          '& .ant-collapse-expand-icon': {
            marginLeft: '8px',
            marginRight: 0,
          },
        },
        '& .ant-collapse-content': {
          borderBottomLeftRadius: '8px',
          borderBottomRightRadius: '8px',
          overflow: 'hidden',
          position: 'relative',
          zIndex: 3,
          maxHeight: '700px',
          '& .ant-collapse-content-box': {
            padding: '0',
            opacity: 0,
            transition: 'none',
            transform: 'translateZ(0)',
            willChange: 'auto',
            maxHeight: '700px',
            overflowY: 'auto',
            overflowX: 'hidden',
            scrollbarWidth: 'thin',
            scrollbarColor: `${colors.purple} ${colors.backgroundLight}`,
            '&::-webkit-scrollbar': {
              width: '8px',
              display: 'block',
            },
            '&::-webkit-scrollbar-track': {
              background: colors.backgroundLight,
              borderRadius: '4px',
            },
            '&::-webkit-scrollbar-thumb': {
              background: colors.purple,
              borderRadius: '4px',
              '&:hover': {
                background: colors.purple,
                opacity: 0.8,
              },
            },
          },
          '& .ant-collapse': {
            '& > .ant-collapse-item > .ant-collapse-header .ant-collapse-arrow': { verticalAlign: 'middle' },
            '& .ant-collapse-content': {
              transition: 'max-height 0.3s ease-out, opacity 0.25s ease-out, transform 0.25s ease-out',
              overflow: 'hidden',
              opacity: '0',
              maxHeight: '0',
              transform: 'scaleY(0) translateZ(0)',
              transformOrigin: 'top',
              willChange: 'max-height, opacity, transform',
            },
            '& .ant-collapse-content-active': {
              transition: 'max-height 0.3s ease-out, opacity 0.25s ease-out, transform 0.25s ease-out',
              overflow: 'visible',
              opacity: '1',
              maxHeight: '2000px',
              transform: 'scaleY(1) translateZ(0)',
              transformOrigin: 'top',
              willChange: 'max-height, opacity, transform',
            },
            '& .ant-motion-collapse': {
              transition: 'max-height 0.3s ease-out, opacity 0.25s ease-out, transform 0.25s ease-out',
              overflow: 'hidden',
              willChange: 'max-height, opacity, transform',
              transform: 'scaleY(0) translateZ(0)',
              transformOrigin: 'top',
            },
          },
          '& .ant-collapse-item': {
            border: 'none',
            borderBottom: `1px solid ${colors.borderGray}`,
            marginBottom: 0,
            borderRadius: '0',
            position: 'relative',
            zIndex: 3,
            isolation: 'isolate',
            '& .ant-collapse-header': {
              flexDirection: 'row !important',
              display: 'flex',
              alignItems: 'center',
              '& .ant-collapse-expand-icon': {
                marginLeft: 0,
                marginRight: '8px',
                verticalAlign: 'middle',
                marginTop: '2px',
                '& img': {
                  width: '20px',
                  height: '20px',
                },
              },
            },
          },
        },
        '&.ant-collapse-item-active': {
          '& .ant-collapse-content .ant-collapse-content-box': {
            opacity: 1,
            transform: 'translateZ(0)',
          },
        },
      },
      '& .ant-collapse-item-active': {
        '& .ant-collapse-header': {
          borderBottomLeftRadius: '0',
          borderBottomRightRadius: '0',
        },
      },
    },
  },
  darkStoreHeader: {
    display: 'flex',
    alignItems: 'center',
    width: '100%',
  },
  darkStoreName: {
    color: colors.purple,
    fontSize: '16px',
    fontWeight: '700 !important',
  },
  selectContainer: {
    display: 'flex',
    alignItems: 'center',
    marginLeft: 'auto',
    gap: '8px',
    position: 'relative',
    zIndex: 10,
    '& span': { fontSize: '12px' },
    '& .ant-row': { width: '200px' },
    '& .ant-select-arrow': { right: '20px', top: '20px' },
  },
  headerSelect: {
    width: '300px',
    '& .ant-select-arrow': { right: '20px' },
  },
  removeButton: {
    minWidth: '80px',
    transition: transitions.default,
    '&.active': {
      backgroundColor: colors.purple,
      borderColor: colors.purple,
      color: colors.backgroundWhite,
      '&:hover': {
        backgroundColor: colors.purple,
        borderColor: colors.purple,
        color: colors.backgroundWhite,
        opacity: 0.9,
        boxShadow: `0 4px 12px ${colors.textLight}`,
      },
      '&:focus': {
        backgroundColor: colors.purple,
        borderColor: colors.purple,
        color: colors.backgroundWhite,
      },
    },
    '&:hover:not(.active)': {
      borderColor: colors.purple,
      color: colors.purple,
      boxShadow: `0 2px 8px ${colors.textLight}`,
    },
  },
  tableHeader: {
    display: 'grid',
    gridTemplateColumns: '1fr 120px 300px 320px',
    gap: '16px',
    padding: '24px 16px',
    backgroundColor: colors.backgroundLight,
  },
  headerCell: {
    fontSize: '14px',
    fontWeight: 500,
    color: colors.textDark,
  },
  categoryRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 100px 300px 300px',
    gap: '16px',
    alignItems: 'center',
    width: '100%',
    padding: '12px 16px',
    '& span': { fontSize: '12px' },
    '& .ant-tag': {
      backgroundColor: colors.lightPurple,
      color: colors.purple,
      border: `1px solid ${colors.backgroundWhite}`,
      borderRadius: '8px',
      padding: '4px 8px',
      fontSize: '12px',
      fontWeight: 500,
    },
  },
  categorySelect: {
    width: '100%',
    '& .ant-select-selector': { borderRadius: '8px' },
    '& .ant-select-arrow': { right: '20px' },
  },
  productRowCollapse: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gridTemplateColumns: '1fr 100px 200px',
    gap: '16px',
    alignItems: 'center',
    padding: '12px 30px 12px 36px',
    backgroundColor: colors.lightPurple,
    borderBottom: `1px solid ${colors.borderGray}`,
    opacity: '0',
    animation: 'fadeInScale 0.25s ease-out 0.1s forwards',
    minHeight: '73px',
    boxSizing: 'border-box',
  },
  productSelect: {
    width: '100%',
    '& .ant-select-selector': { borderRadius: '8px' },
    '& .ant-select-arrow': { right: '20px' },
  },
  defaultCWContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  expandIconImage: {
    transition: 'transform 0.15s ease-out, opacity 0.1s ease-out',
    willChange: 'transform, opacity',
    transform: 'translateZ(0)',
    opacity: 0.8,
    '&.active': {
      transform: 'rotate(180deg) translateZ(0)',
      opacity: 1,
    },
    '&.inactive': {
      transform: 'rotate(0deg) translateZ(0)',
      opacity: 0.8,
    },
  },
  errorText: {
    color: colors.error,
    fontSize: '12px',
    marginTop: '4px',
  },
  loadingContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '12px 0',
    minHeight: '73px',
    transition: 'opacity 0.15s ease-out',
    '&.single-product': {
      minHeight: '73px',
      padding: '12px 0',
    },
    '&.multiple-products': {
      minHeight: '120px',
      padding: '28px 0',
    },
  },
  noDataContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '24px',
    backgroundColor: colors.backgroundWhite,
    borderRadius: '8px',
    color: colors.textDark,
    fontSize: '14px',
  },
  virtualScrollContainer: {
    height: 'calc(100vh - 300px)',
    overflowY: 'auto',
    overflowX: 'hidden',
    position: 'relative',
    width: '100%',
    scrollBehavior: 'smooth',
    contain: 'layout style',
    scrollbarWidth: 'none',
    msOverflowStyle: 'none',
    '&::-webkit-scrollbar': { display: 'none' },
    minHeight: 'calc(100vh - 300px)',
    maxHeight: 'calc(100vh - 300px)',
  },
  saveButton: {
    '&:focus': {
      backgroundColor: `${colors.purple} !important`,
      borderColor: `${colors.purple} !important`,
    },
  },
  selectedFilters: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  filterGroup: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '4px',
  },
  productVirtualContainer: {
    maxHeight: '370px',
    overflowY: 'auto',
    overflowX: 'hidden',
    position: 'relative',
    width: '100%',
    backgroundColor: colors.backgroundWhite,
    border: `1px solid ${colors.borderGray}`,
    zIndex: 4,
    '& > div': { padding: '0 16px' },
    opacity: '0',
    animation: 'fadeIn 0.4s ease-out 0.2s forwards',
    scrollbarWidth: 'thin',
    scrollbarColor: `${colors.purple} ${colors.backgroundLight}`,
    '&::-webkit-scrollbar': {
      width: '8px',
      display: 'block',
    },
    '&::-webkit-scrollbar-track': {
      background: colors.backgroundLight,
      borderRadius: '4px',
    },
    '&::-webkit-scrollbar-thumb': {
      background: colors.purple,
      borderRadius: '4px',
      '&:hover': {
        background: colors.purple,
        opacity: 0.8,
      },
    },
  },
  virtualCategoryScroll: {
    maxHeight: '600px',
    height: '600px',
    overflowY: 'auto',
    overflowX: 'hidden',
    position: 'relative',
    width: '100%',
    backgroundColor: colors.backgroundWhite,
    border: `1px solid ${colors.borderGray}`,
    zIndex: 4,
    scrollbarWidth: 'thin',
    scrollbarColor: `${colors.purple} ${colors.backgroundLight}`,
    '&::-webkit-scrollbar': {
      width: '8px',
      display: 'block',
    },
    '&::-webkit-scrollbar-track': {
      background: colors.backgroundLight,
      borderRadius: '4px',
    },
    '&::-webkit-scrollbar-thumb': {
      background: colors.purple,
      borderRadius: '4px',
      '&:hover': {
        background: colors.purple,
        opacity: 0.8,
      },
    },
  },
  productName: {
    fontSize: '14px',
    color: colors.textDark,
    flex: '1 1 auto',
  },
  virtualContainer: {
    width: '100%',
    position: 'relative',
    willChange: 'height',
    contain: 'layout style',
    overflow: 'visible',
    transition: 'height 0.15s ease-out',
    minHeight: '0',
    '&:has(.ant-collapse-content-active)': { minHeight: '40px' },
  },
  virtualItem: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    zIndex: 'auto',
    willChange: 'transform',
    contain: 'layout style',
    isolation: 'isolate',
    transition: 'transform 0.15s ease-out',
    backfaceVisibility: 'hidden',
    '&:hover': { zIndex: 10 },
  },
});

export default useStyles;
