export const AB_TEST_FILTER_TYPE = {
  abTestCode: 'AB_TEST_CODE',
  dateRange: 'DATE_RANGE',
};

export const AB_TEST_DB_SOURCE = {
  MARKETING_COMMERCIAL_DB_SOURCE: 'MARKETING_COMMERCIAL_DB_SOURCE',
  DATA_PANEL_DB_SOURCE: 'DATA_PANEL_DB_SOURCE',
};

export const AB_TEST_DB_SOURCE_VALUE = {
  MARKETING_COMMERCIAL_DB_SOURCE: 0,
  DATA_PANEL_DB_SOURCE: 1,
};
