import { createUseStyles } from 'react-jss';

export default createUseStyles(() => (
  {
    timeline: { fontSize: '14px' },
    tlHeader: {
      display: 'block',
      marginBottom: '15px',
      width: '12em',
      marginLeft: '2px',
      textAlign: 'center',
    },
    tlWrapBprimary: {
      display: 'block',
      padding: '15px 0 15px 20px',
      marginLeft: '6em',
      borderColor: '#5D3EBD',
      borderStyle: 'solid',
      borderWidth: '0 0 0 4px',
      '&:before': {
        content: ' ',
        position: 'absolute',
        bottom: 0,
        left: 50,
        width: '100%',
        height: '1rem',
        display: 'block',
        background: '#ffffff',
      },
    },
    tlDate: {
      position: 'relative',
      top: '10px',
      display: 'block',
      float: 'left',
      width: '4.5em',
      marginLeft: '-8.5em',
      textAlign: 'right',
      color: '#58666e',
    },
    tlContent: {
      border: '1px solid #dee5e7',
      paddingRight: '15px',
      paddingLeft: '15px',
      position: 'relative',
      display: 'inline-block',
      paddingTop: '10px',
      paddingBottom: '10px',
      backgroundColor: '#ffffff',
      maxWidth: '100%',
      overflowWrap: 'break-word',
    },
    tlContentBasket: {
      paddingRight: '15px',
      paddingLeft: '15px',
      position: 'relative',
      display: 'inline-block',
      paddingTop: '10px',
      paddingBottom: '10px',
      backgroundColor: '#ffffff',
    },
    tlContentClient: {
      paddingRight: '15px',
      paddingLeft: '15px',
      position: 'relative',
      display: 'inline-block',
      paddingBottom: '10px',
      backgroundColor: '#ffffff',
      borderBottom: '1px solid #edf1f2',
      width: '100%',
    },
    tlContentEco: {
      paddingRight: '15px',
      paddingLeft: '15px',
      position: 'relative',
      display: 'inline-block',
      paddingBottom: '10px',
      paddingTop: '10px',
      backgroundColor: '#ffffff',
      borderTop: '1px solid #edf1f2',
      width: '100%',
    },
    textPrimary: {
      color: '#5D3EBC',
      fontWeight: '700',
      marginLeft: '3px',
      marginRight: '3px',
    },
    panelFooter: {
      backgroundColor: '#ffffff',
      borderRadius: '0 0 2px 2px',
      textAlign: 'right',
      padding: '10px 15px 0px 15px',
      borderTop: '1px solid #edf1f2',
    },
    textAlignLeft: { textAlign: 'left' },
    textAlignRight: { textAlign: 'right' },
    ltItem: {
      display: 'block',
      '&:before': {
        display: 'table',
        content: ' ',
      },
    },
    ltWrap: {
      display: 'block',
      padding: '15px 0 15px 20px',
      marginLeft: '6em',
      borderColor: '#5D3EBD',
      borderStyle: 'solid',
      borderWidth: '0 0 0 4px',
    },
    orderButton: {
      backgroundColor: '#5D3EBD',
      fontSize: '12px',
      color: '#FFD10D',
      fontWeight: '700',
    },
    panelBody: {
      marginRight: '-15px',
      marginLeft: '-15px',
    },
    timelineIcon: {
      position: 'absolute',
      left: '-29px',
      background: '#ffffff',
      borderRadius: '100%',
      top: '50%',
    },
    upperTimelineIcon: { top: '7%' },
    muted: { color: '#697488', opacity: 0.6 },
    seperator: {
      width: '100%',
      borderTop: '1px solid #edf1f2',
    },
    customProgressHeader: {
      width: '100%',
      textAlign: 'center',
    },
    customProgress: {
      display: 'flex',
      width: '100%',
      height: '20px',
      marginBottom: '20px',
      boxShadow: 'none',
      borderRadius: '4px',
      overflow: 'hidden',
      backgroundColor: '#edf1f2',
    },
    customBar: {
      height: '100%',
      textAlign: 'center',
      color: '#fff',
    },
    bgInfo: { backgroundColor: '#23b7e5' },
    bgInfoDarker: { backgroundColor: '#359BBA' },
    bgPrimary: { backgroundColor: '#5D3EBD' },
    bgInfoLighter: { backgroundColor: '#75CBE6' },
  }));
