import { LOCALS_DELIVERY, LOCALS_ORDER_STATUS } from '@shared/shared/constants';

export const DELIVERY_TYPE_COLOR_MAP = {
  [LOCALS_DELIVERY.STORE]: 'green',
  [LOCALS_DELIVERY.GETIR]: 'purple',
};

export const LOCALS_CONFIG_KEYS = { CALL_INFO: 'co:locals:CALL_INFO' };

export const ORDER_STATUS_KEY = {
  [LOCALS_ORDER_STATUS.INCOMPLETE]: 'INCOMPLETE',
  [LOCALS_ORDER_STATUS.ABORTED]: 'ABORTED',
  [LOCALS_ORDER_STATUS.BROWSING]: 'BROWSING',
  [LOCALS_ORDER_STATUS.SCHEDULED_VERIFYING]: 'SCHEDULED_VERIFYING',
  [LOCALS_ORDER_STATUS.SCHEDULED]: 'SCHEDULED',
  [LOCALS_ORDER_STATUS.VERIFYING]: 'VERIFYING',
  [LOCALS_ORDER_STATUS.PREPARING]: 'PREPARING',
  [LOCALS_ORDER_STATUS.PREPARED]: 'PREPARED',
  [LOCALS_ORDER_STATUS.HANDOVER_TO_RUNNER]: 'HANDOVER_TO_RUNNER',
  [LOCALS_ORDER_STATUS.ON_RUNNER]: 'ON_RUNNER',
  [LOCALS_ORDER_STATUS.HANDOVER]: 'HANDOVER',
  [LOCALS_ORDER_STATUS.ONWAY]: 'ONWAY',
  [LOCALS_ORDER_STATUS.REACHED]: 'REACHED',
  [LOCALS_ORDER_STATUS.DELIVERED]: 'DELIVERED',
  [LOCALS_ORDER_STATUS.RATED]: 'RATED',
  [LOCALS_ORDER_STATUS.CANCELED_ADMIN]: 'CANCELED_ADMIN',
  [LOCALS_ORDER_STATUS.CANCELED_RESTAURANT]: 'CANCELED_SHOP',
};
