import { createActions } from 'reduxsauce';

import { REDUX_KEY } from '@shared/shared/constants';

export const { Types, Creators } = createActions({
  initPage: null,
  destroyPage: null,
  forceLogoutRequest: { courierId: null },
  forceLogoutSuccess: { data: {} },
  forceLogoutFailure: { error: null },
  getCourierRequest: { id: null, hasFinanceEmployeeRole: false },
  getCourierSuccess: { data: {} },
  getCourierFailure: { error: null },
  releaseCourierRequest: { courierId: null, warehouseId: null },
  releaseCourierSuccess: { data: [] },
  releaseCourierFailure: { error: null },
  getCourierBusyOptionsRequest: null,
  getCourierBusyOptionsSuccess: { data: {} },
  getCourierBusyOptionsFailure: { error: null },
  setCourierFreeRequest: { id: null },
  setCourierFreeSuccess: null,
  setCourierFreeFailure: { error: null },
  setCourierBusyRequest: { id: null, reason: '' },
  setCourierBusySuccess: null,
  setCourierBusyFailure: { error: null },
  setCourierActivateRequest: { id: null },
  setCourierActivateSuccess: null,
  setCourierActivateFailure: { error: null },
  setCourierDeactivateRequest: { id: null },
  setCourierDeactivateSuccess: null,
  setCourierDeactivateFailure: { error: null },
  restartCourierMduRequest: { id: null },
  restartCourierMduSuccess: null,
  restartCourierMduFailure: { error: null },
  sendPullAppsNotificationRequest: { id: null },
  sendPullAppsNotificationSuccess: null,
  sendPullAppsNotificationFailure: { error: null },
  sendCheckServicesNotificationRequest: { id: null },
  sendCheckServicesNotificationSuccess: null,
  sendCheckServicesNotificationFailure: { error: null },
  sendStartServicesNotificationRequest: { id: null },
  sendStartServicesNotificationSuccess: null,
  sendStartServicesNotificationFailure: { error: null },
  removeCourierFromSystemRequest: { id: null },
  removeCourierFromSystemSuccess: null,
  removeCourierFromSystemFailure: { error: null },
  sendNotificationMessageRequest: { id: null, title: '', message: '' },
  sendNotificationMessageSuccess: null,
  sendNotificationMessageFailure: { error: null },
  setWarehouseToCourierRequest: { courierId: null, warehouseId: null, warehouseFranchiseId: null, currentMarketEmployer: {}, workStatus: null },
  setWarehouseToCourierSuccess: { data: {} },
  setWarehouseToCourierFailure: { error: null },
  setDomainTypeRequest: { courierId: null, domainTypes: [] },
  setDomainTypeSuccess: { data: {} },
  setDomainTypeFailure: { error: null },
  setAvailableVehicleTypesRequest: { courierId: null, availableVehicleTypes: [] },
  setAvailableVehicleTypesSuccess: null,
  setAvailableVehicleTypesFailure: { error: null },
  setChiefCourierRequest: { courierId: null, chiefRank: null },
  setChiefCourierSuccess: null,
  setChiefCourierFailure: { error: null },
  setGeofenceByCourierIdRequest: { courierId: null, isGeoFenceDisabled: null },
  setGeofenceByCourierIdSuccess: { data: {} },
  setGeofenceByCourierIdFailure: { error: null },
  setEmploymentTypeRequest: { courierId: null, employmentType: null },
  setEmploymentTypeSuccess: null,
  setEmploymentTypeFailure: { error: null },
  setIsLoginDisabledRequest: { courierId: null, isLoginDisabled: null },
  setIsLoginDisabledSuccess: { data: {} },
  setIsLoginDisabledFailure: { error: null },
  getOrderListRequest: { courierId: null, domainType: null, limit: 10, offset: 0 },
  getOrderListSuccess: { data: [], count: 0 },
  getOrderListFailure: { error: null },
  getReturnDetailsWithReturnIdListRequest: { returnIds: null },
  getReturnDetailsWithReturnIdListSuccess: { data: null },
  getReturnDetailsWithReturnIdListFailure: { error: null },
  getStatusLogsRequest: { courierId: null, startDate: null, endDate: null },
  getStatusLogsSuccess: { data: [], batchData: [] },
  getStatusLogsFailure: { error: null },
  getCourierTasksRequest: { courierId: null },
  getCourierTasksSuccess: { data: [] },
  getCourierTasksFailure: { error: null },
  getGeoFenceRequest: { courierId: null, startDate: null, endDate: null },
  getGeoFenceSuccess: { data: [], batchData: [] },
  getGeoFenceFailure: { error: null },
  getCommonFeedbackRequest: { filterOptions: {}, language: undefined, pageNumber: 0, limit: 10 },
  getCommonFeedbackRequestSuccess: { data: [] },
  getCommonFeedbackRequestFailure: { error: null },
  getCourierLogsRequest: { courierId: null },
  getCourierLogsSuccess: {},
  getCourierLogsFailure: { error: null },
  resetCourierPasswordRequest: { courierId: null },
  resetCourierPasswordSuccess: { data: {} },
  resetCourierPasswordFailure: { error: null },
}, { prefix: `${REDUX_KEY.COURIER.DETAIL}_` });
