/* eslint-disable max-len */
// since this is a constant file length of lines are not that important
import moment, { Moment } from 'moment';

import { TAG_COLORS } from '@shared/shared/constants';

export const TURKEY_DIALING_CODE = '+90';

// EMPLOYMENT_ELIGIBILITY_DAYS: Represents the minimum number of days (16 years)
// required between an employee's birthdate and their employment start date
// to ensure age eligibility for employment.
export const EMPLOYMENT_ELIGIBILITY_DAYS = 5844;

export const TURKEY_MAX_ALLOWED_PHONE_NUMBER_LENGTH = 10;

export const GENDERS = {
  MALE: 1,
  FEMALE: 2,
  OTHER: 3,
  PREFER_NOT_TO_DISCLOSE: 4,
} as const;

export const EMERGENCY_CONTACT_RELATIONSHIPS = {
  SPOUSE: 100,
  CHILD: 200,
  PARENT: 300,
  SIBLING: 400,
  FRIEND: 500,
  OTHER: 1000,
} as const;

export const POSITION_LEVELS = {
  FOUNDER: 100,
  C_LEVEL: 200,
  VP: 300,
  DIRECTOR: 400,
  HEAD: 500,
  LEAD: 600,
  MANAGER: 700,
  ASSOCIATE: 800,
  SPECIALIST: 900,
  INTERN: 1000,
} as const;

export const LOCATION_TYPES = {
  OFFICE: 100,
  FIELD: 200,
} as const;

export const EMPLOYMENT_TYPES = {
  FULL_TIME: 100,
  PART_TIME: 200,
  CONTRACTOR: 300,
} as const;

export const CONTRACT_TYPES = {
  INDEFINITE_TERM: 100,
  FIXED_TERM: 200,
} as const;

export const PAYROLL_STATUSES = {
  GETIR: 1,
  NOT_GETIR: 2,
} as const;

export const EMPLOYMENT_STATUSES = {
  PENDING_HIRE: 50,
  WORKING: 100,
  ON_LEAVE: 200,
  NOT_WORKING: 300,
  WITHDRAWN: 400,
} as const;

export const END_OF_EMPLOYMENT_LEAVE_REASONS = {
  ANOTHER_JOB: 100,
  PERSONAL_AND_FAMILY: 101,
  RETIREMENT: 102,
  MARRIAGE: 103,
  MILITARY_SERVICE: 104,
  JOB_OPPORTUNITY: 105,
  WORKING_CONDITIONS_AND_CULTURAL_FIT: 106,
  CAREER_AND_JOB_SATISFACTION: 107,
  OTHER: 1000,
} as const;

export const EMPLOYEE_SURVEY_TURNOVER_TYPES = {
  REGRETTED: 1,
  NON_REGRETTED: 2,
  CANCEL_HIRING: 3,
} as const;

export const LEAVE_TYPES = {
  COMPENSATION_AND_BENEFITS: 101,
  NO_REMOTE_HYBRID_FLEXIBLE_WORKING_CONDITIONS: 102,
  WORK_LIFE_BALANCE: 103,
  ROLES_AND_RESPONSIBILITIES: 104,
  PERFORMANCE_ASSESSMENT_PROCESS: 105,
  MANAGERIAL_ISSUES: 106,
  TOP_DOWN_DECISIONS_PROCESSES_IN_BUSINESS: 107,
  WORKING_ABROAD_CAREER_ECONOMIC_DEVELOPMENT: 108,
  MARRIAGE: 109,
  UNCLEAR_NO_CAREER_PATHS_AT_GETIR: 110,
  LACK_OF_LEARNING_OPPORTUNITIES: 111,
  LACK_OF_INTERNAL_MOBILITY_OPPORTUNITIES: 112,
  LACK_OF_SYSTEMS_TECH_PROCEDURES_INFRASTRUCTURE: 113,
  CO_WORKERS_TEAM_MEMBERS: 114,
  CULTURE_OF_APPRECIATION_RECOGNITION: 115,
  DIVERSITY_EQUALITY_INCLUSION_ISSUES: 116,
  HEALTH_AND_SAFETY: 117,
  INDUSTRY_CHANGE: 118,
  STARTING_OWN_BUSINESS: 119,
  FAMILY_ISSUES: 120,
  HEALTH_ISSUES: 121,
  MILITARY_SERVICES: 122,
  RETIREMENT: 123,
  PERSONAL_REASON_EDUCATION: 124,
  END_OF_FIXED_EMPLOYEE_CONTRACT: 125,
  JOB_INSECURITY: 126,
  OTHER: 127,
  // Involuntarily Leaves
  PERFORMANCE_ISSUES: 201,
  ATTENDANCE: 202,
  ORGANIZATIONAL_CHANGES: 203,
  REDUNDANCY: 204,
  DISGRACEFUL_OFFENSE: 205,
  OTHER_DISCIPLINARY_ACTIONS: 206,
  WORKPLACE_CO_WORKERS_MANAGER_CONFLICT: 207,
  PROBATION_PERIOD_LESS_THAN_2_MONTHS: 208,
  PROBATION_PERIOD_LESS_THAN_6_MONTHS: 209,
  END_OF_FIXED_TERM_EMPLOYEE_CONTRACT: 210,
  TRANSFER: 211,
  LAYOFF: 212,
  HEALTH_ISSUES_FOR_INVOLUNTARILY_TYPE: 213,

  CANCEL_HIRING: 300,
} as const;

export const EMPLOYEE_ONBOARDING_INFO_TYPES = {
  START: 1,
  TERMINATE: 2,
  REHIRE: 3,
} as const;

export const EMPLOYEE_ON_AND_OFF_BOARDING_STATUS = {
  ON_GOING: 100,
  COMPLETED: 200,
} as const;

export const EMPLOYEE_SURVEY_LEAVE_TYPES = {
  VOLUNTARILY_LEAVES: [
    LEAVE_TYPES.COMPENSATION_AND_BENEFITS,
    LEAVE_TYPES.NO_REMOTE_HYBRID_FLEXIBLE_WORKING_CONDITIONS,
    LEAVE_TYPES.WORK_LIFE_BALANCE,
    LEAVE_TYPES.ROLES_AND_RESPONSIBILITIES,
    LEAVE_TYPES.PERFORMANCE_ASSESSMENT_PROCESS,
    LEAVE_TYPES.MANAGERIAL_ISSUES,
    LEAVE_TYPES.TOP_DOWN_DECISIONS_PROCESSES_IN_BUSINESS,
    LEAVE_TYPES.WORKING_ABROAD_CAREER_ECONOMIC_DEVELOPMENT,
    LEAVE_TYPES.MARRIAGE,
    LEAVE_TYPES.UNCLEAR_NO_CAREER_PATHS_AT_GETIR,
    LEAVE_TYPES.LACK_OF_LEARNING_OPPORTUNITIES,
    LEAVE_TYPES.LACK_OF_INTERNAL_MOBILITY_OPPORTUNITIES,
    LEAVE_TYPES.LACK_OF_SYSTEMS_TECH_PROCEDURES_INFRASTRUCTURE,
    LEAVE_TYPES.CO_WORKERS_TEAM_MEMBERS,
    LEAVE_TYPES.CULTURE_OF_APPRECIATION_RECOGNITION,
    LEAVE_TYPES.DIVERSITY_EQUALITY_INCLUSION_ISSUES,
    LEAVE_TYPES.HEALTH_AND_SAFETY,
    LEAVE_TYPES.INDUSTRY_CHANGE,
    LEAVE_TYPES.STARTING_OWN_BUSINESS,
    LEAVE_TYPES.FAMILY_ISSUES,
    LEAVE_TYPES.HEALTH_ISSUES,
    LEAVE_TYPES.MILITARY_SERVICES,
    LEAVE_TYPES.RETIREMENT,
    LEAVE_TYPES.PERSONAL_REASON_EDUCATION,
    LEAVE_TYPES.END_OF_FIXED_EMPLOYEE_CONTRACT,
    LEAVE_TYPES.JOB_INSECURITY,
    LEAVE_TYPES.OTHER,
  ],
  INVOLUNTARILY_LEAVES: [
    LEAVE_TYPES.PERFORMANCE_ISSUES,
    LEAVE_TYPES.ATTENDANCE,
    LEAVE_TYPES.ORGANIZATIONAL_CHANGES,
    LEAVE_TYPES.REDUNDANCY,
    LEAVE_TYPES.DISGRACEFUL_OFFENSE,
    LEAVE_TYPES.OTHER_DISCIPLINARY_ACTIONS,
    LEAVE_TYPES.WORKPLACE_CO_WORKERS_MANAGER_CONFLICT,
    LEAVE_TYPES.HEALTH_ISSUES_FOR_INVOLUNTARILY_TYPE,
    LEAVE_TYPES.PROBATION_PERIOD_LESS_THAN_2_MONTHS,
    LEAVE_TYPES.PROBATION_PERIOD_LESS_THAN_6_MONTHS,
    LEAVE_TYPES.END_OF_FIXED_TERM_EMPLOYEE_CONTRACT,
    LEAVE_TYPES.TRANSFER,
    LEAVE_TYPES.LAYOFF,
    LEAVE_TYPES.OTHER,
  ],
};

export const EMPLOYMENT_STATUSES_TAG_COLORS = {
  [EMPLOYMENT_STATUSES.PENDING_HIRE]: TAG_COLORS.default,
  [EMPLOYMENT_STATUSES.WORKING]: TAG_COLORS.success,
  [EMPLOYMENT_STATUSES.ON_LEAVE]: TAG_COLORS.warning,
  [EMPLOYMENT_STATUSES.NOT_WORKING]: TAG_COLORS.danger,
  [EMPLOYMENT_STATUSES.WITHDRAWN]: TAG_COLORS.danger,
} as const;

export const DEPARTMENT_LEVELS = {
  MAIN_DEPARTMENT: 'main',
  SUB_DEPARTMENT_FIRST: 'firstLevelSub',
};

export const DEPARTMENT_LEVEL_ORDERS_BY_LEVEL = {
  [DEPARTMENT_LEVELS.MAIN_DEPARTMENT]: 0,
  [DEPARTMENT_LEVELS.SUB_DEPARTMENT_FIRST]: 1,
} as const;

export const DEPARTMENT_LEVEL_ORDERS_BY_ORDER = Object.entries(DEPARTMENT_LEVEL_ORDERS_BY_LEVEL).reduce((acc, [key, value]) => {
  acc[value] = key;
  return acc;
}, {} as { [key: string]: string });

export const BASE_DATE_FORMAT_WITHOUT_TIME: string = 'YYYY-MM-DD';

export const TODAY_START: Moment = moment().startOf('day');

export const JOB_STATUSES = {
  WORKING: 100,
  ON_LEAVE: 200,
  NOT_WORKING: 300,
} as const;

export const WORK_TYPES = {
  FULL_TIME: 1,
  PART_TIME: 2,
  INTERN: 3,
} as const;

export const COLLAR_TYPES = {
  WHITE_COLLAR: 1,
  BLUE_COLLAR: 2,
} as const;

export const EMPLOYEE_PERMIT_ACTIONS = {
  REQUEST: 1,
  APPROVE: 2,
  REJECTED: 3,
  CANCELED: 4,
} as const;

export const EMPLOYEE_PERMIT_STATUSES = {
  REQUESTED: 100,
  APPROVED: 200,
  REJECTED: 300,
  CANCELED: 400,
  CANCELED_REQUEST: 500,
} as const;

export const PERMIT_STATUS_TAG_COLORS = {
  [EMPLOYEE_PERMIT_STATUSES.REQUESTED]: TAG_COLORS.warning,
  [EMPLOYEE_PERMIT_STATUSES.APPROVED]: TAG_COLORS.success,
  [EMPLOYEE_PERMIT_STATUSES.REJECTED]: TAG_COLORS.danger,
  [EMPLOYEE_PERMIT_STATUSES.CANCELED]: TAG_COLORS.danger,
  [EMPLOYEE_PERMIT_STATUSES.CANCELED_REQUEST]: TAG_COLORS.danger,
} as const;

export const EMPLOYEE_PERMIT_TYPES = {
  ANNUAL_PERMIT: 1,
  ADMINISTRATIVE_PERMIT: 2,
  UNPAID_PERMIT: 3,
  REPORTED_PERMIT: 4,
  OTHER: 5,
  HOURLY_PTO: 6,
  NO_SHOW_EXCUSE: 7, // not actually a leave, quick & dirty solution for office no show excuses
} as const;

export const EMPLOYEE_PERMIT_REASONS = {
  COMPASSIONATE_PERMIT: 1,
  HOUSE_MOVE_PERMIT: 2,
  MATERNITY_PERMIT: 3,
  MARRIAGE_PERMIT: 4,
  OTHER: 5,
  PATERNITY_PERMIT: 6,
  RELOCATION_BUSINESS_PERMIT: 7,
  JURY_SERVICE_PERMIT: 8,
  STUDY_PERMIT: 9,
  LOCAL_COUNCIL_COMMITTEE_PERMIT: 10,
  ASSISTANCE_TO_FAMILY_PERMIT: 11,
  EMERGENCY_LEAVE: 12,
  FOSTER_CARE_LEAVE: 13,
  BIRTHDAY_LEAVE: 14,
  TAKE_CARE_OF_YOURSELF_LEAVE: 15,

  // those are not actually a leave reasons, quick & dirty solution for office no show excuses
  NO_SHOW_EXCUSE_SICK: 101,
  NO_SHOW_EXCUSE_FIELD_VISIT: 102,
  NO_SHOW_EXCUSE_OFF_SITE_WORK: 103,
  NO_SHOW_EXCUSE_EXCUSE: 104,
} as const;

export const NON_MATCHED_PAYROLL_COUNTRY_PERMITS = {
  types: {},
  otherLeaveTypeReasons: {},
  noShowExcuseReasons: {},
} as const;

const noShowExcuseReasons = {
  [EMPLOYEE_PERMIT_REASONS.NO_SHOW_EXCUSE_SICK]: { isDocumentRequired: false },
  [EMPLOYEE_PERMIT_REASONS.NO_SHOW_EXCUSE_FIELD_VISIT]: { isDocumentRequired: false },
  [EMPLOYEE_PERMIT_REASONS.NO_SHOW_EXCUSE_OFF_SITE_WORK]: { isDocumentRequired: false },
  [EMPLOYEE_PERMIT_REASONS.NO_SHOW_EXCUSE_EXCUSE]: { isDocumentRequired: false },
} as const;

export const EMPLOYEE_PAYROLL_COUNTRY_PERMITS = {
  TR: {
    types: {
      [EMPLOYEE_PERMIT_TYPES.REPORTED_PERMIT]: { isDocumentRequired: true, minDaysRequireDocument: 0.5 },
      [EMPLOYEE_PERMIT_TYPES.ANNUAL_PERMIT]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_TYPES.UNPAID_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_TYPES.OTHER]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_TYPES.NO_SHOW_EXCUSE]: { isDocumentRequired: false },
    },
    otherLeaveTypeReasons: {
      [EMPLOYEE_PERMIT_REASONS.BIRTHDAY_LEAVE]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.TAKE_CARE_OF_YOURSELF_LEAVE]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.COMPASSIONATE_PERMIT]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.PATERNITY_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.MATERNITY_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.RELOCATION_BUSINESS_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.HOUSE_MOVE_PERMIT]: { isDocumentRequired: false, maxAllowedDays: 1 },
      [EMPLOYEE_PERMIT_REASONS.MARRIAGE_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.OTHER]: { isDocumentRequired: false },
    },
    noShowExcuseReasons,
  },
  DE: {
    types: {},
    // [EMPLOYEE_PERMIT_TYPES.REPORTED_PERMIT]: { isDocumentRequired: true, minDaysRequireDocument: 4 },
    // [EMPLOYEE_PERMIT_TYPES.ANNUAL_PERMIT]: { isDocumentRequired: false },
    // [EMPLOYEE_PERMIT_TYPES.OTHER]: { isDocumentRequired: false },
    otherLeaveTypeReasons: {
      [EMPLOYEE_PERMIT_REASONS.BIRTHDAY_LEAVE]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.TAKE_CARE_OF_YOURSELF_LEAVE]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.COMPASSIONATE_PERMIT]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.PATERNITY_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.MATERNITY_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.RELOCATION_BUSINESS_PERMIT]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.OTHER]: { isDocumentRequired: false },
    },
    noShowExcuseReasons,
  },
  IT: {
    types: {},
    // types: {
    //   [EMPLOYEE_PERMIT_TYPES.REPORTED_PERMIT]: { isDocumentRequired: true, minDaysRequireDocument: 2 },
    //   [EMPLOYEE_PERMIT_TYPES.ANNUAL_PERMIT]: { isDocumentRequired: false },
    //   [EMPLOYEE_PERMIT_TYPES.UNPAID_PERMIT]: { isDocumentRequired: false },
    //   [EMPLOYEE_PERMIT_TYPES.OTHER]: { isDocumentRequired: false },
    //   [EMPLOYEE_PERMIT_TYPES.HOURLY_PTO]: { isDocumentRequired: false, maxAllowedHours: 9 },
    // },
    otherLeaveTypeReasons: {
      [EMPLOYEE_PERMIT_REASONS.BIRTHDAY_LEAVE]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.TAKE_CARE_OF_YOURSELF_LEAVE]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.COMPASSIONATE_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.PATERNITY_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.MATERNITY_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.RELOCATION_BUSINESS_PERMIT]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.HOUSE_MOVE_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.MARRIAGE_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.JURY_SERVICE_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.STUDY_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.OTHER]: { isDocumentRequired: false },
    },
    noShowExcuseReasons,
  },
  ES: {
    types: {},
    // types: {
    //   [EMPLOYEE_PERMIT_TYPES.REPORTED_PERMIT]: { isDocumentRequired: true },
    //   [EMPLOYEE_PERMIT_TYPES.ANNUAL_PERMIT]: { isDocumentRequired: false },
    //   [EMPLOYEE_PERMIT_TYPES.OTHER]: { isDocumentRequired: false },
    // },
    otherLeaveTypeReasons: {
      [EMPLOYEE_PERMIT_REASONS.BIRTHDAY_LEAVE]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.TAKE_CARE_OF_YOURSELF_LEAVE]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.COMPASSIONATE_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.PATERNITY_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.MATERNITY_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.HOUSE_MOVE_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.MARRIAGE_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.JURY_SERVICE_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.LOCAL_COUNCIL_COMMITTEE_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.OTHER]: { isDocumentRequired: false },
    },
    noShowExcuseReasons,
  },
  PT: {
    types: {},
    // types: {
    //   [EMPLOYEE_PERMIT_TYPES.REPORTED_PERMIT]: { isDocumentRequired: true },
    //   [EMPLOYEE_PERMIT_TYPES.ANNUAL_PERMIT]: { isDocumentRequired: false },
    //   [EMPLOYEE_PERMIT_TYPES.UNPAID_PERMIT]: { isDocumentRequired: true },
    //   [EMPLOYEE_PERMIT_TYPES.OTHER]: { isDocumentRequired: false },
    // },
    otherLeaveTypeReasons: {
      [EMPLOYEE_PERMIT_REASONS.BIRTHDAY_LEAVE]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.TAKE_CARE_OF_YOURSELF_LEAVE]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.COMPASSIONATE_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.PATERNITY_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.MATERNITY_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.MARRIAGE_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.JURY_SERVICE_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.ASSISTANCE_TO_FAMILY_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.OTHER]: { isDocumentRequired: false },
    },
    noShowExcuseReasons,
  },
  GB: {
    types: {},
    // types: {
    //   [EMPLOYEE_PERMIT_TYPES.REPORTED_PERMIT]: { isDocumentRequired: true, minDaysRequireDocument: 4 },
    //   [EMPLOYEE_PERMIT_TYPES.ANNUAL_PERMIT]: { isDocumentRequired: false },
    //   [EMPLOYEE_PERMIT_TYPES.UNPAID_PERMIT]: { isDocumentRequired: false },
    //   [EMPLOYEE_PERMIT_TYPES.OTHER]: { isDocumentRequired: false },
    // },
    otherLeaveTypeReasons: {
      [EMPLOYEE_PERMIT_REASONS.BIRTHDAY_LEAVE]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.TAKE_CARE_OF_YOURSELF_LEAVE]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.COMPASSIONATE_PERMIT]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.PATERNITY_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.MATERNITY_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.MARRIAGE_PERMIT]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.JURY_SERVICE_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.OTHER]: { isDocumentRequired: false },
    },
    noShowExcuseReasons,
  },
  US: {
    types: {},
    // types: {
    //   [EMPLOYEE_PERMIT_TYPES.REPORTED_PERMIT]: { isDocumentRequired: true },
    //   [EMPLOYEE_PERMIT_TYPES.ANNUAL_PERMIT]: { isDocumentRequired: false },
    //   [EMPLOYEE_PERMIT_TYPES.OTHER]: { isDocumentRequired: false },
    //   [EMPLOYEE_PERMIT_TYPES.HOURLY_PTO]: { isDocumentRequired: false, maxAllowedHours: 9 },
    // },
    otherLeaveTypeReasons: {
      [EMPLOYEE_PERMIT_REASONS.BIRTHDAY_LEAVE]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.TAKE_CARE_OF_YOURSELF_LEAVE]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.PATERNITY_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.MATERNITY_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.JURY_SERVICE_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.OTHER]: { isDocumentRequired: false },
    },
    noShowExcuseReasons,
  },
  IN: {
    types: {},
    // types: {
    //   [EMPLOYEE_PERMIT_TYPES.REPORTED_PERMIT]: { isDocumentRequired: false },
    //   [EMPLOYEE_PERMIT_TYPES.ANNUAL_PERMIT]: { isDocumentRequired: false },
    //   [EMPLOYEE_PERMIT_TYPES.UNPAID_PERMIT]: { isDocumentRequired: false },
    //   [EMPLOYEE_PERMIT_TYPES.OTHER]: { isDocumentRequired: false },
    // },
    otherLeaveTypeReasons: {
      [EMPLOYEE_PERMIT_REASONS.BIRTHDAY_LEAVE]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.TAKE_CARE_OF_YOURSELF_LEAVE]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.COMPASSIONATE_PERMIT]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.PATERNITY_PERMIT]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.MATERNITY_PERMIT]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.RELOCATION_BUSINESS_PERMIT]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.HOUSE_MOVE_PERMIT]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.MARRIAGE_PERMIT]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.OTHER]: { isDocumentRequired: false },
    },
    noShowExcuseReasons,
  },
  NL: {
    types: {},
    // most of them are disabled due to conflicting information, Jasmin wanted this way
    // [EMPLOYEE_PERMIT_TYPES.REPORTED_PERMIT]: { isDocumentRequired: false },
    // [EMPLOYEE_PERMIT_TYPES.ANNUAL_PERMIT]: { isDocumentRequired: false },
    // [EMPLOYEE_PERMIT_TYPES.UNPAID_PERMIT]: { isDocumentRequired: false },
    // [EMPLOYEE_PERMIT_TYPES.OTHER]: { isDocumentRequired: false },
    // [EMPLOYEE_PERMIT_TYPES.NO_SHOW_EXCUSE]: { isDocumentRequired: false },
    otherLeaveTypeReasons: {
      [EMPLOYEE_PERMIT_REASONS.BIRTHDAY_LEAVE]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.TAKE_CARE_OF_YOURSELF_LEAVE]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.PATERNITY_PERMIT]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.MATERNITY_PERMIT]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.HOUSE_MOVE_PERMIT]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.MARRIAGE_PERMIT]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.COMPASSIONATE_PERMIT]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.EMERGENCY_LEAVE]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.FOSTER_CARE_LEAVE]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.OTHER]: { isDocumentRequired: false },
    },
    noShowExcuseReasons,
  },
  FR: {
    types: {},
    // types: {
    //   [EMPLOYEE_PERMIT_TYPES.REPORTED_PERMIT]: { isDocumentRequired: true },
    //   [EMPLOYEE_PERMIT_TYPES.ANNUAL_PERMIT]: { isDocumentRequired: false },
    //   [EMPLOYEE_PERMIT_TYPES.UNPAID_PERMIT]: { isDocumentRequired: false },
    //   [EMPLOYEE_PERMIT_TYPES.OTHER]: { isDocumentRequired: false },
    // },
    otherLeaveTypeReasons: {
      [EMPLOYEE_PERMIT_REASONS.BIRTHDAY_LEAVE]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.TAKE_CARE_OF_YOURSELF_LEAVE]: { isDocumentRequired: false },
      [EMPLOYEE_PERMIT_REASONS.PATERNITY_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.MATERNITY_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.MARRIAGE_PERMIT]: { isDocumentRequired: true, maxAllowedDays: 5 },
      [EMPLOYEE_PERMIT_REASONS.COMPASSIONATE_PERMIT]: { isDocumentRequired: true },
      [EMPLOYEE_PERMIT_REASONS.OTHER]: { isDocumentRequired: false },
    },
    noShowExcuseReasons,
  },
} as const;

export const EDUCATION_LEVELS = {
  HIGH_SCHOOL: 200,
  ASSOCIATE_DEGREE: 300,
  BACHELORS_DEGREE: 400,
  MASTERS_DEGREE: 500,
  DOCTORATE: 600,
} as const;

export const EDUCATION_STATUSES = {
  ONGOING: 100,
  GRADUATED: 200,
} as const;

export const INTERNATIONAL_DIALING_CODES = [
  { group: 'T', value: { country: 'Turkey', countryCode: 'TR', dialingCode: '+90' } },
  { group: 'A', value: { country: 'Afghanistan', countryCode: 'AF', dialingCode: '+93' } },
  { group: 'A', value: { country: 'Albania', countryCode: 'AL', dialingCode: '+355' } },
  { group: 'A', value: { country: 'Algeria', countryCode: 'DZ', dialingCode: '+213' } },
  { group: 'A', value: { country: 'American Samoa', countryCode: 'AS', dialingCode: '+1-684' } },
  { group: 'A', value: { country: 'Andorra, Principality of', countryCode: 'AD', dialingCode: '+376' } },
  { group: 'A', value: { country: 'Angola', countryCode: 'AO', dialingCode: '+244' } },
  { group: 'A', value: { country: 'Anguilla', countryCode: 'AI', dialingCode: '+1-264' } },
  { group: 'A', value: { country: 'Antarctica', countryCode: 'AQ', dialingCode: '+672' } },
  { group: 'A', value: { country: 'Antigua and Barbuda', countryCode: 'AG', dialingCode: '+1-268' } },
  { group: 'A', value: { country: 'Argentina', countryCode: 'AR', dialingCode: '+54' } },
  { group: 'A', value: { country: 'Armenia', countryCode: 'AM', dialingCode: '+374' } },
  { group: 'A', value: { country: 'Aruba', countryCode: 'AW', dialingCode: '+297' } },
  { group: 'A', value: { country: 'Australia', countryCode: 'AU', dialingCode: '+61' } },
  { group: 'A', value: { country: 'Austria', countryCode: 'AT', dialingCode: '+43' } },
  { group: 'A', value: { country: 'Azerbaijan or Azerbaidjan (Former Azerbaijan Soviet Socialist Republic)', countryCode: 'AZ', dialingCode: '+994' } },
  { group: 'B', value: { country: 'Bahamas, Commonwealth of The', countryCode: 'BS', dialingCode: '+1-242' } },
  { group: 'B', value: { country: 'Bahrain, Kingdom of (Former Dilmun)', countryCode: 'BH', dialingCode: '+973' } },
  { group: 'B', value: { country: 'Bangladesh (Former East Pakistan)', countryCode: 'BD', dialingCode: '+880' } },
  { group: 'B', value: { country: 'Barbados', countryCode: 'BB', dialingCode: '+1-246' } },
  { group: 'B', value: { country: 'Belarus (Former Belorussian [Byelorussian] Soviet Socialist Republic)', countryCode: 'BY', dialingCode: '+375' } },
  { group: 'B', value: { country: 'Belgium', countryCode: 'BE', dialingCode: '+32' } },
  { group: 'B', value: { country: 'Belize (Former British Honduras)', countryCode: 'BZ', dialingCode: '+501' } },
  { group: 'B', value: { country: 'Benin (Former Dahomey)', countryCode: 'BJ', dialingCode: '+229' } },
  { group: 'B', value: { country: 'Bermuda', countryCode: 'BM', dialingCode: '+1-441' } },
  { group: 'B', value: { country: 'Bhutan, Kingdom of', countryCode: 'BT', dialingCode: '+975' } },
  { group: 'B', value: { country: 'Bolivia', countryCode: 'BO', dialingCode: '+591' } },
  { group: 'B', value: { country: 'Bosnia and Herzegovina', countryCode: 'BA', dialingCode: '+387' } },
  { group: 'B', value: { country: 'Botswana (Former Bechuanaland)', countryCode: 'BW', dialingCode: '+267' } },
  { group: 'B', value: { country: 'Bouvet Island (Territory of Norway)', countryCode: 'BV', dialingCode: '' } },
  { group: 'B', value: { country: 'Brazil', countryCode: 'BR', dialingCode: '+55' } },
  { group: 'B', value: { country: 'British Indian Ocean Territory (BIOT)', countryCode: 'IO', dialingCode: '' } },
  { group: 'B', value: { country: 'Brunei (Negara Brunei Darussalam)', countryCode: 'BN', dialingCode: '+673' } },
  { group: 'B', value: { country: 'Bulgaria', countryCode: 'BG', dialingCode: '+359' } },
  { group: 'B', value: { country: 'Burkina Faso (Former Upper Volta)', countryCode: 'BF', dialingCode: '+226' } },
  { group: 'B', value: { country: 'Burundi (Former Urundi)', countryCode: 'BI', dialingCode: '+257' } },
  { group: 'C', value: { country: 'Cambodia, Kingdom of (Former Khmer Republic, Kampuchea Republic)', countryCode: 'KH', dialingCode: '+855' } },
  { group: 'C', value: { country: 'Cameroon (Former French Cameroon)', countryCode: 'CM', dialingCode: '+237' } },
  { group: 'C', value: { country: 'Canada', countryCode: 'CA', dialingCode: '+1' } },
  { group: 'C', value: { country: 'Cape Verde', countryCode: 'CV', dialingCode: '+238' } },
  { group: 'C', value: { country: 'Cayman Islands', countryCode: 'KY', dialingCode: '+1-345' } },
  { group: 'C', value: { country: 'Central African Republic', countryCode: 'CF', dialingCode: '+236' } },
  { group: 'C', value: { country: 'Chad', countryCode: 'TD', dialingCode: '+235' } },
  { group: 'C', value: { country: 'Chile', countryCode: 'CL', dialingCode: '+56' } },
  { group: 'C', value: { country: 'China', countryCode: 'CN', dialingCode: '+86' } },
  { group: 'C', value: { country: 'Christmas Island', countryCode: 'CX', dialingCode: '+53' } },
  { group: 'C', value: { country: 'Cocos (Keeling) Islands', countryCode: 'CC', dialingCode: '+61' } },
  { group: 'C', value: { country: 'Colombia', countryCode: 'CO', dialingCode: '+57' } },
  { group: 'C', value: { country: 'Comoros, Union of the', countryCode: 'KM', dialingCode: '+269' } },
  { group: 'C', value: { country: 'Congo, Democratic Republic of the (Former Zaire)', countryCode: 'CD', dialingCode: '+243' } },
  { group: 'C', value: { country: 'Congo, Republic of the', countryCode: 'CG', dialingCode: '+242' } },
  { group: 'C', value: { country: 'Cook Islands (Former Harvey Islands)', countryCode: 'CK', dialingCode: '+682' } },
  { group: 'C', value: { country: 'Costa Rica', countryCode: 'CR', dialingCode: '+506' } },
  { group: 'C', value: { country: 'Cote D`Ivoire (Former Ivory Coast)', countryCode: 'CI', dialingCode: '+225' } },
  { group: 'C', value: { country: 'Croatia (Hrvatska)', countryCode: 'HR', dialingCode: '+385' } },
  { group: 'C', value: { country: 'Cuba', countryCode: 'CU', dialingCode: '+53' } },
  { group: 'C', value: { country: 'Cyprus', countryCode: 'CY', dialingCode: '+357' } },
  { group: 'C', value: { country: 'Czech Republic', countryCode: 'CZ', dialingCode: '+420' } },
  { group: 'C', value: { country: 'Czechoslavakia (Former) See CZ Czech Republic or Slovakia', countryCode: 'CS', dialingCode: '' } },
  { group: 'D', value: { country: 'Denmark', countryCode: 'DK', dialingCode: '+45' } },
  { group: 'D', value: { country: 'Djibouti (Former French Territory of the Afars and Issas, French Somaliland)', countryCode: 'DJ', dialingCode: '+253' } },
  { group: 'D', value: { country: 'Dominica', countryCode: 'DM', dialingCode: '+1-767' } },
  { group: 'D', value: { country: 'Dominican Republic', countryCode: 'DO', dialingCode: '+1-809' } },
  { group: 'D', value: { country: 'Dominican Republic', countryCode: 'DO', dialingCode: '+1-829' } },
  { group: 'E', value: { country: 'East Timor (Former Portuguese Timor)', countryCode: 'TP', dialingCode: '+670' } },
  { group: 'E', value: { country: 'Ecuador', countryCode: 'EC', dialingCode: '+593 ' } },
  { group: 'E', value: { country: 'Egypt (Former United Arab Republic - with Syria)', countryCode: 'EG', dialingCode: '+20' } },
  { group: 'E', value: { country: 'El Salvador', countryCode: 'SV', dialingCode: '+503' } },
  { group: 'E', value: { country: 'Equatorial Guinea (Former Spanish Guinea)', countryCode: 'GQ', dialingCode: '+240' } },
  { group: 'E', value: { country: 'Eritrea (Former Eritrea Autonomous Region in Ethiopia)', countryCode: 'ER', dialingCode: '+291' } },
  { group: 'E', value: { country: 'Estonia (Former Estonian Soviet Socialist Republic)', countryCode: 'EE', dialingCode: '+372' } },
  { group: 'E', value: { country: 'Ethiopia (Former Abyssinia, Italian East Africa)', countryCode: 'ET', dialingCode: '+251' } },
  { group: 'F', value: { country: 'Falkland Islands (Islas Malvinas)', countryCode: 'FK', dialingCode: '+500' } },
  { group: 'F', value: { country: 'Faroe Islands', countryCode: 'FO', dialingCode: '+298' } },
  { group: 'F', value: { country: 'Fiji', countryCode: 'FJ', dialingCode: '+679' } },
  { group: 'F', value: { country: 'Finland', countryCode: 'FI', dialingCode: '+358' } },
  { group: 'F', value: { country: 'France', countryCode: 'FR', dialingCode: '+33' } },
  { group: 'F', value: { country: 'French Guiana or French Guyana', countryCode: 'GF', dialingCode: '+594' } },
  { group: 'F', value: { country: 'French Polynesia (Former French Colony of Oceania)', countryCode: 'PF', dialingCode: '+689' } },
  { group: 'F', value: { country: 'French Southern Territories and Antarctic Lands', countryCode: 'TF', dialingCode: '' } },
  { group: 'G', value: { country: 'Gabon (Gabonese Republic)', countryCode: 'GA', dialingCode: '+241' } },
  { group: 'G', value: { country: 'Gambia, The', countryCode: 'GM', dialingCode: '+220' } },
  { group: 'G', value: { country: 'Georgia (Former Georgian Soviet Socialist Republic)', countryCode: 'GE', dialingCode: '+995' } },
  { group: 'G', value: { country: 'Germany', countryCode: 'DE', dialingCode: '+49' } },
  { group: 'G', value: { country: 'Ghana (Former Gold Coast)', countryCode: 'GH', dialingCode: '+233' } },
  { group: 'G', value: { country: 'Gibraltar', countryCode: 'GI', dialingCode: '+350' } },
  { group: 'G', value: { country: 'Great Britain (United Kingdom)', countryCode: 'GB', dialingCode: '' } },
  { group: 'G', value: { country: 'Greece', countryCode: 'GR', dialingCode: '+30' } },
  { group: 'G', value: { country: 'Greenland', countryCode: 'GL', dialingCode: '+299' } },
  { group: 'G', value: { country: 'Grenada', countryCode: 'GD', dialingCode: '+1-473' } },
  { group: 'G', value: { country: 'Guadeloupe', countryCode: 'GP', dialingCode: '+590' } },
  { group: 'G', value: { country: 'Guam', countryCode: 'GU', dialingCode: '+1-671' } },
  { group: 'G', value: { country: 'Guatemala', countryCode: 'GT', dialingCode: '+502' } },
  { group: 'G', value: { country: 'Guinea (Former French Guinea)', countryCode: 'GN', dialingCode: '+224' } },
  { group: 'G', value: { country: 'Guinea-Bissau (Former Portuguese Guinea)', countryCode: 'GW', dialingCode: '+245' } },
  { group: 'G', value: { country: 'Guyana (Former British Guiana)', countryCode: 'GY', dialingCode: '+592' } },
  { group: 'H', value: { country: 'Haiti', countryCode: 'HT', dialingCode: '+509' } },
  { group: 'H', value: { country: 'Heard Island and McDonald Islands (Territory of Australia)', countryCode: 'HM', dialingCode: '' } },
  { group: 'H', value: { country: 'Holy See (Vatican City State)', countryCode: 'VA', dialingCode: '' } },
  { group: 'H', value: { country: 'Honduras', countryCode: 'HN', dialingCode: '+504' } },
  { group: 'H', value: { country: 'Hong Kong', countryCode: 'HK', dialingCode: '+852' } },
  { group: 'H', value: { country: 'Hungary', countryCode: 'HU', dialingCode: '+36' } },
  { group: 'I', value: { country: 'Iceland', countryCode: 'IS', dialingCode: '+354' } },
  { group: 'I', value: { country: 'India', countryCode: 'IN', dialingCode: '+91' } },
  { group: 'I', value: { country: 'Indonesia (Former Netherlands East Indies; Dutch East Indies)', countryCode: 'ID', dialingCode: '+62' } },
  { group: 'I', value: { country: 'Iran, Islamic Republic of', countryCode: 'IR', dialingCode: '+98' } },
  { group: 'I', value: { country: 'Iraq', countryCode: 'IQ', dialingCode: '+964' } },
  { group: 'I', value: { country: 'Ireland', countryCode: 'IE', dialingCode: '+353' } },
  { group: 'I', value: { country: 'Israel', countryCode: 'IL', dialingCode: '+972' } },
  { group: 'I', value: { country: 'Italy', countryCode: 'IT', dialingCode: '+39' } },
  { group: 'J', value: { country: 'Jamaica', countryCode: 'JM', dialingCode: '+1-876' } },
  { group: 'J', value: { country: 'Japan', countryCode: 'JP', dialingCode: '+81' } },
  { group: 'J', value: { country: 'Jordan (Former Transjordan)', countryCode: 'JO', dialingCode: '+962' } },
  { group: 'K', value: { country: 'Kazakstan or Kazakhstan (Former Kazakh Soviet Socialist Republic)', countryCode: 'KZ', dialingCode: '+7' } },
  { group: 'K', value: { country: 'Kenya (Former British East Africa)', countryCode: 'KE', dialingCode: '+254' } },
  { group: 'K', value: { country: 'Kiribati (Pronounced keer-ree-bahss) (Former Gilbert Islands)', countryCode: 'KI', dialingCode: '+686' } },
  { group: 'K', value: { country: 'Korea, Democratic People`s Republic of (North Korea)', countryCode: 'KP', dialingCode: '+850' } },
  { group: 'K', value: { country: 'Korea, Republic of (South Korea)', countryCode: 'KR', dialingCode: '+82' } },
  { group: 'K', value: { country: 'Kuwait', countryCode: 'KW', dialingCode: '+965' } },
  { group: 'K', value: { country: 'Kyrgyzstan (Kyrgyz Republic) (Former Kirghiz Soviet Socialist Republic)', countryCode: 'KG', dialingCode: '+996' } },
  { group: 'L', value: { country: 'Lao People`s Democratic Republic (Laos)', countryCode: 'LA', dialingCode: '+856' } },
  { group: 'L', value: { country: 'Latvia (Former Latvian Soviet Socialist Republic)', countryCode: 'LV', dialingCode: '+371' } },
  { group: 'L', value: { country: 'Lebanon', countryCode: 'LB', dialingCode: '+961' } },
  { group: 'L', value: { country: 'Lesotho (Former Basutoland)', countryCode: 'LS', dialingCode: '+266' } },
  { group: 'L', value: { country: 'Liberia', countryCode: 'LR', dialingCode: '+231' } },
  { group: 'L', value: { country: 'Libya (Libyan Arab Jamahiriya)', countryCode: 'LY', dialingCode: '+218' } },
  { group: 'L', value: { country: 'Liechtenstein', countryCode: 'LI', dialingCode: '+423' } },
  { group: 'L', value: { country: 'Lithuania (Former Lithuanian Soviet Socialist Republic)', countryCode: 'LT', dialingCode: '+370' } },
  { group: 'L', value: { country: 'Luxembourg', countryCode: 'LU', dialingCode: '+352' } },
  { group: 'M', value: { country: 'Macau', countryCode: 'MO', dialingCode: '+853' } },
  { group: 'M', value: { country: 'Macedonia, The Former Yugoslav Republic of', countryCode: 'MK', dialingCode: '+389' } },
  { group: 'M', value: { country: 'Madagascar (Former Malagasy Republic)', countryCode: 'MG', dialingCode: '+261' } },
  { group: 'M', value: { country: 'Malawi (Former British Central African Protectorate, Nyasaland)', countryCode: 'MW', dialingCode: '+265' } },
  { group: 'M', value: { country: 'Malaysia', countryCode: 'MY', dialingCode: '+60' } },
  { group: 'M', value: { country: 'Maldives', countryCode: 'MV', dialingCode: '+960' } },
  { group: 'M', value: { country: 'Mali (Former French Sudan and Sudanese Republic)', countryCode: 'ML', dialingCode: '+223' } },
  { group: 'M', value: { country: 'Malta', countryCode: 'MT', dialingCode: '+356' } },
  { group: 'M', value: { country: 'Marshall Islands (Former Marshall Islands District - Trust Territory of the Pacific Islands)', countryCode: 'MH', dialingCode: '+692' } },
  { group: 'M', value: { country: 'Martinique (French)', countryCode: 'MQ', dialingCode: '+596' } },
  { group: 'M', value: { country: 'Mauritania', countryCode: 'MR', dialingCode: '+222' } },
  { group: 'M', value: { country: 'Mauritius', countryCode: 'MU', dialingCode: '+230' } },
  { group: 'M', value: { country: 'Mayotte (Territorial Collectivity of Mayotte)', countryCode: 'YT', dialingCode: '+269' } },
  { group: 'M', value: { country: 'Mexico', countryCode: 'MX', dialingCode: '+52' } },
  { group: 'M', value: { country: 'Micronesia, Federated States of (Former Ponape, Truk, and Yap Districts - Trust Territory of the Pacific Islands)', countryCode: 'FM', dialingCode: '+691' } },
  { group: 'M', value: { country: 'Moldova, Republic of', countryCode: 'MD', dialingCode: '+373' } },
  { group: 'M', value: { country: 'Monaco, Principality of', countryCode: 'MC', dialingCode: '+377' } },
  { group: 'M', value: { country: 'Mongolia (Former Outer Mongolia)', countryCode: 'MN', dialingCode: '+976' } },
  { group: 'M', value: { country: 'Montserrat', countryCode: 'MS', dialingCode: '+1-664' } },
  { group: 'M', value: { country: 'Morocco', countryCode: 'MA', dialingCode: '+212' } },
  { group: 'M', value: { country: 'Mozambique (Former Portuguese East Africa)', countryCode: 'MZ', dialingCode: '+258' } },
  { group: 'M', value: { country: 'Myanmar, Union of (Former Burma)', countryCode: 'MM', dialingCode: '+95' } },
  { group: 'N', value: { country: 'Namibia (Former German Southwest Africa, South-West Africa)', countryCode: 'NA', dialingCode: '+264' } },
  { group: 'N', value: { country: 'Nauru (Former Pleasant Island)', countryCode: 'NR', dialingCode: '+674' } },
  { group: 'N', value: { country: 'Nepal', countryCode: 'NP', dialingCode: '+977' } },
  { group: 'N', value: { country: 'Netherlands', countryCode: 'NL', dialingCode: '+31' } },
  { group: 'N', value: { country: 'Netherlands Antilles (Former Curacao and Dependencies)', countryCode: 'AN', dialingCode: '+599' } },
  { group: 'N', value: { country: 'New Caledonia', countryCode: 'NC', dialingCode: '+687' } },
  { group: 'N', value: { country: 'New Zealand (Aotearoa)', countryCode: 'NZ', dialingCode: '+64' } },
  { group: 'N', value: { country: 'Nicaragua', countryCode: 'NI', dialingCode: '+505' } },
  { group: 'N', value: { country: 'Niger', countryCode: 'NE', dialingCode: '+227' } },
  { group: 'N', value: { country: 'Nigeria', countryCode: 'NG', dialingCode: '+234' } },
  { group: 'N', value: { country: 'Niue (Former Savage Island)', countryCode: 'NU', dialingCode: '+683' } },
  { group: 'N', value: { country: 'Norfolk Island', countryCode: 'NF', dialingCode: '+672' } },
  { group: 'N', value: { country: 'Northern Mariana Islands (Former Mariana Islands District - Trust Territory of the Pacific Islands)', countryCode: 'MP', dialingCode: '+1-670' } },
  { group: 'N', value: { country: 'Norway', countryCode: 'NO', dialingCode: '+47' } },
  { group: 'O', value: { country: 'Oman, Sultanate of (Former Muscat and Oman)', countryCode: 'OM', dialingCode: '+968' } },
  { group: 'P', value: { country: 'Pakistan (Former West Pakistan)', countryCode: 'PK', dialingCode: '+92' } },
  { group: 'P', value: { country: 'Palau (Former Palau District - Trust Terriroty of the Pacific Islands)', countryCode: 'PW', dialingCode: '+680' } },
  { group: 'P', value: { country: 'Palestinian State (Proposed)', countryCode: 'PS', dialingCode: '+970' } },
  { group: 'P', value: { country: 'Panama', countryCode: 'PA', dialingCode: '+507' } },
  { group: 'P', value: { country: 'Papua New Guinea (Former Territory of Papua and New Guinea)', countryCode: 'PG', dialingCode: '+675' } },
  { group: 'P', value: { country: 'Paraguay', countryCode: 'PY', dialingCode: '+595' } },
  { group: 'P', value: { country: 'Peru', countryCode: 'PE', dialingCode: '+51' } },
  { group: 'P', value: { country: 'Philippines', countryCode: 'PH', dialingCode: '+63' } },
  { group: 'P', value: { country: 'Pitcairn Island', countryCode: 'PN', dialingCode: '' } },
  { group: 'P', value: { country: 'Poland', countryCode: 'PL', dialingCode: '+48' } },
  { group: 'P', value: { country: 'Portugal', countryCode: 'PT', dialingCode: '+351' } },
  { group: 'P', value: { country: 'Puerto Rico', countryCode: 'PR', dialingCode: '+1-787' } },
  { group: 'P', value: { country: 'Puerto Rico', countryCode: 'PR', dialingCode: '+1-939' } },
  { group: 'Q', value: { country: 'Qatar, State of ', countryCode: 'QA', dialingCode: '+974' } },
  { group: 'R', value: { country: 'Reunion (French) (Former Bourbon Island)', countryCode: 'RE', dialingCode: '+262' } },
  { group: 'R', value: { country: 'Romania', countryCode: 'RO', dialingCode: '+40' } },
  { group: 'R', value: { country: 'Russia - USSR (Former Russian Empire, Union of Soviet Socialist Republics, Russian Soviet Federative Socialist Republic) Now RU - Russian Federation', countryCode: 'SU', dialingCode: '' } },
  { group: 'R', value: { country: 'Russian Federation', countryCode: 'RU', dialingCode: '+7' } },
  { group: 'R', value: { country: 'Rwanda (Rwandese Republic) (Former Ruanda)', countryCode: 'RW', dialingCode: '+250' } },
  { group: 'S', value: { country: 'Saint Helena', countryCode: 'SH', dialingCode: '+290' } },
  { group: 'S', value: { country: 'Saint Kitts and Nevis (Former Federation of Saint Christopher and Nevis)', countryCode: 'KN', dialingCode: '+1-869' } },
  { group: 'S', value: { country: 'Saint Lucia', countryCode: 'LC', dialingCode: '+1-758' } },
  { group: 'S', value: { country: 'Saint Pierre and Miquelon', countryCode: 'PM', dialingCode: '+508' } },
  { group: 'S', value: { country: 'Saint Vincent and the Grenadines', countryCode: 'VC', dialingCode: '+1-784' } },
  { group: 'S', value: { country: 'Samoa (Former Western Samoa)', countryCode: 'WS', dialingCode: '+685' } },
  { group: 'S', value: { country: 'San Marino', countryCode: 'SM', dialingCode: '+378' } },
  { group: 'S', value: { country: 'Sao Tome and Principe', countryCode: 'ST', dialingCode: '+239' } },
  { group: 'S', value: { country: 'Saudi Arabia', countryCode: 'SA', dialingCode: '+966' } },
  { group: 'S', value: { country: 'Serbia, Republic of', countryCode: 'RS', dialingCode: '' } },
  { group: 'S', value: { country: 'Senegal', countryCode: 'SN', dialingCode: '+221' } },
  { group: 'S', value: { country: 'Seychelles', countryCode: 'SC', dialingCode: '+248' } },
  { group: 'S', value: { country: 'Sierra Leone', countryCode: 'SL', dialingCode: '+232' } },
  { group: 'S', value: { country: 'Singapore', countryCode: 'SG', dialingCode: '+65' } },
  { group: 'S', value: { country: 'Slovakia', countryCode: 'SK', dialingCode: '+421' } },
  { group: 'S', value: { country: 'Slovenia', countryCode: 'SI', dialingCode: '+386' } },
  { group: 'S', value: { country: 'Solomon Islands (Former British Solomon Islands)', countryCode: 'SB', dialingCode: '+677' } },
  { group: 'S', value: { country: 'Somalia (Former Somali Republic, Somali Democratic Republic)', countryCode: 'SO', dialingCode: '+252' } },
  { group: 'S', value: { country: 'South Africa (Former Union of South Africa)', countryCode: 'ZA', dialingCode: '+27' } },
  { group: 'S', value: { country: 'South Georgia and the South Sandwich Islands', countryCode: 'GS', dialingCode: '' } },
  { group: 'S', value: { country: 'Spain', countryCode: 'ES', dialingCode: '+34' } },
  { group: 'S', value: { country: 'Sri Lanka (Former Serendib, Ceylon)', countryCode: 'LK', dialingCode: '+94' } },
  { group: 'S', value: { country: 'Sudan (Former Anglo-Egyptian Sudan)', countryCode: 'SD', dialingCode: '+249' } },
  { group: 'S', value: { country: 'Suriname (Former Netherlands Guiana, Dutch Guiana)', countryCode: 'SR', dialingCode: '+597' } },
  { group: 'S', value: { country: 'Svalbard (Spitzbergen) and Jan Mayen Islands', countryCode: 'SJ', dialingCode: '' } },
  { group: 'S', value: { country: 'Swaziland, Kingdom of', countryCode: 'SZ', dialingCode: '+268' } },
  { group: 'S', value: { country: 'Sweden', countryCode: 'SE', dialingCode: '+46' } },
  { group: 'S', value: { country: 'Switzerland', countryCode: 'CH', dialingCode: '+41' } },
  { group: 'S', value: { country: 'Syria (Syrian Arab Republic) (Former United Arab Republic - with Egypt)', countryCode: 'SY', dialingCode: '+963' } },
  { group: 'T', value: { country: 'Taiwan (Former Formosa)', countryCode: 'TW', dialingCode: '+886' } },
  { group: 'T', value: { country: 'Tajikistan (Former Tajik Soviet Socialist Republic)', countryCode: 'TJ', dialingCode: '+992' } },
  { group: 'T', value: { country: 'Tanzania, United Republic of (Former United Republic of Tanganyika and Zanzibar)', countryCode: 'TZ', dialingCode: '+255' } },
  { group: 'T', value: { country: 'Thailand (Former Siam)', countryCode: 'TH', dialingCode: '+66' } },
  { group: 'T', value: { country: 'Togo (Former French Togoland)', countryCode: 'TG', dialingCode: '' } },
  { group: 'T', value: { country: 'Tokelau', countryCode: 'TK', dialingCode: '+690' } },
  { group: 'T', value: { country: 'Tonga, Kingdom of (Former Friendly Islands)', countryCode: 'TO', dialingCode: '+676' } },
  { group: 'T', value: { country: 'Trinidad and Tobago', countryCode: 'TT', dialingCode: '+1-868' } },
  { group: 'T', value: { country: 'Tromelin Island', countryCode: 'TE', dialingCode: '' } },
  { group: 'T', value: { country: 'Tunisia', countryCode: 'TN', dialingCode: '+216' } },
  { group: 'T', value: { country: 'Turkmenistan (Former Turkmen Soviet Socialist Republic)', countryCode: 'TM', dialingCode: '+993' } },
  { group: 'T', value: { country: 'Turks and Caicos Islands', countryCode: 'TC', dialingCode: '+1-649' } },
  { group: 'T', value: { country: 'Tuvalu (Former Ellice Islands)', countryCode: 'TV', dialingCode: '+688' } },
  { group: 'U', value: { country: 'Uganda, Republic of', countryCode: 'UG', dialingCode: '+256' } },
  { group: 'U', value: { country: 'Ukraine (Former Ukrainian National Republic, Ukrainian State, Ukrainian Soviet Socialist Republic)', countryCode: 'UA', dialingCode: '+380' } },
  { group: 'U', value: { country: 'United Arab Emirates (UAE) (Former Trucial Oman, Trucial States)', countryCode: 'AE', dialingCode: '+971' } },
  { group: 'U', value: { country: 'United Kingdom (Great Britain / UK)', countryCode: 'GB', dialingCode: '+44' } },
  { group: 'U', value: { country: 'United States', countryCode: 'US', dialingCode: '+1' } },
  { group: 'U', value: { country: 'United States Minor Outlying Islands', countryCode: 'UM', dialingCode: '' } },
  { group: 'U', value: { country: 'Uruguay, Oriental Republic of (Former Banda Oriental, Cisplatine Province)', countryCode: 'UY', dialingCode: '+598' } },
  { group: 'U', value: { country: 'Uzbekistan (Former UZbek Soviet Socialist Republic)', countryCode: 'UZ', dialingCode: '+998' } },
  { group: 'V', value: { country: 'Vanuatu (Former New Hebrides)', countryCode: 'VU', dialingCode: '+678' } },
  { group: 'V', value: { country: 'Vatican City State (Holy See)', countryCode: 'VA', dialingCode: '+418' } },
  { group: 'V', value: { country: 'Venezuela', countryCode: 'VE', dialingCode: '+58' } },
  { group: 'V', value: { country: 'Vietnam', countryCode: 'VN', dialingCode: '+84' } },
  { group: 'V', value: { country: 'Virgin Islands, British', countryCode: 'VI', dialingCode: '+1-284' } },
  { group: 'V', value: { country: 'Virgin Islands, United States (Former Danish West Indies)', countryCode: 'VQ', dialingCode: '+1-340' } },
  { group: 'W', value: { country: 'Wallis and Futuna Islands', countryCode: 'WF', dialingCode: '+681' } },
  { group: 'W', value: { country: 'Western Sahara (Former Spanish Sahara)', countryCode: 'EH', dialingCode: '' } },
  { group: 'Y', value: { country: 'Yemen', countryCode: 'YE', dialingCode: '+967' } },
  { group: 'Y', value: { country: 'Yugoslavia', countryCode: 'YU', dialingCode: '' } },
  { group: 'Z', value: { country: 'Zaire (Former Congo Free State, Belgian Congo, Congo/Leopoldville, Congo/Kinshasa, Zaire) Now CD - Congo, Democratic Republic of the', countryCode: 'ZR', dialingCode: '' } },
  { group: 'Z', value: { country: 'Zambia, Republic of (Former Northern Rhodesia)', countryCode: 'ZM', dialingCode: '+260' } },
  { group: 'Z', value: { country: 'Zimbabwe, Republic of (Former Southern Rhodesia, Rhodesia)', countryCode: 'ZW', dialingCode: '+263' } },
] as const;

export const LANGUAGE_KEYS = [
  'zh',
  'en',
  'hi',
  'es',
  'ru',
  'ar',
  'bn',
  'pt',
  'ms',
  'fr',
  'tr',
  'de',
  'it',
  'ja',
  'fa',
  'pl',
  'az',
  'bs',
  'bg',
  'da',
  'nl',
  'et',
  'fi',
  'ka',
  'el',
  'hu',
  'kk',
  'ko',
  'ku',
  'lt',
  'lv',
  'mk',
  'no',
  'ro',
  'sr',
  'sk',
  'sl',
  'sv',
  'ta',
  'tk',
  'tt',
  'uk',
  'uz',
  'vi',
  'hy',
  'ca',
  'ur',
  'cs',
  'he',
] as const;

export const PERMIT_DATES = {
  SPECIAL_HOLIDAYS: {
    START: 2018,
    END: 2023,
  },
} as const;

export const HOLIDAYS_WITH_NAMES = {
  TR: {
    specialHolidays: [
      // 2022
      { start: moment('2022-01-01'), end: moment('2022-01-01'), translationKey: 'global:NEW_YEAR' },
      { start: moment('2022-04-21'), end: moment('2022-04-21'), translationKey: 'employeePage:HOLIDAYS.RAMADAN_HOLIDAY' },
      { start: moment('2022-04-22'), end: moment('2022-04-22'), translationKey: 'employeePage:HOLIDAYS.RAMADAN_HOLIDAY' },
      { start: moment('2022-04-23'), end: moment('2022-04-23'), translationKey: 'employeePage:HOLIDAYS.RAMADAN_HOLIDAY' },
      { start: moment('2022-04-23'), end: moment('2022-04-23'), translationKey: 'employeePage:HOLIDAYS.NATIONAL_SOVEREIGNTY_AND_CHILDREN_HOLIDAY' },
      { start: moment('2022-05-01'), end: moment('2022-05-01'), translationKey: 'employeePage:HOLIDAYS.LABOR_AND_SOLIDARITY_DAY' },
      { start: moment('2022-05-19'), end: moment('2022-05-19'), translationKey: 'employeePage:HOLIDAYS.COMMEMORATION_OF_ATATURK_YOUTH_AND_SPORTS_HOLIDAY' },
      { start: moment('2022-06-27'), end: moment('2022-06-27'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY_EVE', isHalfDay: true },
      { start: moment('2022-06-28'), end: moment('2022-06-28'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY' },
      { start: moment('2022-06-29'), end: moment('2022-06-29'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY' },
      { start: moment('2022-06-30'), end: moment('2022-06-30'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY' },
      { start: moment('2022-07-01'), end: moment('2022-07-01'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY' },
      { start: moment('2022-07-15'), end: moment('2022-07-15'), translationKey: 'employeePage:HOLIDAYS.TR_DEMOCRACY_AND_NATIONAL_UNION_DAY' },
      { start: moment('2022-08-30'), end: moment('2022-08-30'), translationKey: 'employeePage:HOLIDAYS.TR_VICTORY_DAY' },
      { start: moment('2022-10-28'), end: moment('2022-10-28'), translationKey: 'employeePage:HOLIDAYS.REPUBLIC_DAY_EVE', isHalfDay: true },
      { start: moment('2022-10-29'), end: moment('2022-10-29'), translationKey: 'employeePage:HOLIDAYS.REPUBLIC_DAY' },
      // 2023
      { start: moment('2023-01-01'), end: moment('2023-01-01'), translationKey: 'global:NEW_YEAR' },
      { start: moment('2023-04-20'), end: moment('2023-04-20'), translationKey: 'employeePage:HOLIDAYS.RAMADAN_HOLIDAY_EVE', isHalfDay: true },
      { start: moment('2023-04-21'), end: moment('2023-04-21'), translationKey: 'employeePage:HOLIDAYS.RAMADAN_HOLIDAY' },
      { start: moment('2023-04-22'), end: moment('2023-04-22'), translationKey: 'employeePage:HOLIDAYS.RAMADAN_HOLIDAY' },
      { start: moment('2023-04-23'), end: moment('2023-04-23'), translationKey: 'employeePage:HOLIDAYS.RAMADAN_HOLIDAY' },
      { start: moment('2023-04-23'), end: moment('2023-04-23'), translationKey: 'employeePage:HOLIDAYS.NATIONAL_SOVEREIGNTY_AND_CHILDREN_HOLIDAY' },
      { start: moment('2023-05-01'), end: moment('2023-05-01'), translationKey: 'employeePage:HOLIDAYS.LABOR_AND_SOLIDARITY_DAY' },
      { start: moment('2023-05-19'), end: moment('2023-05-19'), translationKey: 'employeePage:HOLIDAYS.COMMEMORATION_OF_ATATURK_YOUTH_AND_SPORTS_HOLIDAY' },
      { start: moment('2023-06-27'), end: moment('2023-06-27'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY_EVE', isHalfDay: true },
      { start: moment('2023-06-28'), end: moment('2023-06-28'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY' },
      { start: moment('2023-06-29'), end: moment('2023-06-29'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY' },
      { start: moment('2023-06-30'), end: moment('2023-06-30'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY' },
      { start: moment('2023-07-01'), end: moment('2023-07-01'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY' },
      { start: moment('2023-07-15'), end: moment('2023-07-15'), translationKey: 'employeePage:HOLIDAYS.TR_DEMOCRACY_AND_NATIONAL_UNION_DAY' },
      { start: moment('2023-08-30'), end: moment('2023-08-30'), translationKey: 'employeePage:HOLIDAYS.TR_VICTORY_DAY' },
      { start: moment('2023-10-28'), end: moment('2023-10-28'), translationKey: 'employeePage:HOLIDAYS.REPUBLIC_DAY_EVE', isHalfDay: true },
      { start: moment('2023-10-29'), end: moment('2023-10-29'), translationKey: 'employeePage:HOLIDAYS.REPUBLIC_DAY' },
      // 2024
      { start: moment('2024-01-01'), end: moment('2024-01-01'), translationKey: 'global:NEW_YEAR' },
      { start: moment('2024-04-09'), end: moment('2024-04-09'), translationKey: 'employeePage:HOLIDAYS.RAMADAN_HOLIDAY_EVE', isHalfDay: true },
      { start: moment('2024-04-10'), end: moment('2024-04-10'), translationKey: 'employeePage:HOLIDAYS.RAMADAN_HOLIDAY' },
      { start: moment('2024-04-11'), end: moment('2024-04-11'), translationKey: 'employeePage:HOLIDAYS.RAMADAN_HOLIDAY' },
      { start: moment('2024-04-12'), end: moment('2024-04-12'), translationKey: 'employeePage:HOLIDAYS.RAMADAN_HOLIDAY' },
      { start: moment('2024-04-23'), end: moment('2024-04-23'), translationKey: 'employeePage:HOLIDAYS.NATIONAL_SOVEREIGNTY_AND_CHILDREN_HOLIDAY' },
      { start: moment('2024-05-01'), end: moment('2024-05-01'), translationKey: 'employeePage:HOLIDAYS.LABOR_AND_SOLIDARITY_DAY' },
      { start: moment('2024-05-19'), end: moment('2024-05-19'), translationKey: 'employeePage:HOLIDAYS.COMMEMORATION_OF_ATATURK_YOUTH_AND_SPORTS_HOLIDAY' },
      { start: moment('2024-06-15'), end: moment('2024-06-15'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY_EVE', isHalfDay: true },
      { start: moment('2024-06-16'), end: moment('2024-06-16'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY' },
      { start: moment('2024-06-17'), end: moment('2024-06-17'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY' },
      { start: moment('2024-06-18'), end: moment('2024-06-18'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY' },
      { start: moment('2024-06-19'), end: moment('2024-06-19'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY' },
      { start: moment('2024-07-15'), end: moment('2024-07-15'), translationKey: 'employeePage:HOLIDAYS.TR_DEMOCRACY_AND_NATIONAL_UNION_DAY' },
      { start: moment('2024-08-30'), end: moment('2024-08-30'), translationKey: 'employeePage:HOLIDAYS.TR_VICTORY_DAY' },
      { start: moment('2024-10-28'), end: moment('2024-10-28'), translationKey: 'employeePage:HOLIDAYS.REPUBLIC_DAY_EVE', isHalfDay: true },
      { start: moment('2024-10-29'), end: moment('2024-10-29'), translationKey: 'employeePage:HOLIDAYS.REPUBLIC_DAY' },
      // 2025
      { start: moment('2025-01-01'), end: moment('2025-01-01'), translationKey: 'global:NEW_YEAR' },
      { start: moment('2025-03-29'), end: moment('2025-03-29'), translationKey: 'employeePage:HOLIDAYS.RAMADAN_HOLIDAY_EVE', isHalfDay: true },
      { start: moment('2025-03-30'), end: moment('2025-03-30'), translationKey: 'employeePage:HOLIDAYS.RAMADAN_HOLIDAY' },
      { start: moment('2025-03-31'), end: moment('2025-03-31'), translationKey: 'employeePage:HOLIDAYS.RAMADAN_HOLIDAY' },
      { start: moment('2025-04-01'), end: moment('2025-04-01'), translationKey: 'employeePage:HOLIDAYS.RAMADAN_HOLIDAY' },
      { start: moment('2025-04-23'), end: moment('2025-04-23'), translationKey: 'employeePage:HOLIDAYS.NATIONAL_SOVEREIGNTY_AND_CHILDREN_HOLIDAY' },
      { start: moment('2025-05-01'), end: moment('2025-05-01'), translationKey: 'employeePage:HOLIDAYS.LABOR_AND_SOLIDARITY_DAY' },
      { start: moment('2025-05-19'), end: moment('2025-05-19'), translationKey: 'employeePage:HOLIDAYS.COMMEMORATION_OF_ATATURK_YOUTH_AND_SPORTS_HOLIDAY' },
      { start: moment('2025-06-05'), end: moment('2025-06-05'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY_EVE', isHalfDay: true },
      { start: moment('2025-06-06'), end: moment('2025-06-06'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY' },
      { start: moment('2025-06-07'), end: moment('2025-06-07'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY' },
      { start: moment('2025-06-08'), end: moment('2025-06-08'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY' },
      { start: moment('2025-06-09'), end: moment('2025-06-09'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY' },
      { start: moment('2025-07-15'), end: moment('2025-07-15'), translationKey: 'employeePage:HOLIDAYS.TR_DEMOCRACY_AND_NATIONAL_UNION_DAY' },
      { start: moment('2025-08-30'), end: moment('2025-08-30'), translationKey: 'employeePage:HOLIDAYS.TR_VICTORY_DAY' },
      { start: moment('2025-10-28'), end: moment('2025-10-28'), translationKey: 'employeePage:HOLIDAYS.REPUBLIC_DAY_EVE', isHalfDay: true },
      { start: moment('2025-10-29'), end: moment('2025-10-29'), translationKey: 'employeePage:HOLIDAYS.REPUBLIC_DAY' },
      // 2026
      { start: moment('2026-01-01'), end: moment('2026-01-01'), translationKey: 'global:NEW_YEAR' },
      { start: moment('2026-03-19'), end: moment('2026-03-19'), translationKey: 'employeePage:HOLIDAYS.RAMADAN_HOLIDAY_EVE', isHalfDay: true },
      { start: moment('2026-03-20'), end: moment('2026-03-20'), translationKey: 'employeePage:HOLIDAYS.RAMADAN_HOLIDAY' },
      { start: moment('2026-03-21'), end: moment('2026-03-21'), translationKey: 'employeePage:HOLIDAYS.RAMADAN_HOLIDAY' },
      { start: moment('2026-03-22'), end: moment('2026-03-22'), translationKey: 'employeePage:HOLIDAYS.RAMADAN_HOLIDAY' },
      { start: moment('2026-04-23'), end: moment('2026-04-23'), translationKey: 'employeePage:HOLIDAYS.NATIONAL_SOVEREIGNTY_AND_CHILDREN_HOLIDAY' },
      { start: moment('2026-05-01'), end: moment('2026-05-01'), translationKey: 'employeePage:HOLIDAYS.LABOR_AND_SOLIDARITY_DAY' },
      { start: moment('2026-05-19'), end: moment('2026-05-19'), translationKey: 'employeePage:HOLIDAYS.COMMEMORATION_OF_ATATURK_YOUTH_AND_SPORTS_HOLIDAY' },
      { start: moment('2026-05-26'), end: moment('2026-05-26'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY_EVE', isHalfDay: true },
      { start: moment('2026-05-27'), end: moment('2026-05-27'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY' },
      { start: moment('2026-05-28'), end: moment('2026-05-28'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY' },
      { start: moment('2026-05-29'), end: moment('2026-05-29'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY' },
      { start: moment('2026-05-30'), end: moment('2026-05-30'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY' },
      { start: moment('2026-07-15'), end: moment('2026-07-15'), translationKey: 'employeePage:HOLIDAYS.TR_DEMOCRACY_AND_NATIONAL_UNION_DAY' },
      { start: moment('2026-08-30'), end: moment('2026-08-30'), translationKey: 'employeePage:HOLIDAYS.TR_VICTORY_DAY' },
      { start: moment('2026-10-28'), end: moment('2026-10-28'), translationKey: 'employeePage:HOLIDAYS.REPUBLIC_DAY_EVE', isHalfDay: true },
      { start: moment('2026-10-29'), end: moment('2026-10-29'), translationKey: 'employeePage:HOLIDAYS.REPUBLIC_DAY' },
      // 2027
      { start: moment('2027-01-01'), end: moment('2027-01-01'), translationKey: 'global:NEW_YEAR' },
      { start: moment('2027-03-08'), end: moment('2027-03-08'), translationKey: 'employeePage:HOLIDAYS.RAMADAN_HOLIDAY_EVE', isHalfDay: true },
      { start: moment('2027-03-09'), end: moment('2027-03-09'), translationKey: 'employeePage:HOLIDAYS.RAMADAN_HOLIDAY' },
      { start: moment('2027-03-10'), end: moment('2027-03-10'), translationKey: 'employeePage:HOLIDAYS.RAMADAN_HOLIDAY' },
      { start: moment('2027-03-11'), end: moment('2027-03-11'), translationKey: 'employeePage:HOLIDAYS.RAMADAN_HOLIDAY' },
      { start: moment('2027-04-23'), end: moment('2027-04-23'), translationKey: 'employeePage:HOLIDAYS.NATIONAL_SOVEREIGNTY_AND_CHILDREN_HOLIDAY' },
      { start: moment('2027-05-01'), end: moment('2027-05-01'), translationKey: 'employeePage:HOLIDAYS.LABOR_AND_SOLIDARITY_DAY' },
      { start: moment('2027-05-15'), end: moment('2027-05-15'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY_EVE', isHalfDay: true },
      { start: moment('2027-05-16'), end: moment('2027-05-16'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY' },
      { start: moment('2027-05-17'), end: moment('2027-05-17'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY' },
      { start: moment('2027-05-18'), end: moment('2027-05-18'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY' },
      { start: moment('2027-05-19'), end: moment('2027-05-19'), translationKey: 'employeePage:HOLIDAYS.SACRIFICE_HOLIDAY' },
      { start: moment('2027-05-19'), end: moment('2027-05-19'), translationKey: 'employeePage:HOLIDAYS.COMMEMORATION_OF_ATATURK_YOUTH_AND_SPORTS_HOLIDAY' },
      { start: moment('2027-07-15'), end: moment('2027-07-15'), translationKey: 'employeePage:HOLIDAYS.TR_DEMOCRACY_AND_NATIONAL_UNION_DAY' },
      { start: moment('2027-08-30'), end: moment('2027-08-30'), translationKey: 'employeePage:HOLIDAYS.TR_VICTORY_DAY' },
      { start: moment('2027-10-28'), end: moment('2027-10-28'), translationKey: 'employeePage:HOLIDAYS.REPUBLIC_DAY_EVE', isHalfDay: true },
      { start: moment('2027-10-29'), end: moment('2027-10-29'), translationKey: 'employeePage:HOLIDAYS.REPUBLIC_DAY' },
    ],
  },
  DE: {
    specialHolidays: [
      // 2022
      { start: moment('2022-01-01'), end: moment('2022-01-01'), translationKey: 'global:NEW_YEAR' },
      { start: moment('2022-04-15'), end: moment('2022-04-15'), translationKey: 'employeePage:HOLIDAYS.GOOD_FRIDAY' },
      { start: moment('2022-04-18'), end: moment('2022-04-18'), translationKey: 'employeePage:HOLIDAYS.EASTER_MONDAY' },
      { start: moment('2022-05-01'), end: moment('2022-05-01'), translationKey: 'employeePage:HOLIDAYS.LABOUR_DAY' },
      { start: moment('2022-05-26'), end: moment('2022-05-26'), translationKey: 'employeePage:HOLIDAYS.ASCENSION_DAY' },
      { start: moment('2022-06-06'), end: moment('2022-06-06'), translationKey: 'employeePage:HOLIDAYS.WHIT_MONDAY' },
      { start: moment('2022-10-03'), end: moment('2022-10-03'), translationKey: 'employeePage:HOLIDAYS.DAY_OF_GERMAN_UNITY' },
      { start: moment('2022-12-25'), end: moment('2022-12-25'), translationKey: 'employeePage:HOLIDAYS.CHRISTMAS' },
      { start: moment('2022-12-26'), end: moment('2022-12-26'), translationKey: 'employeePage:HOLIDAYS.SECOND_DAY_OF_CHRISTMAS' },
      // 2023
      { start: moment('2023-01-01'), end: moment('2023-01-01'), translationKey: 'global:NEW_YEAR' },
      { start: moment('2023-01-06'), end: moment('2023-01-06'), translationKey: 'global:EPIPHANY', isLocal: true, cities: ['Munich'] },
      { start: moment('2023-03-08'), end: moment('2023-03-08'), translationKey: 'global:INTERNATIONAL_WOMANS_DAY', isLocal: true, cities: ['Berlin'] },
      { start: moment('2023-04-07'), end: moment('2023-04-07'), translationKey: 'employeePage:HOLIDAYS.GOOD_FRIDAY' },
      { start: moment('2023-04-09'), end: moment('2023-04-09'), translationKey: 'employeePage:HOLIDAYS.EASTER_SUNDAY', isLocal: true, cities: ['Berlin'] },
      { start: moment('2023-04-10'), end: moment('2023-04-10'), translationKey: 'employeePage:HOLIDAYS.EASTER_MONDAY' },
      { start: moment('2023-05-01'), end: moment('2023-05-01'), translationKey: 'employeePage:HOLIDAYS.LABOUR_DAY' },
      { start: moment('2023-05-18'), end: moment('2023-05-18'), translationKey: 'employeePage:HOLIDAYS.ASCENSION_DAY' },
      { start: moment('2023-05-28'), end: moment('2023-05-28'), translationKey: 'employeePage:HOLIDAYS.WHIT_SUNDAY', isLocal: true, cities: ['Berlin'] },
      { start: moment('2023-05-29'), end: moment('2023-05-29'), translationKey: 'employeePage:HOLIDAYS.WHIT_MONDAY' },
      { start: moment('2023-06-08'), end: moment('2023-06-08'), translationKey: 'employeePage:HOLIDAYS.CORPUS_CHRISTI', isLocal: true, cities: ['Munich', 'Dusseldorf'] },
      { start: moment('2023-08-15'), end: moment('2023-08-15'), translationKey: 'employeePage:HOLIDAYS.ASSUMPTION_DAY', isLocal: true, cities: ['Munich'] },
      { start: moment('2023-10-03'), end: moment('2023-10-03'), translationKey: 'employeePage:HOLIDAYS.DAY_OF_GERMAN_UNITY' },
      { start: moment('2023-10-31'), end: moment('2023-10-31'), translationKey: 'employeePage:HOLIDAYS.REFORMATION_DAY', isLocal: true, cities: ['Hamburg'] },
      { start: moment('2023-11-01'), end: moment('2023-11-01'), translationKey: 'employeePage:HOLIDAYS.ALL_SAINTS_DAY', isLocal: true, cities: ['Munich', 'Dusseldorf'] },
      { start: moment('2023-12-25'), end: moment('2023-12-25'), translationKey: 'employeePage:HOLIDAYS.CHRISTMAS' },
      { start: moment('2023-12-26'), end: moment('2023-12-26'), translationKey: 'employeePage:HOLIDAYS.SECOND_DAY_OF_CHRISTMAS' },
    ],
  },
  NL: {
    specialHolidays: [
      // 2022
      { start: moment('2022-01-01'), end: moment('2022-01-01'), translationKey: 'global:NEW_YEAR' },
      { start: moment('2022-04-15'), end: moment('2022-04-15'), translationKey: 'employeePage:HOLIDAYS.GOOD_FRIDAY' },
      { start: moment('2022-04-18'), end: moment('2022-04-18'), translationKey: 'employeePage:HOLIDAYS.EASTER_MONDAY' },
      { start: moment('2022-04-27'), end: moment('2022-04-27'), translationKey: 'employeePage:HOLIDAYS.KINGS_DAY' },
      { start: moment('2022-05-26'), end: moment('2022-05-26'), translationKey: 'employeePage:HOLIDAYS.ASCENSION_DAY' },
      { start: moment('2022-06-06'), end: moment('2022-06-06'), translationKey: 'employeePage:HOLIDAYS.WHIT_MONDAY' },
      { start: moment('2022-12-26'), end: moment('2022-12-26'), translationKey: 'employeePage:HOLIDAYS.SECOND_DAY_OF_CHRISTMAS' },
      // 2023
      { start: moment('2023-01-01'), end: moment('2023-01-01'), translationKey: 'global:NEW_YEAR' },
      { start: moment('2023-04-10'), end: moment('2023-04-10'), translationKey: 'employeePage:HOLIDAYS.EASTER_MONDAY' },
      { start: moment('2023-04-27'), end: moment('2023-04-27'), translationKey: 'employeePage:HOLIDAYS.KINGS_DAY' },
      { start: moment('2023-05-18'), end: moment('2023-05-18'), translationKey: 'employeePage:HOLIDAYS.ASCENSION_DAY' },
      { start: moment('2023-05-29'), end: moment('2023-05-29'), translationKey: 'employeePage:HOLIDAYS.WHIT_MONDAY' },
      { start: moment('2023-12-25'), end: moment('2023-12-25'), translationKey: 'employeePage:HOLIDAYS.FIRST_DAY_OF_CHRISTMAS' },
      { start: moment('2023-12-26'), end: moment('2023-12-26'), translationKey: 'employeePage:HOLIDAYS.SECOND_DAY_OF_CHRISTMAS' },
    ],
  },
  FR: {
    specialHolidays: [
      // 2022
      { start: moment('2022-01-01'), end: moment('2022-01-01'), translationKey: 'global:NEW_YEAR' },
      { start: moment('2022-04-18'), end: moment('2022-04-18'), translationKey: 'employeePage:HOLIDAYS.EASTER_MONDAY' },
      { start: moment('2022-05-01'), end: moment('2022-05-01'), translationKey: 'employeePage:HOLIDAYS.LABOUR_DAY' },
      { start: moment('2022-05-08'), end: moment('2022-05-08'), translationKey: 'employeePage:HOLIDAYS.FR_VICTORY_DAY' },
      { start: moment('2022-05-26'), end: moment('2022-05-26'), translationKey: 'employeePage:HOLIDAYS.ASCENSION_DAY' },
      { start: moment('2022-06-06'), end: moment('2022-06-06'), translationKey: 'employeePage:HOLIDAYS.PENTECOST' },
      { start: moment('2022-07-14'), end: moment('2022-07-14'), translationKey: 'employeePage:HOLIDAYS.FR_BANK_HOLIDAY' },
      { start: moment('2022-08-15'), end: moment('2022-08-15'), translationKey: 'employeePage:HOLIDAYS.ASSUMPTION_DAY' },
      { start: moment('2022-11-01'), end: moment('2022-11-01'), translationKey: 'employeePage:HOLIDAYS.ALL_SAINTS_DAY' },
      { start: moment('2022-11-11'), end: moment('2022-11-11'), translationKey: 'employeePage:HOLIDAYS.ARMISTICE_1918' },
      { start: moment('2022-12-25'), end: moment('2022-12-25'), translationKey: 'employeePage:HOLIDAYS.CHRISTMAS' },
      // 2023
      { start: moment('2023-01-01'), end: moment('2023-01-01'), translationKey: 'global:NEW_YEAR' },
      { start: moment('2023-04-10'), end: moment('2023-04-10'), translationKey: 'employeePage:HOLIDAYS.EASTER_MONDAY' },
      { start: moment('2023-05-01'), end: moment('2023-05-01'), translationKey: 'employeePage:HOLIDAYS.LABOUR_DAY' },
      { start: moment('2023-05-08'), end: moment('2023-05-08'), translationKey: 'employeePage:HOLIDAYS.FR_VICTORY_DAY' },
      { start: moment('2023-05-18'), end: moment('2023-05-18'), translationKey: 'employeePage:HOLIDAYS.ASCENSION_DAY' },
      { start: moment('2023-05-29'), end: moment('2023-05-29'), translationKey: 'employeePage:HOLIDAYS.PENTECOST' },
      { start: moment('2023-07-14'), end: moment('2023-07-14'), translationKey: 'employeePage:HOLIDAYS.FR_BANK_HOLIDAY' },
      { start: moment('2023-08-15'), end: moment('2023-08-15'), translationKey: 'employeePage:HOLIDAYS.ASSUMPTION_DAY' },
      { start: moment('2023-11-01'), end: moment('2023-11-01'), translationKey: 'employeePage:HOLIDAYS.ALL_SAINTS_DAY' },
      { start: moment('2023-11-11'), end: moment('2023-11-11'), translationKey: 'employeePage:HOLIDAYS.ARMISTICE_1918' },
      { start: moment('2023-12-25'), end: moment('2023-12-25'), translationKey: 'employeePage:HOLIDAYS.CHRISTMAS' },
    ],
  },
  IT: {
    specialHolidays: [
      // 2022
      { start: moment('2022-01-01'), end: moment('2022-01-01'), translationKey: 'global:NEW_YEAR' },
      { start: moment('2022-01-06'), end: moment('2022-01-06'), translationKey: 'global:EPIPHANY' },
      { start: moment('2022-04-18'), end: moment('2022-04-18'), translationKey: 'employeePage:HOLIDAYS.EASTER_MONDAY' },
      { start: moment('2022-04-25'), end: moment('2022-04-25'), translationKey: 'employeePage:HOLIDAYS.LIBERATION_DAY' },
      { start: moment('2022-06-02'), end: moment('2022-06-02'), translationKey: 'employeePage:HOLIDAYS.REPUBLIC_DAY' },
      { start: moment('2022-08-15'), end: moment('2022-08-15'), translationKey: 'employeePage:HOLIDAYS.ASSUMPTION_DAY' },
      { start: moment('2022-11-01'), end: moment('2022-11-01'), translationKey: 'employeePage:HOLIDAYS.ALL_SAINTS_DAY' },
      { start: moment('2022-12-08'), end: moment('2022-12-08'), translationKey: 'employeePage:HOLIDAYS.FEAST_OF_THE_IMMACULATE_CONCEPTION' },
      { start: moment('2022-12-25'), end: moment('2022-12-25'), translationKey: 'employeePage:HOLIDAYS.CHRISTMAS' },
      { start: moment('2022-12-26'), end: moment('2022-12-26'), translationKey: 'employeePage:HOLIDAYS.SECOND_DAY_OF_CHRISTMAS' },
      // 2023
      { start: moment('2023-01-01'), end: moment('2023-01-01'), translationKey: 'global:NEW_YEAR' },
      { start: moment('2023-01-06'), end: moment('2023-01-06'), translationKey: 'global:EPIPHANY' },
      { start: moment('2023-04-10'), end: moment('2023-04-10'), translationKey: 'employeePage:HOLIDAYS.EASTER_MONDAY' },
      { start: moment('2023-04-25'), end: moment('2023-04-25'), translationKey: 'employeePage:HOLIDAYS.LIBERATION_DAY' },
      { start: moment('2023-06-02'), end: moment('2023-06-02'), translationKey: 'employeePage:HOLIDAYS.REPUBLIC_DAY' },
      { start: moment('2023-06-24'), end: moment('2023-06-24'), translationKey: 'employeePage:HOLIDAYS.SAN_GIOVANNI_DAY', isLocal: true, cities: ['Torino'] },
      { start: moment('2023-06-29'), end: moment('2023-06-29'), translationKey: 'employeePage:HOLIDAYS.FEAST_OF_THE_IMMACULATE_CONCEPTION', isLocal: true, cities: ['Rome'] },
      { start: moment('2023-08-15'), end: moment('2023-08-15'), translationKey: 'employeePage:HOLIDAYS.ASSUMPTION_DAY' },
      { start: moment('2023-08-16'), end: moment('2023-08-16'), translationKey: 'employeePage:HOLIDAYS.FESTA_DEL_COMMERCIO', isLocal: true, cities: ['Milan'] },
      { start: moment('2023-11-01'), end: moment('2023-11-01'), translationKey: 'employeePage:HOLIDAYS.ALL_SAINTS_DAY' },
      { start: moment('2023-12-07'), end: moment('2023-12-07'), translationKey: 'employeePage:HOLIDAYS.THE_FEAST_OF_ST_AMBROSE', isLocal: true, cities: ['Milan'] },
      { start: moment('2023-12-08'), end: moment('2023-12-08'), translationKey: 'employeePage:HOLIDAYS.FEAST_OF_THE_IMMACULATE_CONCEPTION' },
      { start: moment('2023-12-25'), end: moment('2023-12-25'), translationKey: 'employeePage:HOLIDAYS.CHRISTMAS' },
      { start: moment('2023-12-26'), end: moment('2023-12-26'), translationKey: 'employeePage:HOLIDAYS.SECOND_DAY_OF_CHRISTMAS' },
    ],
  },
  ES: {
    specialHolidays: [
      // 2022
      { start: moment('2022-01-01'), end: moment('2022-01-01'), translationKey: 'global:NEW_YEAR' },
      { start: moment('2022-01-06'), end: moment('2022-01-06'), translationKey: 'global:EPIPHANY' },
      { start: moment('2022-04-15'), end: moment('2022-04-15'), translationKey: 'employeePage:HOLIDAYS.GOOD_FRIDAY' },
      { start: moment('2022-08-15'), end: moment('2022-08-15'), translationKey: 'employeePage:HOLIDAYS.ASSUMPTION_DAY' },
      { start: moment('2022-10-12'), end: moment('2022-10-12'), translationKey: 'employeePage:HOLIDAYS.NATIONAL_DAY_OF_SPAIN' },
      { start: moment('2022-11-01'), end: moment('2022-11-01'), translationKey: 'employeePage:HOLIDAYS.ALL_SAINTS_DAY' },
      { start: moment('2022-12-06'), end: moment('2022-12-06'), translationKey: 'employeePage:HOLIDAYS.CONSTITUTION_DAY' },
      { start: moment('2022-12-08'), end: moment('2022-12-08'), translationKey: 'employeePage:HOLIDAYS.FEAST_OF_THE_IMMACULATE_CONCEPTION' },
      { start: moment('2022-12-25'), end: moment('2022-12-25'), translationKey: 'employeePage:HOLIDAYS.CHRISTMAS' },
      // 2023
      { start: moment('2023-01-01'), end: moment('2023-01-01'), translationKey: 'global:NEW_YEAR' },
      { start: moment('2023-01-02'), end: moment('2023-01-02'), translationKey: 'global:NEW_YEARS_FESTIVE_DAY', isLocal: true, cities: ['Seville', 'Zaragoza'] },
      { start: moment('2023-01-06'), end: moment('2023-01-06'), translationKey: 'global:EPIPHANY' },
      { start: moment('2023-01-30'), end: moment('2023-01-30'), translationKey: 'global:LOCAL_HOLIDAY', isLocal: true, cities: ['Zaragoza'] },
      { start: moment('2023-02-28'), end: moment('2023-02-28'), translationKey: 'global:LOCAL_HOLIDAY', isLocal: true, cities: ['Zaragoza', 'Malaga'] },
      { start: moment('2023-03-06'), end: moment('2023-03-06'), translationKey: 'global:LOCAL_HOLIDAY', isLocal: true, cities: ['Zaragoza'] },
      { start: moment('2023-03-20'), end: moment('2023-03-20'), translationKey: 'global:EASTER_FEAST_DAY', isLocal: true, cities: ['Madrid'] },
      { start: moment('2023-04-06'), end: moment('2023-04-06'), translationKey: 'employeePage:HOLIDAYS.GOOD_FRIDAY' },
      { start: moment('2023-04-06'), end: moment('2023-04-06'), translationKey: 'employeePage:HOLIDAYS.EASTER_THURSDAY', isLocal: true, cities: ['Madrid', 'Seville'] },
      { start: moment('2023-04-10'), end: moment('2023-04-10'), translationKey: 'employeePage:HOLIDAYS.EASTER_MONDAY', isLocal: true, cities: ['Barcelona', 'Valencia'] },
      { start: moment('2023-04-17'), end: moment('2023-04-17'), translationKey: 'employeePage:HOLIDAYS.LOCAL_HOLIDAY', isLocal: true, cities: ['Valencia'] },
      { start: moment('2023-04-24'), end: moment('2023-04-24'), translationKey: 'employeePage:HOLIDAYS.LOCAL_HOLIDAY', isLocal: true, cities: ['Zaragoza'] },
      { start: moment('2023-04-26'), end: moment('2023-04-26'), translationKey: 'employeePage:HOLIDAYS.LOCAL_HOLIDAY', isLocal: true, cities: ['Seville'] },
      { start: moment('2023-05-01'), end: moment('2023-05-01'), translationKey: 'employeePage:HOLIDAYS.LABOUR_DAY' },
      { start: moment('2023-05-02'), end: moment('2023-05-02'), translationKey: 'employeePage:HOLIDAYS.DAY_OF_MADRID', isLocal: true, cities: ['Madrid'] },
      { start: moment('2023-05-15'), end: moment('2023-05-15'), translationKey: 'employeePage:HOLIDAYS.LOCAL_HOLIDAY', isLocal: true, cities: ['Madrid'] },
      { start: moment('2023-06-05'), end: moment('2023-06-05'), translationKey: 'employeePage:HOLIDAYS.LOCAL_HOLIDAY', isLocal: true, cities: ['Barcelona'] },
      { start: moment('2023-06-08'), end: moment('2023-06-08'), translationKey: 'employeePage:HOLIDAYS.LOCAL_HOLIDAY', isLocal: true, cities: ['Seville'] },
      { start: moment('2023-06-24'), end: moment('2023-06-24'), translationKey: 'employeePage:HOLIDAYS.NATIVITY_OF_JOHN_THE_BAPTIST', isLocal: true, cities: ['Barcelona', 'Valencia'] },
      { start: moment('2023-08-15'), end: moment('2023-08-15'), translationKey: 'employeePage:HOLIDAYS.ASSUMPTION_DAY' },
      { start: moment('2023-08-19'), end: moment('2023-08-19'), translationKey: 'employeePage:HOLIDAYS.LOCAL_HOLIDAY', isLocal: true, cities: ['Malaga'] },
      { start: moment('2023-09-08'), end: moment('2023-09-08'), translationKey: 'employeePage:HOLIDAYS.LOCAL_HOLIDAY', isLocal: true, cities: ['Malaga'] },
      { start: moment('2023-09-11'), end: moment('2023-09-11'), translationKey: 'employeePage:HOLIDAYS.CATALUNYA_DAY', isLocal: true, cities: ['Barcelona'] },
      { start: moment('2023-09-25'), end: moment('2023-09-25'), translationKey: 'employeePage:HOLIDAYS.LOCAL_HOLIDAY', isLocal: true, cities: ['Barcelona'] },
      { start: moment('2023-10-09'), end: moment('2023-10-09'), translationKey: 'employeePage:HOLIDAYS.LOCAL_HOLIDAY', isLocal: true, cities: ['Valencia'] },
      { start: moment('2023-10-12'), end: moment('2023-10-12'), translationKey: 'employeePage:HOLIDAYS.NATIONAL_DAY_OF_SPAIN' },
      { start: moment('2023-11-01'), end: moment('2023-11-01'), translationKey: 'employeePage:HOLIDAYS.ALL_SAINTS_DAY' },
      { start: moment('2023-11-09'), end: moment('2023-11-09'), translationKey: 'employeePage:HOLIDAYS.LOCAL_HOLIDAY', isLocal: true, cities: ['Madrid'] },
      { start: moment('2023-12-06'), end: moment('2023-12-06'), translationKey: 'employeePage:HOLIDAYS.CONSTITUTION_DAY' },
      { start: moment('2023-12-08'), end: moment('2023-12-08'), translationKey: 'employeePage:HOLIDAYS.FEAST_OF_THE_IMMACULATE_CONCEPTION' },
      { start: moment('2023-12-25'), end: moment('2023-12-25'), translationKey: 'employeePage:HOLIDAYS.CHRISTMAS' },
      { start: moment('2023-12-26'), end: moment('2023-12-26'), translationKey: 'employeePage:HOLIDAYS.ST_MICHAELS_DAY' },
      { start: moment('2023-12-26'), end: moment('2023-12-26'), translationKey: 'employeePage:HOLIDAYS.ST_STEPHENS_DAY', isLocal: true, cities: ['Barcelona'] },
    ],
  },
  PT: {
    specialHolidays: [
      // 2022
      { start: moment('2022-01-01'), end: moment('2022-01-01'), translationKey: 'global:NEW_YEAR' },
      { start: moment('2022-04-15'), end: moment('2022-04-15'), translationKey: 'employeePage:HOLIDAYS.GOOD_FRIDAY' },
      { start: moment('2022-04-17'), end: moment('2022-04-17'), translationKey: 'employeePage:HOLIDAYS.EASTER' },
      { start: moment('2022-04-25'), end: moment('2022-04-25'), translationKey: 'employeePage:HOLIDAYS.FREEDOM_DAY' },
      { start: moment('2022-05-01'), end: moment('2022-05-01'), translationKey: 'employeePage:HOLIDAYS.LABOUR_DAY' },
      { start: moment('2022-06-16'), end: moment('2022-06-16'), translationKey: 'employeePage:HOLIDAYS.CORPUS_CHRISTI' },
      { start: moment('2022-08-15'), end: moment('2022-08-15'), translationKey: 'employeePage:HOLIDAYS.ASSUMPTION_DAY' },
      { start: moment('2022-10-05'), end: moment('2022-10-05'), translationKey: 'employeePage:HOLIDAYS.REPUBLIC_DAY' },
      { start: moment('2022-11-01'), end: moment('2022-11-01'), translationKey: 'employeePage:HOLIDAYS.ALL_SAINTS_DAY' },
      { start: moment('2022-12-01'), end: moment('2022-12-01'), translationKey: 'employeePage:HOLIDAYS.PORTUGAL_RESTORATION_OF_INDEPENDENCE_DAY' },
      { start: moment('2022-12-08'), end: moment('2022-12-08'), translationKey: 'employeePage:HOLIDAYS.FEAST_OF_THE_IMMACULATE_CONCEPTION' },
      { start: moment('2022-12-24'), end: moment('2022-12-24'), translationKey: 'employeePage:HOLIDAYS.CHRISTMAS_EVE' },
      { start: moment('2022-12-25'), end: moment('2022-12-25'), translationKey: 'employeePage:HOLIDAYS.CHRISTMAS' },
      // 2023
      { start: moment('2023-01-01'), end: moment('2023-01-01'), translationKey: 'global:NEW_YEAR' },
      { start: moment('2023-04-07'), end: moment('2023-04-07'), translationKey: 'employeePage:HOLIDAYS.GOOD_FRIDAY' },
      { start: moment('2023-04-09'), end: moment('2023-04-09'), translationKey: 'employeePage:HOLIDAYS.EASTER' },
      { start: moment('2023-04-25'), end: moment('2023-04-25'), translationKey: 'employeePage:HOLIDAYS.FREEDOM_DAY' },
      { start: moment('2023-05-01'), end: moment('2023-05-01'), translationKey: 'employeePage:HOLIDAYS.LABOUR_DAY' },
      { start: moment('2023-06-13'), end: moment('2023-06-13'), translationKey: 'employeePage:HOLIDAYS.THE_SAINT_ANTHONYS_DAY', isLocal: true, cities: ['Lisbon'] },
      { start: moment('2023-06-16'), end: moment('2023-06-16'), translationKey: 'employeePage:HOLIDAYS.CORPUS_CHRISTI' },
      { start: moment('2023-08-15'), end: moment('2023-08-15'), translationKey: 'employeePage:HOLIDAYS.ASSUMPTION_DAY' },
      { start: moment('2023-10-05'), end: moment('2023-10-05'), translationKey: 'employeePage:HOLIDAYS.REPUBLIC_DAY' },
      { start: moment('2023-11-01'), end: moment('2023-11-01'), translationKey: 'employeePage:HOLIDAYS.ALL_SAINTS_DAY' },
      { start: moment('2023-12-01'), end: moment('2023-12-01'), translationKey: 'employeePage:HOLIDAYS.PORTUGAL_RESTORATION_OF_INDEPENDENCE_DAY' },
      { start: moment('2023-12-08'), end: moment('2023-12-08'), translationKey: 'employeePage:HOLIDAYS.FEAST_OF_THE_IMMACULATE_CONCEPTION' },
      { start: moment('2023-12-24'), end: moment('2023-12-24'), translationKey: 'employeePage:HOLIDAYS.CHRISTMAS_EVE' },
      { start: moment('2023-12-25'), end: moment('2023-12-25'), translationKey: 'employeePage:HOLIDAYS.CHRISTMAS' },
    ],
  },
  GB: {
    specialHolidays: [
      // 2022
      { start: moment('2022-01-03'), end: moment('2022-01-03'), translationKey: 'global:NEW_YEAR' },
      { start: moment('2022-04-15'), end: moment('2022-04-15'), translationKey: 'employeePage:HOLIDAYS.GOOD_FRIDAY' },
      { start: moment('2022-04-18'), end: moment('2022-04-18'), translationKey: 'employeePage:HOLIDAYS.EASTER_MONDAY' },
      { start: moment('2022-05-02'), end: moment('2022-05-02'), translationKey: 'employeePage:HOLIDAYS.EARLY_MAY_BANK_HOLIDAY' },
      { start: moment('2022-06-02'), end: moment('2022-06-02'), translationKey: 'employeePage:HOLIDAYS.SPRING_BANK_HOLIDAY' },
      { start: moment('2022-06-03'), end: moment('2022-06-03'), translationKey: 'employeePage:HOLIDAYS.PLATINUM_JUBILEE_BANK_HOLIDAY' },
      { start: moment('2022-08-29'), end: moment('2022-08-29'), translationKey: 'employeePage:HOLIDAYS.SUMMER_BANK_HOLIDAY' },
      { start: moment('2022-09-19'), end: moment('2022-09-19'), translationKey: 'employeePage:HOLIDAYS.STATE_FUNERAL_OF_QUEEN_ELIZABETH-II' },
      { start: moment('2022-12-26'), end: moment('2022-12-26'), translationKey: 'employeePage:HOLIDAYS.BOXING_DAY' },
      { start: moment('2022-12-27'), end: moment('2022-12-27'), translationKey: 'employeePage:HOLIDAYS.CHRISTMAS' },
      // 2023
      { start: moment('2023-01-02'), end: moment('2023-01-02'), translationKey: 'global:NEW_YEAR' },
      { start: moment('2023-04-07'), end: moment('2023-04-07'), translationKey: 'employeePage:HOLIDAYS.GOOD_FRIDAY' },
      { start: moment('2023-04-10'), end: moment('2023-04-10'), translationKey: 'employeePage:HOLIDAYS.EASTER_MONDAY' },
      { start: moment('2023-05-01'), end: moment('2023-05-01'), translationKey: 'employeePage:HOLIDAYS.EARLY_MAY_BANK_HOLIDAY' },
      { start: moment('2023-05-29'), end: moment('2023-05-29'), translationKey: 'employeePage:HOLIDAYS.SPRING_BANK_HOLIDAY' },
      { start: moment('2023-08-28'), end: moment('2023-08-28'), translationKey: 'employeePage:HOLIDAYS.SUMMER_BANK_HOLIDAY' },
      { start: moment('2023-12-25'), end: moment('2023-12-25'), translationKey: 'employeePage:HOLIDAYS.BOXING_DAY' },
      { start: moment('2023-12-26'), end: moment('2023-12-26'), translationKey: 'employeePage:HOLIDAYS.CHRISTMAS' },
    ],
  },
  US: {
    specialHolidays: [
      // 2022
      { start: moment('2022-05-30'), end: moment('2022-05-30'), translationKey: 'employeePage:HOLIDAYS.MEMORIAL_DAY' },
      { start: moment('2022-06-19'), end: moment('2022-06-19'), translationKey: 'employeePage:HOLIDAYS.JUNETEENTH' },
      { start: moment('2022-07-04'), end: moment('2022-07-04'), translationKey: 'employeePage:HOLIDAYS.INDEPENDENCE_DAY' },
      { start: moment('2022-09-05'), end: moment('2022-09-05'), translationKey: 'employeePage:HOLIDAYS.LABOUR_DAY' },
      { start: moment('2022-11-24'), end: moment('2022-11-24'), translationKey: 'employeePage:HOLIDAYS.THANKSGIVING' },
      { start: moment('2022-11-25'), end: moment('2022-11-25'), translationKey: 'employeePage:HOLIDAYS.BLACK_FRIDAY' },
      { start: moment('2022-12-23'), end: moment('2022-12-23'), translationKey: 'employeePage:HOLIDAYS.CHRISTMAS_EVE' },
      { start: moment('2022-12-26'), end: moment('2022-12-26'), translationKey: 'employeePage:HOLIDAYS.CHRISTMAS' },
      // 2023
      { start: moment('2023-01-01'), end: moment('2023-01-01'), translationKey: 'global:NEW_YEAR' },
      { start: moment('2023-01-16'), end: moment('2023-01-16'), translationKey: 'employeePage:MLK' },
      { start: moment('2023-02-20'), end: moment('2023-02-20'), translationKey: 'global:PRESIDENT_WASHINGTONS_BIRTHDAY' },
      { start: moment('2023-05-29'), end: moment('2023-05-29'), translationKey: 'employeePage:HOLIDAYS.MEMORIAL_DAY' },
      { start: moment('2023-06-19'), end: moment('2023-06-19'), translationKey: 'employeePage:HOLIDAYS.JUNETEENTH' },
      { start: moment('2023-07-04'), end: moment('2023-07-04'), translationKey: 'employeePage:HOLIDAYS.INDEPENDENCE_DAY' },
      { start: moment('2023-09-04'), end: moment('2023-09-04'), translationKey: 'employeePage:HOLIDAYS.LABOUR_DAY' },
      { start: moment('2023-11-11'), end: moment('2023-11-11'), translationKey: 'employeePage:HOLIDAYS.VETERANS_DAY' },
      { start: moment('2023-11-23'), end: moment('2023-11-23'), translationKey: 'employeePage:HOLIDAYS.THANKSGIVING' },
      { start: moment('2023-11-24'), end: moment('2023-11-24'), translationKey: 'employeePage:HOLIDAYS.BLACK_FRIDAY' },
      { start: moment('2023-12-23'), end: moment('2023-12-23'), translationKey: 'employeePage:HOLIDAYS.CHRISTMAS_EVE' },
      { start: moment('2023-12-26'), end: moment('2023-12-26'), translationKey: 'employeePage:HOLIDAYS.CHRISTMAS' },
    ],
  },
  IN: {
    specialHolidays: [
      // 2022
      { start: moment('2022-01-26'), end: moment('2022-01-26'), translationKey: 'employeePage:HOLIDAYS.REPUBLIC_DAY' },
      { start: moment('2022-03-18'), end: moment('2022-03-18'), translationKey: 'employeePage:HOLIDAYS.HOLI' },
      { start: moment('2022-04-15'), end: moment('2022-04-15'), translationKey: 'employeePage:HOLIDAYS.GOOD_FRIDAY' },
      { start: moment('2022-05-03'), end: moment('2022-05-03'), translationKey: 'employeePage:HOLIDAYS.ID_UL_FITR' },
      { start: moment('2022-08-15'), end: moment('2022-08-15'), translationKey: 'employeePage:HOLIDAYS.INDEPENDENCE_DAY' },
      { start: moment('2022-08-31'), end: moment('2022-08-31'), translationKey: 'employeePage:HOLIDAYS.GANESH_CHATURTI' },
      { start: moment('2022-10-05'), end: moment('2022-10-05'), translationKey: 'employeePage:HOLIDAYS.DUSSHERA' },
      { start: moment('2022-10-24'), end: moment('2022-10-24'), translationKey: 'employeePage:HOLIDAYS.DIWALI' },
      { start: moment('2022-10-25'), end: moment('2022-10-25'), translationKey: 'employeePage:HOLIDAYS.DIWALI' },
      { start: moment('2022-11-01'), end: moment('2022-11-01'), translationKey: 'employeePage:HOLIDAYS.KARNATAKA_RAJYOTSAVA' },
      { start: moment('2022-12-25'), end: moment('2022-12-25'), translationKey: 'employeePage:HOLIDAYS.CHRISTMAS' },
      // 2023
      { start: moment('2023-01-26'), end: moment('2023-01-26'), translationKey: 'employeePage:HOLIDAYS.REPUBLIC_DAY' },
      { start: moment('2023-03-22'), end: moment('2023-03-22'), translationKey: 'employeePage:HOLIDAYS.UGADI' },
      { start: moment('2023-04-21'), end: moment('2023-04-21'), translationKey: 'employeePage:HOLIDAYS.ID_UL_FITR' },
      { start: moment('2023-05-01'), end: moment('2023-05-01'), translationKey: 'employeePage:HOLIDAYS.MAY_DAY' },
      { start: moment('2023-08-15'), end: moment('2023-08-15'), translationKey: 'employeePage:HOLIDAYS.INDEPENDENCE_DAY' },
      { start: moment('2023-09-19'), end: moment('2023-09-19'), translationKey: 'employeePage:HOLIDAYS.GANESH_CHATURTI' },
      { start: moment('2023-10-02'), end: moment('2023-10-02'), translationKey: 'employeePage:HOLIDAYS.GANDHI_JAYANTHI' },
      { start: moment('2023-10-24'), end: moment('2023-10-24'), translationKey: 'employeePage:HOLIDAYS.DUSSHERA' },
      { start: moment('2023-11-01'), end: moment('2023-11-01'), translationKey: 'employeePage:HOLIDAYS.KARNATAKA_RAJYOTSAVA' },
      { start: moment('2023-11-10'), end: moment('2023-11-10'), translationKey: 'employeePage:HOLIDAYS.DIWALI' },
      { start: moment('2023-12-25'), end: moment('2023-12-25'), translationKey: 'employeePage:HOLIDAYS.CHRISTMAS' },
    ],
  },
} as const;

export const PAGINATION_MODES = {
  CURSOR: 'cursor',
  OFFSET: 'offset',
} as const;

export const EMPLOYEE_PAYROLL_COUNTRY_OPTIONS = {
  tr: { en: 'Turkey', tr: 'Türkiye' },
  gb: { en: 'United Kingdom', tr: 'Birleşik Krallık' },
  us: { en: 'United States', tr: 'Amerika Birleşik Devletleri' },
  de: { en: 'Germany', tr: 'Almanya' },
  es: { en: 'Spain', tr: 'Spain' },
  fr: { en: 'France', tr: 'Fransa' },
  it: { en: 'Italy', tr: 'Italy' },
  nl: { en: 'Netherlands', tr: 'Hollanda' },
  pt: { en: 'Portugal', tr: 'Portugal' },
  in: { en: 'India', tr: 'India' },
} as const;

export const EMPLOYEE_BUSINESS_COUNTRY_OPTIONS = {
  global: { en: 'Global', tr: 'Global' },
  tr: { en: 'Turkey', tr: 'Türkiye' },
  gb: { en: 'United Kingdom', tr: 'Birleşik Krallık' },
  us: { en: 'United States', tr: 'Amerika Birleşik Devletleri' },
  de: { en: 'Germany', tr: 'Almanya' },
  es: { en: 'Spain', tr: 'Spain' },
  fr: { en: 'France', tr: 'Fransa' },
  it: { en: 'Italy', tr: 'Italy' },
  nl: { en: 'Netherlands', tr: 'Hollanda' },
  pt: { en: 'Portugal', tr: 'Portugal' },
} as const;

export const EMPLOYEE_CHANGE_LOG_REASONS = {
  PROMOTION: 'PROMOTION',
  PROMOTION_HORIZONTAL: 'PROMOTION_HORIZONTAL',
  POSITION_CHANGE: 'POSITION_CHANGE',
  INTERN_TO_SPECIALIST: 'INTERN_TO_SPECIALIST',
  DATA_CORRECTION: 'DATA_CORRECTION',
} as const;

export const FEATURE_FLAGS = {
  REGULAR_LEAVE_REQUESTS_ARE_ENABLED: true,
  OFF_SITE_WORK_REQUESTS_ARE_ENABLED: true,
} as const;

export const EMPLOYEE_CHANGE_LOG_CHANGE_MODELS = {
  EMPLOYEE: 'EMPLOYEE',
  EDUCATION: 'EDUCATION',
} as const;

export const FIELD_PATHS = {
  [EMPLOYEE_CHANGE_LOG_CHANGE_MODELS.EMPLOYEE]: {
    PAYROLL_COUNTRY_CODE: 'payrollCountryCode',
    EMPLOYMENT_STATUS: 'employmentStatus',
    NAME: 'name',
    SURNAME: 'surname',
    UNIQUE_IDENTIFIER: 'uniqueIdentifier',
    BIRTHDATE: 'birthdate',
    NATIONALITY: 'nationality',
    GENDER: 'gender',
    PERSONAL_EMAIL: 'personalEmail',
    PERSONAL_GSM: 'personalGSM_number',
    RESIDENTIAL_ADDRESS: 'residentialAddress_address',
    WORK_START_DATE: 'workStartDate',
    EMPLOYMENT_TYPE: 'employmentType',
    CONTRACT_TYPE: 'contractType',
    BUSINESS_UNIT: 'businessUnit',
    DEPARTMENT: 'department',
    SUB_DEPARTMENTS: 'subDepartments_firstLevelSub',
    JOB_TITLE: 'jobTitle',
    POSITION_LEVEL: 'positionLevel',
    LINE_MANAGER: 'lineManager',
    MAIN_WORK_LOCATION: 'mainWorkLocation',
    OFFICE_ACCESS_CARD_ID: 'officeAccessCardId',
    SENIORITY_START_DATE: 'seniorityStartDate',
    ANNUAL_LEAVE_CALCULATION_START_DATE: 'annualLeaveCalculationStartDate',
    IS_INTERNATIONAL_BUSINESS_EMPLOYEE: 'isInternationalBusinessEmployee',
    BUSINESS_COUNTRY_CODE: 'businessCountryCodes',
    WORK_EMAIL: 'workEmail',
    COMPANY: 'company',
    MAIN_WORK_LOCATION_TYPE: 'mainWorkLocationType',
    WORK_END_DATE: 'workEndDate',
    SURVEY_INFO: 'surveyInfo',
    SHOULD_IMMEDIATELY_TERMINATE: 'shouldImmediatelyTerminate',
    PAYROLL_STATUS: 'payrollStatus',
    MATRIX_MANAGER: 'matrixManager',
    FULL_NAME: 'fullName',
    EMERGENCY_CONTACT_NAME: 'emergencyContact_name',
    EMERGENCY_CONTACT_GSM: 'emergencyContact_gsm',
    HAS_INVALID_EMAIL: 'onboardingInfo_hasInvalidEmail',
    RESIDENTIAL_ADDRESS_DISTRICT: 'residentialAddress_district',
    RESIDENTIAL_ADDRESS_COUNTRY: 'residentialAddress_country',
    RESIDENTIAL_ADDRESS_CITY: 'residentialAddress_city',
    WORK_GSM_DIAL: 'workGSM_dialCode',
    WORK_GSM_NUMBER: 'workGSM_number',
    PERSONAL_GSM_DIAL_CODE: 'personalGSM_dialCode',
    EMERGENCY_CONTACT_DIAL_CODE: 'emergencyContact_dialCode',
    EMERGENCY_CONTACT_RELATIONS_TYPE: 'emergencyContact_relationsType',
    ONBOARDING_IS_GWS_ACCOUNT_CREATED: 'onboardingInfo_isGWSAccountCreated',
    ONBOARDING_IS_GWS_PASSWORD_SENT: 'onboardingInfo_isGWSPasswordSent',
    ONBOARDING_IS_ADMIN_PANEL_USER_CREATED: 'onboardingInfo_isAdminPanelUserCreated',
    PIC_URL: 'picURL',
    SGK_CITY: 'sgkCity',
    BUSINESS_PARTNER: 'businessPartner',
  },
  [EMPLOYEE_CHANGE_LOG_CHANGE_MODELS.EDUCATION]: {
    EMPLOYEE: 'employee',
    LEVEL: 'level',
    STATUS: 'status',
    INSTITUTE: 'institute',
    GRADUATION_YEAR: 'graduationYear',
    ACADEMIC_PROGRAM: 'academicProgram',
    IS_DELETED: 'isDeleted',
  },
} as const;

export const ACCEPTABLE_WORK_EMAIL_DOMAINS: string[] = [
  'getir.com',
  'moovtr.com',
  'ekya.tech',
  'getirfinans.com',
  'bitaksi.com',
  'getirarac.com',
];
