import { createActions } from 'reduxsauce';

import { REDUX_KEY } from '@shared/shared/constants';

export const { Types, Creators } = createActions({
  getMarketProductsRequest: { limit: 10, offset: 0, queryText: null, filterOptions: {}, statusList: [], ids: [] },
  getMarketProductsSuccess: { data: [] },
  getMarketProductsFailure: { error: null },
  exportActiveMarketProductsRequest: { t: undefined },
  exportActiveMarketProductsSuccess: {},
  exportActiveMarketProductsFailure: { error: null },
  importMarketProductDomainLimitsRequest: { loadedFile: null },
  importMarketProductDomainLimitsSuccess: { data: [] },
  importMarketProductDomainLimitsFailure: { error: null },
  exportMarketProductDomainLimitsRequest: {},
  exportMarketProductDomainLimitsSuccess: { data: [] },
  exportMarketProductDomainLimitsFailure: { error: null },
  importMarketProductDetailsRequest: { loadedFile: null },
  importMarketProductDetailsSuccess: { data: [] },
  importMarketProductDetailsFailure: { error: null },
  exportMarketProductDetailsRequest: {},
  exportMarketProductDetailsSuccess: { data: [] },
  exportMarketProductDetailsFailure: { error: null },
  importMarketProductAdditionalTablesRequest: { loadedFile: null },
  importMarketProductAdditionalTablesSuccess: { data: [] },
  importMarketProductAdditionalTablesFailure: { error: null },
  exportMarketProductAdditionalTablesRequest: {},
  exportMarketProductAdditionalTablesSuccess: { data: [] },
  exportMarketProductAdditionalTablesFailure: { error: null },
  importMarketProductCategoryPositionsRequest: { loadedFile: null },
  importMarketProductCategoryPositionsSuccess: { data: [] },
  importMarketProductCategoryPositionsFailure: { error: null },
  exportMarketProductCategoryPositionsRequest: {},
  exportMarketProductCategoryPositionsSuccess: { data: [] },
  exportMarketProductCategoryPositionsFailure: { error: null },
  exportMarketProductSupplyAndLogisticRequest: {},
  exportMarketProductSupplyAndLogisticSuccess: { data: [] },
  exportMarketProductSupplyAndLogisticFailure: { error: null },
  exportMarketProductPricingMetadataRequest: {},
  exportMarketProductPricingMetadataSuccess: { data: [] },
  exportMarketProductPricingMetadataFailure: { error: null },
  importMarketProductSupplyAndLogisticRequest: { loadedFile: null },
  importMarketProductSupplyAndLogisticSuccess: { data: [] },
  importMarketProductSupplyAndLogisticFailure: { error: null },
  importMarketProductPricingMetadataRequest: { loadedFile: null },
  importMarketProductPricingMetadataSuccess: { data: [] },
  importMarketProductPricingMetadataFailure: { error: null },
  importMarketProductTogglesRequest: { loadedFile: null },
  importMarketProductTogglesSuccess: { data: [] },
  importMarketProductTogglesFailure: { error: null },
  initPage: null,
  destroyPage: null,
  setFilterOptions: { selectedOptions: [] },
  setStatusFilterOptions: { selectedStatusOptions: [] },
  setEnteredIds: { ids: [] },
}, { prefix: `${REDUX_KEY.MARKET_PRODUCT.LIST}_` });
