export const PAGE_TYPES = {
  ANNOUNCEMENT_NEW: 'ANNOUNCEMENT_NEW',
  ANNOUNCEMENT_DETAIL: 'ANNOUNCEMENT_DETAIL',
  BANNER_NEW: 'BANNER_NEW',
  BANNER_DETAIL: 'BANNER_DETAIL',
  NOTIFICATION_NEW: 'NOTIFICATION_NEW',
  NOTIFICATION_DETAIL: 'NOTIFICATION_DETAIL',
  POPUP_NEW: 'POPUP_NEW',
  POPUP_DETAIL: 'POPUP_DETAIL',
  PUSH_NOTIFICATION_NEW: 'PUSH_NOTIFICATION_NEW',
  PUSH_NOTIFICATION_DETAIL: 'PUSH_NOTIFICATION_DETAIL',
};
