export const mockedListingPromo = {
  _id: '659d494750d97ba2bbe9cbb1',
  domainTypes: [],
  promoCode: 'DONOTCHANGEPROMO',
  createdAt: '2024-01-09T13:25:27.171Z',
  isBannerEnabled: null,
  badgeId: null,
  promoTarget: 4,
  isParent: false,
  isP3Enabled: false,
  deviceTypes: [],
  openAggressionStates: [
    0,
  ],
  isAggressionStateNonAffected: true,
  priority: 100,
  clientSegments: [
    0,
  ],
  clientExSegments: [],
  doNotAllowMultiUsage: false,
  cities: [],
  warehouses: [],
  linkedPromos: [],
  isHealthCareProfessionalsPromo: false,
  dependentPromos: [],
  items: [],
  country: '55999ad00000010000000000',
  condition: {
    items: [],
    minItemCount: 0,
    minItemTotalAmount: 0,
  },
  exItems: [],
  excludedProductCategories: [],
  excludedProductSubCategories: [],
  validFrom: '2024-01-09T13:25:27.171Z',
  status: 1,
  promoType: 1,
  promoMechanic: 4,
  autoAggressionLevels: [],
  availableTimes: [],
  promoURL: null,
  promoContentURL: null,
  promoBodyContentURL: null,
  promoContentHTML: null,
  validUntil: '2024-01-09T13:25:27.171Z',
  title: null,
  description: null,
  accessibilityLabel: null,
  promoContentSectionTitle: null,
  promoGroup: null,
  promoClassification: {
    promoClass: 0,
    responsibleDepartment: null,
    objective: 0,
    occasion: 0,
    daypart: 0,
    weekpart: 0,
    funnelSegment: 0,
    benefitGroup: 0,
    productTLGroup: 0,
    location: 0,
  },
  button: {
    text: null,
    action: {
      type: 1,
      data: {},
      isConfirmationPopupEnabled: null,
      confirmationPopup: {
        positiveButton: { text: null },
        negativeButton: { text: null },
        message: null,
      },
    },
  },
  banner: {
    isServiceBusinessDetailPageBanner: false,
    isServiceCategoryDetailPageBanner: false,
    serviceCategoryVerticalPages: [],
    serviceBusinessMerchantShops: [],
    action: {
      type: 1,
      data: {},
      ownerService: null,
      service: null,
      isConfirmationPopupEnabled: null,
      confirmationPopup: {
        positiveButton: { text: null },
        negativeButton: { text: null },
        message: null,
      },
    },
    button: {
      text: null,
      action: {
        type: 1,
        data: {},
        isConfirmationPopupEnabled: null,
        confirmationPopup: {
          positiveButton: { text: null },
          negativeButton: { text: null },
          message: null,
        },
      },
    },
    priority: null,
    isLandingPageBanner: false,
    isServiceHomePageBanner: false,
    title: {
      tr: '',
      en: '',
    },
    description: {
      tr: '',
      en: '',
    },
    picUrl: {
      tr: '',
      en: '',
    },
    picBackgroundUrl: {
      tr: '',
      en: '',
    },
    picForegroundUrl: {
      tr: '',
      en: '',
    },
  },
  picURL: null,
  popup: { imageUrl: null },
  notification: null,
  thumbnailURL: null,
  useLimit: 1,
  useLimitPerDay: 0,
  minSucOrderCount: 0,
  maxSucOrderCount: -1,
  minSucFoodOrderCount: 0,
  maxSucFoodOrderCount: -1,
  minSucMarketOrderCount: 0,
  maxSucMarketOrderCount: -1,
  minSucWaterOrderCount: 0,
  maxSucWaterOrderCount: -1,
  minSucKuzeydenOrderCount: 0,
  maxSucKuzeydenOrderCount: -1,
  reqDaysAfterLastOrder: 0,
  reqDaysAfterLastFoodOrder: 0,
  orderLimitCount: 0,
  isOnlyPremiumDeviceModels: false,
  isOnlyNotPremiumDeviceModels: false,
  isLocalCountryPhoneCodeRequired: false,
  isPublic: false,
  usedOrderCount: 0,
  usedTotalPrice: 0,
  usedTotalWholesalePrice: 0,
  usedTotalVatValue: 0,
  usedTotalDiscountAmount: 0,
  benefitType: null,
  discountAmount: 0,
  maxItemCount: 0,
  changePrice: null,
  deliveryFee: {
    amount: null,
    doNotCharge: false,
  },
  foodBasketValueBehaviorType: null,
  maxOrderTotalPrice: 0,
  minOrderTotalPrice: 0,
  paymentMethods: [],
  doNotApplyMinimumBasketSize: false,
  cardBins: [],
  supplier: null,
  supplierSupportRate: 0,
  thirdPartySupportRate: 0,
  isFreeProduct: false,
};

export const mockSingleBuyXAndGetYFreePromo = {
  promo: {
    _id: '673dbd82449767cd36cfaf53',
    domainTypes: [],
    promoCode: 'SINGLE_BUY_X_AND_GET_Y_FOR_FREE',
    createdAt: '2024-11-20T10:44:18.715Z',
    isBannerEnabled: null,
    badgeId: null,
    promoTarget: 4,
    isParent: false,
    isP3Enabled: false,
    isCommsEnabled: false,
    deviceTypes: [],
    openAggressionStates: [
      0,
    ],
    isAggressionStateNonAffected: true,
    priority: 100,
    clientSegments: [
      0,
    ],
    clientExSegments: [],
    doNotAllowMultiUsage: false,
    cities: [],
    warehouses: [],
    linkedPromos: [],
    isHealthCareProfessionalsPromo: false,
    dependentPromos: [],
    items: [],
    country: '55999ad00000010000000000',
    condition: {
      items: [],
      minItemCount: 0,
      minItemTotalAmount: 0,
    },
    exItems: [],
    excludedProductCategories: [],
    excludedProductSubCategories: [],
    validFrom: '2024-11-20T10:44:18.715Z',
    status: 1,
    promoType: 1,
    promoMechanic: 4,
    autoAggressionLevels: [],
    availableTimes: [],
    promoURL: null,
    promoContentURL: null,
    promoBodyContentURL: null,
    promoContentHTML: null,
    validUntil: '2024-11-20T10:44:18.715Z',
    title: null,
    description: null,
    accessibilityLabel: null,
    promoContentSectionTitle: null,
    promoClassification: {
      promoClass: 0,
      responsibleDepartment: null,
      objective: 0,
      occasion: 0,
      daypart: 0,
      weekpart: 0,
      funnelSegment: 0,
      benefitGroup: 0,
      productTLGroup: 0,
      location: 0,
    },
    button: {
      text: null,
      action: {
        type: 1,
        data: {},
        isConfirmationPopupEnabled: null,
        confirmationPopup: {
          positiveButton: { text: null },
          negativeButton: { text: null },
          message: null,
        },
      },
    },
    banner: {
      isServiceBusinessDetailPageBanner: false,
      isServiceCategoryDetailPageBanner: false,
      serviceCategoryVerticalPages: [],
      serviceBusinessMerchantShops: [],
      action: {
        type: 1,
        data: {},
        ownerService: null,
        service: null,
        isConfirmationPopupEnabled: null,
        confirmationPopup: {
          positiveButton: { text: null },
          negativeButton: { text: null },
          message: null,
        },
      },
      button: {
        text: null,
        action: {
          type: 1,
          data: {},
          isConfirmationPopupEnabled: null,
          confirmationPopup: {
            positiveButton: { text: null },
            negativeButton: { text: null },
            message: null,
          },
        },
      },
      priority: null,
      isLandingPageBanner: false,
      isServiceHomePageBanner: false,
      title: {
        tr: '',
        en: '',
      },
      description: {
        tr: '',
        en: '',
      },
      picUrl: {
        tr: '',
        en: '',
      },
      picBackgroundUrl: {
        tr: '',
        en: '',
      },
      picForegroundUrl: {
        tr: '',
        en: '',
      },
    },
    picURL: null,
    popup: { imageUrl: null },
    notification: null,
    thumbnailURL: null,
    useLimit: 1,
    useLimitPerDay: 0,
    minSucOrderCount: 0,
    maxSucOrderCount: -1,
    minSucFoodOrderCount: 0,
    maxSucFoodOrderCount: -1,
    minSucMarketOrderCount: 0,
    maxSucMarketOrderCount: -1,
    minSucWaterOrderCount: 0,
    maxSucWaterOrderCount: -1,
    minSucKuzeydenOrderCount: 0,
    maxSucKuzeydenOrderCount: -1,
    minSucGorillasOrderCount: 0,
    maxSucGorillasOrderCount: -1,
    reqDaysAfterLastOrder: 0,
    reqDaysAfterLastFoodOrder: 0,
    orderLimitCount: 0,
    isOnlyPremiumDeviceModels: false,
    isOnlyNotPremiumDeviceModels: false,
    isLocalCountryPhoneCodeRequired: false,
    isPublic: false,
    usedOrderCount: 0,
    usedTotalPrice: 0,
    usedTotalWholesalePrice: 0,
    usedTotalVatValue: 0,
    usedTotalDiscountAmount: 0,
    benefitType: null,
    discountAmount: 0,
    maxItemCount: 0,
    changePrice: null,
    deliveryFee: {
      amount: null,
      doNotCharge: false,
    },
    foodBasketValueBehaviorType: null,
    maxOrderTotalPrice: 0,
    minOrderTotalPrice: 0,
    paymentMethods: [],
    doNotApplyMinimumBasketSize: false,
    cardBins: [],
    supplier: null,
    supplierSupportRate: 0,
    thirdPartySupportRate: 0,
    isFreeProduct: false,
  },
};

export const mockMasterBuyXAndGetYFreePromo = {
  promo: {
    _id: '673dc5c9449767cd36cfb020',
    domainTypes: [],
    promoCode: 'MASTER_MASTER_BUY_X_AND_GET_Y_FOR_FREE',
    createdAt: '2024-11-20T11:19:37.862Z',
    isBannerEnabled: null,
    badgeId: null,
    promoTarget: 4,
    isParent: true,
    isP3Enabled: false,
    isCommsEnabled: false,
    deviceTypes: [],
    openAggressionStates: [
      0,
    ],
    isAggressionStateNonAffected: true,
    priority: 100,
    clientSegments: [
      0,
    ],
    clientExSegments: [],
    doNotAllowMultiUsage: false,
    cities: [],
    warehouses: [],
    linkedPromos: [],
    isHealthCareProfessionalsPromo: false,
    dependentPromos: [],
    items: [],
    country: '55999ad00000010000000000',
    condition: {
      items: [],
      minItemCount: 0,
      minItemTotalAmount: 0,
    },
    exItems: [],
    excludedProductCategories: [],
    excludedProductSubCategories: [],
    validFrom: '2024-11-20T11:19:37.862Z',
    status: 1,
    promoType: 1,
    promoMechanic: 4,
    autoAggressionLevels: [],
    availableTimes: [],
    promoURL: null,
    promoContentURL: null,
    promoBodyContentURL: null,
    promoContentHTML: null,
    validUntil: '2024-11-20T11:19:37.862Z',
    title: null,
    description: null,
    accessibilityLabel: null,
    promoContentSectionTitle: null,
    promoClassification: {
      promoClass: 0,
      responsibleDepartment: null,
      objective: 0,
      occasion: 0,
      daypart: 0,
      weekpart: 0,
      funnelSegment: 0,
      benefitGroup: 0,
      productTLGroup: 0,
      location: 0,
    },
    button: {
      text: null,
      action: {
        type: 1,
        data: {},
        isConfirmationPopupEnabled: null,
        confirmationPopup: {
          positiveButton: { text: null },
          negativeButton: { text: null },
          message: null,
        },
      },
    },
    banner: {
      isServiceBusinessDetailPageBanner: false,
      isServiceCategoryDetailPageBanner: false,
      serviceCategoryVerticalPages: [],
      serviceBusinessMerchantShops: [],
      action: {
        type: 1,
        data: {},
        ownerService: null,
        service: null,
        isConfirmationPopupEnabled: null,
        confirmationPopup: {
          positiveButton: { text: null },
          negativeButton: { text: null },
          message: null,
        },
      },
      button: {
        text: null,
        action: {
          type: 1,
          data: {},
          isConfirmationPopupEnabled: null,
          confirmationPopup: {
            positiveButton: { text: null },
            negativeButton: { text: null },
            message: null,
          },
        },
      },
      priority: null,
      isLandingPageBanner: false,
      isServiceHomePageBanner: false,
      title: {
        tr: '',
        en: '',
      },
      description: {
        tr: '',
        en: '',
      },
      picUrl: {
        tr: '',
        en: '',
      },
      picBackgroundUrl: {
        tr: '',
        en: '',
      },
      picForegroundUrl: {
        tr: '',
        en: '',
      },
    },
    picURL: null,
    popup: { imageUrl: null },
    notification: null,
    thumbnailURL: null,
    useLimit: 1,
    useLimitPerDay: 0,
    minSucOrderCount: 0,
    maxSucOrderCount: -1,
    minSucFoodOrderCount: 0,
    maxSucFoodOrderCount: -1,
    minSucMarketOrderCount: 0,
    maxSucMarketOrderCount: -1,
    minSucWaterOrderCount: 0,
    maxSucWaterOrderCount: -1,
    minSucKuzeydenOrderCount: 0,
    maxSucKuzeydenOrderCount: -1,
    minSucGorillasOrderCount: 0,
    maxSucGorillasOrderCount: -1,
    reqDaysAfterLastOrder: 0,
    reqDaysAfterLastFoodOrder: 0,
    orderLimitCount: 0,
    isOnlyPremiumDeviceModels: false,
    isOnlyNotPremiumDeviceModels: false,
    isLocalCountryPhoneCodeRequired: false,
    isPublic: false,
    usedOrderCount: 0,
    usedTotalPrice: 0,
    usedTotalWholesalePrice: 0,
    usedTotalVatValue: 0,
    usedTotalDiscountAmount: 0,
    benefitType: null,
    discountAmount: 0,
    maxItemCount: 0,
    changePrice: null,
    deliveryFee: {
      amount: null,
      doNotCharge: false,
    },
    foodBasketValueBehaviorType: null,
    maxOrderTotalPrice: 0,
    minOrderTotalPrice: 0,
    paymentMethods: [],
    doNotApplyMinimumBasketSize: false,
    cardBins: [],
    supplier: null,
    supplierSupportRate: 0,
    thirdPartySupportRate: 0,
    isFreeProduct: false,
  },
};

export const mockSingleStarDealsPromo = {
  promo: {
    _id: '673ddbc3385e87473e4d420d',
    domainTypes: [],
    promoCode: 'SINGLE_STAR_DEALS',
    createdAt: '2024-11-20T12:53:23.603Z',
    isBannerEnabled: null,
    badgeId: null,
    promoTarget: 4,
    isParent: false,
    isP3Enabled: false,
    isCommsEnabled: false,
    deviceTypes: [],
    openAggressionStates: [
      0,
    ],
    isAggressionStateNonAffected: true,
    priority: 100,
    clientSegments: [
      0,
    ],
    clientExSegments: [],
    doNotAllowMultiUsage: false,
    cities: [],
    warehouses: [],
    linkedPromos: [],
    isHealthCareProfessionalsPromo: false,
    dependentPromos: [],
    items: [],
    country: '55999ad00000010000000000',
    condition: {
      items: [],
      minItemCount: 0,
      minItemTotalAmount: 0,
    },
    exItems: [],
    excludedProductCategories: [],
    excludedProductSubCategories: [],
    validFrom: '2024-11-20T12:53:23.603Z',
    status: 1,
    promoType: 3,
    promoMechanic: 8,
    autoAggressionLevels: [],
    availableTimes: [],
    promoURL: null,
    promoContentURL: null,
    promoBodyContentURL: null,
    promoContentHTML: null,
    validUntil: '2024-11-20T12:53:23.603Z',
    title: null,
    description: null,
    accessibilityLabel: null,
    promoContentSectionTitle: null,
    promoClassification: {
      promoClass: 0,
      responsibleDepartment: null,
      objective: 0,
      occasion: 0,
      daypart: 0,
      weekpart: 0,
      funnelSegment: 0,
      benefitGroup: 0,
      productTLGroup: 0,
      location: 0,
    },
    button: {
      text: null,
      action: {
        type: 1,
        data: {},
        isConfirmationPopupEnabled: null,
        confirmationPopup: {
          positiveButton: { text: null },
          negativeButton: { text: null },
          message: null,
        },
      },
    },
    banner: {
      isServiceBusinessDetailPageBanner: false,
      isServiceCategoryDetailPageBanner: false,
      serviceCategoryVerticalPages: [],
      serviceBusinessMerchantShops: [],
      action: {
        type: 1,
        data: {},
        ownerService: null,
        service: null,
        isConfirmationPopupEnabled: null,
        confirmationPopup: {
          positiveButton: { text: null },
          negativeButton: { text: null },
          message: null,
        },
      },
      button: {
        text: null,
        action: {
          type: 1,
          data: {},
          isConfirmationPopupEnabled: null,
          confirmationPopup: {
            positiveButton: { text: null },
            negativeButton: { text: null },
            message: null,
          },
        },
      },
      priority: null,
      isLandingPageBanner: false,
      isServiceHomePageBanner: false,
      title: {
        tr: '',
        en: '',
      },
      description: {
        tr: '',
        en: '',
      },
      picUrl: {
        tr: '',
        en: '',
      },
      picBackgroundUrl: {
        tr: '',
        en: '',
      },
      picForegroundUrl: {
        tr: '',
        en: '',
      },
    },
    picURL: null,
    popup: { imageUrl: null },
    notification: null,
    thumbnailURL: null,
    useLimit: 1,
    useLimitPerDay: 0,
    minSucOrderCount: 0,
    maxSucOrderCount: -1,
    minSucFoodOrderCount: 0,
    maxSucFoodOrderCount: -1,
    minSucMarketOrderCount: 0,
    maxSucMarketOrderCount: -1,
    minSucWaterOrderCount: 0,
    maxSucWaterOrderCount: -1,
    minSucKuzeydenOrderCount: 0,
    maxSucKuzeydenOrderCount: -1,
    minSucGorillasOrderCount: 0,
    maxSucGorillasOrderCount: -1,
    reqDaysAfterLastOrder: 0,
    reqDaysAfterLastFoodOrder: 0,
    orderLimitCount: 0,
    isOnlyPremiumDeviceModels: false,
    isOnlyNotPremiumDeviceModels: false,
    isLocalCountryPhoneCodeRequired: false,
    isPublic: false,
    usedOrderCount: 0,
    usedTotalPrice: 0,
    usedTotalWholesalePrice: 0,
    usedTotalVatValue: 0,
    usedTotalDiscountAmount: 0,
    benefitType: null,
    discountAmount: 0,
    maxItemCount: 1,
    changePrice: null,
    deliveryFee: {
      amount: null,
      doNotCharge: false,
    },
    foodBasketValueBehaviorType: null,
    maxOrderTotalPrice: 0,
    minOrderTotalPrice: 0,
    paymentMethods: [],
    doNotApplyMinimumBasketSize: false,
    cardBins: [],
    supplier: null,
    supplierSupportRate: 0,
    thirdPartySupportRate: 0,
    isFreeProduct: false,
  },
};
