export const IT_SUPPORT_REQUEST_URL = 'https://getirdev.atlassian.net/servicedesk/customer/portal/3/group/50';

export const EMPLOYE_BASICS_DEFAULTS = {
  NOT_APPLICABLE: 'N/A',
  FALSE: false,
};

export const EMPLOYEE_BASIC_DATA_FIELDS = {
  DEPARTMENT: 'departmentName',
  FULLNAME: 'fullName',
  LOCATION: 'locationName',
  BUSINESS_TITLE: 'businessTitle',
  JOB_FAMILY: 'jobFamilyName',
  BUSINESS_UNIT: 'businessUnit',
  PERSONAL_EMAIL: 'personalEmail',
  PAYROLL_COUNTRY: 'payrollCountryCode',
  SUPERVISOR: 'supervisor',
  WORK_START_DATE: 'workStartDate',
  WORKDAY_ID: 'workdayId',
  WORK_EMAIL: 'workEmail',
  COUNTRIES: 'countries',
};

export const PROFILE_TAB_PANES = {
  MY_PROFILE: 0,
  SHORTCUTS: 1,
  PERMISSION_REQUESTS: 2,
};

export const PROFILE_TAB_PANE_KEYS = {
  MY_PROFILE: 'myProfile',
  SHORTCUTS: 'shortcuts',
  PERMISSION_REQUESTS: 'permissionRequests',
};

export const GLOBALLY_PERMITTED_TRANSLATION_KEYS = {
  GLOBALLY_PERMITTED: 'globallyPermitted',
  GLOBALLY_NOT_PERMITTED: 'globallyNotPermitted',
};

export const PROFILE_PAGE_COMPONENTS_TRANSLATION_PREFIXES = {
  ACCOUNT_INFO: 'COMPONENTS.ACCOUNT_INFO',
  EMPLOYEE_INFO: 'COMPONENTS.EMPLOYEE_INFO',
  ACTIVE_SESSIONS: 'COMPONENTS.ACTIVE_SESSIONS',
};

export const EMPLOYEE_BASIC_FIELDS_TRANSLATION_KEYS = {
  [EMPLOYEE_BASIC_DATA_FIELDS.WORK_EMAIL]: 'EMAIL_ADDRESS',
  [EMPLOYEE_BASIC_DATA_FIELDS.COUNTRIES]: 'COUNTRIES',
  [EMPLOYEE_BASIC_DATA_FIELDS.BUSINESS_TITLE]: 'BUSINESS_TITLE',
  [EMPLOYEE_BASIC_DATA_FIELDS.DEPARTMENT]: 'DEPARTMENT',
  [EMPLOYEE_BASIC_DATA_FIELDS.LOCATION]: 'LOCATION',
  [EMPLOYEE_BASIC_DATA_FIELDS.JOB_FAMILY]: 'JOB_FAMILY',
  [EMPLOYEE_BASIC_DATA_FIELDS.BUSINESS_UNIT]: 'BUSINESS_UNIT',
  [EMPLOYEE_BASIC_DATA_FIELDS.PERSONAL_EMAIL]: 'PERSONAL_EMAIL',
  [EMPLOYEE_BASIC_DATA_FIELDS.PAYROLL_COUNTRY]: 'PAYROLL_COUNTRY',
  [EMPLOYEE_BASIC_DATA_FIELDS.SUPERVISOR]: 'SUPERVISOR',
  [EMPLOYEE_BASIC_DATA_FIELDS.WORK_START_DATE]: 'WORK_START_DATE',
  [EMPLOYEE_BASIC_DATA_FIELDS.WORKDAY_ID]: 'WORKDAY_ID',
};

export const EMPLOYEE_BASIC_DATA_FIELD_PATH_MAP = {
  [EMPLOYEE_BASIC_DATA_FIELDS.WORK_EMAIL]: 'accountInfo.workEmail',
  [EMPLOYEE_BASIC_DATA_FIELDS.BUSINESS_TITLE]: 'employeeInfo.businessTitle',
  [EMPLOYEE_BASIC_DATA_FIELDS.DEPARTMENT]: 'employeeInfo.departmentName',
  [EMPLOYEE_BASIC_DATA_FIELDS.LOCATION]: 'employeeInfo.locationName',
  [EMPLOYEE_BASIC_DATA_FIELDS.JOB_FAMILY]: 'employeeInfo.jobFamilyName',
  [EMPLOYEE_BASIC_DATA_FIELDS.BUSINESS_UNIT]: 'employeeInfo.businessUnit',
  [EMPLOYEE_BASIC_DATA_FIELDS.PERSONAL_EMAIL]: 'employeeInfo.personalEmail',
  [EMPLOYEE_BASIC_DATA_FIELDS.PAYROLL_COUNTRY]: 'employeeInfo.payrollCountryCode',
  [EMPLOYEE_BASIC_DATA_FIELDS.SUPERVISOR]: 'employeeInfo.supervisor',
  [EMPLOYEE_BASIC_DATA_FIELDS.WORK_START_DATE]: 'employeeInfo.workStartDate',
  [EMPLOYEE_BASIC_DATA_FIELDS.WORKDAY_ID]: 'employeeInfo.workdayId',
  [EMPLOYEE_BASIC_DATA_FIELDS.FULLNAME]: 'person.fullName',
};

export const EMPLOYEE_EXTERNAL_BASIC_DATA_FIELD_PATH_MAP = { [EMPLOYEE_BASIC_DATA_FIELDS.COUNTRIES]: 'accountInfo.countries' };

export const EDUCATION_STATUSES = {
  ONGOING: 100,
  GRADUATED: 200,
};

export const EDUCATION_LEVELS = {
  HIGH_SCHOOL: 200,
  ASSOCIATE_DEGREE: 300,
  BACHELORS_DEGREE: 400,
  MASTERS_DEGREE: 500,
  DOCTORATE: 600,
};
