import { createUseStyles } from 'react-jss';

export default createUseStyles(() => ({
  timeline: { fontSize: '14px' },
  tlHeader: {
    display: 'block',
    marginBottom: '15px',
    width: '12em',
    textAlign: 'center',
  },
  etaInfo: {
    display: 'flex',
    marginBottom: '15px',
    width: '100%',
    height: '40px',
    alignItems: 'center',
    gap: '1',
    textAlign: 'center',
    backgroundColor: '#fff',
    paddingBlock: '10px',
    paddingInline: '5px',
    borderRadius: '5px',
  },
  tlWrapBprimary: {
    display: 'block',
    padding: '15px 0 15px 20px',
    marginLeft: '6em',
    borderColor: '#5D3EBD',
    borderStyle: 'solid',
    borderWidth: '0 0 0 4px',
    '&:before': {
      content: ' ',
      position: 'absolute',
      bottom: 0,
      left: 50,
      width: '100%',
      height: '1rem',
      display: 'block',
      background: '#ffffff',
    },
  },
  tlDate: {
    position: 'relative',
    top: '10px',
    display: 'block',
    float: 'left',
    width: '4.5em',
    marginLeft: '-8.5em',
    textAlign: 'right',
    color: '#58666e',
  },
  tlContent: {
    paddingBlock: '10px',
    paddingInline: '5px',
  },
  tlContentBasket: {
    paddingRight: '10px',
    paddingLeft: '10px',
    position: 'relative',
    display: 'inline-block',
    paddingTop: '5px',
    paddingBottom: '5px',
    backgroundColor: '#ffffff',
  },
  initialTotalAmount: { color: '#B5B5B5' },
  textPrimary: {
    color: '#5D3EBC',
    fontWeight: '700',
    marginLeft: '3px',
    marginRight: '3px',
  },
  panelFooter: {
    backgroundColor: '#ffffff',
    borderRadius: '0 0 2px 2px',
    textAlign: 'left',
    padding: '10px 20px',
    borderTop: '1px solid #edf1f2',
    '& > p, & > h6': { margin: 0 },
  },
  textAlignLeft: { textAlign: 'left' },
  textAlignRight: { textAlign: 'right' },
  ltItem: {
    display: 'block',
    '&:before': {
      display: 'table',
      content: ' ',
    },
  },
  ltWrap: {
    display: 'block',
    padding: '15px 0 15px 20px',
    marginLeft: '6em',
    borderColor: '#5D3EBD',
    borderStyle: 'solid',
    borderWidth: '0 0 0 4px',
  },
  orderButton: {
    backgroundColor: '#5D3EBD',
    fontSize: '12px',
    color: '#FFD10D',
    fontWeight: '700',
  },
  panelBody: {
    marginRight: '-15px',
    marginLeft: '-15px',
  },
  timelineIcon: {
    position: 'absolute',
    left: '-29px',
    background: '#ffffff',
    borderRadius: '100%',
    top: '50%',
  },
  cancelTitleText: { color: '#ff4338' },

}));
