import { GETIR_DOMAIN_TYPES } from '@shared/shared/constants';
import permKey from '@shared/shared/permKey.json';

export const DEFAULT_REFRESH_PAGE_TIMER = 30000;
export const TIMER_OPTIONS = [30000, 60000, 120000, 300000];
export const domainTypeByKeys = {
  [GETIR_DOMAIN_TYPES.GETIR10]: permKey.PAGE_LIVE_MONITORING_COMPONENT_VIEW_PERMISSION_G10,
  [GETIR_DOMAIN_TYPES.FOOD]: permKey.PAGE_LIVE_MONITORING_COMPONENT_VIEW_PERMISSION_GETIR_FOOD,
  [GETIR_DOMAIN_TYPES.MARKET]: permKey.PAGE_LIVE_MONITORING_COMPONENT_VIEW_PERMISSION_GETIR_MORE,
  [GETIR_DOMAIN_TYPES.VOYAGER]: permKey.PAGE_LIVE_MONITORING_COMPONENT_VIEW_PERMISSION_GETIR_VOYAGER,
  [GETIR_DOMAIN_TYPES.LOCALS]: permKey.PAGE_LIVE_MONITORING_COMPONENT_VIEW_PERMISSION_GETIR_LOCALS,
};

export const DURATIONS = [
  '0-29',
  '30-59',
  '60-89',
  '90-119',
  '+90',
  '-90',
];

export const NOT_APPLICABLE_VALUE = 'N/A';

export const GETIR_WATER_AVERAGE_TP = 4.8;
