import { createUseStyles } from 'react-jss';

export default createUseStyles(
  {
    comboboxTreeContainer: { position: 'relative' },
    comboboxTreeWrapper: {
      width: '100%',
      border: '1px solid rgb(217, 217, 217)',
      borderRadius: '2px',
      padding: '2px 20px 2px 2px',
      cursor: 'text',
      minHeight: '32px',
      display: 'flex',
      alignItems: 'center',
      transition: 'border-color 0.3s ease-in-out 0s, box-shadow 0.3s ease-in-out 0s',
    },
    'comboboxTreeContainer:not(.comboboxTreeIsDisabled) $comboboxTreeWrapper:hover': { borderColor: '#8063c9' },
    comboboxTreeIsDisabled: {
      '& $comboboxTreeWrapper, & $comboboxTreeInput': {
        background: '#f5f5f5',
        cursor: 'not-allowed',
      },
    },
    comboboxTreeIsActive: {
      '& $comboboxTreeWrapper': {
        borderColor: '#8063c9',
        boxShadow: 'rgb(188 99 201 / 20%) 0px 0px 0px 2px',
        transition: 'box-shadow 0.3s ease-in-out 0.2s, border-color 0.3s ease-in-out 0s',
      },
    },
    comboboxTreeInputContainer: {
      display: 'flex',
      alignItems: 'center',
      flexWrap: 'wrap',
      width: '100%',
    },
    comboboxTreeInput: {
      display: 'inline-block',
      padding: '0 5px',
      margin: '0',
      background: 'transparent',
      border: 'none',
      outline: 'none',
      appearance: 'none',
      minWidth: '200px',
      height: '20px',
      maxWidth: '100%',
      '&::placeholder': { opacity: 1, color: '#bfbfbf' },
    },
    comboboxTreeInputWidth: {
      position: 'absolute',
      opacity: 0,
    },
    comboboxTreeTag: {
      position: 'relative',
      display: 'inline-flex',
      width: 'auto',
      alignItems: 'center',
      background: '#f5f5f5',
      border: '1px solid #f0f0f0',
      borderRadius: '2px',
      height: '19px',
      fontSize: '12px',
      lineHeight: '19px',
      margin: '3px',
      padding: '0 6px',
      cursor: 'default',
      userSelect: 'none',
    },
    comboboxTreeTagTitle: {
      color: 'rgb(88, 102, 110)',
      cursor: 'default',
    },
    comboboxTreeTagRemoveButon: {
      appearance: 'none',
      background: 'transparent',
      display: 'flex',
      alignItems: 'center',
      padding: '0',
      border: 'none',
      marginLeft: '3px',
      ' & svg': {
        width: '10px',
        height: '10px',
        color: 'rgba(0, 0, 0, 0.45)',
      },
      '&:hover svg': { color: 'rgba(0, 0, 0, 1)' },
    },
    comboboxTreeDropdown: {
      position: 'absolute',
      zIndex: '100',
      background: '#fff',
      width: '100%',
      maxHeight: '20rem',
      overflowY: 'auto',
      boxShadow: '0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 9px 28px 8px rgba(0, 0, 0, 0.05)',
      padding: '5px 0',
      transition: 'all 0.2s, opacity 0.15s',
      opacity: '0',
      pointerEvents: 'none',
      transform: 'scaleY(0.9)',
      transformOrigin: 'top',
    },
    comboboxTreeDropdownIsOpen: {
      opacity: '1',
      pointerEvents: 'auto',
      transform: 'scale(1) translateY(2px)',
    },
    comboboxTreeDropdownOption: {
      position: 'relative',
      padding: '1px 5px 1px 2px',
      margin: '2px 0',
      display: 'flex',
      width: '100%',
    },
    comboboxTreeDropdownOptionCheckbox: {
      position: 'absolute',
      opacity: '0',
      cursor: 'pointer',
      height: '0',
      width: '0',
    },
    comboboxTreeDropdownOptionCheckmark: {
      position: 'absolute',
      top: '50%',
      transform: 'translateY(-50%)',
      left: '0',
      height: '16px',
      width: '16px',
      borderRadius: '2px',
      backgroundColor: '#fff',
      border: '1px solid #d9d9d9',
      transition: 'all 0.3s',
      '&:after': {
        content: '""',
        position: 'absolute',
        display: 'none',
      },
    },
    comboboxTreeDropdownOptionCheckmarkInderminate: { backgroundColor: '#fff' },
    comboboxTreeDropdownOptionHandler: {
      position: 'relative',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '24px',
      height: '20px',
      marginTop: '1px',
      zIndex: '10',
    },
    comboboxTreeDropdownOptionTitle: {
      display: 'block',
      padding: '2px 4px',
      background: 'transparent',
      borderRadius: '2px',
      cursor: 'pointer',
      width: '100%',
    },
    comboboxTreeDropdownOptionLabel: {
      display: 'flex',
      width: '100%',
      position: 'relative',
      paddingLeft: '20px',
      marginBottom: '0',
      cursor: 'pointer',
      userSelect: 'none',
      '&:hover $comboboxTreeDropdownOptionCheckbox ~ $comboboxTreeDropdownOptionCheckmark': { borderColor: '#5D3EBC' },
      '& $comboboxTreeDropdownOptionCheckbox:checked ~ $comboboxTreeDropdownOptionCheckmark': {
        backgroundColor: '#5D3EBC',
        borderColor: '#5D3EBC',
      },
      '& $comboboxTreeDropdownOptionCheckbox:checked ~ $comboboxTreeDropdownOptionCheckmark:after': { display: 'block' },
      '& $comboboxTreeDropdownOptionCheckmark:after': {
        top: '1px',
        left: '4px',
        width: '6px',
        height: '10px',
        border: 'solid #fff',
        borderWidth: '0 2px 2px 0',
        transform: 'rotate(45deg)',
      },
      '&:hover $comboboxTreeDropdownOptionTitle': { background: '#f5f5f5' },
      '& $comboboxTreeDropdownOptionCheckbox ~ $comboboxTreeDropdownOptionCheckmarkInderminate': {
        '&:after': {
          top: '3px',
          left: '3px',
          width: '8px',
          border: '1px solid #5D3EBC',
          background: '#5D3EBC',
          height: '8px',
          borderRadius: '0',
          display: 'block',
          transform: 'rotate(0deg)',
        },
      },
    },

    comboboxTreeDropdownOptionHandlerButton: {
      appearance: 'none',
      background: 'transparent',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '0',
      width: 'inherit',
      height: 'inherit',
      border: 'none',
      ' & svg': {
        width: '10px',
        height: '10px',
        color: 'rgb(88, 102, 110)',
      },
    },
    comboboxTreeDropdownOptionChildren: { paddingLeft: '24px' },
    comboboxTreeActionWrapper: {
      position: 'absolute',
      right: '0',
      top: '50%',
      height: '100%',
      transform: 'translateY(-50%)',
    },
    comboboxTreeActionButton: {
      position: 'absolute',
      right: '10px',
      appearance: 'none',
      background: 'transparent',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '0',
      width: 'inherit',
      height: 'inherit',
      border: 'none',
      pointerEvents: 'none',
      opacity: '0',
      ' & svg': {
        width: '12px',
        height: '12px',
        color: 'rgba(0, 0, 0, 0.65)',
        transition: 'all 0.3s',
      },
    },
    comboboxTreeActionButtonDown: { opacity: 1 },
    comboboxTreeActionButtonSearch: { opacity: 0 },
    comboboxTreeActionButtonLoading: {
      opacity: 0,
      '& svg': { color: 'rgba(0, 0, 0, 0.45)' },
    },
    comboboxTreeActionButtonClear: {
      opacity: 0,
      '& svg': { color: '#5D3EBC' },
    },
    comboboxTreeIsSearching: {
      '& $comboboxTreeActionButtonDown': { opacity: 0 },
      '& $comboboxTreeActionButtonSearch': { opacity: 1 },
      '&:hover $comboboxTreeActionButtonSearch': { opacity: 0 },
      '&:hover $comboboxTreeActionButtonClear': {
        opacity: 1,
        visibility: 'visible',
        pointerEvents: 'all',
      },
    },
    comboboxTreeHasTags: {
      '&:hover': {
        '& $comboboxTreeActionButtonClear': {
          opacity: '1',
          visibility: 'visible',
          pointerEvents: 'all',
        },
        '& $comboboxTreeActionButtonDown': { opacity: '0' },
      },
    },
    comboboxTreeIsLoading: {
      '& $comboboxTreeActionButtonDown': { opacity: 0 },
      '& $comboboxTreeActionButtonSearch': { opacity: 0 },
      '& $comboboxTreeActionButtonClear': { opacity: 0 },
      '& $comboboxTreeActionButtonLoading': { opacity: 1 },
    },
    comboboxTreeDropdownActions: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'flex-end',
      padding: '0 5px 5px',
      marginBottom: '5px',
      borderBottom: '1px solid #d9d9d9',
    },
  },
);
