import { createUseStyles } from 'react-jss';

export default createUseStyles({
  'ant-table-title': { padding: '0 !important' },
  selectTitle: {
    marginBottom: '5px important',
    width: '120px',
    fontSize: '12px',
    fontWeight: 600,
  },
  selectTitleIcon: {
    width: '15px',
    height: '15px',
    marginBottom: '5px',
  },
  filterItem: { width: '200px', marginBottom: '20px' },
  filterContainer: {
    display: 'flex',
    justifyContent: 'center',
  },
  tableTitle: { display: 'flex', justifyContent: 'space-between' },
  tableTitleLabel: { marginRight: '90px', height: '36px' },
  selectItem: { width: '100%', fontSize: '8px' },
  selectItemPacket: { width: '100%' },
  selectItemText: { width: '100%', fontSize: '9px' },
  tableButtons: {
    display: 'flex',
    width: '100%',
    justifyContent: 'flex-end',
  },
  bucketGroupButtons: {
    display: 'flex',
    width: '100%',
    justifyContent: 'flex-start',
  },
  deleteBucketButton: { margin: '0px 20px' },
  purpleGetirColor: {
    borderRadius: '8px',
    boxShadow: 'rgb(105 116 136 / 15%) 0px 2px 6px',
    width: '100%',
    border: '0px',
    color: '#5d3ebc',
    fontWeight: '600',
    '&:hover': {
      color: 'rgb(255, 228, 48)',
      transition: 'all 0.2s ease 0s',
      backgroundColor: 'rgb(120, 73, 247)',
      borderColor: 'rgb(120, 73, 247)',
      fontWeight: '800',
    },
  },
  yellowGetirColor: {
    borderRadius: '8px',
    boxShadow: 'rgb(105 116 136 / 15%) 0px 2px 6px',
    width: '100%',
    minWidth: 'fit-content',
    border: '0px',
    color: 'rgb(255, 152, 0)',
    fontWeight: '600',
    '&:hover': {
      color: '#5d3ebc',
      transition: 'all 0.2s ease 0s',
      backgroundColor: '#ffd300',
      borderColor: '#ffd300',
      fontWeight: '800',
    },
  },
  disabledSaveButton: { '&:hover': { backgroundColor: 'white' } },
  saveButton: { margin: '0px 5px', textAlign: 'center', height: 'fit-content' },
  differenceModal: { width: '1100px !important' },
  updateColor: { color: 'blue' },
  addColor: { color: 'green' },
  deleteColor: { color: 'red' },
  page: { marginBottom: '100px' },
  bucketTypeInput: { width: '120px' },
  bucketTypeName: {
    width: '120px',
    fontSize: '22px',
    height: '36px',
    textOverflow: 'ellipsis',
    display: 'inline-block',
    whiteSpace: 'nowrap',
    overflow: 'hidden !important',
    '&:hover': {
      marginRight: '16px',
      width: '100%',
      textOverflow: 'unset',
    },
  },
  tableButtonContainer: { backgroundColor: '#fff', padding: '20px' },
  divider: {
    margin: '0px 6px !important',
    borderColor: '#fafafa',
    borderWidth: '0.1px',
  },
  tableButtonWrapper: { display: 'flex' },
  fullPromo: {
    height: '8px',
    width: '8px',
    backgroundColor: '#666',
    borderRadius: '50%',
    display: 'inline-block',
  },
  emptyPromo: {
    height: '8px',
    width: '8px',
    backgroundColor: '#bbb',
    borderRadius: '50%',
    display: 'inline-block',
  },
  promoOption: { display: 'flex' },
  pageFilter: { display: 'flex', justifyContent: 'center' },
  changeReasonTitle: {
    fontSize: '12px',
    display: 'inline',
    marginRight: '10px',
  },
  saveWarningMessage: { fontSize: '12px' },
  errorMessage: { fontSize: '12px', color: '#ff4d4f', fontWeight: 600 },
  warningMessage: { fontSize: '12px', color: '#faad14', fontWeight: 600 },
  editBucketNameButton: { minWidth: '120px' },
  infoCircleOutlined: { color: '#1677ff', marginLeft: '5px' },
  leftSideButtons: {
    display: 'flex',
    justifyContent: 'flex-start',
    width: '50%',
  },
  rightSideButtons: {
    display: 'flex',
    justifyContent: 'flex-end',
    width: '50%',
  },
  tableButtonItem: { marginRight: '15px' },
  '@keyframes fadeAnimation': {
    '0%,100%': { backgroundColor: 'transparent' },
    '50%': { backgroundColor: '#5d3ebc', color: 'rgb(255, 152, 0)' },
  },
  isUpdated: { animation: '$fadeAnimation 5s linear forwards' },
  information: { alignSelf: 'center', color: 'rgb(255, 228, 48)', fontWeight: 600, backgroundColor: '#5d3ebc', padding: '5px', borderRadius: '2px' },
  replaceButtons: { display: 'flex', flexDirection: 'column', alignItems: 'center' },
  setLine: { alignItems: 'center', justifyContent: 'space-around' },
  setNumber: { fontSize: 'medium' },
  replaceButtonItems: { minWidth: '60%', display: 'flex', justifyContent: 'center' },
});
