export const COMMUNICATION_BULK_SMS_ACTIONS = { DETAIL: 'DETAIL', DUPLICATE: 'DUPLICATE', CANCEL: 'CANCEL' };
export const CAMPAIGN_STATUS = {
  INITIALIZING: 'INITIALIZING',
  READY_FOR_DELIVERY: 'READY_FOR_DELIVERY',
  DELIVERY_IN_PROGRESS: 'DELIVERY_IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  FAILED: 'FAILED',
};

export const ACTIVENESS_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
};
