import { createActions } from 'reduxsauce';

import { REDUX_KEY } from '@shared/shared/constants';

export const { Types, Creators } = createActions({
  getRoleByIdRequest: { id: null },
  getRoleByIdSuccess: { data: {} },
  getRoleByIdFailure: { error: null },
  updateRoleRequest: { id: null, updateData: {}, deleteParent: null, afterSuccess: null },
  updateRoleSuccess: { data: {} },
  updateRoleFailure: { error: null },

  updateRoleMemberTypeRequest: { userId: null, roleId: null, memberType: null, expiryDate: null },
  updateRoleMemberTypeSuccess: { data: {} },
  updateRoleMemberTypeFailure: { error: null },

  removeUsersFromRoleRequest: { userIds: null, roleId: null, afterSuccess: null },
  removeUsersFromRoleSuccess: { data: {} },
  removeUsersFromRoleFailure: { error: null },

  removeRoleFromUserByRoleOwnerRequest: { user: null, roleId: null },
  addRoleToUsersByRoleOwnerRequest: { users: null, expiryDate: null, roleId: null },
  getRoleUsersForExcelTableRequest: { roleId: null, isActive: null, countries: null },
  getRoleUsersForExcelTableSuccess: { data: [] },
  getRoleUsersForExcelTableFailure: { error: null },
  updatePermissionOfRoleRequest: { roleId: null, permKeys: [], countryIds: [], hasGlobalAccess: false },
  updateRolePagesRequest: { roleId: null, permKeys: [], countryIds: [], hasGlobalAccess: false },
  removePermissionFromRoleRequest: { roleId: null, permKey: null },
  updateRolePageComponentsRequest: { id: null, countries: [], hasGlobalAccess: false },
  getPageAndComponentPermissionsOfRoleRequest: { roleId: null },
  getPageAndComponentPermissionsOfRoleSuccess: { data: [] },
  getPageAndComponentPermissionsOfRoleFailure: { error: null },
  getPageAndComponentPermissionsOfRoleReset: { },
  exportAccessGrantedPagesExcel: { t: null, role: null },
  exportAccessGrantedPagesExcelFailure: { error: null },
  requestUserRoleRequest: { roleId: null, requestReason: null, timeLimit: '', durationType: '', durationDays: 0, endDate: null },
  requestUserRoleSuccess: { data: {} },
  requestUserRoleFailure: { error: null },
  getUserRoleRequestsRequest: null,
  getUserRoleRequestsSuccess: { roleRequests: [] },
  getUserRoleRequestsFailure: { error: null },
  getReportTagsByRolesRequest: { data: {} },
  getReportTagsByRolesSuccess: { data: [] },
  getReportTagsByRolesFailure: { error: null },
  getReportTagsByRolesReset: { },
  getReportTypesRequest: { data: null },
  getReportTypesSuccess: { data: null },
  getReportTypesFailure: { error: null },
  deleteRoleRequest: { id: null },
  deleteRoleSuccess: { },
  deleteRoleFailure: { error: null },
  updateReportTagReportTypesMap: { request: null, response: null, isPending: null },
  getRoleHierarchyRequest: { id: null },
  getRoleHierarchySuccess: { data: null },
  getRoleHierarchyFailure: { error: null },
  initPage: null,
  destroyPage: null,
}, { prefix: `${REDUX_KEY.ROLE.DETAIL}_` });
