import {
  GETIR_BITAKSI_DOMAIN_TYPE,
  GETIR_MARKET_DOMAIN_TYPES,
  GETIR_WATER_MARKETPLACE_DOMAIN_TYPE,
  GETIR_LOCALS_DOMAIN_TYPE,
  GETIR_FOOD_DOMAIN_TYPE,
} from '@shared/shared/constants';

export const GROWTH_DASHBOARD_DOMAIN_TYPES = [
  ...GETIR_MARKET_DOMAIN_TYPES,
  GETIR_BITAKSI_DOMAIN_TYPE,
  GETIR_WATER_MARKETPLACE_DOMAIN_TYPE,
  GETIR_LOCALS_DOMAIN_TYPE,
  GETIR_FOOD_DOMAIN_TYPE,
];
