import { createActions } from 'reduxsauce';

import { REDUX_KEY } from '@shared/shared/constants';

const prefix = `${REDUX_KEY.GETIR_DRIVE.DASHBOARD}_`;

export const { Types, Creators } = createActions({
  getInstantVehicleStatusRequest: { data: {} },
  getInstantVehicleStatusSuccess: { data: [] },
  getInstantVehicleStatusFailure: { error: null },
  getRentalStatusRequest: { data: {} },
  getRentalStatusSuccess: { data: [] },
  getRentalStatusFailure: { error: null },
  getFinancialRequest: { data: {} },
  getFinancialSuccess: { data: [] },
  getFinancialFailure: { error: null },
  getFinancialDistributionRequest: { data: {} },
  getFinancialDistributionSuccess: { data: [] },
  getFinancialDistributionFailure: { error: null },
  getVehicleBasedStatsRequest: { data: {} },
  getVehicleBasedStatsSuccess: { data: [] },
  getVehicleBasedStatsFailure: { error: null },
  getClientDistributionRequest: { data: {} },
  getClientDistributionSuccess: { data: [] },
  getClientDistributionFailure: { error: null },
  getNewClientDistributionRequest: { data: {} },
  getNewClientDistributionSuccess: { data: [] },
  getNewClientDistributionFailure: { error: null },
  getCleaningScoreCountsRequest: { data: {} },
  getCleaningScoreCountsSuccess: { data: [] },
  getCleaningScoreCountsFailure: { error: null },
  getRateCountsRequest: { data: {} },
  getRateCountsSuccess: { data: [] },
  getRateCountsFailure: { error: null },
  getRentTimeSeriesRequest: { data: {} },
  getRentTimeSeriesSuccess: { data: [] },
  getRentTimeSeriesFailure: { error: null },
  getNetRevenueTimeSeriesRequest: { data: {} },
  getNetRevenueTimeSeriesSuccess: { data: [] },
  getNetRevenueTimeSeriesFailure: { error: null },
  getExternalSourcesSummaryCurrentRequest: { data: {} },
  getExternalSourcesSummaryCurrentSuccess: { data: [] },
  getExternalSourcesSummaryCurrentFailure: { error: null },
  getExternalSourcesSummaryPreviousRequest: { data: {} },
  getExternalSourcesSummaryPreviousSuccess: { data: [] },
  getExternalSourcesSummaryPreviousFailure: { error: null },
  getRentalCountByNetRevenueRequest: { data: {} },
  getRentalCountByNetRevenueSuccess: { data: [] },
  getRentalCountByNetRevenueFailure: { error: null },
  getRentalCountByDurationRequest: { data: {} },
  getRentalCountByDurationSuccess: { data: [] },
  getRentalCountByDurationFailure: { error: null },
  getRentalCountByDistanceRequest: { data: {} },
  getRentalCountByDistanceSuccess: { data: [] },
  getRentalCountByDistanceFailure: { error: null },
  getDailyFrequencyRequest: { data: {} },
  getDailyFrequencySuccess: { data: [] },
  getDailyFrequencyFailure: { error: null },
  getPromoDistributionRequest: { data: {} },
  getPromoDistributionSuccess: { data: [] },
  getPromoDistributionFailure: { error: null },
  getRentalTypeDistributionRequest: { data: {} },
  getRentalTypeDistributionSuccess: { data: [] },
  getRentalTypeDistributionFailure: { error: null },
  initPage: null,
  destroyPage: null,
}, { prefix });
