import { createActions } from 'reduxsauce';

import { CALLER_TYPES, REDUX_KEY } from '@shared/shared/constants';

export const { Types, Creators } = createActions(
  {
    getOrderDetailRequest: { id: null, domainType: null },
    getOrderDetailSuccess: { orderDetail: {} },
    getOrderDetailFailure: { error: null },
    getFraudOrderDetailRequest: { id: null, domainType: null },
    getFraudOrderDetailSuccess: { fraudOrderDetail: {} },
    getFraudOrderDetailFailure: { error: null },
    createOrderNoteRequest: {
      from: {
        _id: null,
        name: null,
      },
      to: null,
      toType: 'MarketOrder',
      domainType: null,
      message: null,
    },
    createOrderNoteSuccess: { note: null },
    createOrderNoteFailure: { error: null },
    getOrderNotesRequest: { orderId: null, toType: null },
    getOrderNotesSuccess: { notes: [] },
    getOrderNotesFailure: { error: null },
    getClientFeedbacksRequest: { clientId: null },
    getClientFeedbacksSuccess: { data: [] },
    getClientFeedbacksFailure: { error: null },
    updateClientDetailAccessToken: { token: undefined },
    createForbiddenMatchRequest: { body: null },
    createForbiddenMatchSuccess: { data: [] },
    createForbiddenMatchFailure: { error: null },
    getInvoiceUrlRequest: { orderId: null, clientId: null, domainType: null },
    getInvoiceUrlSuccess: { data: [] },
    getInvoiceUrlFailure: { error: null },
    updateFraudOrderRequest: { domainType: null, id: null, status: null },
    updateFraudOrderSuccess: { data: [] },
    updateFraudOrderFailure: { error: null },
    cancelOrderRequest: {
      note: null,
      domainType: null,
      id: null,
      status: null,
      callerType: CALLER_TYPES.ADMIN,
      reasonId: null,
      onSuccess: null,
      channel: null,
      action: null,
      source: null,
    },
    cancelOrderSuccess: { data: [] },
    cancelOrderFailure: { error: null },
    cancelOrderCustomerRequest: {
      note: null,
      domainType: null,
      id: null,
      status: null,
      callerId: null,
      reasonName: null,
      reasonId: null,
    },
    cancelOrderCustomerSuccess: { data: [] },
    cancelOrderCustomerFailure: { error: null },
    getOrderCancelOptionsRequest: { id: null, domainType: null },
    getOrderCancelOptionsSuccess: { data: [] },
    getOrderCancelOptionsFailure: { error: null },
    partialRefundOrderCustomerRequest: {
      orderId: null,
      domainType: null,
      products: null,
      callerId: null,
      refundDeliveryFee: null,
      refundBagFee: null,
      refundServiceFee: null,
      onSuccess: null,
      channel: null,
      action: null,
    },
    partialRefundOrderCustomerSuccess: { data: [] },
    partialRefundOrderCustomerFailure: { error: null },
    getWholeRefundReasonsRequest: {},
    getWholeRefundReasonsSuccess: { data: [] },
    getWholeRefundReasonsFailure: { error: null },
    wholeRefundOrderRequest: {
      orderId: null,
      warehouseId: null,
      products: null,
    },
    wholeRefundOrderSuccess: { data: null },
    wholeRefundOrderFailure: { error: null },
    initPage: null,
    destroyPage: null,
    createMarketOrderFeedbackRequest: { data: {} },
    createMarketOrderFeedbackSuccess: { data: [] },
    createMarketOrderFeedbackFailure: { error: null },
    createPromoRequest: { data: {} },
    createPromoSuccess: { data: {} },
    createPromoFailure: { error: null },
    updateOrderStatus: { status: null },
    updateCourierStatus: { status: null },
    updateCourier: { courier: null },
    updateCourierLocation: { coordinates: null },
    startListeningSocketEvents: { marketOrder: null },
    stopListeningSocketEvents: { marketOrder: null },
    getDiscountWarnConfigRequest: {},
    getDiscountWarnConfigSuccess: { data: null },
    getDiscountWarnConfigFailure: { error: null },
    createStockRefundOrderRequest: {
      isWholeRefund: null,
      refundProducts: null,
      warehouseId: null,
      language: null,
      orderId: null,
    },
    createStockRefundOrderSuccess: { data: {} },
    createStockRefundOrderFailure: { error: null },
    getSlottedDeliveryOptionsRequest: {
      warehouseId: null,
      clientAddressLat: null,
      clientAddressLon: null,
      clientId: null,
      etaVersion: 1,
      source: 'MarketOrderDetailPage',
      selectedSlotId: null,
      warehousePolygonTypes: ['17'],
      domainType: null,
    },
    getSlottedDeliveryOptionsSuccess: { data: {} },
    getSlottedDeliveryOptionsFailure: { error: null },
    changeDeliveryTimeSlotRequest: {
      orderId: null,
      clientId: null,
      selectedSlotId: null,
      domainType: null,
      onSuccess: null,
      selectedSlotInfo: null,
    },
    changeDeliveryTimeSlotSuccess: { slotId: null },
    toggleSlotModal: { isVisible: false },
    toggleCancelOrderModal: { isVisible: false },
    getConfigWithKeyRequest: { body: null },
    getConfigWithKeySuccess: { data: {} },
    getConfigWithKeyFailure: { error: null },
    getOrderPartialRefundReasonsRequest: { domainType: null },
    getOrderPartialRefundReasonsSuccess: { data: {} },
    getOrderPartialRefundReasonsFailure: { error: null },
    getOrderByIdRequest: { orderId: null },
    getOrderByIdSuccess: { data: {} },
    getOrderByIdFailure: { error: null },
  },
  { prefix: `${REDUX_KEY.MARKET_ORDER.ORDER_DETAIL}_` },
);
