export const REQUEST_ERROR_REASON = {
  INVALID_PATH_VARIABLE: 'INVALID_PATH_VARIABLE',
  ENTITY_NOT_FOUND: 'ENTITY_NOT_FOUND',
  WRONG_COUNTRY_SELECTION: 'ACCESS_DENIED',
};

export const DATE_FORMAT = 'YYYY/MM/DD HH:mm';

export const TRANSACTIONAL_SMS_ACTIONS = {
  DETAIL: 'DETAIL',
  DUPLICATE: 'DUPLICATE',
};
