import { EMPLOYMENT_STATUSES } from '@app/pages/Employee/constants';
import { MIME_TYPE, TAG_COLORS } from '@shared/shared/constants';

export const ASSET_TYPE_IDS = { VEHICLE: '67a3663c764e17b2a83f5bb3' };

export const FIELD_TYPES = {
  STRING: 'String',
  NUMBER: 'Number',
  OBJECT_ID: 'ObjectId',
};

export const ASSET_STATUSES = {
  ASSIGNABLE: 100,
  ASSIGNED: 200,
};

export const ASSIGNABLE_STATUS = {
  ASSIGNABLE: 100,
  NON_ASSIGNABLE: 200,
};

export const ASSET_STATUSES_TAG_COLORS = {
  [ASSET_STATUSES.ASSIGNABLE]: TAG_COLORS.danger,
  [ASSET_STATUSES.ASSIGNED]: TAG_COLORS.success,
} as const;

// TODO: check allowed types are correct
export const ALLOWED_TYPES = [MIME_TYPE.JPEG, MIME_TYPE.PNG, MIME_TYPE.PDF, MIME_TYPE.DOC, MIME_TYPE.DOCX].join(',');

export const COMPONENT_TYPES = {
  TEXT: 'text',
  VEHICLE_BRAND: 'vehicleBrand',
  VEHICLE_MODEL: 'vehicleModel',
  VEHICLE_BRAND_AND_MODEL: 'vehicleBrandAndModel',
  VEHICLE_MODEL_YEAR: 'vehicleModelYear',
  VEHICLE_FUEL_TYPE: 'vehicleFuelType',
  VEHICLE_TRANSMISSION_TYPE: 'vehicleTransmissionType',
  VEHICLE_IS_COMMON_CAR: 'vehicleIsCommonCar',
  REGISTRATION_OWNER: 'registrationOwner',
  UPLOAD: 'documentFileKey',
  CITY: 'city',
  ASSIGNABLE_STATUS: 'assignableStatus',
  ASSIGNABLE_STATUS_REASON: 'assignableStatusReason',
  ASSIGNMENT_STATUS: 'assignmentStatus',
  FINANCIAL_LEASING_VALIDATION_DATE: 'financialLeasingValidationDate',
  FINANCIAL_LEASING_COMPANY: 'financialLeasingCompany',
  SHORT_LONG_TERM_RENTING_COMPANY: 'shortLongTermRentingCompany',
  SHORT_LONG_TERM_RENTING_VALIDATION_DATE: 'shortLongTermRentingValidationDate',
  EFFECTED_FIELD: 'effectedField',
  DATE_RANGE: 'dateRange',
  UNIQUE_IDENTIFIER: 'uniqueIdentifier',
  USER_ID: 'userId',
};

export const VEHICLE_BRANDS = {
  AUDI: 100,
  BMW: 200,
  FIAT: 300,
  HYUNDAI: 400,
  KIA: 500,
  RENAULT: 600,
  TESLA: 700,
  VOLKSWAGEN: 800,
};

export const VEHICLE_ASSIGNABLE_STATUSES = {
  ASSIGNABLE: 100,
  NON_ASSIGNABLE: 200,
};

export const VEHICLE_ASSIGNABLE_REASON_STATUSES = {
  DAMAGED: 100,
  UNDER_MAINTENANCE: 200,
  PLANNED: 300,
  OTHER: 1000,
};

export const VEHICLE_REASON_TO_STATUS_MAP = {
  [VEHICLE_ASSIGNABLE_STATUSES.NON_ASSIGNABLE]: [
    VEHICLE_ASSIGNABLE_REASON_STATUSES.DAMAGED,
    VEHICLE_ASSIGNABLE_REASON_STATUSES.UNDER_MAINTENANCE,
    VEHICLE_ASSIGNABLE_REASON_STATUSES.PLANNED,
    VEHICLE_ASSIGNABLE_REASON_STATUSES.OTHER,
  ],
  [VEHICLE_ASSIGNABLE_STATUSES.ASSIGNABLE]: [],
};

export const VEHICLE_MODELS = {
  A5_SPORTBACK_45_TFSI_QUATTRO_265_SLINE_STR_PI: 10,
  A8_L_55_TFSI_QUATTRO_340_HP_TIPTRONIC_PI: 20,
  '520I_1.6_LUXURY_LINE': 30,
  '520I_1.6_170_M_SPORT_EDITION': 40,
  X3_LCI_SDRIVE20I_1_6_170_X_LINE: 50,
  EGEA_1_3_MJET_95_HP_EASY: 60,
  EGEA_1_6_EASY_MJET_120_HP_DCT: 70,
  EGEA_1_6_EASY_MJET_130_E6D: 80,
  EGEA_URBAN_1_6_MJET_130_E6D: 90,
  EGEA_SW_URBAN_1_6_MJET_130_E6D: 100,
  FIORINO_1_3_MJET_95_HP_EASY: 110,
  ELANTRA_1_6_MPI_123_CVT_STYLE_COMFORT: 120,
  ELANTRA_1_6_MPI_132_PS_ELITE_CVT_G2TC: 130,
  I20_1_4_MPI_100_JUMP_6_AT: 140,
  STONIC_COOL_1_4_100_OV: 150,
  MEGANE_JOY_1_3_TCE_EDC_140_FAZ2: 160,
  MODEL_Y_ELEKTRIKLI: 170,
  MODEL_Y_LONG_PERFORMANCE_ELEKTRIKLI: 180,
  MODEL_Y_LONG_RANGE_ELEKTRIKLI: 190,
  PASSAT_1_5_TSI_ACT_150_PS_BUSINESS: 200,
  PASSAT_1_5_TSI_ACT_150_PS_IMPRESSION: 210,
  PASSAT_1_5_TSI_CR_DSG_IMPRESSION: 220,
  PASSAT_1_6_TDI_CR_DSG_110_HP_EU6: 230,
  PASSAT_1_5_TSI_ACT_150_DSG_ELEGANCE: 240,
};

export const VEHICLE_BRANDS_TO_MODELS_MAP = {
  [VEHICLE_BRANDS.AUDI]: [
    VEHICLE_MODELS.A5_SPORTBACK_45_TFSI_QUATTRO_265_SLINE_STR_PI,
    VEHICLE_MODELS.A8_L_55_TFSI_QUATTRO_340_HP_TIPTRONIC_PI,
  ],
  [VEHICLE_BRANDS.BMW]: [
    VEHICLE_MODELS['520I_1.6_LUXURY_LINE'],
    VEHICLE_MODELS['520I_1.6_170_M_SPORT_EDITION'],
    VEHICLE_MODELS.X3_LCI_SDRIVE20I_1_6_170_X_LINE,
  ],
  [VEHICLE_BRANDS.FIAT]: [
    VEHICLE_MODELS.EGEA_1_3_MJET_95_HP_EASY,
    VEHICLE_MODELS.EGEA_1_6_EASY_MJET_120_HP_DCT,
    VEHICLE_MODELS.EGEA_1_6_EASY_MJET_130_E6D,
    VEHICLE_MODELS.EGEA_URBAN_1_6_MJET_130_E6D,
    VEHICLE_MODELS.EGEA_SW_URBAN_1_6_MJET_130_E6D,
    VEHICLE_MODELS.FIORINO_1_3_MJET_95_HP_EASY,
  ],
  [VEHICLE_BRANDS.HYUNDAI]: [
    VEHICLE_MODELS.ELANTRA_1_6_MPI_123_CVT_STYLE_COMFORT,
    VEHICLE_MODELS.ELANTRA_1_6_MPI_132_PS_ELITE_CVT_G2TC,
    VEHICLE_MODELS.I20_1_4_MPI_100_JUMP_6_AT,
  ],
  [VEHICLE_BRANDS.KIA]: [
    VEHICLE_MODELS.STONIC_COOL_1_4_100_OV,
  ],
  [VEHICLE_BRANDS.RENAULT]: [
    VEHICLE_MODELS.MEGANE_JOY_1_3_TCE_EDC_140_FAZ2,
  ],
  [VEHICLE_BRANDS.TESLA]: [
    VEHICLE_MODELS.MODEL_Y_ELEKTRIKLI,
    VEHICLE_MODELS.MODEL_Y_LONG_PERFORMANCE_ELEKTRIKLI,
    VEHICLE_MODELS.MODEL_Y_LONG_RANGE_ELEKTRIKLI,
  ],
  [VEHICLE_BRANDS.VOLKSWAGEN]: [
    VEHICLE_MODELS.PASSAT_1_5_TSI_ACT_150_PS_BUSINESS,
    VEHICLE_MODELS.PASSAT_1_5_TSI_ACT_150_PS_IMPRESSION,
    VEHICLE_MODELS.PASSAT_1_5_TSI_CR_DSG_IMPRESSION,
    VEHICLE_MODELS.PASSAT_1_6_TDI_CR_DSG_110_HP_EU6,
    VEHICLE_MODELS.PASSAT_1_5_TSI_ACT_150_DSG_ELEGANCE,
  ],
};

export const VEHICLE_TRANSMISSION_TYPES = {
  AUTOMATIC: 100,
  MANUEL: 200,
  C: 300,
};

export const VEHICLE_FUEL_TYPES = {
  GASOLINE: 100,
  DIESEL: 200,
  LPG: 300,
  HYBRID: 400,
  ELECTRIC: 500,
};

export const ASSIGNMENT_PERIOD_TYPES = {
  DEFINITE_TERM: 100,
  INDEFINITE_TERM: 200,
};

export const VEHICLE_MODEL_YEAR_RANGE = [2010, 2051];

export const REGISTRATION_OWNERS = {
  GETIR: 100,
  FINANCIAL_RENTING: 200,
  SHORT_LONG_TERM_RENTING: 300,
};

export const FINANCIAL_LEASING_COMPANIES = {
  AK_LEASING: 100,
  QNB_FINANS: 200,
  SEKER_LEASING: 300,
};

export const FORM_MODES = {
  ADD: 'ADD',
  EDIT: 'EDIT',
};

export const VEHICLE_TIRE_TYPES = {
  SUMMER: 100,
  WINTER: 200,
  ALL_SEASON: 300,
};

export const TRACKING_DEVICE_STATUSES = {
  AVAILABLE: 100,
  NOT_AVAILABLE: 200,
  DAMAGED: 300,
  DEMOUNTED: 400,
};

export const VEHICLE_EQUIPMENTS = {
  SPARE_TIRE: 100,
  JACK: 200,
  TRAFFIC_KIT: 300,
  REGISTRATION: 400,
};

export const VEHICLE_TABLE_TABS = {
  VEHICLE_LIST: 'vehicleList',
  CONTROL_NEEDED_VEHICLES: 'controlNeededVehicles',
};

export const VEHICLE_COMPLIANCE_RECORD_TYPES = {
  INSURANCE: 100,
  COVERAGE: 200,
  INSPECTION: 300,
};

export const FILTER_DISABLED_TABS = [VEHICLE_TABLE_TABS.CONTROL_NEEDED_VEHICLES];

export const CONTROL_NEEDED_AFTER_DAYS = 5;

export const DEFAULT_DATE_FORMAT = 'DD.MM.YYYY';

export const S3_UPLOAD_FOLDER_PATH = { VEHICLES: 'asset-management/vehicles' };

export const MODE_CHANGE_LOG_MODELS = {
  ASSET: 'Asset',
  ASSET_HISTORY: 'AssetHistory',
  DAMAGE_RECORD: 'DamageRecord',
  TRAFFIC_PENALTY: 'TrafficPenalty',
  COMPLIANCE_RECORD: 'ComplianceRecord',
  VEHICLE_EQUIPMENT: 'VehicleEquipment',
};

export const LOCAL_DATE_FORMAT: { [x: string]: string } = {
  TR: 'YYYY-MM-DD',
  EN: 'YYYY/MM/DD',
};

export const LOCAL_DATE_TIME_FORMAT: { [x: string]: string } = {
  TR: 'YYYY-MM-DD HH:mm',
  EN: 'YYYY/MM/DD hh:mm A ',
};
