export const SELECT_ALL_KEY = 'SELECT_ALL';
export const GETIR_10_DOMAIN_TYPE_KEY = 'GETIR_10_DOMAIN_TYPE';
export const GETIR_MARKET_DOMAIN_TYPE_KEY = 'GETIR_MARKET_DOMAIN_TYPE';
export const GETIR_WATER_DOMAIN_TYPE_KEY = 'GETIR_WATER_MARKETPLACE_DOMAIN_TYPE';
export const STORE_CONVERSION_MARKET_FRANCHISE_TYPE_KEY = 'STORE_CONVERSION_MARKET_FRANCHISE_TYPE';
export const MAIN_WAREHOUSE_TYPE_KEY = 'MAIN_WAREHOUSE_TYPE';
export const MAX_TAG_COUNT_FOR_CUSTOM_FRANCHISE_SELECT = 20;
