export const COMMUNICATION_SERVICE_CREDENTIALS_ACTIONS = { DETAIL: 'DETAIL' };

export const SERVICE_TYPES = {
  NOTIF: 1,
  SMS: 2,
  EMAIL: 3,
};

export const REQUEST_ERROR_REASON = {
  INVALID_PATH_VARIABLE: 'INVALID_PATH_VARIABLE',
  ENTITY_NOT_FOUND: 'ENTITY_NOT_FOUND',
  WRONG_COUNTRY_SELECTION: 'ACCESS_DENIED',
};

export const STATUSES = {
  ACTIVE: 1,
  INACTIVE: 2,
};

export const PROVIDER_TYPE = {
  NET_GSM: 1,
  MOBILE_DEV: 2,
  NEXMO: 3,
  TWILIO: 4,
};
