import { createActions } from 'reduxsauce';

import { REDUX_KEY } from '@shared/shared/constants';

export const { Types, Creators } = createActions({
  initPage: null,
  destroyPage: null,
  getMarketFranchiseRequest: { id: null },
  getMarketFranchiseSuccess: { data: {} },
  getMarketFranchiseFailure: { error: null },
  updateCommissionRatesRequest: { id: null, updateData: {} },
  updateCommissionRatesSuccess: { data: {} },
  updateCommissionRatesFailure: { error: null },
  updateMarketFranchiseRequest: { id: null, updateData: {} },
  updateMarketFranchiseSuccess: { data: {} },
  updateMarketFranchiseFailure: { error: null },
  updateMarketFranchiseWithSAPRequest: { referenceCode: null, updateData: {} },
  updateMarketFranchiseWithSAPSuccess: { data: {} },
  updateMarketFranchiseWithSAPFailure: { error: null },
  createNewCrisisCardRequest: { requestBody: {} },
  createNewCrisisCardSuccess: { data: {} },
  createNewCrisisCardFailure: { error: null },
  createNewCrisisCardModalClose: null,
  updateCrisisCardRequest: { requestBody: {} },
  updateCrisisCardSuccess: null,
  updateCrisisCardFailure: { error: null },
  getCrisisCardListRequest: { limit: 10, offset: 0, franchiseId: undefined, topicId: undefined },
  getCrisisCardListSuccess: { data: [], count: 0 },
  getCrisisCardListFailure: { error: null },
  changeCrisisCardListPagination: { currentPage: 1, rowsPerPage: 10 },
  exportCrisisCardListRequest: { franchiseId: undefined, topicId: undefined },
  exportCrisisCardListSuccess: null,
  exportCrisisCardListFailure: { error: null },
  getCrisisLogsRequest: {
    cardNumber: undefined,
    limit: undefined,
    offset: undefined,
    franchiseId: undefined,
  },
  getCrisisLogsSuccess: { data: null, count: 0 },
  getCrisisLogsFailure: { error: null },
  changeCrisisLogsPagination: { currentPage: 1, rowsPerPage: 10 },
  exportCrisisLogsRequest: { franchiseId: undefined, cardNumber: undefined },
  exportCrisisLogsSuccess: null,
  exportCrisisLogsFailure: { error: null },
  getCrisisCardRequest: { cardId: undefined },
  getCrisisCardSuccess: { data: null },
  getCrisisCardFailure: { error: null },
  removeCrisisCardRequest: { cardId: null },
  removeCrisisCardSuccess: null,
  removeCrisisCardFailure: { error: null },
  createFranchiseAreaRequest: { areaName: null, franchiseId: null },
  createFranchiseAreaSuccess: { data: {} },
  createFranchiseAreaFailure: { error: null },
  updateFranchiseAreaRequest: { areaName: null, franchiseAreaId: null },
  updateFranchiseAreaSuccess: {},
  updateFranchiseAreaFailure: { error: null },
  deleteFranchiseAreaRequest: { franchiseAreaId: null },
  deleteFranchiseAreaSuccess: {},
  deleteFranchiseAreaFailure: { error: null },
}, { prefix: `${REDUX_KEY.MARKET_FRANCHISE.DETAIL}_` });
