import { CONFIDENCE_LEVEL_COUNTS, PRODUCT_MATCHING_TAB_COUNTS } from './mockData';

export const PRODUCT_MATCHING_ANALYTICS_CONFIG = {
  name: 'COMMERCE_INTELLIGENCE_PRODUCT_MATCHING',
  squad: 'COMMERCE',
};

export const SMART_PRICING_ANALYTICS_CONFIG = {
  name: 'COMMERCE_INTELLIGENCE_SMART_PRICING_INDEX',
  squad: 'COMMERCE',
};

export const REDUX_STORE_KEYS = {
  PRODUCT_MATCHING: 'productMatching',
  SMART_PRICING: 'smartPricing',
  CONFIDENCE_VERY_HIGH: 'confidenceVeryHigh',
};

export const TRANSLATION_NAMESPACE = 'commerceIntelligence';

export const PRODUCT_MATCHING_TABS = {
  CONFIDENCE: 1,
  MATCHED: 2,
  UNMATCHED: 3,
};

export const SMART_PRICING_TABS = {
  GETIR: 1,
  GETIR_MORE: 2,
};

export const CONFIDENCE_LEVELS = {
  VERY_HIGH: 1,
  HIGH: 2,
  MEDIUM: 3,
  LOW: 4,
};

export const TAB_NAMES = {
  CONFIDENCE: 'CONFIDENCE',
  MATCHED: 'MATCHED',
  UNMATCHED: 'UNMATCHED',
  CONFIDENCE_VERY_HIGH: 'CONFIDENCE_LEVELS.VERY_HIGH',
  CONFIDENCE_HIGH: 'CONFIDENCE_LEVELS.HIGH',
  CONFIDENCE_MEDIUM: 'CONFIDENCE_LEVELS.MEDIUM',
  CONFIDENCE_LOW: 'CONFIDENCE_LEVELS.LOW',
  GETIR: 'GETIR',
  GETIR_MORE: 'GETIR_MORE',
};

export { CONFIDENCE_LEVEL_COUNTS, PRODUCT_MATCHING_TAB_COUNTS };
