import { createActions } from 'reduxsauce';

import { REDUX_KEY } from '@shared/shared/constants';

export const { Types, Creators } = createActions({
  getMarketProductByIdRequest: { id: null, populate: undefined },
  getMarketProductByIdSuccess: { data: {} },
  getMarketProductByIdFailure: { error: null },
  createMarketProductRequest: { body: null },
  createMarketProductSuccess: { data: [] },
  createMarketProductFailure: { error: null },
  updateMarketProductRequest: { id: null, body: null },
  updateMarketProductSuccess: { data: {} },
  updateMarketProductFailure: { error: null },
  assignFamilyToProductRequest: { productId: null, familyId: null },
  assignFamilyToProductSuccess: { data: {} },
  assignFamilyToProductFailure: { error: null },
  getTransferGroupsRequest: { status: null },
  getTransferGroupsSuccess: { data: [] },
  getTransferGroupsFailure: { error: null },
  getProductTransferGroupsByProductRequest: { productId: null },
  getProductTransferGroupsByProductSuccess: { data: [] },
  getProductTransferGroupsByProductFailure: { error: null },
  updateTransferGroupsOfProductRequest: { productId: null, transferGroups: null },
  updateTransferGroupsOfProductSuccess: { data: [] },
  updateTransferGroupsOfProductFailure: { error: null },
  createMarketProductImageUrlRequest: {
    key: null,
    loadedImage: null,
    extension: null,
  },
  createMarketProductImageUrlSuccess: { data: {} },
  createMarketProductImageUrlFailure: { key: null, error: null },
  getProductsOfSubCategoryRequest: { categoryId: null, subCategoryId: null },
  getProductsOfSubCategorySuccess: { data: {} },
  getProductsOfSubCategoryFailure: { error: null },
  resetProductsOfSubCategory: {},
  resetProductsOfSubCategorySuccess: { data: {} },
  resetProductsOfSubCategoryFailure: { error: null },
  updateMarketCategoryPositionRequest: { id: null, body: null },
  updateMarketCategoryPositionSuccess: { data: {} },
  updateMarketCategoryPositionFailure: { error: null },
  deleteMarketCategoryPositionRequest: { id: null, categoryId: null, subCategoryId: null },
  deleteMarketCategoryPositionSuccess: { data: {} },
  deleteMarketCategoryPositionFailure: { error: null },
  addMarketCategoryPositionRequest: { id: null, categoryId: null, subCategoryId: null, enteredPosition: null },
  addMarketCategoryPositionSuccess: { data: {} },
  addMarketCategoryPositionFailure: { error: null },
  updateMainCategoryRequest: { id: null, body: null },
  updateMainCategorySuccess: { data: {} },
  updateMainCategoryFailure: { error: null },
  createMarketProductTagRequest: { marketProductTagData: null, loadedImage: null, extension: null },
  createMarketProductTagSuccess: { data: {} },
  createMarketProductTagFailure: { error: null },
  updateMarketProductTagRequest: { id: null, marketProductTagData: null, loadedImage: null, extension: null },
  updateMarketProductTagSuccess: { data: {} },
  updateMarketProductTagFailure: { error: null },
  deleteMarketProductTagRequest: { tagId: null },
  deleteMarketProductTagSuccess: { data: {} },
  deleteMarketProductTagFailure: { error: null },
  getMarketProductTagsRequest: {},
  getMarketProductTagsSuccess: { data: {} },
  getMarketProductTagsFailure: { error: null },
  getMarketProductFeedDataRequest: { productId: null },
  getMarketProductFeedDataSuccess: { data: {} },
  getMarketProductFeedDataFailure: { error: null },
  getMarketProductSlugsRequest: { id: null },
  getMarketProductSlugsSuccess: { data: {} },
  getMarketProductSlugsFailure: { error: null },
  getMarketProductBundlesDataRequest: { id: null, fields: undefined },
  getMarketProductBundlesDataSuccess: { data: {} },
  getMarketProductBundlesDataFailure: { error: null },
  getMarketProductMasterCategoriesOldRequest: { limit: null, offset: null, isSubCategory: null },
  getMarketProductMasterCategoriesOldSuccess: { data: [] },
  getMarketProductMasterCategoriesOldFailure: { error: null },
  getProductActivationValidationErrorsRequest: { ids: undefined },
  getProductActivationValidationErrorsSuccess: { data: [] },
  getProductActivationValidationErrorsFailure: { error: null },
  activateProductsRequest: { ids: undefined },
  activateProductsSuccess: {},
  activateProductsFailure: { error: null },
  setIsImperialUnitUsed: { isImperialUnitUsed: false },
  getMarketProductAllPriceRequest: { id: undefined, warehouseId: undefined },
  getMarketProductAllPriceSuccess: { data: [] },
  getMarketProductAllPriceFailure: { error: null },
  updateMarketProductPricingRequest: { id: undefined, body: null, errors: [] },
  updateMarketProductPricingSuccess: { data: [] },
  updateMarketProductPricingFailure: { error: null },
  createBuyingPriceFinancialsRequest: { body: null, errors: [] },
  createBuyingPriceFinancialsSuccess: { data: [] },
  createBuyingPriceFinancialsFailure: { error: null },
  getWarehouseSegmentsRequest: {},
  getWarehouseSegmentsSuccess: { data: [] },
  getWarehouseSegmentsFailure: { error: null },
  getBadgesRequest: { limit: 0, offset: 0 },
  getBadgesSuccess: { data: [] },
  getBadgesFailure: { error: null },
  updateBuyingPriceFinancialsRequest: { body: null, errors: [] },
  updateBuyingPriceFinancialsSuccess: { data: [] },
  updateBuyingPriceFinancialsFailure: { error: null },
  updateWastePricingRequest: { body: null, productId: undefined },
  updateWastePricingSuccess: { data: [] },
  updateWastePricingFailure: { error: null },
  updateWarehousePricingRequest: { body: null, productId: undefined },
  updateWarehousePricingSuccess: { data: [] },
  updateWarehousePricingFailure: { error: null },
  getSupplyLogisticInfoRequest: { id: undefined },
  getSupplyLogisticInfoSuccess: { data: [] },
  getSupplyLogisticInfoFailure: { error: null },
  updateSupplyLogisticInfoRequest: { id: undefined, body: null, errors: [] },
  updateSupplyLogisticInfoSuccess: { data: [] },
  updateSupplyLogisticInfoFailure: { error: null },
  createSupplyLogisticInfoRequest: { body: null },
  createSupplyLogisticInfoSuccess: { data: [] },
  createSupplyLogisticInfoFailure: { error: null },
  createOrUpdateSupplyLogisticInfoRequest: { id: undefined, body: null, isCreated: undefined, hasTransferGroup: undefined, errors: [] },
  getMasterCategoriesV2Request: { queryText: undefined, level: undefined, limit: undefined, offset: undefined, fields: [], status: undefined },
  getMasterCategoriesV2Success: { data: [] },
  getMasterCategoriesV2Failure: { error: null },
  getSupplyBrandsRequest: { name: undefined, limit: undefined, offset: 0 },
  getSupplyBrandsSuccess: { data: [] },
  getSupplyBrandsFailure: { error: null },
  createSellingPriceFinancialsRequest: { body: null, errors: [] },
  createSellingPriceFinancialsSuccess: { data: [], errors: [] },
  createSellingPriceFinancialsFailure: { error: null },
  createSellingPriceDiscountedFinancialsRequest: { body: null },
  createSellingPriceDiscountedFinancialsSuccess: { data: [] },
  createSellingPriceDiscountedFinancialsFailure: { error: null },
  getSellingPriceListRequest: {
    limit: 10000,
    offset: undefined,
    productIds: undefined,
    domainTypes: undefined,
    warehouseIds: undefined,
    startDate: undefined,
    endDate: undefined,
    pricingTypes: undefined,
  },
  getSellingPriceListSuccess: { data: [] },
  getSellingPriceListFailure: { error: null },
  getMarketProductsPriceListRequest: {
    limit: 10,
    offset: undefined,
    productIds: undefined,
    domainTypes: undefined,
    warehouseIds: undefined,
    startDate: undefined,
    endDate: undefined,
    pricingTypes: undefined,
    callbackForProducts: false,
  },
  getMarketProductsPriceListSuccess: { data: [] },
  getMarketProductsPriceListFailure: { error: null },
  updateBundleSubProductPricesRequest: { body: null },
  updateBundleSubProductPricesSuccess: { data: [] },
  updateBundleSubProductPricesFailure: { error: null },
  updateBundleSubProductStruckPriceRequest: { body: null },
  updateBundleSubProductStruckPriceSuccess: { data: [] },
  updateBundleSubProductStruckPriceFailure: { error: null },
  deleteBundleStruckPriceRequest: { body: null },
  deleteBundleStruckPriceSuccess: { data: [] },
  deleteBundleStruckPriceFailure: { error: null },
  updateMarketProductPriceRequest: { body: null, productId: undefined, errors: [] },
  updateMarketProductPriceSuccess: { data: [] },
  updateMarketProductPriceFailure: { error: null },
  updateMarketProductDiscountedPriceRequest: { body: null, productId: undefined, errors: [] },
  updateMarketProductDiscountedPriceSuccess: { data: [] },
  updateMarketProductDiscountedPriceFailure: { error: null },
  deleteBuyingPriceFinancialsRequest: { body: null },
  deleteBuyingPriceFinancialsSuccess: { data: [] },
  deleteBuyingPriceFinancialsFailure: { error: null },
  deleteDiscountedPriceRequest: { discountedPriceId: undefined, productId: undefined },
  deleteDiscountedPriceSuccess: { data: [] },
  deleteDiscountedPriceFailure: { error: null },
  initPage: null,
  destroyPage: null,
}, { prefix: `${REDUX_KEY.MARKET_PRODUCT.DETAIL}_` });
