export const BUTTON = {
  EDIT: 'EDIT',
  COMPLETE: 'COMPLETE',
  INACTIVATE: 'INACTIVATE',
  SAVE: 'SAVE',
  CANCEL: 'CANCEL',
  SEND_TO_FRANCHISE: 'SEND_TO_FRANCHISE',
  IN_PROGRESS: 'IN_PROGRESS',
};
