export const COMMUNICATION_CALLBACK_URLS_ACTIONS = { DETAIL: 'DETAIL' };

export const SERVICE_TYPES = {
  NOTIF: 1,
  SMS: 2,
  EMAIL: 3,
};

export const REQUEST_ERROR_REASON = {
  INVALID_PATH_VARIABLE: 'INVALID_PATH_VARIABLE',
  ENTITY_NOT_FOUND: 'ENTITY_NOT_FOUND',
  WRONG_COUNTRY_SELECTION: 'ACCESS_DENIED',
};

export const CALLBACK_TYPES = {
  DATA: 'DATA',
  STATUS: 'STATUS',
};
