import { createActions } from 'reduxsauce';

import { REDUX_KEY } from '@shared/shared/constants';

export const { Types, Creators } = createActions({
  // Init
  initPage: null,
  destroyPage: null,

  // Filters
  resetFilters: null,
  setFiltersPage: { page: 1 },
  setFiltersPagePerRow: { pagePerRow: 10 },
  setOrderStatus: { status: null },
  setDeliveryTypes: { deliveryTypes: null },
  setPaymentMethods: { paymentMethods: null },
  setStartDate: { startDate: null },
  setEndDate: { endDate: null },

  // Network
  getPaymentMethodsRequest: { includeOnline: false },
  getPaymentMethodsSuccess: { data: [] },
  getPaymentMethodsFailure: { error: null },
  getClientDetailAccessTokenRequest: { clientId: undefined },
  getClientDetailAccessTokenSuccess: { data: {} },
  getClientDetailAccessTokenFailure: { error: null },
  updateClientDetailAccessToken: { token: undefined },
  checkOtpRequest: { clientId: undefined, code: undefined },
  checkOtpSuccess: { isOtpValid: undefined },
  checkOtpFailure: { error: null },
  sendOtpRequest: { clientId: undefined },
  sendOtpSuccess: {},
  sendOtpFailure: { error: null },
  getClientRequest: { data: {} },
  getClientSuccess: { data: [] },
  getClientFailure: { error: null },
  getSegmentsOfClientRequest: { clientId: null },
  getSegmentsOfClientSuccess: { data: [] },
  getSegmentsOfClientFailure: { error: null },
  getClientNotesRequest: { data: {} },
  getClientNotesSuccess: { data: [] },
  getClientNotesFailure: { error: null },
  createClientNoteRequest: { data: {} },
  createClientNoteSuccess: { data: {} },
  createClientNoteFailure: { error: null },
  updateClientNoteRequest: { data: {} },
  updateClientNoteSuccess: { data: {} },
  updateClientNoteFailure: { error: null },
  getClientMarketingCommunicationPreferencesRequest: { clientId: undefined },
  getClientMarketingCommunicationPreferencesSuccess: { data: {} },
  getClientMarketingCommunicationPreferencesFailure: { error: null },
  updateClientMarketingCommunicationPreferencesLoading: { loading: {}, val: {} },
  updateClientMarketingCommunicationPreferencesRequest: { data: {}, loading: {} },
  updateClientMarketingCommunicationPreferencesSuccess: { data: {}, loading: {}, val: {} },
  updateClientMarketingCommunicationPreferencesFailure: { error: null, loading: {}, val: {} },
  getOrdersHistoryRequest: { data: {} },
  getOrdersHistorySuccess: { data: [] },
  getOrdersHistoryFailure: { error: null },
  getClientDiscountsRequest: { data: {} },
  getClientDiscountsSuccess: { data: [] },
  getClientDiscountsFailure: { error: null },
  updateOrdersHistoryFiltersRequest: { data: {} },
  updateOrdersHistoryFiltersSuccess: { data: {} },
  updateOrdersHistoryFiltersFailure: { error: null },
  getFoodOrdersRequest: null,
  getFoodOrdersSuccess: { data: [] },
  getFoodOrdersFailure: { error: null },
  getLocalsOrdersRequest: { data: {} },
  getLocalsOrdersSuccess: { data: [] },
  getLocalsOrdersFailure: { error: null },
  getClientEligiblePromosRequest: { data: {} },
  getClientEligiblePromosSuccess: { data: [] },
  getClientEligiblePromosFailure: { error: null },
  getClientShownPromosRequest: { data: {} },
  getClientShownPromosSuccess: { data: [] },
  getClientShownPromosFailure: { error: null },
  getClientLoyaltyStampsRequest: { clientId: null },
  getClientLoyaltyStampsSuccess: { data: {} },
  getClientLoyaltyStampsFailure: { error: null },
  getInvoicesRequest: { data: {} },
  getGetirBiTaksiOrdersRequest: { data: {} },
  getGetirBiTaksiOrdersSuccess: { data: [] },
  getGetirBiTaksiOrdersFailure: { error: null },
  getClientDevicesRequest: { clientId: undefined },
  getClientDevicesSuccess: { data: [] },
  getClientDevicesFailure: { error: null },
  blockClientDeviceRequest: { deviceId: undefined },
  blockClientDeviceSuccess: {},
  blockClientDeviceFailure: { error: null },
  unblockClientDeviceRequest: { deviceId: undefined },
  unblockClientDeviceSuccess: {},
  unblockClientDeviceFailure: { error: null },
  logoutFromAllClientDevicesRequest: { clientId: undefined },
  logoutFromAllClientDevicesSuccess: {},
  logoutFromAllClientDevicesFailure: { error: null },
  logoutClientDeviceRequest: { clientId: undefined, deviceId: undefined },
  logoutClientDeviceSuccess: {},
  logoutClientDeviceFailure: { error: null },
  getClientFeedbacksRequest: { clientId: undefined },
  getClientFeedbacksSuccess: { data: [] },
  getClientFeedbacksFailure: { error: null },
  createClientFeedbackRequest: { data: {} },
  createClientFeedbackSuccess: { data: [] },
  createClientFeedbackFailure: { error: null },
  resolveClientFeedbackRequest: { data: {} },
  resolveClientFeedbackSuccess: {},
  resolveClientFeedbackFailure: { error: null },
  getClientForbiddenMatchesRequest: { clientId: undefined },
  getClientForbiddenMatchesSuccess: { data: [] },
  getClientForbiddenMatchesFailure: { error: null },
  updateClientForbiddenMatchRequest: { data: {} },
  updateClientForbiddenMatchSuccess: { data: {} },
  updateClientForbiddenMatchFailure: { error: null },
  updateContactNumberRequest: { clientId: undefined, contactNumber: undefined },
  updateContactNumberSuccess: { data: {} },
  updateContactNumberFailure: { error: null },
  updateClientActivenessRequest: { clientId: undefined, isActivated: undefined },
  updateClientActivenessSuccess: { data: {} },
  updateClientActivenessFailure: { error: null },
  closeClientAccountRequest: { clientId: undefined },
  closeClientAccountSuccess: {},
  closeClientAccountFailure: { error: null },
  reopenClientAccountRequest: { clientId: undefined },
  reopenClientAccountSuccess: {},
  reopenClientAccountFailure: { error: null },
  anonymiseClientAccountRequest: { clientId: undefined },
  anonymiseClientAccountSuccess: {},
  anonymiseClientAccountFailure: { error: null },
  unlinkFacebookRequest: { clientId: undefined },
  unlinkFacebookSuccess: {},
  unlinkFacebookFailure: { error: null },
  getGetirWaterMarketplaceOrdersRequest: { clientId: undefined, count: undefined, page: undefined },
  getGetirWaterMarketplaceOrdersSuccess: { data: [], pagination: {} },
  getGetirWaterMarketplaceOrdersFailure: { error: null },
  validateActiveChatTokenRequest: { clientId: undefined, activeChatToken: undefined },
  validateActiveChatTokenSuccess: {},
  validateActiveChatTokenFailure: { error: null },
  getSubscriptionDetailsRequest: { id: null, typeCode: null, countryCode: null },
  getSubscriptionDetailsSuccess: { data: [] },
  getSubscriptionDetailsFailure: { error: null },
  getTransactionDetailsRequest: { cycleId: null },
  getTransactionDetailsSuccess: { data: [] },
  getTransactionDetailsFailure: { error: null },
  getClientDiscountWarnConfigRequest: {},
  getClientDiscountWarnConfigSuccess: { data: null },
  getClientDiscountWarnConfigFailure: { error: null },
  getClientGetirTableOrdersRequest: { clientId: null },
  getClientGetirTableOrdersSuccess: { data: {} },
  getClientGetirTableOrdersFailure: { error: null },
  getClientFinanceOrdersRequest: { clientId: undefined, size: undefined, page: undefined },
  getClientFinanceOrdersSuccess: { data: [], totalCount: 0 },
  getClientFinanceOrdersFailure: { error: null },
  getClientStatusGetirJobsRequest: { clientId: undefined },
  getClientStatusGetirJobsSuccess: { data: null },
  getClientStatusGetirJobsFailure: { error: null },
  deleteClientGetirJobsRequest: { clientId: undefined, onSuccess: null },
  deleteClientGetirJobsSuccess: { data: null },
  deleteClientGetirJobsFailure: { error: null },
}, { prefix: `${REDUX_KEY.CLIENT.DETAIL}_` });
