export const refundOptions = {
  MISSING_PRODUCT_BECAUSE_OF_GETIR: 1,
  DAMAGED_PRODUCT_BECAUSE_OF_GETIR: 2,
  MISSING_PRODUCT_BECAUSE_OF_VENDOR: 3,
  DAMAGED_PRODUCT_BECAUSE_OF_VENDOR: 4,
  NO_PRODUCT_DELIVERY_BECAUSE_OF_VENDOR: 5,
};
