import {
  REGULAR_WAREHOUSE_TYPE,
  SC_GROCER_WAREHOUSE_TYPE,
  STORE_CONVERSION_WAREHOUSE_TYPE,
  OTHER_WAREHOUSE_TYPE,
  BANNED_FOR_COURIER_GETIR_MARKET_POLYGON_TYPE,
  BANNED_FOR_PRODUCT_DISPLAY_GETIR_MARKET_POLYGON_TYPE,
  BANNED_FOR_PROMO_GETIR_MARKET_POLYGON_TYPE,
  TOTALLY_BANNED_GETIR_MARKET_POLYGON_TYPE,
  SUB_REGION_GETIR_MARKET_POLYGON_TYPE,
  EXTENDED_GETIR_MARKET_POLYGON_TYPE,
  GETIR_10_DOMAIN_TYPE,
  GETIR_MARKET_DOMAIN_TYPE,
  GETIR_MARKET_SUBREGION_INTERVAL_TYPES,
} from '@shared/shared/constants';

export const DOMAIN_TYPES = [GETIR_10_DOMAIN_TYPE, GETIR_MARKET_DOMAIN_TYPE];
export const POLYGON_TYPES = [SUB_REGION_GETIR_MARKET_POLYGON_TYPE, EXTENDED_GETIR_MARKET_POLYGON_TYPE];
export const SUBREGION_INTERVAL_TYPES = [...GETIR_MARKET_SUBREGION_INTERVAL_TYPES];

export const BAN_POLYGON_TYPES = [
  BANNED_FOR_PRODUCT_DISPLAY_GETIR_MARKET_POLYGON_TYPE,
  BANNED_FOR_PROMO_GETIR_MARKET_POLYGON_TYPE,
  TOTALLY_BANNED_GETIR_MARKET_POLYGON_TYPE,
  BANNED_FOR_COURIER_GETIR_MARKET_POLYGON_TYPE,
];

export const WAREHOUSE_TYPES_FOR_MAPS = new Set([
  REGULAR_WAREHOUSE_TYPE,
  SC_GROCER_WAREHOUSE_TYPE,
  STORE_CONVERSION_WAREHOUSE_TYPE,
  OTHER_WAREHOUSE_TYPE,
]);

// Additional fields can be use in following const. (weather_code etc)
export const TEMPERATURE_FIELD = 'temperature';
export const WIND_SPEED_FIELD = 'wind_speed';
export const WEATHER_CODE_FIELD = 'weather_code';
export const REQUIRED_FIELDS = [TEMPERATURE_FIELD, WIND_SPEED_FIELD, WEATHER_CODE_FIELD];

export const H3_RESOLUTION = 8;
export const POLYGON_BUFFER_DISTANCE = 500;
export const POLYGON_BUFFER_UNIT = 'meters';
export const SLIDER_HOUR_MARKS = {
  0: '00:00',
  3: '03:00',
  6: '06:00',
  9: '09:00',
  12: '12:00',
  15: '15:00',
  18: '18:00',
  21: '21:00',
  24: '24:00',
};

export const HIGH_WIND_SPEED = 10;
export const MID_WIND_SPEED = 5;
export const LOW_WIND_SPEED = 0;

export const GREEN_RGB = [0, 255, 0]; // Green
export const NORMAL_TEMPERATURE = [0, 255, 0]; // Green
export const ORANGE_RGB = [255, 140, 0]; // Orange
export const RED_RGB = [255, 0, 0]; // Red
export const YELLOW_RGB = [255, 255, 0]; // Yellow

export const DATE_FORMAT = 'YYYY-MM-DDT00:00:00Z';
export const DATE_FORMAT_FOR_FORM = 'YYYY-MM-DD';

export const DEFAULT_MAP_OPTIONS = {
  CENTER: [41, 29],
  ZOOM_LEVEL: 12,
};

// Followings are used for controlling icon visibility.
export const MIN_ZOOM_LEVEL = 10;
export const MAX_ZOOM_LEVEL = 20;
