import { ClockCircleOutlined, CloseCircleOutlined, ExclamationCircleOutlined, CheckCircleOutlined } from '@ant-design/icons';

export const MENTORSHIP_REQUEST_STATUSES = {
  PENDING: 1,
  ACCEPTED: 2,
  DECLINED: 3,
  WITHDRAWN: 4,
};

export const MENTORSHIP_STATUSES = {
  IN_PROGRESS: 1,
  FINISHED: 2,
};

const SECONDARY = 'secondary';
const ACTIVE = 'active';
const DANGER = 'danger';
const INACTIVE = 'inactive';

export const MENTORSHIP_REQUEST_STATUSES_TAG_COLORS = {
  [MENTORSHIP_REQUEST_STATUSES.PENDING]: SECONDARY,
  [MENTORSHIP_REQUEST_STATUSES.ACCEPTED]: ACTIVE,
  [MENTORSHIP_REQUEST_STATUSES.DECLINED]: DANGER,
  [MENTORSHIP_REQUEST_STATUSES.WITHDRAWN]: INACTIVE,
};

export const MENTORSHIP_STATUSES_TAG_COLORS = {
  [MENTORSHIP_STATUSES.IN_PROGRESS]: ACTIVE,
  [MENTORSHIP_STATUSES.FINISHED]: INACTIVE,
};

export const MENTORSHIP_REQUEST_STATUS_ICONS = {
  [MENTORSHIP_REQUEST_STATUSES.PENDING]: <ClockCircleOutlined />,
  [MENTORSHIP_REQUEST_STATUSES.ACCEPTED]: <CheckCircleOutlined />,
  [MENTORSHIP_REQUEST_STATUSES.DECLINED]: <CloseCircleOutlined />,
  [MENTORSHIP_REQUEST_STATUSES.WITHDRAWN]: <ExclamationCircleOutlined />,
};

export const MENTORSHIP_FINISH_REASONS = {
  SUCCESSFULLY_COMPLETED: 1,
  TIME_LIMITATIONS_BY_MENTOR: 2,
  TIME_LIMITATIONS_BY_MENTEE: 3,
  WRONG_MATCH: 4,
  NO_RESPONSE: 5,
  MENTOR_DID_NOT_SHOW_UP: 6,
  MENTEE_DID_NOT_SHOW_UP: 7,
  COMMUNITY_RULES_VIOLATION: 8,
};
