import { ENVIRONMENT } from '@shared/config';
import {
  FACTORY_WAREHOUSE_TYPE,
  GETIR_10_DOMAIN_TYPE,
  GETIR_FINANCE_DOMAIN_TYPE,
  GETIR_FOOD_DOMAIN_TYPE,
  GETIR_GORILLAS_DOMAIN_TYPE,
  GETIR_LOCALS_DOMAIN_TYPE,
  GETIR_MARKET_DOMAIN_TYPE,
  GETIR_N11_DOMAIN_TYPE,
  GETIR_VOYAGER_DOMAIN_TYPE,
  HUB_WAREHOUSE_TYPE,
  MAIN_WAREHOUSE_TYPE,
  NONAGREEMENT_WAREHOUSE_TYPE,
  OTHER_WAREHOUSE_TYPE,
  REGULAR_WAREHOUSE_TYPE,
  SC_GROCER_WAREHOUSE_TYPE,
  STORE_CONVERSION_WAREHOUSE_TYPE,
  SUPPLY_CHAIN_OPERATIONS_WAREHOUSE_TYPE,
  VEHICLE_PARK_WAREHOUSE_TYPE,
  VIRTUAL_WAREHOUSE_TYPE,
} from '@shared/shared/constants';

export const GETIR_WAREHOUSE_DOMAIN_TYPE_CODES = [
  GETIR_10_DOMAIN_TYPE,
  GETIR_FOOD_DOMAIN_TYPE,
  GETIR_MARKET_DOMAIN_TYPE,
  GETIR_VOYAGER_DOMAIN_TYPE,
  GETIR_LOCALS_DOMAIN_TYPE,
  GETIR_FINANCE_DOMAIN_TYPE,
  GETIR_N11_DOMAIN_TYPE,
  GETIR_GORILLAS_DOMAIN_TYPE,
];

export const SAP_NON_REQUIRED_WAREHOUSE_TYPES = [
  VIRTUAL_WAREHOUSE_TYPE,
  SC_GROCER_WAREHOUSE_TYPE,
  FACTORY_WAREHOUSE_TYPE,
  SUPPLY_CHAIN_OPERATIONS_WAREHOUSE_TYPE,
  VEHICLE_PARK_WAREHOUSE_TYPE,
  STORE_CONVERSION_WAREHOUSE_TYPE,
  NONAGREEMENT_WAREHOUSE_TYPE,
  OTHER_WAREHOUSE_TYPE,
];

export const SAP_REQUIRED_WAREHOUSE_TYPES = [
  MAIN_WAREHOUSE_TYPE,
  REGULAR_WAREHOUSE_TYPE,
  HUB_WAREHOUSE_TYPE,
];

export const isDevUrl = ENVIRONMENT.ENV !== 'production' || process.env.NODE_ENV !== 'production';
