import { createUseStyles } from 'react-jss';

export default createUseStyles(() => {
  return {
    titleImage: {
      width: '15px',
      height: '15px',
    },
    indexFilterContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: '10px',
    },
    flexBadge: { display: 'flex' },
    noneBadge: { display: 'none' },
    tableRowContainer: { alignItems: 'center', justifyContent: 'center' },
    categoryFilter: { marginRight: '10px' },
    tableRowContainerFilter: {
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    tableCol: { marginTop: '30px' },
    tableContainer: { margin: '20px' },
    tooltipTitle: { width: '150px' },
    tooltipImage: { width: '25px' },
    tooltipImageSec: { maxWidth: '40px' },
    matchedSpan: {
      fontWeight: 'bolder',
      textAlign: 'center',
      color: '#ab47bc',
    },
    downArrowRow: {
      marginTop: 'auto',
      marginBottom: 'auto',
      marginRight: '6px',
      minWidth: '15px',
    },
    priceIndexRow: {
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
    },
    priceIndexCol: {
      marginTop: 'auto',
      marginBottom: 'auto',
      marginLeft: '4px',
    },
    priceIndexImage: { height: '20px' },
    selectWidth: { width: '150px', fontSize: '14px' },
    selectWidthOther: { width: '200px' },
    selectCompetitor: { width: '150px' },
    selectCompetitorImage: { width: '20px' },
    renderDivider: { margin: '4px 0' },
    renderContainer: {
      display: 'flex',
      flexWrap: 'nowrap',
      padding: 8,
    },
    actionTreeCancel: {
      height: '20px',
      maxWidth: '20px',
    },
    actionTreeSubmit: {
      height: '20px',
      maxWidth: '20px',
      marginRight: '5px',
    },
    demoOptionLabelItem: { width: '140px', fontSize: '14px' },
    competitionInformation: {
      fontSize: '15px !important',
      marginTop: '30px',
      fontWeight: 'bolder',
      textAlign: 'center',
      paddingRight: '100px',
      paddingLeft: '100px',
      paddingBottom: '200px',
    },
    colChildrenContent: {
      display: 'flex',
      justifyContent: 'space-around',
      whiteSpace: 'nowrap',
    },
    colChildrenImageContainer: { flex: 1 },
    rowChildrenContainer: {
      justifyContent: 'space-around',
      alignItems: 'center',
      flexFlow: 'row',
      minWidth: '50px',
    },
    colChildrenContainer: {
      flex: 3,
      alignItems: 'center',
      minWidth: '50px',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'space-around',
      flexFlow: 'unset',
    },
    rowChildrenContent: {
      display: 'flex',
      justifyContent: 'space-around',
      whiteSpace: 'nowrap',
      minWidth: '75%',
    },
    rowTitle: {
      justifyContent: 'space-around',
      alignItems: 'center',
      flexFlow: 'row',
      minWidth: '50px',
    },
    rowInfoWrapper: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'space-around',
      flexFlow: 'unset',
      minWidth: '50px',
    },
    divider: {
      marginTop: '8px',
      marginBottom: '8px',
    },
    rowChildrenImage: { maxHeight: '50px', maxWidth: '50px' },
    downButton: { width: '15px', height: '15px' },
    indexDiv: { textAlign: 'center' },
    discountedPriceDiv: { fontSize: '8px', color: 'grey' },
    selectTitle: {
      width: '150px',
      fontWeight: 600,
      whiteSpace: 'nowrap',
      marginBottom: '6px',
    },
    selectTitleImage: {
      width: '15px',
      height: '15px',
    },
    tableCategoryRow: {
      justifyContent: 'space-between',
      paddingTop: '4px',
      paddingBottom: '4px',
    },
    centerItems: { alignItems: 'center', display: 'flex' },
    highDiv: {
      fontWeight: 'bold',
      textAlign: 'center',
      color: 'black',
    },
    veryHighDiv: {
      fontWeight: 'bolder',
      textAlign: 'center',
      color: '#1b5e20',
    },
    barCodeDiv: {
      fontWeight: 'bolder',
      textAlign: 'center',
      color: '#0d47a1',
    },
    labeledDiv: {
      fontWeight: 'bolder',
      textAlign: 'center',
      color: '#ab47bc',
    },
    bolderDiv: {
      fontWeight: 'bolder',
      whiteSpace: 'nowrap',
      marginLeft: 'auto',
      marginRight: 'auto',
      width: 'min-content',
    },
    overallDiv: {
      fontWeight: 'bold',
      textAlign: 'left',
      color: 'black',
    },
    filterContainer: { maxWidth: 'fit-content !important', marginLeft: '10px' },
    exclamationCircle: { fontSize: '11px' },
    outdatedFilter: {
      flex: 'unset',
      marginRight: '8px',
      marginLeft: '8px',
      display: 'flex',
    },
    exludeFilter: {
      flex: 'unset',
      marginRight: '8px',
      marginLeft: '8px',
      display: 'flex',
      width: '100%',
      justifyContent: 'flex-end',
    },
    lastCrawlDate: {
      fontSize: '10px',
      color: 'red',
      justifyContent: 'space-around',
      alignItems: 'center',
      flexFlow: 'row',
      minWidth: '50px',
    },
    excelExport: { display: 'flex', alignItems: 'center' },
    excludeOutdatedProducts: {
      display: 'flex',
      flexDirection: 'column',
    },
    outdatedSwitch: { width: '40px' },
  };
});
