import { createUseStyles } from 'react-jss';

import { borderRadius, colors, fontSizes, fontWeights, transitions } from '@app/pages/CommerceIntelligence/styleVariables';
import { placeholder, primary } from '@shared/components/GUI/styles/guiThemes';

export const useStyles = createUseStyles({
  floatingLabelContainer: {
    position: 'relative',
    display: 'flex',
    width: '100%',
    marginBottom: 0,
    '& .flabel': {
      color: colors.textLight,
      position: 'absolute',
      fontSize: fontSizes.sm,
      fontWeight: fontWeights.regular,
      lineHeight: '16px',
      transform: 'translate(0, 0)',
      transformOrigin: 'top left',
      transition: transitions.default,
      left: '12px',
      top: '50%',
      marginTop: '-8px',
      zIndex: 1,
      pointerEvents: 'none',
    },
    '& input:not([value=""]) + .flabel': {
      color: colors.purple,
      transform: 'translate(0, 0)',
      fontSize: fontSizes.xs,
      top: '6px',
      marginTop: '0',
      zIndex: 1,
      pointerEvents: 'none',
    },
    '& .ant-select:has(.ant-select-selection-search-input:focus) + .flabel': {
      color: colors.purple,
      transform: 'translate(0, 0)',
      fontSize: fontSizes.xs,
      top: '6px',
      marginTop: '0',
      zIndex: 1,
      pointerEvents: 'none',
    },
    '& .ant-select:has(.ant-select-selection-item) + .flabel': {
      color: colors.purple,
      transform: 'translate(0, 0)',
      fontSize: fontSizes.xs,
      top: '6px',
      marginTop: '0',
      zIndex: 1,
      pointerEvents: 'none',
    },
    '& .ant-select-selector': {
      '&:hover': { borderColor: `${colors.purple} !important` },
      '&.ant-select-open': { borderColor: `${colors.purple} !important` },
    },
    '& .ant-select-open .ant-select-selector': { borderColor: `${colors.purple} !important` },
    '& .ant-select-focused:not(.ant-select-disabled).ant-select:not(.ant-select-customize-input) .ant-select-selector': {
      borderColor: `${colors.borderGray} !important`,
      boxShadow: 'none !important',
    },
    '& input:focus + .flabel': {
      color: colors.purple,
      transform: 'translate(0, 0)',
      fontSize: fontSizes.xs,
      top: '6px',
      marginTop: '0',
    },
    '& .ant-select-clear': {
      opacity: '0',
      visibility: 'hidden',
      position: 'absolute',
      right: '32px',
      top: '50%',
      transform: 'translateY(-50%)',
      zIndex: 2,
      cursor: 'pointer',
      transition: transitions.default,
    },
    '& .ant-select:hover .ant-select-clear': {
      opacity: '1',
      visibility: 'visible',
    },
    '& .search-input': {
      paddingTop: '16px',
      height: '48px !important',
      '& + .flabel': {
        top: '6px',
        marginTop: '0',
        fontSize: fontSizes.xs,
      },
    },
    '& .ant-select': { width: '100% !important' },
    '& .ant-select:not(.ant-select-multiple) .ant-select-selector': {
      height: '48px !important',
      borderRadius: borderRadius.md,
      display: 'flex !important',
      alignItems: 'center !important',
      transition: transitions.default,
      border: `1px solid ${colors.borderGray} !important`,
      '&:hover': { borderColor: `${colors.purple} !important` },
      paddingTop: '12px !important',
    },
    '& .ant-select.ant-select-open:not(.ant-select-disabled):not(.ant-select-customize-input) .ant-select-selector': {
      borderColor: `${colors.purple} !important`,
      boxShadow: `0 0 0 2px ${colors.lightPurple} !important`,
    },
    '& .ant-select-focused:not(.ant-select-open):not(.ant-select-disabled) .ant-select-selector': {
      borderColor: `${colors.borderGray} !important`,
      boxShadow: 'none !important',
    },
    '& .ant-select-selection-search': {
      flex: 'none',
      width: 'auto',
      maxWidth: '100%',
      alignSelf: 'center',
      margin: '0 0 0 6px',
      height: '18px',
      lineHeight: '18px',
      order: 999,
    },
    '& .ant-select-selection-search-input': { height: '24px' },
    '& .ant-select:not(.ant-select-multiple) .ant-select-selection-item': {
      display: 'flex !important',
      alignItems: 'center !important',
      lineHeight: '20px !important',
      marginTop: '0 !important',
      paddingTop: '0 !important',
    },
    '& .ant-select-arrow': {
      top: '50%',
      right: '11px',
      width: '12px',
      height: '12px',
      marginTop: '-6px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    '& .ant-select-dropdown': {
      padding: '12px 12px 48px 12px',
      borderRadius: borderRadius.md,
      top: 'calc(100% + 4px)',
      position: 'absolute',
      boxShadow: `0 6px 16px 0 ${colors.boxShadowLight}`,
      border: `1px solid ${colors.borderGray}`,
      backgroundColor: colors.backgroundWhite,
      maxHeight: 'none !important',
      overflow: 'visible !important',
      '& .ant-select-dropdown-menu': {
        maxHeight: 'none !important',
        overflow: 'visible !important',
      },
      '& .rc-virtual-list': {
        maxHeight: 'none !important',
        overflow: 'visible !important',
      },
      '& .rc-virtual-list-holder': {
        maxHeight: 'none !important',
        overflowY: 'auto !important',
        overflow: 'visible !important',
        paddingBottom: '24px !important',
        '& .rc-virtual-list-holder': { overflowY: 'auto !important' },
      },
      '& .ant-select-item-option-content': {
        whiteSpace: 'normal',
        fontSize: fontSizes.xs,
        lineHeight: '16px',
        color: colors.inputBlack,
        fontWeight: fontWeights.semibold,
      },
    },
    '& .ant-select-dropdown .ant-checkbox-inner': { borderRadius: borderRadius.xs },
    '& .ant-select-item': {
      borderRadius: '4px',
      padding: '8px 12px',
      margin: '0',
      transition: transitions.default,
      minHeight: '42px',
      border: `1px solid ${colors.backgroundWhite}`,
      '&:first-child': { borderTop: 'none' },
      '&:last-child': { borderBottom: 'none' },
      '&-option-selected': {
        backgroundColor: colors.backgroundImage,
        color: colors.purple,
        fontWeight: fontWeights.medium,
      },
      '&-option-active': {
        backgroundColor: colors.lightPurple,
        color: colors.purple,
      },
      '&-option-selected:not(.ant-select-item-option-disabled)': { color: colors.purple },
    },
    '& .ant-select-dropdown .ant-select-item-option': {
      borderRadius: '4px',
      margin: '0',
    },
    '& .ant-select-multiple': {
      '& .ant-select-selector': {
        display: 'flex',
        alignItems: 'center',
        flexWrap: 'nowrap',
        overflow: 'hidden',
        height: '48px',
        minHeight: '48px',
        maxHeight: '48px',
        borderRadius: borderRadius.md,
        transition: transitions.default,
        border: `1px solid ${colors.borderGray}`,
        '&:hover': { borderColor: colors.purple },
        paddingTop: '26px',
        paddingBottom: '4px',
        paddingRight: '32px',
        paddingLeft: '12px',
        '&::-webkit-scrollbar': { display: 'none' },
        '-ms-overflow-style': 'none',
        'scrollbar-width': 'none',
      },
      '& .ant-select-focused .ant-select-selector': { paddingTop: '26px' },
      '& .ant-select-selection-overflow': {
        display: 'flex',
        flexWrap: 'nowrap',
        alignItems: 'center',
        overflow: 'hidden',
        width: 'auto',
        gap: '3px',
        marginTop: '0',
        color: colors.inputBlack,
      },
      '& .ant-select-selection-overflow-item': {
        flex: 'none',
        maxWidth: '100%',
        alignSelf: 'baseline',
      },
      '& .ant-select-selection-overflow-item-rest': {
        display: 'inline-flex !important',
        alignItems: 'center !important',
        alignSelf: 'center !important',
        height: '18px !important',
        lineHeight: '16px !important',
      },
      '& .ant-select-selection-search': {
        flex: 'none',
        width: 'auto',
        maxWidth: '100%',
        alignSelf: 'center',
        margin: '0',
        height: '18px',
        lineHeight: '18px',
      },
      '& .ant-select-selection-search-input': { marginLeft: '12px !important' },
      '& .ant-select-selection-item': {
        height: '18px',
        lineHeight: '16px',
        margin: '0',
        padding: '0 5px',
        background: colors.inputGray,
        borderRadius: borderRadius.sm,
        border: 'none',
        fontSize: fontSizes.xs,
        fontWeight: fontWeights.semibold,
        color: colors.inputBlack,
        whiteSpace: 'nowrap',
        textOverflow: 'ellipsis',
        overflow: 'hidden',
        display: 'inline-flex',
        alignItems: 'center',
        transition: transitions.default,
        '&:hover': { background: colors.lightPurple },
      },
      '& .ant-select-selection-item-content': {
        fontSize: fontSizes.xs,
        lineHeight: '16px',
        fontWeight: fontWeights.semibold,
        color: `${colors.inputBlack} !important`,
      },
      '& .ant-select-selection-item-remove': {
        color: colors.inputBlack,
        opacity: 1,
        fontSize: '9px',
        marginLeft: '3px',
        height: '18px',
        lineHeight: '16px',
        transition: 'opacity 0.2s ease',
        display: 'flex',
        alignItems: 'center',
        '&:hover': { opacity: 0.8 },
        '& img': {
          width: '12px',
          height: '12px',
        },
      },
      '& .ant-select-selection-placeholder': {
        padding: '0',
        lineHeight: '48px',
        fontSize: '14px',
        display: 'flex',
        alignItems: 'center',
        order: 1000,
      },
    },
    '& .ant-input': {
      '&:hover': { borderColor: `${colors.purple} !important` },
      '&:focus': {
        borderColor: `${colors.purple} !important`,
        boxShadow: `0 0 0 2px ${colors.lightPurple} !important`,
      },
    },
    '& .ant-input-affix-wrapper': {
      height: '48px !important',
      lineHeight: '48px !important',
      borderRadius: '8px !important',
    },
    '& .ant-input-prefix': { marginRight: '12px' },
    '& .ant-select-item-option': {
      borderRadius: '4px !important',
      background: `${colors.backgroundImage} !important`,
      margin: '2px 4px !important',
      overflow: 'hidden',
    },
    '& .ant-select-item-option-content .ant-checkbox-wrapper': { display: 'flex !important', alignItems: 'center' },
    '& .ant-select-selection-item-content .ant-checkbox-wrapper': { display: 'none !important' },
    '& .ant-checkbox-inner': { borderRadius: '4px' },
    '& .ant-select-item-option .ant-checkbox': { display: 'none !important' },
  },
  error: { '& .flabel': { color: colors.errorRed } },
  icon: {
    position: 'absolute',
    right: '11px',
    top: '50%',
    transform: 'translateY(-50%)',
    pointerEvents: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '12px',
    height: '12px',
    color: primary,
    zIndex: 2,
    fontWeight: 800,
  },
  searchInputContainer: {
    '& .flabel': {
      left: '40px',
      zIndex: 1,
      pointerEvents: 'none',
    },
    '& .ant-input': {
      paddingTop: '4px',
      color: colors.inputBlack,
      '& + .flabel': {
        top: '50%',
        marginTop: '-8px',
        fontSize: '14px',
        color: placeholder,
        transform: 'translate(0, 0)',
        zIndex: 1,
        pointerEvents: 'none',
      },
    },
    '& .ant-input-affix-wrapper': {
      '& + .flabel': {
        top: '50%',
        marginTop: '-8px',
        fontSize: '14px',
        color: placeholder,
        transform: 'translate(0, 0)',
        zIndex: 1,
        pointerEvents: 'none',
      },
    },
    [
    `& .ant-input-affix-wrapper:has(input:not([value=""])) + .flabel,
      & .ant-input-affix-wrapper:has(input:focus) + .flabel`]: {
      top: '6px',
      marginTop: '0',
      fontSize: '12px',
      color: primary,
      transform: 'translate(0, 0)',
      zIndex: 1,
      pointerEvents: 'none',
    },
    '& input:not([value=""]), & input:focus': { paddingTop: '20px' },
    '& .ant-input-prefix': {
      marginLeft: '2px',
      marginRight: '10px',
      color: primary,
    },
  },
  optionWithCheckbox: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    width: '100%',
    padding: '2px 0',
    '& .ant-checkbox-wrapper': { marginRight: '8px' },
    '& .ant-checkbox': { marginRight: 0 },
  },
  optionLabel: {
    flex: 1,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  dropdownMenuWithScrollbar: {
    overflowY: 'auto',
    '&::-webkit-scrollbar': { width: 8, background: 'transparent' },
    '&::-webkit-scrollbar-thumb': { background: colors.purple, borderRadius: 8, minHeight: 24 },
    '&:hover::-webkit-scrollbar-thumb, &:focus::-webkit-scrollbar-thumb': { background: colors.purple },
    scrollbarColor: `${colors.purple} transparent`,
    scrollbarWidth: 'thin',
    '& .rc-virtual-list-holder': {
      overflowY: 'visible !important',
      maxHeight: 'none !important',
    },
    '& .ant-select-item': {
      borderRadius: borderRadius.md,
      margin: '0',
      padding: '8px',
      border: `1px solid ${colors.backgroundWhite}`,
      '&:first-child': { borderTop: 'none' },
      '&:last-child': { borderBottom: 'none' },
    },
    '& .ant-spin': {
      display: 'flex',
      justifyContent: 'center',
      padding: '12px 0',
    },
  },
  clearSelectionsRow: {
    display: 'flex',
    alignItems: 'center',
    padding: '8px 12px 4px 12px',
    borderBottom: `1px solid ${colors.borderGray}`,
    justifyContent: 'flex-start',
    color: colors.textDark,
    fontWeight: 600,
    fontSize: 14,
    background: colors.backgroundImage,
  },
  clearIconCircle: {
    width: 22,
    height: 22,
    borderRadius: '50%',
    background: colors.lightGray,
    color: colors.iconGray,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
    fontSize: 14,
  },
  rcVirtualListHolder: { overflowY: 'visible !important' },
  clearSelectionsButton: {
    background: 'none',
    border: 'none',
    color: colors.inputBlack,
    fontWeight: fontWeights.semibold,
    fontSize: fontSizes.xs,
    cursor: 'pointer',
    outline: 'none',
    padding: 0,
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  clearSelectionsHeader: {
    display: 'flex',
    alignItems: 'center',
    padding: '8px 12px 4px 12px',
    borderBottom: `1px solid ${colors.borderGray}`,
    justifyContent: 'space-between',
    margin: '2px 4px',
  },
  closeIconCircle: {
    width: '16px',
    height: '16px',
  },
  closeIcon: {
    width: '8px',
    height: '8px',
  },
  optionContent: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 8,
    '& .optionText': { paddingBottom: '2px' },
    '.ant-select-item-option-selected:not(.ant-select-item-option-disabled) &': { color: colors.purple },
  },
  optionCheckbox: {
    '& .ant-checkbox-inner': { borderRadius: '4px', height: '18px', width: '18px' },
    '& .ant-checkbox-wrapper:hover .ant-checkbox-inner': { border: `1px solid ${colors.checkboxBorder}` },
    '& .ant-checkbox-checked::after': { borderRadius: borderRadius.xs },
  },
  optionText: {
    flex: 1,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    color: colors.inputBlack,
    fontWeight: fontWeights.semibold,
    '.ant-select-item-option-selected:not(.ant-select-item-option-disabled) &': { color: colors.purple },
  },
  arrowIconWrapper: {
    display: 'flex',
    alignItems: 'center',
    '&.isOpen': { transform: 'rotate(-180deg)' },
    transform: 'rotate(0deg)',
    transition: 'transform 0.3s ease',
  },
  arrowIcon: {
    width: '13px',
    height: '8px',
  },
  searchInput: { width: '100%' },
  antSelectItemOptionState: { display: 'none !important' },
  selectFullWidth: { width: '100%' },
  customMaxTagPlaceholder: {
    display: 'inline-flex',
    alignItems: 'center',
    height: '18px',
    lineHeight: '16px',
    margin: '0',
    padding: '0 5px',
    background: colors.inputGray,
    borderRadius: borderRadius.sm,
    fontSize: fontSizes.xs,
    fontWeight: fontWeights.semibold,
    color: colors.inputBlack,
    whiteSpace: 'nowrap',
  },
  '@global': {
    '.ant-select-item': {
      borderRadius: '4px',
      padding: '8px 12px',
      margin: '0',
      transition: 'all 0.2s',
      minHeight: '42px',
      border: `1px solid ${colors.backgroundWhite}`,
      '&:first-child': { borderTop: 'none' },
      '&:last-child': { borderBottom: 'none' },
      '&-option-selected': {
        backgroundColor: colors.backgroundImage,
        color: colors.purple,
        fontWeight: fontWeights.medium,
      },
      '&-option-active': {
        backgroundColor: colors.lightPurple,
        color: colors.purple,
      },
      '&-option-selected:not(.ant-select-item-option-disabled)': { color: colors.purple },
    },
    '.ant-select-item-option-selected': {
      backgroundColor: colors.backgroundImage,
      color: colors.purple,
      fontWeight: fontWeights.medium,
    },
    '.ant-select-item-option-active': {
      backgroundColor: colors.lightPurple,
      color: colors.purple,
    },
    '.ant-select-item-option-state': { display: 'none !important' },
    '.ant-select-dropdown .ant-spin': { display: 'flex', justifyContent: 'center', alignItems: 'center', padding: '12px 0' },
    '.ant-select-dropdown .rc-virtual-list': {
      scrollbarColor: `${colors.purple} transparent`,
      scrollbarWidth: 'thin',
      margin: '4px 4px 8px 4px',
      '& .rc-virtual-list-holder': { overflowY: 'auto !important' },
    },
    '.ant-select-dropdown .rc-virtual-list::-webkit-scrollbar': { width: 8, background: 'transparent' },
    '.ant-select-dropdown .rc-virtual-list::-webkit-scrollbar-thumb': { background: `${colors.purple} !important`, borderRadius: 8, minHeight: 24 },
    '.ant-select-dropdown .rc-virtual-list:hover::-webkit-scrollbar-thumb': { background: `${colors.purple} !important` },
    '.ant-select-dropdown .rc-virtual-list:focus::-webkit-scrollbar-thumb': { background: `${colors.purple} !important` },
    '.rc-virtual-list-scrollbar-thumb': { background: 'transparent !important' },
  },
  '& .ant-select .ant-select-selector': { '&:hover, &.ant-select-open': { borderColor: `${colors.purple} !important` } },
  '& .ant-select-open .ant-select-selector': { borderColor: `${colors.purple} !important` },
});
