export const COURIER_PLAN_TYPE_KEYS = {
  STANDARD: 'STANDARD',
  SCHEDULED: 'SCHEDULED',
  SLOT_CAPACITY: 'SLOT_CAPACITY',
};

export const EMPLOYEE_TYPE = {
  COURIER: 'COURIER',
  STORE_ASSISTANT: 'STORE_ASSISTANT',
};
