export const COUNTRIES = {
  bd: { en: 'Bangladesh', tr: 'Bangladeş' },
  be: { en: 'Belgium', tr: 'Belçika' },
  bf: { en: 'Burkina Faso', tr: 'Burkina Faso' },
  bg: { en: 'Bulgaria', tr: 'Bulgaristan' },
  ba: { en: 'Bosnia and Herzegovina', tr: 'Bosna Hersek' },
  bb: { en: 'Barbados', tr: 'Barbados' },
  wf: { en: 'Wallis and Futuna', tr: 'Wallis ve Futuna' },
  bl: { en: 'Saint Barthelemy', tr: 'Aziz Barthelemy' },
  bm: { en: 'Bermuda', tr: 'Bermuda' },
  bn: { en: 'Brunei', tr: 'Brunei' },
  bo: { en: 'Bolivia', tr: 'Bolivya' },
  bh: { en: 'Bahrain', tr: 'Bahreyn' },
  bi: { en: 'Burundi', tr: 'Burundi' },
  bj: { en: 'Benin', tr: 'Benin' },
  bt: { en: 'Bhutan', tr: 'Butan' },
  jm: { en: 'Jamaica', tr: 'Jamaika' },
  bv: { en: 'Bouvet Island', tr: 'Bouvet Adası' },
  bw: { en: 'Botswana', tr: 'Botsvana' },
  ws: { en: 'Samoa', tr: 'Samoa' },
  bq: { en: 'Bonaire, Saint Eustatius and Saba ', tr: 'Bonaire, Aziz Eustatius ve Saba' },
  br: { en: 'Brazil', tr: 'Brezilya' },
  bs: { en: 'Bahamas', tr: 'Bahamalar' },
  je: { en: 'Jersey', tr: 'Jersey' },
  by: { en: 'Belarus', tr: 'Belarus' },
  bz: { en: 'Belize', tr: 'Belize' },
  ru: { en: 'Russia', tr: 'Rusya' },
  rw: { en: 'Rwanda', tr: 'Ruanda' },
  rs: { en: 'Serbia', tr: 'Sırbistan' },
  tl: { en: 'East Timor', tr: 'Doğu Timor' },
  re: { en: 'Reunion', tr: 'Reunion' },
  tm: { en: 'Turkmenistan', tr: 'Türkmenistan' },
  tj: { en: 'Tajikistan', tr: 'Tacikistan' },
  ro: { en: 'Romania', tr: 'Romanya' },
  tk: { en: 'Tokelau', tr: 'Tokelau' },
  gw: { en: 'Guinea-Bissau', tr: 'Gine-Bissau' },
  gu: { en: 'Guam', tr: 'Guam' },
  gt: { en: 'Guatemala', tr: 'Guatemala' },
  gs: { en: 'South Georgia and the South Sandwich Islands', tr: 'Güney Georgia ve Güney Sandviç Adaları' },
  gr: { en: 'Greece', tr: 'Yunanistan' },
  gq: { en: 'Equatorial Guinea', tr: 'Ekvator Ginesi' },
  gp: { en: 'Guadeloupe', tr: 'Guadelupe' },
  jp: { en: 'Japan', tr: 'Japonya' },
  gy: { en: 'Guyana', tr: 'Guyana' },
  gg: { en: 'Guernsey', tr: 'Guernsey' },
  gf: { en: 'French Guiana', tr: 'Fransız Guyanası' },
  ge: { en: 'Georgia', tr: 'Gürcistan' },
  gd: { en: 'Grenada', tr: 'Grenada' },
  gb: { en: 'United Kingdom', tr: 'Birleşik Krallık' },
  ga: { en: 'Gabon', tr: 'Gabon' },
  sv: { en: 'El Salvador', tr: 'El Salvador' },
  gn: { en: 'Guinea', tr: 'Gine' },
  gm: { en: 'Gambia', tr: 'Gambiya' },
  gl: { en: 'Greenland', tr: 'Grönland' },
  gi: { en: 'Gibraltar', tr: 'Cebelitarık' },
  gh: { en: 'Ghana', tr: 'Gana' },
  om: { en: 'Oman', tr: 'Umman' },
  tn: { en: 'Tunisia', tr: 'Tunus' },
  jo: { en: 'Jordan', tr: 'Ürdün' },
  hr: { en: 'Croatia', tr: 'Hırvatistan' },
  ht: { en: 'Haiti', tr: 'Haiti' },
  hu: { en: 'Hungary', tr: 'Macaristan' },
  hk: { en: 'Hong Kong', tr: 'Hong Kong' },
  hn: { en: 'Honduras', tr: 'Honduras' },
  hm: { en: 'Heard Island and McDonald Islands', tr: 'Heard Adası ve McDonald Adaları' },
  ve: { en: 'Venezuela', tr: 'Venezuela' },
  pr: { en: 'Puerto Rico', tr: 'Porto Riko' },
  ps: { en: 'Palestinian Territory', tr: 'Filistin Bölgesi' },
  pw: { en: 'Palau', tr: 'Pala' },
  pt: { en: 'Portugal', tr: 'Portekiz' },
  sj: { en: 'Svalbard and Jan Mayen', tr: 'Svalbard ve Jan Mayen' },
  py: { en: 'Paraguay', tr: 'Paraguay' },
  iq: { en: 'Iraq', tr: 'Irak' },
  pa: { en: 'Panama', tr: 'Panama' },
  pf: { en: 'French Polynesia', tr: 'Fransız Polinezyası' },
  pg: { en: 'Papua New Guinea', tr: 'Papua Yeni Gine' },
  pe: { en: 'Peru', tr: 'Peru' },
  pk: { en: 'Pakistan', tr: 'Pakistan' },
  ph: { en: 'Philippines', tr: 'Filipinler' },
  pn: { en: 'Pitcairn', tr: 'Pitcairn' },
  pl: { en: 'Poland', tr: 'Polonya' },
  pm: { en: 'Saint Pierre and Miquelon', tr: 'Saint Pierre ve Miquelon' },
  zm: { en: 'Zambia', tr: 'Zambiya' },
  eh: { en: 'Western Sahara', tr: 'Batı Sahra' },
  ee: { en: 'Estonia', tr: 'Estonya' },
  eg: { en: 'Egypt', tr: 'Mısır' },
  za: { en: 'South Africa', tr: 'Güney Afrika' },
  ec: { en: 'Ecuador', tr: 'Ekvador' },
  it: { en: 'Italy', tr: 'İtalya' },
  vn: { en: 'Vietnam', tr: 'Vietnam' },
  sb: { en: 'Solomon Islands', tr: 'Solomon Adaları' },
  et: { en: 'Ethiopia', tr: 'Etiyopya' },
  so: { en: 'Somalia', tr: 'Somali' },
  zw: { en: 'Zimbabwe', tr: 'Zimbabve' },
  sa: { en: 'Saudi Arabia', tr: 'Suudi Arabistan' },
  es: { en: 'Spain', tr: 'İspanya' },
  er: { en: 'Eritrea', tr: 'Eritre' },
  me: { en: 'Montenegro', tr: 'Karadağ' },
  md: { en: 'Moldova', tr: 'Moldova' },
  mg: { en: 'Madagascar', tr: 'Madagaskar' },
  mf: { en: 'Saint Martin', tr: 'Aziz Martin' },
  ma: { en: 'Morocco', tr: 'Fas' },
  mc: { en: 'Monaco', tr: 'Monako' },
  uz: { en: 'Uzbekistan', tr: 'Özbekistan' },
  mm: { en: 'Myanmar', tr: 'Myanmar' },
  ml: { en: 'Mali', tr: 'Mali' },
  mo: { en: 'Macao', tr: 'Makao' },
  mn: { en: 'Mongolia', tr: 'Moğolistan' },
  mh: { en: 'Marshall Islands', tr: 'Marşal Adaları' },
  mk: { en: 'Macedonia', tr: 'Makedonya' },
  mu: { en: 'Mauritius', tr: 'Mauritius' },
  mt: { en: 'Malta', tr: 'Malta' },
  mw: { en: 'Malawi', tr: 'Malawi' },
  mv: { en: 'Maldives', tr: 'Maldivler' },
  mq: { en: 'Martinique', tr: 'Martinik' },
  mp: { en: 'Northern Mariana Islands', tr: 'Kuzey Mariana Adaları' },
  ms: { en: 'Montserrat', tr: 'Montserrat' },
  mr: { en: 'Mauritania', tr: 'Moritanya' },
  im: { en: 'Isle of Man', tr: 'Man Adası' },
  ug: { en: 'Uganda', tr: 'Uganda' },
  tz: { en: 'Tanzania', tr: 'Tanzanya' },
  my: { en: 'Malaysia', tr: 'Malezya' },
  mx: { en: 'Mexico', tr: 'Meksika' },
  il: { en: 'Israel', tr: 'İsrail' },
  fr: { en: 'France', tr: 'Fransa' },
  io: { en: 'British Indian Ocean Territory', tr: 'Britanya Hint Okyanusu Bölgesi' },
  sh: { en: 'Saint Helena', tr: 'Aziz Helena' },
  fi: { en: 'Finland', tr: 'Finlandiya' },
  fj: { en: 'Fiji', tr: 'Fiji' },
  fk: { en: 'Falkland Islands', tr: 'Falkland adaları' },
  fm: { en: 'Micronesia', tr: 'Mikronezya' },
  fo: { en: 'Faroe Islands', tr: 'Faroe Adaları' },
  ni: { en: 'Nicaragua', tr: 'Nikaragua' },
  nl: { en: 'Netherlands', tr: 'Hollanda' },
  no: { en: 'Norway', tr: 'Norveç' },
  na: { en: 'Namibia', tr: 'Namibya' },
  vu: { en: 'Vanuatu', tr: 'Vanuatu' },
  nc: { en: 'New Caledonia', tr: 'Yeni Kaledonya' },
  ne: { en: 'Niger', tr: 'Nijer' },
  nf: { en: 'Norfolk Island', tr: 'Norfolk Adası' },
  ng: { en: 'Nigeria', tr: 'Nijerya' },
  nz: { en: 'New Zealand', tr: 'Yeni Zelanda' },
  np: { en: 'Nepal', tr: 'Nepal' },
  nr: { en: 'Nauru', tr: 'Nauru' },
  nu: { en: 'Niue', tr: 'Niue' },
  ck: { en: 'Cook Islands', tr: 'Cook Adaları' },
  xk: { en: 'Kosovo', tr: 'Kosova' },
  ci: { en: 'Ivory Coast', tr: 'Fildişi Sahili' },
  ch: { en: 'Switzerland', tr: 'İsviçre' },
  co: { en: 'Colombia', tr: 'Kolombiya' },
  cn: { en: 'China', tr: 'Çin' },
  cm: { en: 'Cameroon', tr: 'Kamerun' },
  cl: { en: 'Chile', tr: 'Şili' },
  cc: { en: 'Cocos Islands', tr: 'Cocos Adaları' },
  ca: { en: 'Canada', tr: 'Kanada' },
  cg: { en: 'Republic of the Congo', tr: 'Kongo Cumhuriyeti' },
  cf: { en: 'Central African Republic', tr: 'Orta Afrika Cumhuriyeti' },
  cd: { en: 'Democratic Republic of the Congo', tr: 'Kongo Demokratik Cumhuriyeti' },
  cz: { en: 'Czech Republic', tr: 'Çek Cumhuriyeti' },
  cy: { en: 'Cyprus', tr: 'Kıbrıs' },
  cx: { en: 'Christmas Island', tr: 'Noel Adası' },
  cr: { en: 'Costa Rica', tr: 'Kosta Rika' },
  cw: { en: 'Curacao', tr: 'Curacao' },
  cv: { en: 'Cape Verde', tr: 'Yeşil Burun' },
  cu: { en: 'Cuba', tr: 'Küba' },
  sz: { en: 'Swaziland', tr: 'Svaziland' },
  sy: { en: 'Syria', tr: 'Suriye' },
  sx: { en: 'Sint Maarten', tr: 'Sint Maarten' },
  kg: { en: 'Kyrgyzstan', tr: 'Kırgızistan' },
  ke: { en: 'Kenya', tr: 'Kenya' },
  ss: { en: 'South Sudan', tr: 'Güney Sudan' },
  sr: { en: 'Suriname', tr: 'Surinam' },
  ki: { en: 'Kiribati', tr: 'Kiribati' },
  kh: { en: 'Cambodia', tr: 'Kamboçya' },
  kn: { en: 'Saint Kitts and Nevis', tr: 'Saint Kitts ve Nevis' },
  km: { en: 'Comoros', tr: 'Komor' },
  st: { en: 'Sao Tome and Principe', tr: 'Sao Tome ve Principe' },
  sk: { en: 'Slovakia', tr: 'Slovakya' },
  kr: { en: 'South Korea', tr: 'Güney Kore' },
  si: { en: 'Slovenia', tr: 'Slovenya' },
  kp: { en: 'North Korea', tr: 'Kuzey Kore' },
  kw: { en: 'Kuwait', tr: 'Kuveyt' },
  sn: { en: 'Senegal', tr: 'Senegal' },
  sm: { en: 'San Marino', tr: 'San Marino' },
  sl: { en: 'Sierra Leone', tr: 'Sierra Leone' },
  sc: { en: 'Seychelles', tr: 'Seyşeller' },
  kz: { en: 'Kazakhstan', tr: 'Kazakistan' },
  ky: { en: 'Cayman Islands', tr: 'Cayman Adaları' },
  sg: { en: 'Singapore', tr: 'Singapur' },
  se: { en: 'Sweden', tr: 'İsveç' },
  sd: { en: 'Sudan', tr: 'Sudan' },
  do: { en: 'Dominican Republic', tr: 'Dominik Cumhuriyeti' },
  dm: { en: 'Dominica', tr: 'Dominika' },
  dj: { en: 'Djibouti', tr: 'Cibuti' },
  dk: { en: 'Denmark', tr: 'Danimarka' },
  vg: { en: 'British Virgin Islands', tr: 'Britanya Virjin Adaları' },
  de: { en: 'Germany', tr: 'Almanya' },
  ye: { en: 'Yemen', tr: 'Yemen' },
  dz: { en: 'Algeria', tr: 'Cezayir' },
  us: { en: 'United States', tr: 'Amerika Birleşik Devletleri' },
  uy: { en: 'Uruguay', tr: 'Uruguay' },
  yt: { en: 'Mayotte', tr: 'Mayot' },
  um: { en: 'United States Minor Outlying Islands', tr: 'Amerika Birleşik Devletleri Küçük Dış Adaları' },
  lb: { en: 'Lebanon', tr: 'Lübnan' },
  lc: { en: 'Saint Lucia', tr: 'Aziz Lucia' },
  la: { en: 'Laos', tr: 'Laos' },
  tv: { en: 'Tuvalu', tr: 'Tuval' },
  tw: { en: 'Taiwan', tr: 'Tayvan' },
  tt: { en: 'Trinidad and Tobago', tr: 'Trinidad ve Tobago' },
  tr: { en: 'Turkey', tr: 'Türkiye' },
  lk: { en: 'Sri Lanka', tr: 'Sri Lanka' },
  li: { en: 'Liechtenstein', tr: 'Lihtenştayn' },
  lv: { en: 'Latvia', tr: 'Letonya' },
  to: { en: 'Tonga', tr: 'Tonga' },
  lt: { en: 'Lithuania', tr: 'Litvanya' },
  lu: { en: 'Luxembourg', tr: 'Lüksemburg' },
  lr: { en: 'Liberia', tr: 'Liberya' },
  ls: { en: 'Lesotho', tr: 'Lesoto' },
  th: { en: 'Thailand', tr: 'Tayland' },
  tf: { en: 'French Southern Territories', tr: 'Fransız Güney Toprakları' },
  tg: { en: 'Togo', tr: 'Togo' },
  td: { en: 'Chad', tr: 'Çad' },
  tc: { en: 'Turks and Caicos Islands', tr: 'Turks ve Caicos Adaları' },
  ly: { en: 'Libya', tr: 'Libya' },
  va: { en: 'Vatican', tr: 'Vatikan' },
  vc: { en: 'Saint Vincent and the Grenadines', tr: 'Saint Vincent ve Grenadinler' },
  ae: { en: 'United Arab Emirates', tr: 'Birleşik Arap Emirlikleri' },
  ad: { en: 'Andorra', tr: 'Andora' },
  ag: { en: 'Antigua and Barbuda', tr: 'Antigua ve Barbuda' },
  af: { en: 'Afghanistan', tr: 'Afganistan' },
  ai: { en: 'Anguilla', tr: 'Anguilla' },
  vi: { en: 'U.S. Virgin Islands', tr: 'Birleşmiş Devletler Virgin Adaları' },
  is: { en: 'Iceland', tr: 'İzlanda' },
  ir: { en: 'Iran', tr: 'İran' },
  am: { en: 'Armenia', tr: 'Ermenistan' },
  al: { en: 'Albania', tr: 'Arnavutluk' },
  ao: { en: 'Angola', tr: 'Angola' },
  aq: { en: 'Antarctica', tr: 'Antarktika' },
  as: { en: 'American Samoa', tr: 'Amerikan Samoası' },
  ar: { en: 'Argentina', tr: 'Arjantin' },
  au: { en: 'Australia', tr: 'Avustralya' },
  at: { en: 'Austria', tr: 'Avusturya' },
  aw: { en: 'Aruba', tr: 'Aruba' },
  in: { en: 'India', tr: 'Hindistan' },
  ax: { en: 'Aland Islands', tr: 'Aland Adaları' },
  az: { en: 'Azerbaijan', tr: 'Azerbaycan' },
  ie: { en: 'Ireland', tr: 'İrlanda' },
  id: { en: 'Indonesia', tr: 'Endonezya' },
  ua: { en: 'Ukraine', tr: 'Ukrayna' },
  qa: { en: 'Qatar', tr: 'Katar' },
  mz: { en: 'Mozambique', tr: 'Mozambik' },
};
