import { createUseStyles } from 'react-jss';

export default createUseStyles(() => {
  return {
    justifyContentStart: { justifyContent: 'flex-start' },
    justifyContentEnd: { justifyContent: 'flex-end' },
    boldCenterBlack: {
      fontWeight: 'bold',
      textAlign: 'center',
      color: 'black',
    },
    categorySelect: { width: '200px' },
    priceDiv: {
      margin: '0',
      width: '150px',
      fontWeight: 600,
    },
    discountedDiv: {
      margin: '0',
      width: '150px',
      fontWeight: 600,
    },
    widthHeightvh: {
      width: '15px',
      height: '15px',
    },
    setStruckPriceDiv: {
      margin: '0',
      width: '150px',
      fontWeight: 600,
    },
    subcategoryColumns: { marginTop: '20px' },
    excelExport: {
      position: 'absolute',
      right: '50px',
      top: '11px',
    },
    productSelect: { width: '270px' },
    productSelectImg: { width: '15px', height: '15px' },
    productNameSpan: {
      whiteSpace: 'pre-wrap',
      overflowWrap: 'break-word',
      cursor: 'pointer',
      display: 'flex',
      height: 'fit-content',
    },
    currentPriceImg: { width: '15px', height: '15px' },
    currentPriceDiv: { fontSize: '10px', color: 'grey' },
    productColumn: { fontSize: '10px' },
    downloadOutlined: { color: 'green', fontSize: '20px !important' },
    downArrowCol: { display: 'flex', alignItems: 'center' },
    columnDiv: { minWidth: '60px', whiteSpace: 'nowrap' },
    selectContainer: {
      minWidth: '600px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-evenly',
    },
    applyButton: {
      display: 'flex',
      justifyContent: 'center',
      marginTop: '10px',
    },
    productCardContainer: { display: 'flex', justifyContent: 'space-around' },
    productCardCol: { maxWidth: '60%' },
    productCardRow: { marginBottom: '5px' },
    productCardColItem: { maxWidth: '60%' },
    productCardTag: { maxHeight: '23px', minWidth: '100px', maxWidth: '40%' },
    productCardUl: { padding: '0px', paddingLeft: '20px' },
    productCardDivider: { margin: '5px 0' },
    producCardModal: {
      width: '50% !important',
      height: '1000px',
      '& .ant-modal-content': { height: 'auto', overflow: 'scroll' },
    },
    productCardName: {
      marginLeft: '5px',
      cursor: 'pointer',
      fontWeight: '600',
    },
    productCardProfile: {
      display: 'flex',
      alignItems: 'center',
    },
    productCardLink: { color: '#58666E' },
    priceIndexImage: { height: '20px' },
    priceIndexRow: {
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
    },
    competitorInfoBadge: { alignSelf: 'center', marginLeft: '10px' },
    matchedProductCardImg: { maxHeight: '120px' },
    productCardMatchedCol: {
      display: 'flex',
      flexFlow: 'wrap',
      justifyContent: 'space-around',
      width: '100%',
    },
    matchedProductCard: {
      width: '20%',
      marginLeft: '5px',
      height: 'auto',
      borderRadius: '30px',
      boxShadow: 'rgb(25 25 25 / 25%) 0px 0px 5px',
      margin: '15px',
      '& .ant-ribbon': { backgroundColor: '#5D3EBC !important' },
      '& .ant-card-cover': { minHeight: '120px !important' },
      '& .ant-image-mask': { minHeight: '120px !important' },
      '& .ant-card-body': {
        padding: '10px',
        display: 'flex',
        textAlign: 'center',
      },
      '& .ant-card-meta-title': {
        whiteSpace: 'normal !important',
        minHeight: '65px',
      },
      '& .ant-image': {
        display: 'flex',
        justifyContent: 'center',
        height: '100%',
        padding: '30px',
        maxHeight: '120px',
      },
    },
    downArrowCard: {
      justifyContent: 'flex-end',
      right: '-10px',
      alignSelf: 'center',
    },
    csvImporter: { '& .anticon-cloud-upload': { color: 'green', fontSize: '20px' } },
    csvImporterWrapper: {
      position: 'absolute',
      right: '90px !important',
      top: '11px',
    },
    indexDiv: { fontWeight: '600' },
    subcategoryPriceChange: { flexFlow: 'nowrap' },
    simulateButtonWrapper: { display: 'flex', alignSelf: 'center', position: 'absolute', right: '300px' },
    purpleGetirColor: {
      borderRadius: '8px',
      width: '130px',
      color: 'rgb(120, 73, 247) !important',
      fontWeight: '600',
      border: '1px solid rgb(180, 163, 227) !important',
      '&:hover': {
        color: 'rgb(255, 228, 48) !important',
        backgroundColor: 'rgb(120, 73, 247) !important',
        borderColor: 'rgb(180, 163, 227)',
        fontWeight: '800',
      },
    },
    clearButtonWrapper: { alignSelf: 'center', position: 'absolute', right: '150px' },
    simulationModal: {
      width: '600px !important',
      '& .ant-modal-content': { overflow: 'scroll' },
      '& .ant-modal-body': { textAlign: 'center' },
    },
    simulateCard: {
      width: '45%',
      marginLeft: '5px',
      height: 'auto',
      borderRadius: '30px',
      boxShadow: 'rgb(25 25 25 / 25%) 0px 0px 5px',
      margin: '15px',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      '& .ant-card-cover': { minHeight: '100px !important', width: '60%' },
      '& .ant-card-body': {
        padding: '10px',
        display: 'flex',
        textAlign: 'center',
        width: '80%',
        justifyContent: 'center',
      },
      '& .ant-card-meta': { width: '100%' },
      '& .ant-card-meta-title': {
        whiteSpace: 'normal !important',
        minHeight: '30px',
      },
      '& .ant-image': {
        display: 'flex',
        justifyContent: 'center',
        height: '100%',
        padding: '15px 30px',
        maxHeight: '100px',
      },
    },
    simulateRow: { justifyContent: 'space-evenly' },
    simulateArrow: { display: 'flex', flexDirection: 'column', alignSelf: 'center' },
    csvModal: { width: '550px' },
    indexDescriptionDivider: { width: '100%' },
    spin: { margin: '20px', padding: '30px 50px', textAlign: 'center' },
  };
});
