import { createActions } from 'reduxsauce';

import { REDUX_KEY } from '@shared/shared/constants';

export const { Types, Creators } = createActions(
  {
    getPromoByIdRequest: { id: null },
    getPromoByIdSuccess: { data: {} },
    getPromoByIdFailure: { error: null },
    getPromoBadgesRequest: { promoMechanic: null },
    getPromoBadgesSuccess: { data: {} },
    getPromoBadgesFailure: { error: null },
    updateClassificationRequest: { body: null },
    updateClassificationSuccess: { data: {} },
    updateClassificationFailure: { error: null },
    updatePromoSegmentTypesRequest: { id: null, body: null },
    updatePromoSegmentTypesSuccess: { data: {} },
    updatePromoSegmentTypesFailure: { error: null },
    updatePromoBadgeRequest: { id: null, body: null },
    updatePromoBadgeSuccess: { data: {} },
    updatePromoBadgeFailure: { error: null },
    updatePromoButtonActionRequest: { body: null },
    updatePromoButtonActionSuccess: { data: {} },
    updatePromoButtonActionFailure: { error: null },
    updateFinancialConditionRequest: { body: null },
    updateFinancialConditionSuccess: { data: {} },
    updateFinancialConditionFailure: { error: null },
    updateGeneralInfoRequest: { body: null },
    updateGeneralInfoSuccess: null,
    updateGeneralInfoFailure: null,
    updateClientSegmentRequest: { id: null, body: null },
    updateClientSegmentSuccess: { data: {} },
    updateClientSegmentFailure: { error: null },
    updateP3StatusRequest: { id: null, body: null },
    updateP3StatusSuccess: { data: {} },
    updateP3StatusFailure: { error: null },
    getP3DetailsRequest: { id: null },
    getP3DetailsSuccess: { data: {} },
    getP3DetailsFailure: { error: null },
    downloadP3SegmentClientsRequest: { id: null },
    downloadP3SegmentClientsSuccess: { data: {} },
    downloadP3SegmentClientsFailure: { error: null },
    generateP3SegmentRequest: {
      id: null,
      p3Objective: null,
      regenerate: null,
      ownProducts: null,
      targetedProducts: null,
      ownBrands: null,
      targetedBrands: null,
      subcategories: null,
    },
    generateP3SegmentSuccess: { data: {} },
    generateP3SegmentFailure: { error: null },
    deleteP3Request: { id: null },
    deleteP3Success: { data: {} },
    deleteP3Failure: { error: null },
    getResponsibleDepartmentsRequest: {},
    getResponsibleDepartmentsSuccess: { data: {} },
    getResponsibleDepartmentsFailure: { error: null },
    getArtisanVerticalsRequest: { },
    getArtisanVerticalsSuccess: { data: null },
    getArtisanVerticalsFailure: { error: null },
    updatePromoContentRequest: { id: null, body: null },
    updatePromoContentSuccess: { data: {} },
    updatePromoContentFailure: { error: null },
    getSegmentClientCountsRequest: { body: null },
    getSegmentClientCountsSuccess: { data: {} },
    getSegmentClientCountsFailure: { error: null },
    updatePromoHTMLRequest: { id: null, body: null },
    updatePromoHTMLSuccess: { data: {} },
    updatePromoHTMLFailure: { error: null },
    updateWorkingHoursRequest: { id: null, body: null },
    updateWorkingHoursSuccess: { data: {} },
    updateWorkingHoursFailure: { error: null },
    getMarketProductsRequest: { body: null },
    getMarketProductsSuccess: { data: {} },
    getMarketProductsFailure: { error: null },
    updateUserFilteringRequest: { id: null, body: null },
    updateUserFilteringSuccess: { data: {} },
    updateUserFilteringFailure: { error: null },
    getMarketProductsByIdsRequest: { productIds: null, fields: null },
    getMarketProductsByIdsSuccess: { data: {} },
    getMarketProductsByIdsFailure: { error: null },
    updateConditionProductsRequest: { body: null },
    updateConditionProductsSuccess: { data: {} },
    updateConditionProductsFailure: { error: null },
    updateExcludedProductsRequest: { body: null },
    updateExcludedProductsSuccess: { data: {} },
    updateExcludedProductsFailure: { error: null },
    updateBenefitTypeRequest: { body: null },
    updateBenefitTypeSuccess: { data: {} },
    updateBenefitTypeFailure: { error: null },
    updateBenefitSAPBulkRequest: { body: null },
    updateBenefitSAPBulkSuccess: { data: {} },
    updateBenefitSAPBulkFailure: { error: null },
    uploadPromoImageRequest: {
      loadedImage: null,
      contentType: null,
      imagePath: null,
      isAppliedToOtherLanguages: null,
    },
    uploadPromoImageSuccess: { data: {} },
    uploadPromoImageFailure: { error: null },
    getConditionalProductsRequest: { data: null },
    updateConditionalProductRequest: { data: {} },
    getChildPromosRequest: { limit: null, page: null, isBenefitSAP: null },
    resetBenefitItemsSAPDataRequest: {},
    getBenefitSAPPromosSuccess: { data: null },
    getChildPromosSuccess: { data: null },
    getChildPromosFailure: { error: null },
    updateBulkPromosRequest: { body: {} },
    updateBulkPromosSuccess: { data: {} },
    updateBulkPromosFailure: { error: null },
    getBenefitProductsRequest: { data: null },
    updateBenefitProductRequest: { data: {} },
    initPage: null,
    destroyPage: null,
  },
  { prefix: `${REDUX_KEY.PROMO.DETAIL}_` },
);
