import { createActions } from 'reduxsauce';

import { REDUX_KEY } from '@shared/shared/constants';

export const { Types, Creators } = createActions(
  {
    getCourierTasksRequest: {
      orderDetailId: null,
      returnId: null,
    },
    getCourierTasksSuccess: { data: [] },
    getCourierTasksFailure: { error: null },
    getReturnRequest: { orderId: null },
    getReturnRequestSuccess: { data: [] },
    getReturnRequestFailure: { error: null },
    setReturnDeliveryRequest: {
      returnId: null,
      selectedProducts: null,
      deliveryType: null,
      isFullReturn: null,
    },
    setReturnDeliveryRequestSuccess: { data: [] },
    setReturnDeliveryRequestFailure: { error: null },
    createReturnRequest: {
      onSuccess: null,
      returnId: null,
      deliveryType: null,
      selectedSlotId: null,
      selectedPid: null,
      selectedSlotStartTime: null,
      selectedSlotEndTime: null,
    },
    createReturnRequestSuccess: { data: {} },
    createReturnRequestFailure: { error: null },
    getShopReturnDetailsRequest: {
      onSuccess: null,
      onFinally: null,
      returnId: null,
    },
    changeReturnSlotRequest: {
      onSuccess: null,
      onFinally: null,
      returnId: null,
      deliveryType: null,
      selectedSlotId: null,
      selectedPid: null,
      selectedSlotStartTime: null,
      selectedSlotEndTime: null,
    },
    getAvailableSlotsForReturnRequest: {
      onSuccess: null,
      onFinally: null,
      returnId: null,
    },
    openReturnDetailsModal: { returnId: null },
    closeReturnDetailsModal: [],
    getOrderDetailRequest: { orderDetailId: null },
    getOrderDetailSuccess: { data: [] },
    getOrderDetailFailure: { error: null },
    getOrderCancelOptionRequest: { orderDetailId: null },
    getOrderCancelOptionSuccess: { data: [] },
    getOrderCancelOptionFailure: { error: null },
    getOrderCancelRequest: { id: null, body: null },
    getOrderCancelSuccess: { data: [] },
    getOrderCancelFailure: { error: null },
    createExternalTransactionRequest: { body: null },
    createExternalTransactionSuccess: { data: {} },
    createExternalTransactionFailure: { error: null },
    getOrderRefundOptionRequest: { orderDetailId: null },
    getOrderRefundOptionSuccess: { data: [] },
    getOrderRefundOptionFailure: { error: null },
    getOrderRefundRequest: { orderDetailId: null, body: null },
    getOrderRefundSuccess: { data: [] },
    getOrderRefundFailure: { error: null },
    getOrderReturnsRequest: { returnId: null },
    getOrderReturnsSuccess: { data: {} },
    getOrderReturnsFailure: { error: null },
    getReturnsAvailabilityRequest: { orderDetailId: null },
    getReturnsAvailabilitySuccess: { data: {} },
    getReturnsAvailabilityFailure: { error: null },
    cancelReturnRequest: { returnId: null },
    cancelReturnSuccess: { data: {} },
    cancelReturnFailure: { error: null },
    setRefundTabActiveKey: { refundTabActiveKey: '' },
    exportFinancialInfoRequest: { financialInfo: {} },
    exportFinancialInfoSuccess: {},
    exportFinancialInfoFailure: { error: null },
    getOrderNoteRequest: { data: null },
    getOrderNoteSuccess: { data: [] },
    getOrderNoteFailure: { error: null },
    createOrderNoteRequest: { data: null },
    createOrderNoteSuccess: { data: [] },
    createOrderNoteFailure: { error: null },
    getPaymentMethodsRequest: { includeOnline: false },
    getPaymentMethodsSuccess: { data: [] },
    getPaymentMethodsFailure: { error: null },
    getWarehouseRequest: { id: null },
    getWarehouseSuccess: { data: [] },
    getWarehouseFailure: { error: null },
    createForbiddenMatchRequest: { body: null },
    createForbiddenMatchSuccess: { data: [] },
    createForbiddenMatchFailure: { error: null },
    getUserByIdRequest: { id: null },
    getUserByIdSuccess: { data: {} },
    getUserByIdFailure: { error: null },
    getCourierRouteRequest: { body: null },
    getCourierRouteSuccess: { data: {} },
    getCourierRouteFailure: { error: null },
    getCourierReturnRouteRequest: { body: null },
    getCourierReturnRouteSuccess: { data: {} },
    getCourierReturnRouteFailure: { error: null },
    getCourierByIdRequest: { courierId: null },
    getCourierByIdSuccess: { data: {} },
    getCourierByIdFailure: { error: null },
    getArtisanCourierByIdRequest: { courierId: null },
    getArtisanCourierByIdSuccess: { data: {} },
    getArtisanCourierByIdFailure: { error: null },
    getReturnRunnerRequest: { returnId: null },
    getReturnRunnerSuccess: { data: {} },
    getReturnRunnerFailure: { error: null },
    getReturnRunnerHistoryRequest: { returnId: null },
    getReturnRunnerHistorySuccess: { data: {} },
    getReturnRunnerHistoryFailure: { error: null },
    getCurrentRunnerRequest: { orderId: null },
    getCurrentRunnerSuccess: { data: {} },
    getCurrentRunnerFailure: { error: null },
    getCallInfoRequest: { orderId: null, callPin: null },
    getCallInfoSuccess: { data: null },
    getCallInfoFailure: { error: null },
    getCallInfoMessagesRequest: null,
    getCallInfoMessagesSuccess: { data: null },
    getCallInfoMessagesFailure: { error: null },
    getReturnDetailsWithReturnIdListRequest: { returnIds: null },
    getReturnDetailsWithReturnIdListSuccess: { data: null },
    getReturnDetailsWithReturnIdListFailure: { error: null },
    initPage: null,
    destroyPage: null,
  },
  { prefix: `${REDUX_KEY.ARTISAN_ORDER.DETAIL}_` },
);
