const PREFIX = 'marketProductChain/suppliers';

// Suppliers
export const FETCH_SUPPLIERS_REQUEST = `${PREFIX}/FETCH_SUPPLIERS_REQUEST`;
export const FETCH_SUPPLIERS_SUCCESS = `${PREFIX}/FETCH_SUPPLIERS_SUCCESS`;
export const FETCH_SUPPLIERS_FAILURE = `${PREFIX}/FETCH_SUPPLIERS_FAILURE`;

// Cities
export const FETCH_CITIES_REQUEST = `${PREFIX}/FETCH_CITIES_REQUEST`;
export const FETCH_CITIES_SUCCESS = `${PREFIX}/FETCH_CITIES_SUCCESS`;
export const FETCH_CITIES_FAILURE = `${PREFIX}/FETCH_CITIES_FAILURE`;

// Regions
export const FETCH_REGIONS_REQUEST = `${PREFIX}/FETCH_REGIONS_REQUEST`;
export const FETCH_REGIONS_SUCCESS = `${PREFIX}/FETCH_REGIONS_SUCCESS`;
export const FETCH_REGIONS_FAILURE = `${PREFIX}/FETCH_REGIONS_FAILURE`;

// Domain Types
export const FETCH_DOMAIN_TYPES_REQUEST = `${PREFIX}/FETCH_DOMAIN_TYPES_REQUEST`;
export const FETCH_DOMAIN_TYPES_SUCCESS = `${PREFIX}/FETCH_DOMAIN_TYPES_SUCCESS`;
export const FETCH_DOMAIN_TYPES_FAILURE = `${PREFIX}/FETCH_DOMAIN_TYPES_FAILURE`;

// Filters, Pagination, and Sort
export const UPDATE_FILTERS = `${PREFIX}/UPDATE_FILTERS`;
export const UPDATE_PAGINATION = `${PREFIX}/UPDATE_PAGINATION`;
export const UPDATE_SORT = `${PREFIX}/UPDATE_SORT`;
