import { createActions } from 'reduxsauce';

import { REDUX_KEY } from '@shared/shared/constants';

export const { Types, Creators } = createActions({
  getSupplierByIdRequest: { id: null },
  getSupplierByIdSuccess: { data: {} },
  getSupplierByIdFailure: { error: null },
  mapSupplierProductsRequest: { id: null },
  mapSupplierProductsSuccess: { data: {} },
  mapSupplierProductsFailure: { error: null },
  mapSupplierWarehousesRequest: {},
  mapSupplierWarehousesSuccess: { data: {} },
  mapSupplierWarehousesFailure: { error: null },
  getSupplierProductMappingsRequest: { id: null },
  getSupplierProductMappingsSuccess: { data: {} },
  getSupplierProductMappingsFailure: { error: null },
  updateSupplierRequest: { id: null, updateData: {} },
  updateSupplierSuccess: { data: {} },
  updateSupplierFailure: { error: null },
  updateSupplierCustomSettingsRequest: { id: null, updateData: {} },
  updateSupplierCustomSettingsSuccess: { data: {} },
  updateSupplierCustomSettingsFailure: { error: null },
  createSupplierAccountRequest: { body: {} },
  createSupplierAccountSuccess: { data: {} },
  createSupplierAccountFailure: { error: null },
  updateDCBonusForLogoAccountRequest: { id: null, updateData: {} },
  updateDCBonusForLogoAccountSuccess: { data: {} },
  updateDCBonusForLogoAccountFailure: { error: null },
  updateSupplierProductMappingBarcodeAndCodeRequest: { id: null, updateData: {} },
  updateSupplierProductMappingBarcodeAndCodeSuccess: { data: {} },
  updateSupplierProductMappingBarcodeAndCodeFailure: { error: null },
  activateSupplierRequest: { id: null },
  activateSupplierSuccess: {},
  activateSupplierFailure: { error: null },
  deactivateSupplierRequest: { id: null },
  deactivateSupplierSuccess: {},
  deactivateSupplierFailure: { error: null },
  initPage: null,
  destroyPage: null,
}, { prefix: `${REDUX_KEY.SUPPLIER.DETAIL}_` });
