const PREFIX = 'marketProductChain/centralWarehouseTable';

export const FETCH_CENTRAL_WAREHOUSES_REQUEST = `${PREFIX}/FETCH_CENTRAL_WAREHOUSES_REQUEST`;
export const FETCH_CENTRAL_WAREHOUSES_SUCCESS = `${PREFIX}/FETCH_CENTRAL_WAREHOUSES_SUCCESS`;
export const FETCH_CENTRAL_WAREHOUSES_FAILURE = `${PREFIX}/FETCH_CENTRAL_WAREHOUSES_FAILURE`;

export const FETCH_CITIES_REQUEST = `${PREFIX}/FETCH_CITIES_REQUEST`;
export const FETCH_CITIES_SUCCESS = `${PREFIX}/FETCH_CITIES_SUCCESS`;
export const FETCH_CITIES_FAILURE = `${PREFIX}/FETCH_CITIES_FAILURE`;

export const FETCH_REGIONS_REQUEST = `${PREFIX}/FETCH_REGIONS_REQUEST`;
export const FETCH_REGIONS_SUCCESS = `${PREFIX}/FETCH_REGIONS_SUCCESS`;
export const FETCH_REGIONS_FAILURE = `${PREFIX}/FETCH_REGIONS_FAILURE`;

export const FETCH_DOMAIN_TYPES_REQUEST = `${PREFIX}/FETCH_DOMAIN_TYPES_REQUEST`;
export const FETCH_DOMAIN_TYPES_SUCCESS = `${PREFIX}/FETCH_DOMAIN_TYPES_SUCCESS`;
export const FETCH_DOMAIN_TYPES_FAILURE = `${PREFIX}/FETCH_DOMAIN_TYPES_FAILURE`;

export const UPDATE_FILTERS = `${PREFIX}/UPDATE_FILTERS`;
export const UPDATE_PAGINATION = `${PREFIX}/UPDATE_PAGINATION`;
export const UPDATE_SORT = `${PREFIX}/UPDATE_SORT`;
