import { createUseStyles } from 'react-jss';

import { placeholder, primary, inactive, grey } from '@shared/components/GUI/styles/guiThemes';

export const useStyles = createUseStyles({
  floatingLabelContainer: {
    position: 'relative',
    display: 'flex',
    width: '100%',
    marginBottom: 0,
    '& .flabel': {
      color: placeholder,
      position: 'absolute',
      fontSize: '14px',
      fontWeight: 400,
      lineHeight: '16px',
      transform: 'translate(0, 0)',
      transformOrigin: 'top left',
      transition: 'all 200ms ease',
      left: '12px',
      top: '50%',
      marginTop: '-8px',
      zIndex: 1,
      pointerEvents: 'none',
    },
    '& input:not([value=""]) + .flabel, & .ant-select-focused + .flabel, & .ant-select:has(.ant-select-selection-item) + .flabel': {
      color: primary,
      transform: 'translate(0, 0)',
      fontSize: '12px',
      top: '6px',
      marginTop: '0',
      zIndex: 1,
      pointerEvents: 'none',
    },
    '& input:focus + .flabel': {
      color: primary,
      transform: 'translate(0, 0)',
      fontSize: '12px',
      top: '6px',
      marginTop: '0',
    },
    '& .search-input': {
      paddingTop: '16px',
      height: '48px !important',
      '& + .flabel': {
        top: '6px',
        marginTop: '0',
        fontSize: '12px',
      },
    },
    '& .ant-select': { width: '100% !important' },
    '& .ant-select:not(.ant-select-multiple) .ant-select-selector': {
      height: '48px !important',
      borderRadius: '8px !important',
      display: 'flex !important',
      alignItems: 'center !important',
      transition: 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
      border: `1px solid ${grey} !important`,
      '&:hover': { borderColor: `${primary} !important` },
      paddingTop: '12px !important',
    },
    '& .ant-select-focused .ant-select-selector': {
      borderColor: `${primary} !important`,
      boxShadow: '0 0 0 2px rgba(135, 94, 196, 0.2) !important',
    },
    '& .ant-select:not(.ant-select-multiple) .ant-select-selection-search': {
      height: '46px !important',
      display: 'flex !important',
      alignItems: 'center !important',
      '& .ant-select-selection-search-input': {
        marginTop: '0 !important',
        height: '24px !important',
      },
    },
    '& .ant-select:not(.ant-select-multiple) .ant-select-selection-item': {
      display: 'flex !important',
      alignItems: 'center !important',
      lineHeight: '20px !important',
      marginTop: '0 !important',
      paddingTop: '0 !important',
    },
    '& .ant-select-arrow': {
      top: '50%',
      right: '11px',
      width: '12px',
      height: '12px',
      marginTop: '-6px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    '& .ant-select-dropdown': {
      padding: '12px',
      borderRadius: '8px',
      top: 'calc(100% + 4px)',
      position: 'absolute',
      boxShadow: '0 6px 16px 0 rgba(0, 0, 0, 0.08)',
      border: `1px solid ${grey}`,
      backgroundColor: '#fff',
      '& .rc-virtual-list-holder': {
        overflowY: 'auto',
        maxHeight: 'none',
      },
      '& .rc-virtual-list': { maxHeight: 'none' },
      '& .ant-select-item-option-content': {
        whiteSpace: 'normal',
        fontSize: '12px',
        lineHeight: '16px',
        color: '#333',
      },
    },
    '& .ant-select-item': {
      borderRadius: '4px',
      padding: '6px 10px',
      margin: '1px 0',
      transition: 'all 0.2s ease',
      minHeight: '30px',
      '&-option-selected': {
        backgroundColor: 'rgba(93, 62, 188, 0.04)',
        color: primary,
        fontWeight: 500,
      },
      '&-option-active': {
        backgroundColor: 'rgba(93, 62, 188, 0.02)',
        color: primary,
      },
    },
    '& .ant-select-multiple': {
      '& .ant-select-selector': {
        height: '48px',
        minHeight: '48px',
        maxHeight: '48px',
        borderRadius: '8px',
        display: 'flex',
        alignItems: 'flex-start',
        transition: 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
        border: `1px solid ${grey}`,
        '&:hover': { borderColor: primary },
        paddingTop: '26px',
        paddingBottom: '4px',
        paddingRight: '32px',
        paddingLeft: '12px',
        flexWrap: 'nowrap',
        overflowX: 'auto',
        '&::-webkit-scrollbar': { display: 'none' },
        '-ms-overflow-style': 'none',
        'scrollbar-width': 'none',
      },
      '& .ant-select-focused .ant-select-selector': { paddingTop: '26px' },
      '& .ant-select-selection-overflow': { display: 'flex', flexWrap: 'nowrap', width: 'auto', gap: '3px', marginTop: '0' },
      '& .ant-select-selection-overflow-item': { flex: 'none', alignSelf: 'baseline', maxWidth: '100%' },
      '& .ant-select-selection-item': {
        height: '18px',
        lineHeight: '18px',
        margin: '0',
        padding: '0 5px',
        background: 'rgba(93, 62, 188, 0.04)',
        borderRadius: '3px',
        border: 'none',
        fontSize: '11px',
        color: primary,
        whiteSpace: 'nowrap',
        textOverflow: 'ellipsis',
        overflow: 'hidden',
        display: 'inline-flex',
        alignItems: 'center',
        transition: 'all 0.2s ease',
        '&:hover': { background: 'rgba(93, 62, 188, 0.06)' },
      },
      '& .ant-select-selection-item-content': {
        fontSize: '11px',
        lineHeight: '18px',
        fontWeight: 400,
      },
      '& .ant-select-selection-item-remove': {
        color: primary,
        opacity: 0.5,
        fontSize: '9px',
        marginLeft: '3px',
        height: '18px',
        lineHeight: '18px',
        transition: 'opacity 0.2s ease',
        '&:hover': { opacity: 0.8 },
      },
      '& .ant-select-selection-search': {
        margin: '0',
        height: '18px',
        lineHeight: '18px',
        alignSelf: 'baseline',
      },
      '& .ant-select-selection-placeholder': {
        padding: '0',
        lineHeight: '48px',
        fontSize: '14px',
        display: 'flex',
        alignItems: 'center',
      },
    },
    '& .ant-input': {
      height: '48px !important',
      borderRadius: '8px !important',
      '&:hover': { borderColor: `${primary} !important` },
      '&:focus': {
        borderColor: `${primary} !important`,
        boxShadow: '0 0 0 2px rgba(135, 94, 196, 0.2) !important',
      },
    },
    '& .ant-input-prefix': { marginRight: '12px' },
  },
  error: { '& .flabel': { color: '#FF4D4F' } },
  icon: {
    position: 'absolute',
    right: '11px',
    top: '50%',
    transform: 'translateY(-50%)',
    pointerEvents: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '12px',
    height: '12px',
    color: primary,
    zIndex: 2,
    fontWeight: 800,
  },
  searchInputContainer: {
    '& input:not([value=""]) + .flabel, & input:focus + .flabel': {
      top: '8px',
      marginTop: '0',
      fontSize: '12px',
      color: primary,
    },
    '& .ant-input': { paddingTop: '4px' },
    '& input:not([value=""]), & input:focus': { paddingTop: '20px' },
  },
});
