import { createActions } from 'reduxsauce';

import { REDUX_KEY } from '@shared/shared/constants';

export const { Types, Creators } = createActions({
  initPage: null,
  destroyPage: null,
  getWarehouseRequest: { id: null },
  getWarehouseSuccess: { data: {} },
  getWarehouseFailure: { error: null },
  getEmployeesRequest: {},
  getEmployeesSuccess: { data: [] },
  getEmployeesFailure: { error: null },
  getShipmentFrequenciesRequest: {},
  getShipmentFrequenciesSuccess: { data: [] },
  getShipmentFrequenciesFailure: { error: null },
  getShipmentPreparationsRequest: {},
  getShipmentPreparationsSuccess: { data: [] },
  getShipmentPreparationsFailure: { error: null },
  getWarehouseShipmentFrequenciesRequest: { warehouseId: null },
  getWarehouseShipmentFrequenciesSuccess: { data: [] },
  getWarehouseShipmentFrequenciesFailure: { error: null },
  updateWarehouseShipmentFrequencyRequest: { warehouseId: null, shipmentFrequency: {} },
  updateWarehouseShipmentFrequencySuccess: { data: [] },
  updateWarehouseShipmentFrequencyFailure: { error: null },
  updateWarehouseShipmentPreparationRequest: { warehouseId: null, shipmentPreparation: {} },
  updateWarehouseShipmentPreparationSuccess: { data: [] },
  updateWarehouseShipmentPreparationFailure: { error: null },
  addWarehouseShipmentPreparationRequest: { warehouseId: null, shipmentPreparation: {} },
  addWarehouseShipmentPreparationSuccess: { data: [] },
  addWarehouseShipmentPreparationFailure: { error: null },
  addWarehouseShipmentFrequencyRequest: { warehouseId: null, shipmentFrequency: {} },
  addWarehouseShipmentFrequencySuccess: { data: [] },
  addWarehouseShipmentFrequencyFailure: { error: null },
  getWarehouseShipmentPreparationsRequest: { warehouseId: null },
  getWarehouseShipmentPreparationsSuccess: { data: [] },
  getWarehouseShipmentPreparationsFailure: { error: null },
  getWarehouseTransferGroupRequest: { id: null },
  getWarehouseTransferGroupSuccess: { data: {} },
  getWarehouseTransferGroupFailure: { error: null },
  updateWarehouseInfoRequest: { id: null, updateData: {} },
  updateWarehouseInfoSuccess: { data: {} },
  updateWarehouseInfoFailure: { error: null },
  updateWarehouseBudgetInfoRequest: { id: null, SAPReferenceCode: null, updatedBudgetInfoData: {} },
  updateWarehouseBudgetInfoSuccess: { data: {} },
  updateWarehouseBudgetInfoFailure: { error: null },
  updateWarehouseTestStatusRequest: { id: null, isTestWarehouse: false },
  updateWarehouseTestStatusSuccess: { isTestWarehouse: false },
  updateWarehouseTestStatusFailure: { error: null },
  updateWarehouseAcceptReturnsRequest: { id: null, acceptReturns: false },
  updateWarehouseAcceptReturnsSuccess: { acceptReturns: false },
  updateWarehouseAcceptReturnsFailure: { error: null },
  updateWarehouseAddressRequest: { id: null, updateData: {} },
  updateWarehouseAddressSuccess: { data: {} },
  updateWarehouseAddressFailure: { error: null },
  updateWarehouseTypeRequest: { id: null, updateData: {} },
  updateWarehouseTypeSuccess: { data: {} },
  updateWarehouseTypeFailure: { error: null },
  updateWarehouseDomainTypesRequest: { id: null, updateData: {} },
  updateWarehouseDomainTypesSuccess: { data: {} },
  updateWarehouseDomainTypesFailure: { error: null },
  updateWarehouseMainStoreRequest: { id: null, updateData: {} },
  updateWarehouseMainStoreSuccess: { data: {} },
  updateWarehouseMainStoreFailure: { error: null },
  updateWarehouseManpowerRequest: { id: null, updateData: {} },
  updateWarehouseManpowerSuccess: { data: {} },
  updateWarehouseManpowerFailure: { error: null },
  unassignFranchiseRequest: { id: null, franchiseId: null },
  unassignFranchiseSuccess: { data: {} },
  unassignFranchiseFailure: { error: null },
  assignFranchiseRequest: { id: null, franchiseId: null },
  assignFranchiseSuccess: { data: {} },
  assignFranchiseFailure: { error: null },
  updateWarehouseBusinessDecisionsRequest: { id: null, updateData: {} },
  updateWarehouseBusinessDecisionsSuccess: { data: {} },
  updateWarehouseBusinessDecisionsFailure: { error: null },
  updateWarehouseConfigRequest: { id: null, updateData: {} },
  updateWarehouseConfigSuccess: { data: {} },
  updateWarehouseConfigFailure: { error: null },
  archiveWarehouseRequest: { id: null },
  archiveWarehouseSuccess: { data: {} },
  archiveWarehouseFailure: { error: null },
  deactivateWarehouseRequest: { id: null },
  deactivateWarehouseSuccess: { data: {} },
  deactivateWarehouseFailure: { error: null },
  activateWarehouseRequest: { id: null },
  activateWarehouseSuccess: { data: {} },
  activateWarehouseFailure: { error: null },
  updateWarehouseStatusRequest: { id: null, updateData: {} },
  updateWarehouseStatusSuccess: { data: {} },
  updateWarehouseStatusFailure: { error: null },
  deleteTransferGroupOfWarehouseRequest: { warehouse: null },
  deleteTransferGroupOfWarehouseSuccess: {},
  deleteTransferGroupOfWarehouseFailure: { error: null },
  updateTransferGroupOfWarehouseRequest: { warehouse: null, transferGroup: null },
  updateTransferGroupOfWarehouseSuccess: { data: {} },
  updateTransferGroupOfWarehouseFailure: { error: null },
  getWarehouseWorkingHoursRequest: {},
  getWarehouseWorkingHoursSuccess: { data: {} },
  getWarehouseWorkingHoursFailure: { error: null },
  updateBaseWorkingHoursTypeRequest: { id: null, updateData: {} },
  updateBaseWorkingHoursTypeSuccess: { data: {} },
  updateBaseWorkingHoursTypeFailure: { error: null },
  updateWorkingHoursRequest: { id: null, updateData: {} },
  updateWorkingHoursSuccess: { data: {} },
  updateWorkingHoursFailure: { error: null },
  updateWorkingHoursMessageRequest: { id: null, updateData: {} },
  updateWorkingHoursMessageSuccess: { data: [] },
  updateWorkingHoursMessageFailure: { error: null },
  getWarehousePeakHoursRequest: {},
  getWarehousePeakHoursSuccess: { data: {} },
  getWarehousePeakHoursFailure: { error: null },
  updateBasePeakHoursTypeRequest: { id: null, updateData: {} },
  updateBasePeakHoursTypeSuccess: { data: {} },
  updateBasePeakHoursTypeFailure: { error: null },
  updatePeakHoursRequest: { id: null, updateData: {} },
  updatePeakHoursSuccess: { data: {} },
  updatePeakHoursFailure: { error: null },
  updatePeakHoursMessageRequest: { id: null, updateData: {} },
  updatePeakHoursMessageSuccess: { data: [] },
  updatePeakHoursMessageFailure: { error: null },
  updateTransferReceivingRequest: { id: null, updateData: {} },
  updateTransferReceivingSuccess: { data: {} },
  updateTransferReceivingFailure: { error: null },
  getWarehouseLocationTemplatesRequest: { warehouseType: null },
  getWarehouseLocationTemplatesSuccess: { data: [] },
  getWarehouseLocationTemplatesFailure: { error: null },
  getWarehouseSectionsRequest: { warehouseId: null },
  getWarehouseSectionsSuccess: { data: [] },
  getWarehouseSectionsFailure: { error: null },
  createNewSectionRequest: { warehouseId: null, template: null, sectionOpts: {} },
  createNewSectionSuccess: {},
  createNewSectionFailure: { error: null },
  createNewBlockRequest: { warehouseId: null, sectionId: null, template: null, blockOpts: {} },
  createNewBlockSuccess: {},
  createNewBlockFailure: { error: null },
  updateWarehouseLocationActivateRequest: { warehouseLocationId: null, applyToChildren: false },
  updateWarehouseLocationActivateSuccess: {},
  updateWarehouseLocationActivateFailure: { error: null },
  updateWarehouseLocationDeactivateRequest: { warehouseLocationId: null },
  updateWarehouseLocationDeactivateSuccess: {},
  updateWarehouseLocationDeactivateFailure: { error: null },
  updateWarehouseLocationAllowedForTransferRequest: { locationId: null, isAllowed: null },
  updateWarehouseLocationAllowedForTransferSuccess: {},
  updateWarehouseLocationAllowedForTransferFailure: { error: null },
  updateWarehouseLocationArchiveRequest: { warehouseLocationId: null },
  updateWarehouseLocationArchiveSuccess: {},
  updateWarehouseLocationArchiveFailure: { error: null },
  saveWarehouseLocationSelfCodeRequest: { warehouseLocationId: null, selfCode: null },
  saveWarehouseLocationSelfCodeSuccess: {},
  saveWarehouseLocationSelfCodeFailure: { error: null },
  updateLocationWriteOffEnabledRequest: { warehouseLocationId: null, isAllowed: null },
  updateLocationWriteOffEnabledSuccess: {},
  updateLocationWriteOffEnabledFailure: { error: null },
  updateAlgorithmConfigRequest: { warehouseId: null, algorithmConfig: null },
  updateAlgorithmConfigFailure: { error: null },
  getWarehouseSegmentsRequest: null,
  getWarehouseSegmentsSuccess: { data: [] },
  getWarehouseSegmentsFailure: { error: null },
  updateWarehouseDeliveryFeeSegmentRequest: { warehouseId: null, segmentId: null },
  updateWarehouseDeliveryFeeSegmentSuccess: { data: {} },
  updateWarehouseDeliveryFeeSegmentFailure: { error: null },
  updateWarehouseProductPricingSegmentRequest: { warehouseId: null, segmentId: null },
  updateWarehouseProductPricingSegmentSuccess: { data: {} },
  updateWarehouseProductPricingSegmentFailure: { error: null },
  updateWarehousePromoAggressionLevelRequest: { id: null, updateData: {} },
  updateWarehousePromoAggressionLevelSuccess: { data: {} },
  updateWarehousePromoAggressionLevelFailure: { error: null },
  assignFranchiseAreaRequest: { warehouseId: null, franchiseAreaId: null },
  assignFranchiseAreaSuccess: { data: {} },
  assignFranchiseAreaFailure: { error: null },
  getWarehousesFilterRequest: {
    name: undefined,
    fields: undefined,
  },
  getWarehousesFilterSuccess: { warehouses: [], totalCount: 0 },
  getWarehousesFilterFailure: { error: null },
}, { prefix: `${REDUX_KEY.WAREHOUSE.DETAIL}_` });
