import {
  COURIER_STATUS_CANCELED,
  COURIER_STATUS_ONWAY,
  COURIER_STATUS_REACHED,
  COURIER_STATUS_REACHED_TO_RESTAURANT,
  COURIER_STATUS_RETURNING,
  COURIER_STATUS_PREPARING,
  COURIER_STATUS_BEFORE_PREPARING,
  COURIER_RETURN_STATUS_SLOT_VERIFY,
  COURIER_RETURN_STATUS_ONWAY_TO_PICKUP,
  COURIER_RETURN_STATUS_PICKUP_FROM_CLIENT,
  COURIER_RETURN_STATUS_ONWAY_TO_DELIVER,
  COURIER_RETURN_STATUS_DELIVER_TO_SHOP,
  COURIER_RETURN_STATUS_SLOT_DELIVER_AND_WAIT,
  COURIER_RETURN_STATUS_CANCELED,
  VEHICLE_TYPE,
} from '@shared/shared/constants';

export const LOCALS_WAREHOUSE_UTILIZATION_THRESHOLD = 85;

export const COURIER_ONWAY_ALERT_TIME = 13; // as min
export const COURIER_REACHED_ALERT_TIME = 10; // as min
export const COURIER_REACHED_TO_RESTAURANT_ALERT_TIME = 5; // as min
export const COURIER_CANCELED_ALERT_TIME = 5; // as min
export const COURIER_LONG_BUSY_TIME_DURATION = 45; // as min
export const COURIER_LONG_CANCELLED_TIME_DURATION = 15; // as min
export const COURIER_LONG_AVAILABLE_TIME_DURATION = 90; // as min
export const COURIER_RETURNING_ALERT_TIME = 15; // as min
export const COURIER_PREPARING_ALERT_TIME = 15; // as min
export const COURIER_BEFORE_PREPARING_ALERT_TIME = 1; // as min
export const COURIER_SLOT_VERIFY_ALERT_TIME = 1; // as min
export const COURIER_SLOT_ONWAY_TO_PICKUP_ALERT_TIME = 15; // as min
export const COURIER_SLOT_PICKUP_FROM_CLIENT_ALERT_TIME = 7; // as min
export const COURIER_SLOT_ONWAY_TO_DELIVER_ALERT_TIME = 15; // as min
export const COURIER_SLOT_DELIVER_TO_SHOP_ALERT_TIME = 5; // as min
export const COURIER_SLOT_DELIVER_AND_WAIT_ALERT_TIME = 5; // as min
export const COURIER_SLOT_CANCELLED_ALERT_TIME = 1; // as min

export const LOCALS_LIVEMAP_COURIER_ALERT_THRESHOLDS_BY_STATUS = {
  [COURIER_STATUS_REACHED_TO_RESTAURANT]: COURIER_REACHED_TO_RESTAURANT_ALERT_TIME,
  [COURIER_STATUS_ONWAY]: COURIER_ONWAY_ALERT_TIME,
  [COURIER_STATUS_REACHED]: COURIER_REACHED_ALERT_TIME,
  [COURIER_STATUS_CANCELED]: COURIER_CANCELED_ALERT_TIME,
  [COURIER_STATUS_RETURNING]: COURIER_RETURNING_ALERT_TIME,
  [COURIER_STATUS_PREPARING]: COURIER_PREPARING_ALERT_TIME,
  [COURIER_STATUS_BEFORE_PREPARING]: COURIER_BEFORE_PREPARING_ALERT_TIME,
  [COURIER_RETURN_STATUS_SLOT_VERIFY]: COURIER_SLOT_VERIFY_ALERT_TIME,
  [COURIER_RETURN_STATUS_ONWAY_TO_PICKUP]: COURIER_SLOT_ONWAY_TO_PICKUP_ALERT_TIME,
  [COURIER_RETURN_STATUS_PICKUP_FROM_CLIENT]: COURIER_SLOT_PICKUP_FROM_CLIENT_ALERT_TIME,
  [COURIER_RETURN_STATUS_ONWAY_TO_DELIVER]: COURIER_SLOT_ONWAY_TO_DELIVER_ALERT_TIME,
  [COURIER_RETURN_STATUS_DELIVER_TO_SHOP]: COURIER_SLOT_DELIVER_TO_SHOP_ALERT_TIME,
  [COURIER_RETURN_STATUS_SLOT_DELIVER_AND_WAIT]: COURIER_SLOT_DELIVER_AND_WAIT_ALERT_TIME,
  [COURIER_RETURN_STATUS_CANCELED]: COURIER_SLOT_CANCELLED_ALERT_TIME,
};

export const DEFAULT_MARKER_SIZE = [16, 16];
export const DEFAULT_FOOD_WH_MARKER_SIZE = [20, 20];
export const ANIMATED_MARKER_SIZE = [24, 24];
export const MEDIUM_MARKER_SIZE = [28, 28];
export const LARGE_MARKER_SIZE = [50, 50];

export const DEFAULT_COURIER_VEHICLE_TYPE = [VEHICLE_TYPE.MOTO, VEHICLE_TYPE.MOTO_50CC, VEHICLE_TYPE.VAN];

export const VISIBLE_VEHICLE_TYPES = [
  VEHICLE_TYPE.MOTO,
  VEHICLE_TYPE.MOTO_50CC,
  VEHICLE_TYPE.VAN,
];

export const LOCALS_ALGO = 'LOCALS_ALGO';
