import { createUseStyles } from 'react-jss';

export default createUseStyles(() => {
  return {
    bottomLeftHideButtonWrapper: {
      position: 'absolute',
      bottom: '0px',
      width: '35px',
      zIndex: 900,
      marginLeft: '362px',
    },
    activeOrderAreaWrapper: {
      boxShadow: '2px 2px 10px rgba(0, 0, 0, 0.1)',
      position: 'absolute',
      width: '380px',
      minHeight: '50px',
      background: '#f5f5f5',
      borderRadius: '0 5px 5px 0 !important',
      bottom: '0px',
    },
    selectedCityActiveOrdersTable: {
      borderColor: '#dee5e7',
      borderRadius: '5px',
      marginBottom: '5px !important',
      boxShadow: '2px 2px 10px rgba(0, 0, 0, 0.1)',
    },
    activeOrderCountCellHead: {
      width: '45px !important',
      fontSize: '11px',
      textAlign: 'right',
    },
    wrapperOuterContainer: {
      position: 'absolute',
      top: '40px',
      width: '30%',
      padding: '1rem',
      zIndex: 1005,
    },
    wrapperPadding: {
      paddingRight: '4px',
      width: '123px',
    },
    wrapperMargin: {
      width: '100%',
      marginLeft: '2px',
    },
    wrapper: {
      margin: '10px 10px auto',
      top: '10px',
      position: 'relative',
    },
    activeArtisanOrderCountCell: {
      textAlign: 'right',
      fontSize: '11px',
      width: '40px !important',
      borderRight: '1px solid #F5F5F5',
    },
    activeOrderErrorCountCell: {
      textAlign: 'right',
      whiteSpace: 'nowrap',
      fontSize: '10px',
      color: '#900C3F',
      width: '105px !important',
      borderRight: '1px solid #F5F5F5',
    },
    errorCountHead: {
      fontSize: '11px',
      verticalAlign: 'bottom',
      textAlign: 'right',
      whiteSpace: 'nowrap',
      width: '105px !important',
      borderRight: '1px solid #F5F5F5',
    },
    financialCellHead: {
      textAlign: 'right',
      width: '45px !important',
      fontSize: '11px',
      verticalAlign: 'bottom',
      borderRight: '1px solid #F5F5F5',
    },
    financialCell: {
      textAlign: 'right',
      fontSize: '11px',
      color: '#27C24C',
      width: '45px !important',
    },
    orderCountCell: {
      textAlign: 'right',
      fontSize: '11px',
      color: '#5D3EBC',
      width: '45px !important',
    },
    orderCountCellHead: {
      textAlign: 'right',
      fontSize: '11px',
      width: '45px !important',
    },
    orderCountGrowthCellHead: {
      textAlign: 'right',
      color: '#27C24C',
      fontSize: '11px !important',
      verticalAlign: 'bottom',
      width: '45px !important',
      borderRight: '1px solid #F5F5F5',
    },
    financialGrowthCell: {
      textAlign: 'right',
      color: '#27C24C',
      fontSize: '11px !important',
      verticalAlign: 'bottom',
      width: '45px !important',
      borderRight: '1px solid #F5F5F5',
    },
    orderCountGrowthCell: {
      textAlign: 'right',
      color: '#FFD10D',
      fontSize: '11px !important',
      verticalAlign: 'bottom',
      width: '45px !important',
      borderRight: '1px solid #F5F5F5',
    },
    financialGrowthCellHead: {
      fontSize: '11px',
      verticalAlign: 'bottom',
      textAlign: 'right',
      width: '45px !important',
      borderRight: '1px solid #F5F5F5',
    },
    previousArtisanOrderCountCell: {
      textAlign: 'right',
      fontSize: '11px',
      color: '5D3EBC',
      width: '43px !important',
    },
    dedicatedCourierCountCellHead: {
      textAlign: 'right',
      width: '45px !important',
      fontSize: '11px',
    },
    dedicatedCourierCountCell: {
      textAlign: 'right',
      width: '45px !important',
      fontSize: '11px',
    },
    G10CellHead: {
      textAlign: 'right',
      width: '45px !important',
      fontSize: '11px',
    },
    G10Cell: {
      textAlign: 'right',
      width: '45px !important',
      fontSize: '11px',
      color: '#0C30D6',
    },
    GBCellHead: {
      textAlign: 'right',
      width: '45px !important',
      fontSize: '11px',
    },
    GBCell: {
      textAlign: 'right',
      width: '45px !important',
      fontSize: '11px',
    },
    mapWrapper: { height: '100%' },
    shopStatistics: {
      position: 'absolute',
      bottom: '5px',
      backgroundColor: '#f5f5f5',
      width: '380px',
      borderRadius: '3px',
      height: '20px',
      fontSize: '12px',
      padding: '4px',
    },
  };
});
