export const WAREHOUSE_DETAIL_TYPES = {
  WAREHOUSE: 'warehouse',
  DARK_STORE: 'darkStore',
};

export const ANALYTICS_CONFIG = {
  name: 'MARKET_PRODUCT_CHAIN_MANAGEMENT_WAREHOUSES_DETAIL',
  squad: 'MARKET_PRODUCT_CHAIN_MANAGEMENT_WAREHOUSES_DETAIL',
};

export const MATCH_SUPPLIER_ANALYTICS_CONFIG = {
  name: 'MARKET_PRODUCT_CHAIN_MANAGEMENT_MATCH_SUPPLIERS',
  squad: 'MARKET_PRODUCT_CHAIN_MANAGEMENT_MATCH_SUPPLIERS',
};
