import pages from '@app/pages';

const ROUTE_COMPONENTS = {
  HEALTH: pages.Health,
  LOGIN: pages.Login,
  LOGOUT: pages.Logout,
  COUNTRY_SELECTION: pages.CountrySelection,
  NOT_FOUND: pages.NotFound,
  HOME: pages.Home,
  TRANSFER_GROUP_LIST: pages.TransferGroupList,
  TRANSFER_GROUP_NEW: pages.TransferGroupNew,
  TRANSFER_GROUP_DETAIL: pages.TransferGroupDetail,
  SUPPLIER_LIST: pages.SupplierList,
  SUPPLIER_NEW: pages.SupplierNew,
  SUPPLIER_DETAIL: pages.SupplierDetail,
  PAGE_LIST: pages.PageList,
  PAGE_NEW: pages.PageNew,
  PAGE_DETAIL: pages.PageDetail,
  PANEL_DOC_DETAIL: pages.PanelDocDetail,
  PANEL_DOC_PREVIEW: pages.PanelDocPreview,
  PANEL_DOC_SEARCH: pages.PanelDocSearch,
  USER_LIST: pages.UserList,
  USER_WEBHELP_MATCHING: pages.UserWebhelpMatching,
  EXTERNAL_CUSTOMER_SERVICES_PANEL_ACCOUNT_MANAGEMENT:
    pages.ExternalCustomerServicesPanelAccountManagement,
  COMPANY_KPI_DICTIONARY: pages.CompanyKPIDictionary,
  USER_NEW: pages.UserNew,
  USER_DETAIL: pages.UserDetail,
  ROLE_HIERARCHY: pages.RoleHierarchy,
  ROLE_LIST: pages.RoleList,
  ROLE_NEW: pages.RoleNew,
  ROLE_DETAIL: pages.RoleDetail,
  COMPONENT_NEW: pages.ComponentNew,
  COMPONENT_DETAIL: pages.ComponentDetail,
  BRAND_LIST: pages.BrandList,
  BRAND_NEW: pages.BrandNew,
  BRAND_DETAIL: pages.BrandDetail,
  MARKET_PRODUCT_LIST: pages.MarketProductListV2,
  MARKET_PRODUCT_DETAIL: pages.MarketProductDetailV2,
  MARKET_PRODUCT_PRICING_LIST: pages.MarketProductPricingList,
  MARKET_PRODUCT_PRICING_DETAIL: pages.MarketProductPricingDetail,
  MARKET_PRODUCT_FAMILY_LIST: pages.MarketProductFamilyList,
  MARKET_PRODUCT_RECIPES: pages.MarketProductRecipes,
  MARKET_PRODUCT_RECIPES_DETAIL: pages.MarketProductRecipesDetail,
  MARKET_PRODUCT_RECIPES_SORT: pages.MarketProductRecipesSort,
  MARKET_PRODUCT_FAMILY_DETAIL: pages.MarketProductFamilyDetail,
  MARKET_PRODUCT_PRICING_DISCOUNTED_DETAIL: pages.MarketProductPricingDiscountedDetail,
  MARKET_PRODUCT_SORT: pages.MarketProductSort,
  MARKET_PRODUCT_CATEGORY_LIST: pages.MarketProductCategoryList,
  MARKET_PRODUCT_CATEGORY_NEW: pages.MarketProductCategoryNew,
  MARKET_PRODUCT_CATEGORY_DETAIL: pages.MarketProductCategoryDetail,
  MARKET_PRODUCT_CATEGORY_SORT: pages.MarketProductCategorySort,
  MARKET_PRODUCT_SUB_CATEGORY_SORT: pages.MarketProductSubCategorySort,
  MARKET_PRODUCT_BADGE_LIST: pages.MarketProductBadgeList,
  MARKET_PRODUCT_BADGE_NEW: pages.MarketProductBadgeNew,
  MARKET_PRODUCT_BADGE_DETAIL: pages.MarketProductBadgeDetail,
  MARKET_PRODUCT_GROUP_LIST: pages.MarketProductGroupList,
  MARKET_PRODUCT_GROUP_NEW: pages.MarketProductGroupNew,
  MARKET_PRODUCT_GROUP_DETAIL: pages.MarketProductGroupDetail,
  MARKET_PRODUCT_CATEGORY_VISIBILITY_LIST:
    pages.MarketProductCategoryVisibilityList,
  MARKET_PRODUCT_CATEGORY_VISIBILITY_DETAIL:
    pages.MarketProductCategoryVisibilityDetail,
  MARKET_PRODUCT_CATEGORY_VISIBILITY_NEW:
    pages.MarketProductCategoryVisibilityNew,
  MARKET_PRODUCT_MASTER_CATEGORY_LIST: pages.MarketProductMasterCategoryList,
  MARKET_PRODUCT_MASTER_CATEGORY_DETAIL:
    pages.MarketProductMasterCategoryDetail,
  MARKET_PRODUCT_MASTER_CATEGORY_NEW: pages.MarketProductMasterCategoryNew,
  ARTISAN_ORDER_FILTER: pages.artisanOrderFilter,
  WAREHOUSE_LIST: pages.WarehouseList,
  WAREHOUSE_DETAIL: pages.WarehouseDetail,
  WAREHOUSE_NEW: pages.WarehouseNew,
  WAREHOUSE_LIVE_MAP: pages.WarehouseLiveMap,
  DELIVERY_FEE_BULK_UPLOAD: pages.DeliveryFeeBulkUpload,
  SERVICE_FEE_BULK_UPLOAD: pages.ServiceFeeBulkUpload,
  WAREHOUSE_PROPOSAL_LIST: pages.WarehouseProposalList,
  WAREHOUSE_PROPOSAL_DETAIL: pages.WarehouseProposalDetail,
  WAREHOUSE_PROPOSAL_CREATE: pages.WarehouseProposalCreate,
  EMPLOYEE_NEW: pages.EmployeeNew,
  EMPLOYEE_LIST: pages.EmployeeList,
  EMPLOYEE_ASSET_NEW: pages.AssetNew,
  IT_ASSET_DASHBOARD: pages.AssetDashboard,
  EMPLOYEE_ASSET_DETAIL: pages.AssetDetail,
  EMPLOYEE_ASSET_LIST: pages.EmployeeAssetList,
  EMPLOYEE_DETAIL: pages.EmployeeDetail,
  EMPLOYEE_DETAIL_ASSET_LIST: pages.EmployeeDetailAssetList,
  ASSET_MANAGEMENT_LIST: pages.AssetManagementList,
  ASSET_MANAGEMENT_DETAIL: pages.AssetManagementDetail,
  ASSET_MANAGEMENT_NEW: pages.AssetManagementNew,
  ASSET_MANAGEMENT_LOGS: pages.AssetManagementLogs,
  MENTORSHIP_PROFILE: pages.MentorshipProfile,
  MENTORSHIP_MENTOR_DETAIL: pages.MentorshipMentorDetail,
  MENTORSHIP_SEARCH: pages.MentorshipSearch,
  MENTORSHIP_COURSE_DETAIL: pages.MentorshipCourseDetail,
  MENTORSHIP_PROGRESS: pages.MentorshipProgress,
  COURIER_DETAIL: pages.CourierDetail,
  COURIER_COMMUNICATION_NOTIFICATION_LIST: pages.CourierNotificationList,
  COURIER_COMMUNICATION_CREATE_NOTIFICATION: pages.CourierCreateNotification,
  COURIER_COMMUNICATION_NOTIFICATION_DETAIL: pages.CourierNotificationDetail,
  COURIER_STATUS_AND_BUSY_LIST: pages.CourierStatusAndBusyList,
  COURIER_NOTIFICATION_SEGMENT_LIST: pages.CourierNotificationSegmentList,
  COURIER_NOTIFICATION_CREATE_SEGMENT: pages.CourierNotificationCreateSegment,
  COURIER_LOYALTY_LIST: pages.CourierLoyaltyList,
  EMPLOYEE_HOME: pages.EmployeeHome,
  EMPLOYEE_PERMIT_LIST: pages.EmployeePermitList,
  EMPLOYEE_OFFICE_ATTENDANCE_TRACKING_CAPACITY_MANAGEMENT: pages.EmployeeOfficeAttendanceTrackingCapacityManagement,
  EMPLOYEE_OFFICE_ATTENDANCE_TRACKING_DASHBOARD: pages.EmployeeOfficeAttendanceTrackingDashboard,
  EMPLOYEE_OFFICE_ATTENDANCE_TRACKING_EMPLOYEE_TRANSACTIONS: pages.EmployeeOfficeAttendanceTrackingEmployeeTransactions,
  // EMPLOYEE_OFFICE_ATTENDANCE_TRACKING_TREND: pages.EmployeeOfficeAttendanceTrackingTrend,
  EMPLOYEE_LOGS: pages.EmployeeLogs,
  MARKET_FRANCHISE_NEW: pages.MarketFranchiseNew,
  MARKET_FRANCHISE_LIST: pages.MarketFranchiseList,
  MARKET_FRANCHISE_DETAIL: pages.MarketFranchiseDetail,
  MARKET_FRANCHISE_USER_NEW: pages.MarketFranchiseUserNew,
  MARKET_FRANCHISE_USER_LIST: pages.MarketFranchiseUserList,
  MARKET_FRANCHISE_USER_DETAIL: pages.MarketFranchiseUserDetail,
  MARKET_FRANCHISE_USER_ROLE_NEW: pages.MarketFranchiseUserRoleNew,
  MARKET_FRANCHISE_USER_ROLE_LIST: pages.MarketFranchiseUserRoleList,
  MARKET_FRANCHISE_USER_ROLE_DETAIL: pages.MarketFranchiseUserRoleDetail,
  CONFIG_WORKING_HOURS: pages.ConfigWorkingHours,
  CONFIG_PEAK_HOURS: pages.ConfigPeakHours,
  POLYGON_MAP: pages.PolygonMap,
  SERVICE_AVAILABILITY_AREA_LIST: pages.ServiceAvailabilityAreaList,
  SERVICE_AVAILABILITY_AREA_DETAIL: pages.ServiceAvailabilityAreaDetail,
  SERVICE_AVAILABILITY_AREA_EDIT: pages.ServiceAvailabilityAreaEdit,
  SERVICE_AVAILABILITY_AREA_NEW: pages.ServiceAvailabilityAreaNew,
  FOOD_LIVE_MAP: pages.GetirFoodOrderLiveMap,
  GETIR_FOOD_ORDER_ACTIVE: pages.GetirFoodOrderActive,
  GETIR_FOOD_ORDER_FILTER: pages.GetirFoodOrderFilter,
  GETIR_FOOD_ORDER_DETAIL: pages.GetirFoodOrderDetail,
  GETIR_FOOD_ORDER_SUMMARY: pages.GetirFoodOrderSummary,
  GETIR_FOOD_BASKET_DETAIL: pages.GetirFoodBasketDetail,
  GETIR_FOOD_FINANCIAL_DASHBOARD_V2: pages.GetirFoodFinancialDashboardV2,
  GETIR_FOOD_FINANCIAL_DASHBOARD_V2_DETAIL: pages.GetirFoodFinancialDashboardV2Detail,
  GETIR_FOOD_MEAL_CARD_RECONCILIATION: pages.GetirFoodMealCardReconciliation,
  GETIR_FOOD_ERP_DATA_TRACKING_V2: pages.GetirFoodERPDataTrackingV2,
  GETIR_FOOD_RESTAURANT_EXTERNAL_TRANSACTION:
    pages.GetirFoodRestaurantExternalTransaction,
  GETIR_FOOD_RESTAURANT_PAYBACK_STATUS: pages.GetirFoodRestaurantPaybackStatus,
  GETIR_FOOD_FINANCIAL_CONFIGS: pages.GetirFoodFinancialConfigs,
  GETIR_FOOD_WITHHOLDING_TAX_REPORTS: pages.GetirFoodWithholdingTaxReports,
  GETIR_LOCALS_WITHHOLDING_TAX_REPORTS: pages.GetirLocalsWithholdingTaxReports,
  DTS_SUMMARY: pages.DtsSummary,
  DTS_RULE_LIST: pages.DtsRuleList,
  DTS_LOGS_UPDATE: pages.DtsLogsUpdate,
  DTS_RULE_NEW: pages.DtsRuleNew,
  DTS_RULE_DETAIL: pages.DtsRuleDetail,
  DTS_NEW: pages.DtsNew,
  DTS_DETAIL: pages.DtsDetail,
  DTS_FEEDBACK_SOURCE_SETTING_LIST: pages.DtsFeedbackSourceSettingList,
  DTS_FEEDBACK_SOURCE_SETTING_NEW: pages.DtsFeedbackSourceSettingNew,
  DTS_FEEDBACK_SOURCE_SETTING_DETAIL: pages.DtsFeedbackSourceSettingDetail,
  DTS_CATEGORY_SETTING_LIST: pages.DtsCategorySettingList,
  DTS_CATEGORY_SETTING_NEW: pages.DtsCategorySettingNew,
  DTS_CATEGORY_SETTING_DETAIL: pages.DtsCategorySettingDetail,
  DAILY_TRACKING_ORDER: pages.DailyTrackingOrder,
  DAILY_TRACKING_INSTANT: pages.DailyTrackingCourier,
  DAILY_TRACKING_INSTANT_OLD: () => {
    // Note: added _OLD routes so that old "path"s still accessible to users, old "path" routes will redirect to new "paths"
    // TODO: Remove these _OLD keyed routes after 3 months(starting day 2024-04-02) after users get used to them
    const Page = pages.GenericNavigator;
    return <Page to="/dailyTracking/courier" />;
  },
  PROFILE: pages.Profile,
  CONTENT_CREATION: pages.ContentCreation,
  CONTENT_UPLOAD_S3: pages.ContentUploadS3,
  PROMO_BADGES_LIST: pages.PromoBadgesList,
  PROMO_LIST: pages.PromoList,
  PROMO_DETAIL: pages.PromoDetail,
  PERSONAL_PROMO_GENERATOR: pages.PersonalPromoGenerator,
  EXCLUDE_PROMO_PRODUCTS: pages.ExcludePromoProducts,
  PERSONAL_PROMO_NEW: pages.PersonalPromoNew,
  PERSONAL_PROMO_LIST: pages.PersonalPromoList,
  PERSON_REQUEST_LIST: pages.PersonRequestList,
  PERSON_REQUEST_DETAIL: pages.PersonRequesDetail,
  FRANCHISE_BILL_MANAGEMENT_LIST: pages.FranchiseBillManagementList,
  FRANCHISE_BILL_MANAGEMENT_DETAIL: pages.FranchiseBillManagementDetail,
  FRANCHISE_EARNINGS_LIST: pages.FranchiseEarningsList,
  FRANCHISE_EARNINGS_UPLOAD: pages.FranchiseEarningsUpload,
  ARTISAN_ORDER_LIVE_MAP: pages.ArtisanOrderLiveMap,
  LIVE_MONITORING: pages.OrderGrowthMonitoring,
  LIVE_MONITORING_OLD: () => {
    const Page = pages.GenericNavigator;
    return <Page to="/orderGrowthMonitoring" />;
  },
  CLIENT_TARGETING: pages.ClientTargeting,
  ARTISAN_ORDER_ACTIVE: pages.ArtisanOrderActive,
  GETIR_LOCALS_RETURN_LIST: pages.Returns,
  STAFF_PLAN_PUBLICATION: pages.StaffPlanPublication,
  CUSTOMER_AGREEMENT: pages.CustomerAgreement,
  ARTISAN_ORDER_DETAIL: pages.ArtisanOrderDetail,
  GL_RUNNER_DETAIL: pages.GLRunnerDetail,
  GL_RUNNER_LIST: pages.GLRunnerList,
  GL_RUNNER_NEW: pages.GLRunnerNew,
  GL_ERP_DATA_TRACKING: pages.GLERPDataTracking,
  GL_SHOP_EXTERNAL_TRANSACTION: pages.GLShopExternalTransaction,
  GL_SHOP_PAYBACK_STATUS: pages.GLShopPaybackStatus,
  MARKET_ORDER_ANALYTICS_ACTIVE_ORDERS_FOR_MANAGEMENT:
    pages.ActiveOrdersForManagement,
  MARKET_ORDER_ANALYTICS_ACTIVE_ORDERS_FOR_OPERATION:
    pages.ActiveOrdersForOperation,
  MARKET_ORDER_ANALYTICS_ACTIVE_ORDERS_FOR_CUSTOMER_SERVICES:
    pages.ActiveOrdersForCustomerServices,
  MARKET_ORDER_ANALYTICS_ACTIVE_ORDERS_FOR_EXECUTIVE_DASHBOARD:
    pages.ActiveOrdersForExecutiveDashboard,
  MARKET_ORDER_ANALYTICS_ACTIVE_ORDERS_FOR_GROWTH: pages.ActiveOrdersForGrowth,
  REPORTS: pages.ReportsList,
  REPORTS_NEW: pages.ReportNew,
  REPORT_TYPES: pages.ReportTypeList,
  REPORT_TYPES_NEW: pages.ReportTypeNew,
  REPORT_TYPES_DETAIL: pages.ReportTypeDetail,
  REPORT_TAGS: pages.ReportTagsList,
  REPORT_TAGS_NEW: pages.ReportTagsNew,
  REPORT_TAGS_DETAIL: pages.ReportTagsDetail,
  DDS_OBJECTION_LIST: pages.DdsObjectionList,
  DDS_OBJECTION_DETAIL: pages.DdsObjectionDetail,
  PERSON_CANDIDATE_LIST: pages.PersonCandidateList,
  PERSON_CANDIDATE_DETAIL: pages.PersonCandidateDetail,
  CLIENT_LIST_DOUBLE_CHECKER: pages.ClientListDoubleChecker,
  GL_GROWTH_COMPARISON: pages.GLGrowthComparison,
  GL_RETURN_ALERT: pages.GLReturnAlert,
  GL_RETURN_ALERT_DETAIL: pages.GLReturnAlertDetail,
  COURIER_LIVE_MONITORING: pages.CourierLiveMonitoring,
  COURIER_LIVE_MONITORING_OLD: () => {
    const Page = pages.GenericNavigator;
    return <Page to="/courierStatusMonitoring" />;
  },
  OPERATIONS_LIVE_MONITORING: pages.OperationsLiveMonitoring,
  OPERATIONS_LIVE_MONITORING_OLD: () => {
    const Page = pages.GenericNavigator;
    return <Page to="/whOpsMonitoring" />;
  },
  GETIR_MARKET_LIVE_MAP: pages.GetirMarketLiveMap,
  EU_GROWTH_COMPARISON: pages.EUGrowthComparison,
  LOTTERY_NEW: pages.LotteryNew,
  LOTTERY_DETAIL: pages.LotteryDetail,
  FRANCHISE_REQUEST_LIST: pages.FranchiseRequestList,
  GETIR_DRIVE_DASHBOARD: pages.GetirDriveDashboard,
  GETIR_MARKET_DASHBOARD: pages.GetirMarketDashboard,
  GETIR_MARKET_COMMERCIAL_MONITORING: pages.GetirMarketCommercialMonitoring,
  GETIR_MARKET_COMMERCIAL_MONITORING_OLD: () => {
    const Page = pages.GenericNavigator;
    return <Page to="/getirMarket/commercialTrack" />;
  },
  DAILY_SUMMARY_GLOBAL: pages.DailySummaryGlobal,
  DAILY_SUMMARY_GLOBAL_OLD: () => {
    const Page = pages.GenericNavigator;
    return <Page to="/summaryQuick/global" shouldWait={false} />;
  },
  DAILY_SUMMARY_COUNTRY: pages.DailySummaryCountry,
  DAILY_SUMMARY_COUNTRY_OLD: () => {
    const Page = pages.GenericNavigator;
    return <Page to="/summaryQuick" shouldWait={false} />;
  },
  DAILY_SUMMARY_FOUNDERS_CUSTOM: pages.DailySummaryFoundersCustom,
  DAILY_SUMMARY_FOUNDERS_CUSTOM_OLD: () => {
    const Page = pages.GenericNavigator;
    return <Page to="/summaryQuick/foundersCustom" shouldWait={false} />;
  },
  WORKFORCE_CONTRACT_LIST: pages.PersonContractList,
  WORKFORCE_CONTRACT_DETAIL: pages.PersonContractDetail,
  WORKFORCE_EMPLOYEE_LEAVE_MANAGEMENT_LIST: pages.LeaveManagementList,
  WORKFORCE_EMPLOYEE_LEAVE_MANAGEMENT_DETAIL: pages.LeaveManagementDetail,
  WORKFORCE_EMPLOYEE_TIMESHEET_LOCK: pages.TimesheetLock,
  WORKFORCE_EMPLOYEE_TIMESHEET_LOGS: pages.TimesheetLogs,
  WORKFORCE_REPORTS: pages.WorkforceReports,
  WORKFORCE_SLOT_PLAN_MANAGEMENT: pages.SlotPlanManagement,
  GETIR_WATER_ANNOUNCEMENTS_LIST: pages.GetirWaterAnnouncementsList,
  GETIR_WATER_ANNOUNCEMENT_NEW: pages.GetirWaterAnnouncementNew,
  GETIR_WATER_ANNOUNCEMENT_DETAIL: pages.GetirWaterAnnouncementDetail,
  GETIR_WATER_COURIER_STATUS: pages.GetirWaterCourierStatus,
  GETIR_WATER_SLOT_CONFIG: pages.GetirWaterSlotConfig,
  GIVEAWAY_EVENT_DRAW_LIST: pages.GiveawayEventList,
  PUSH_NOTIFICATION_LIST: pages.PushNoticationList,
  PUSH_NOTIFICATION_NEW: pages.PushNoticationNew,
  PUSH_NOTIFICATION_DETAIL: pages.PushNoticationDetail,
  POPUP_LIST: pages.PopupList,
  POPUP_NEW: pages.PopupNew,
  POPUP_DETAIL: pages.PopupDetail,
  SMS_LIST: pages.SmsList,
  SMS_NEW: pages.SmsNew,
  SMS_DETAIL: pages.SmsDetail,
  EMAIL_LIST: pages.EmailList,
  EMAIL_NEW: pages.EmailNew,
  EMAIL_DETAIL: pages.EmailDetail,
  TRANSACTIONAL_NOTIFICATION_LIST: pages.TransactionalNotificationList,
  TRANSACTIONAL_NOTIFICATION_NEW: pages.TransactionalNotificationNew,
  TRANSACTIONAL_NOTIFICATION_DETAIL: pages.TransactionalNotificationDetail,
  TRANSACTIONAL_SMS_LIST: pages.TransactionalSmsList,
  TRANSACTIONAL_SMS_NEW: pages.TransactionalSmsNew,
  TRANSACTIONAL_SMS_DETAIL: pages.TransactionalSmsDetail,
  COMMUNICATION_HISTORY: pages.CommunicationHistory,
  ANNOUNCEMENT_LIST: pages.AnnouncementList,
  ANNOUNCEMENT_NEW: pages.AnnouncementNew,
  ANNOUNCEMENT_DETAIL: pages.AnnouncementDetail,
  NOTIFICATION_CENTER_LIST: pages.NotificationCenterList,
  NOTIFICATION_CENTER_NEW: pages.NotificationCenterNew,
  NOTIFICATION_CENTER_DETAIL: pages.NotificationCenterDetail,
  BANNER_LIST: pages.BannerList,
  BANNER_NEW: pages.BannerNew,
  BANNER_DETAIL: pages.BannerDetail,
  COMMUNICATION_SERVICE_CREDENTIALS_LIST:
    pages.CommunicationServiceCredentialsList,
  COMMUNICATION_SERVICE_CREDENTIALS_NEW:
    pages.CommunicationServiceCredentialsNew,
  COMMUNICATION_SERVICE_CREDENTIALS_DETAIL:
    pages.CommunicationServiceCredentialsDetail,
  TECHNOLOGY_COMPLIANCE_REPORT_HOME: pages.TechnologyComplianceReportHome,
  TECHNOLOGY_COMPLIANCE_REPORT_NODE_VERSIONS: pages.TechnologyComplianceReportNodeVersions,
  TECHNOLOGY_COMPLIANCE_REPORT_NODE_VULNERABILITIES: pages.TechnologyComplianceReportNodeVulnerabilities,
  TECHNOLOGY_COMPLIANCE_REPORT_NODE_VULNERABILITY_DETAIL: pages.TechnologyComplianceReportNodeVulnerabilityDetail,
  COMMUNICATION_CALLBACK_URLS_LIST: pages.CallbackUrlsList,
  COMMUNICATION_CALLBACK_URLS_NEW: pages.CallbackUrlsNew,
  COMMUNICATION_CALLBACK_URLS_DETAIL: pages.CallbackUrlsDetail,
  COMMUNICATION_BULK_SMS_LIST: pages.BulkSmsList,
  COMMUNICATION_BULK_SMS_NEW: pages.BulkSmsNew,
  COMMUNICATION_BULK_SMS_DETAIL: pages.BulkSmsDetail,
  WAREHOUSE_SEGMENT_LIST: pages.WarehouseSegmentList,
  WAREHOUSE_SEGMENT_DETAIL: pages.WarehouseSegmentDetail,
  WAREHOUSE_SEGMENT_NEW: pages.WarehouseSegmentNew,
  WAREHOUSE_SEGMENT_MATCHING_UPLOAD: pages.WarehouseSegmentMatchingUpload,
  GETIR_WATER_ACTIVE_ORDERS: pages.GetirWaterActiveOrders,
  GETIR_WATER_ORDER_FILTER: pages.GetirWaterOrderFilter,
  GETIR_WATER_VENDOR_FILTER: pages.GetirWaterVendorFilter,
  DYS_CONFIGS: pages.DYSConfigurations,
  BANK_RECONCILIATION_REPORT: pages.BankReconciliationReport,
  GETIR_WATER_CAMPAIGNS_LIST: pages.GetirWaterCampaignsList,
  GETIR_WATER_CAMPAIGN_NEW: pages.GetirWaterCampaignNew,
  GETIR_WATER_CAMPAIGN_DETAIL: pages.GetirWaterCampaignDetail,
  GETIR_WATER_ORDER_DETAIL: pages.GetirWaterOrderDetail,
  LOCATION_WRITE_OFF_NEW: pages.LocationWriteOffNew,
  LOCATION_WRITE_OFF_DETAIL: pages.LocationWriteOffDetail,
  LOCATION_WRITE_OFF_LIST: pages.LocationWriteOffList,
  PICKER_LIST: pages.PickerList,
  PICKER_DETAIL: pages.PickerDetail,
  FIELD_ANNOUNCEMENT_LIST: pages.FieldAnnouncementList,
  FIELD_ANNOUNCEMENT_DETAIL: pages.FieldAnnouncementDetail,
  FIELD_ANNOUNCEMENT_CREATE: pages.FieldAnnouncementCreate,
  FIELD_ANNOUNCEMENT_LIST_BY_WAREHOUSE: pages.FieldAnnouncementListByWarehouse,
  CLIENT_DETAIL: pages.ClientDetail,
  CLIENT_LIST: pages.ClientList,
  CLIENT_ATTACHMENTS_DETAIL: pages.ClientAttachmentsDetail,
  GETIR_MARKET_ORDER_RATINGS: pages.MarketOrderRatings,
  E2E_COURIER_PLAN_LIST: pages.CourierPlanList,
  E2E_COURIER_PLAN_NEW: pages.CourierPlanNew,
  E2E_COURIER_PLAN_PROCEED: pages.CourierPlanProceed,
  VEHICLE_CONSTRAINT_NEW: pages.VehicleConstraintNew,
  VEHICLE_CONSTRAINT_DETAIL: pages.VehicleConstraintDetail,
  VEHICLE_CONSTRAINT_LIST: pages.VehicleConstraintList,
  VEHICLE_LIST: pages.VehicleList,
  VEHICLE_NEW: pages.VehicleNew,
  VEHICLE_DETAIL: pages.VehicleDetail,
  TMS_DRIVER_LIST: pages.TmsDriverList,
  TMS_DRIVER_DETAIL: pages.TmsDriverDetail,
  TMS_LIST: pages.TmsList,
  TMS_NEW: pages.TmsNew,
  TMS_DETAIL: pages.TmsDetail,
  FRANCHISE_EQUIPMENT_LIST: pages.FranchiseEquipmentList,
  FRANCHISE_EQUIPMENT_NEW: pages.FranchiseEquipmentNew,
  FRANCHISE_EQUIPMENT_DETAIL: pages.FranchiseEquipmentDetail,
  INTERNAL_AUTHENTICATION_TEAM_DETAIL: pages.InternalAuthenticationTeamDetail,
  INTERNAL_AUTHENTICATION_TEAM_LIST: pages.InternalAuthenticationTeamList,
  INTERNAL_AUTHENTICATION_SERVICE_DETAIL: pages.InternalAuthenticationServiceDetail,
  INTERNAL_AUTHENTICATION_SERVICE_LIST: pages.InternalAuthenticationServiceList,
  KDS_QUESTION_LIST: pages.KdsQuestionList,
  KDS_QUESTION_NEW: pages.KdsQuestionNew,
  KDS_QUESTION_DETAIL: pages.KdsQuestionDetail,
  KDS_QUESTION_GROUP_LIST: pages.KdsQuestionGroupList,
  KDS_QUESTION_GROUP_NEW: pages.KdsQuestionGroupNew,
  KDS_QUESTION_GROUP_DETAIL: pages.KdsQuestionGroupDetail,
  KDS_SCORE_MAPPING: pages.KdsScoreMapping,
  KDS_AUDIT_FORM_TYPE_LIST: pages.KdsAuditFormTypeList,
  KDS_AUDIT_FORM_TYPE_DETAIL: pages.KdsAuditFormTypeDetail,
  KDS_AUDIT_FORM_TYPE_NEW: pages.KdsAuditFormTypeNew,
  STORE_AUDIT_LIST: pages.StoreAuditList,
  STORE_AUDIT_NEW: pages.StoreAuditNew,
  STORE_AUDIT_DETAIL: pages.StoreAuditDetail,
  GIS_HEATMAP: pages.GisHeatMap,
  GIS_BANNED_AREAS: pages.GisBannedAreas,
  GIS_LOCATION_INTELLIGENCE: pages.GisLocationIntelligence,
  GIS_WEATHER_MAP: pages.GisWeatherMap,
  GIS_ADDRESS_SEARCH: pages.GisAddressSearch,
  GIS_COUNTRY_CITY_MANAGEMENT: pages.GisCountryCityManagement,
  GROWTH_DASHBOARD: pages.GrowthDashboard,
  GROWTH_DASHBOARD_OLD: () => {
    const Page = pages.GenericNavigator;
    return <Page to="/growth/dailyTracking" />;
  },
  CONFIG_LIST: pages.ConfigList,
  CONFIG_LOG: pages.ConfigLog,
  CONFIG_NEW: pages.ConfigNew,
  PLANOGRAM_PRODUCTS: pages.PlanogramProductsList,
  PLANOGRAM_WAREHOUSES: pages.PlanogramWarehousesList,
  PLANOGRAM_WAREHOUSES_DETAIL: pages.PlanogramWarehousesDetail,
  PLANOGRAM_WAREHOUSE_CONVERT: pages.PlanogramWarehouseConvert,
  PLANOGRAM_PRODUCT_DETAIL: pages.PlanogramProductDetail,
  PLANOGRAM_PRODUCT_CONVERT: pages.PlanogramProductConvert,
  AB_TEST_LIST: pages.ABTestList,
  AB_TEST_NEW: pages.ABTestNew,
  AB_TEST_DETAIL: pages.ABTestDetail,
  CONFIG_MOBILE_ANIMATION: pages.ConfigMobileAnimation,
  MARKET_FRANCHISE_USER_ROLE_GROUP_LIST: pages.MarketFranchiseUserRoleGroupList,
  MARKET_FRANCHISE_USER_ROLE_GROUP_NEW: pages.MarketFranchiseUserRoleGroupNew,
  MARKET_FRANCHISE_USER_ROLE_GROUP_DETAIL:
    pages.MarketFranchiseUserRoleGroupDetail,
  GETIR_MARKET_ORDER_DETAIL: pages.MarketOrderDetail,
  PAYMENT_MERCHANT_LIST: pages.PaymentMerchantList,
  PAYMENT_MERCHANT_DETAIL: pages.PaymentMerchantDetail,
  PAYMENT_MERCHANT_NEW: pages.PaymentMerchantNew,
  GETIR_MARKET_FRAUD_SUSPICION_ORDERS: pages.FraudSuspicionOrders,
  LOCALS_LIVE_MONITORING_COURIER: pages.LocalsLiveMonitoringCourier,
  PERSON_NEW: pages.PersonNew,
  PERSON_LIST: pages.PersonList,
  PERSON_DETAIL: pages.PersonDetail,
  MISSING_PRODUCT_ORDERS: pages.MissingProductOrders,
  COURIER_LIST: pages.CourierList,
  COURIER_FEEDBACK_LIST: pages.CourierFeedbackList,
  DTS_PRIORITY_SETTING_LIST: pages.DtsPrioritySettingList,
  DTS_PRIORITY_SETTING_NEW: pages.DtsPrioritySettingNew,
  DTS_PRIORITY_SETTING_DETAIL: pages.DtsPrioritySettingDetail,
  STOCK_ORDER_VOLUME_AUTO: pages.StockOrderVolumeAuto,
  ON_OFF_PROMO_CONFIG: pages.OnOffPromoConfig,
  PAYMENT_TRANSACTION_LIST: pages.PaymentTransactionList,
  PAYMENT_TRANSACTION_DETAIL: pages.PaymentTransactionDetail,
  PAYMENT_EVENT_DETAIL: pages.PaymentEventDetail,
  STOCK_ORDER_AUTO: pages.StockOrderAuto,
  STOCK_TRANSFER_AUTO: pages.StockTransferAuto,
  ALGORITHM_CONFIG_LIST: pages.AlgorithmConfigList,
  ALGORITHM_CONFIG_DETAIL: pages.AlgorithmConfigDetail,
  ALGORITHM_MARKET_DOMAIN_CONFIG_LIST: pages.AlgorithmMarketConfigList,
  ALGORITHM_FOOD_DOMAIN_CONFIG_LIST: pages.AlgorithmFoodConfigList,
  ALGORITHM_VOYAGER_DOMAIN_CONFIG_LIST: pages.AlgorithmVoyagerConfigList,
  ALGORITHM_MARKET_DOMAIN_CONFIG_DETAIL: pages.AlgorithmMarketConfigDetail,
  ALGORITHM_FOOD_DOMAIN_CONFIG_DETAIL: pages.AlgorithmFoodConfigDetail,
  ALGORITHM_LOCALS_DOMAIN_CONFIG_DETAIL: pages.AlgorithmLocalsConfigDetail,
  ALGORITHM_LOCALS_DOMAIN_CONFIG_LIST: pages.AlgorithmLocalsConfigList,
  ALGORITHM_VOYAGER_DOMAIN_CONFIG_DETAIL: pages.AlgorithmVoyagerConfigDetail,
  DTS_LIST: pages.DtsList,
  SEGMENTED_CODE_GENERATOR: pages.SegmentedCodeGenerator,
  GETIR_MARKET_ORDER_FILTER: pages.OrderFilter,
  MARKET_BUSINESS_CONFIG: pages.MarketBusinessConfig,
  CUSTOMER_SATISFACTION_REQUEST_NEW: pages.CustomerSatisfactionRequestNew,
  TIP_PAYBACK_PAYOUT_SUMMARY_LIST: pages.TipPaybackPayoutSummaryList,
  TIP_PAYBACK_PAYOUT_SUMMARY_DETAILS: pages.TipPaybackPayoutSummaryDetails,
  TIP_PAYBACK_PAYOUT_SUMMARY_FAIL_REASONS: pages.TipPayoutSummaryFailReasons,
  THIRD_PARTY_COMPANY_LIST: pages.ThirdPartyCompanyList,
  THIRD_PARTY_COMPANY_NEW: pages.ThirdPartyCompanyNew,
  THIRD_PARTY_COMPANY_DETAIL: pages.ThirdPartyCompanyDetail,
  PRICING_TOOL: pages.PricingTool,
  HIGH_LEVEL_DYS: pages.HighLevelDys,
  SEGMENT_DETAIL: pages.SegmentDetail,
  SEGMENT_LIST: pages.SegmentList,
  SEGMENT_NEW: pages.SegmentNew,
  AUTO_SEGMENT_LIST: pages.AutoSegmentList,
  MARKET_INTELLIGENCE_PRICE_INDEX: pages.MarketIntelligencePriceIndex,
  MARKET_INTELLIGENCE_PRODUCTS: pages.MarketIntelligenceProducts,
  MARKET_INTELLIGENCE_PRICE_RECOMMENDATION: pages.MarketIntelligencePriceRecommendation,
  GETIR_PERSONAL_PROMO_DETAIL: pages.DiscountDetail,
  DISCOUNT_CODE_LIST: pages.DiscountCodeList,
  MARKET_GROWTH_OPERATIONS_TOOL_SETTINGS: pages.MarketAutoGrowthOperations,
  GETIR_MARKET_BAG_CONSTRAINTS: pages.BagConstraint,
  GETIR_MARKET_BAG_CONSTRAINT_NEW: pages.CreateBagConstraint,
  FRANCHISE_CONFIG_NEW: pages.FranchiseDynamicConfigNew,
  FRANCHISE_CONFIG_DETAIL: pages.FranchiseDynamicConfigDetail,
  FRANCHISE_CONFIG_LIST: pages.FranchiseDynamicConfigList,
  GETIR_MARKET_GROWTH_COMPARISON: pages.GetirMarketGrowthComparison,
  ORDER_COUNTER: pages.OrderCounter,
  ORDER_COUNTER_OLD: () => {
    const Page = pages.GenericNavigator;
    return <Page to="/count/orderCounter" />;
  },
  RECONCILIATION_DAILY_REPORT: pages.ReconciliationDailyReport,
  INSTALLMENT_COMMISSIONS: pages.InstallmentCommissions,
  GETIR_FINANCE_ORDER_DETAIL: pages.FinanceOrderDetail,
  GETIR_FINANCE_ORDER_FILTER: pages.FinanceOrderFilter,
  FRANCHISE_CONFIG_TYPE_LIST: pages.FranchiseConfigTypeList,
  FRANCHISE_CONFIG_TYPE_NEW: pages.FranchiseConfigTypeNew,
  FRANCHISE_CONFIG_TYPE_DETAIL: pages.FranchiseConfigTypeDetail,
  MARKET_FEES_BULK_UPLOAD: pages.bulkFeeUpload,
  MARKET_BASKET_DETAIL: pages.MarketBasketDetail,
  MARKET_BASKET_LIST: pages.MarketBasketList,
  MARKET_FEES_DETAILS: pages.MarketFeesDetail,
  GETIR_MARKET_BASKET_CONFIG_DETAILS: pages.BasketConfigDetails,
  PAYOUTS_FOR_DOMAINS: pages.PayoutsForDomains,
  PAYOUTS_TRANSACTIONS_FOR_DOMAINS: pages.PayoutsTransactionsForDomains,
  // TODO: Remove N11_ORDER_FILTER as well if permission checks are done on order filter page similar to active orders pages
  N11_ORDER_FILTER: pages.OrderFilter,
  BUSINESS_ALERTING_TOOL_ALERT_CONDITION_LIST: pages.BusinessAlertingToolAlertConditionList,
  BUSINESS_ALERTING_TOOL_INCIDENT_LIST: pages.BusinessAlertingToolIncidentList,
  BUSINESS_ALERTING_TOOL_ALERT_CONDITION_NEW: pages.BusinessAlertingToolAlertConditionNew,
  BUSINESS_ALERTING_TOOL_ALERT_CONDITION_DETAIL: pages.BusinessAlertingToolAlertConditionDetail,
  BUSINESS_ALERTING_TOOL_INCIDENT_DETAIL: pages.BusinessAlertingToolIncidentDetail,
  LMD_AND_OTHER_EXPENSES_UPLOAD: pages.LMDAndOtherExpensesUpload,
  FRANCHISE_LEGAL_LIST: pages.FranchiseLegalList,
  FRANCHISE_LEGAL_NEW: pages.FranchiseLegalNew,
  AB_TEST_V2_LIST: pages.ABTestV2List,
  AB_TEST_V2_NEW: pages.ABTestV2New,
  AB_TEST_V2_DETAIL: pages.ABTestV2Detail,
  FRANCHISE_LEGAL_DETAIL: pages.FranchiseLegalDetail,
  TOBB_GIB_REQUEST: pages.TobbGibRequest,
  BANK_RECONCILIATION_SUMMARY: pages.BankReconciliationSummary,
  MARKETING_APPROVAL_LIST: pages.MarketingApprovalList,
  MARKETING_APPROVAL_DETAIL: pages.MarketingApprovalDetail,
  LLM_AGENT_GUIDANCE_GENERATION: pages.AgentGuidanceGeneration,
  PAYMENT_FRAUD_CONTROL_LIST: pages.PaymentFraudControlList,
  SEGMENT_FRAUD_MANAGEMENT: pages.SegmentFraudManagement,
  COURIER_GAMIFICATION_TASK_LIST: pages.CourierGamificationTaskList,
  COURIER_GAMIFICATION_TASK_DETAIL: pages.CourierGamificationTaskDetail,
  COURIER_GAMIFICATION_TASK_SUMMARY: pages.CourierGamificationTaskSummary,
  COURIER_GAMIFICATION_TASK_CREATE: pages.CourierGamificationTaskCreate,
  MARKET_PRODUCT_CHAIN_MANAGEMENT_CONFIGURATION: pages.ChainManagementConfiguration,
  MARKET_PRODUCT_CHAIN_MANAGEMENT_CHAIN_LIST: pages.ChainManagementChainList,
  MARKET_PRODUCT_CHAIN_MANAGEMENT_CHAIN_DETAIL: pages.ChainManagementChainDetail,
  MARKET_PRODUCT_CHAIN_MANAGEMENT_WAREHOUSES_LIST: pages.ChainManagementWarehousesList,
  MARKET_PRODUCT_CHAIN_MANAGEMENT_WAREHOUSES_DETAIL: pages.ChainManagementWarehousesDetail,
  MARKET_PRODUCT_CHAIN_MANAGEMENT_PRODUCTS_LIST: pages.ChainManagementProductsList,
  MARKET_PRODUCT_CHAIN_MANAGEMENT_PRODUCTS_DETAIL: pages.ChainManagementProductsDetail,
  MARKET_PRODUCT_CHAIN_MANAGEMENT_DARK_STORE_DETAIL: pages.ChainManagementDarkStoreDetail,
  MARKET_PRODUCT_CHAIN_MANAGEMENT_MATCH_SUPPLIERS: pages.ChainManagementMatchSuppliers,
  MARKET_PRODUCT_CHAIN_MANAGEMENT_MATCH_CW_DS: pages.ChainManagementMatchDarkStore,
  COMMERCE_INTELLIGENCE_PRODUCT_MATCHING: pages.CommerceIntelligenceProductMatching,
  COMMERCE_INTELLIGENCE_SMART_PRICING_INDEX: pages.CommerceIntelligenceSmartPricingIndex,
};

export type ROUTE_COMPONENTS_TYPE = typeof ROUTE_COMPONENTS;

export default ROUTE_COMPONENTS;
