import { createActions } from 'reduxsauce';

import { REDUX_KEY } from '@shared/shared/constants';

export const { Types, Creators } = createActions({
  importMarketProductWastePricesRequest: { loadedFile: null },
  importMarketProductWastePricesSuccess: { data: [] },
  importMarketProductWastePricesFailure: { error: null },
  importMarketProductBuyingPricesRequest: { loadedFile: null },
  importMarketProductBuyingPricesSuccess: { data: [] },
  importMarketProductBuyingPricesFailure: { error: null },
  exportMarketProductSupplierBuyingPricesRequest: {},
  exportMarketProductSupplierBuyingPricesSuccess: { data: [] },
  exportMarketProductSupplierBuyingPricesFailure: { error: null },
  exportMarketProductWastePricesRequest: {},
  exportMarketProductWastePricesSuccess: { data: [] },
  exportMarketProductWastePricesFailure: { error: null },
  getMarketProductsPriceListRequest: {
    limit: 10,
    offset: undefined,
    productIds: undefined,
    domainTypes: undefined,
    warehouseIds: undefined,
    startDate: undefined,
    endDate: undefined,
    pricingTypes: undefined,
    priceOption: 0,
  },
  getMarketProductsPriceListSuccess: { data: [] },
  getMarketProductsPriceListFailure: { error: null },
  getActiveMarketProductsRequest: {
    limit: 10,
    offset: 0,
    queryText: null,
    filterOptions: { fullName: true },
  },
  getActiveMarketProductsSuccess: { data: [] },
  getActiveMarketProductsFailure: { error: null },
  updateMarketProductPriceRequest: { body: null, page: undefined },
  updateMarketProductPriceSuccess: { data: [] },
  updateMarketProductPriceFailure: { error: null },
  updateMarketProductDiscountedPriceRequest: { body: null, page: undefined },
  updateMarketProductDiscountedPriceSuccess: { data: [] },
  updateMarketProductDiscountedPriceFailure: { error: null },
  getMarketProductPriceDetailRequest: { id: undefined },
  getMarketProductPriceDetailSuccess: { data: [] },
  getMarketProductPriceDetailFailure: { error: null },
  getMarketProductDiscountedPriceDetailRequest: { discountedPriceId: undefined },
  getMarketProductDiscountedPriceDetailSuccess: { data: [] },
  getMarketProductDiscountedPriceDetailFailure: { error: null },
  deletePriceRequest: { priceId: undefined, formValues: {} },
  deletePriceSuccess: { data: [] },
  deletePriceFailure: { error: null },
  deleteDiscountedPriceRequest: { discountedPriceId: undefined, formValues: {} },
  deleteDiscountedPriceSuccess: { data: [] },
  deleteDiscountedPriceFailure: { error: null },
  exportPricingsRequest: {},
  exportDiscountedPricingsRequest: {},
  importPricingsRequest: { loadedFile: null, priceType: undefined },
  initPage: null,
  destroyPage: null,
}, { prefix: `${REDUX_KEY.MARKET_PRODUCT.PRICING}_` });
