import { createUseStyles } from 'react-jss';

import {
  borderRadius,
  colors,
  fontSizes,
  fontWeights,
  spacing,
  transitions,
  zIndex,
} from '@app/pages/CommerceIntelligence/styleVariables';

export default createUseStyles({
  wrapper: {
    position: 'fixed',
    bottom: spacing.lg,
    left: 0,
    right: 0,
    display: 'flex',
    justifyContent: 'center',
    pointerEvents: 'none',
    zIndex: zIndex.dropdown,
  },
  container: {
    backgroundColor: colors.backgroundWhite,
    boxShadow: '0px 8px 24px -4px rgba(28, 50, 79, 0.19), 0px 2px 6px -1px rgba(28, 55, 90, 0.08)',
    padding: `${spacing.sm} ${spacing.md}`,
    borderRadius: borderRadius.lg,
    minWidth: '320px',
    maxWidth: '90%',
    backdropFilter: 'blur(8px)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    willChange: 'transform, opacity',
    pointerEvents: 'auto',
    opacity: 0,
    transform: 'translate3d(0, 20%, 0)',
    transition: 'transform 0.2s ease-out, opacity 0.2s ease-out',
  },
  visible: {
    opacity: 1,
    transform: 'translate3d(0, 0, 0)',
  },
  content: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: spacing.md,
    position: 'relative',
    paddingRight: '44px',
  },
  info: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.xs,
    minWidth: '240px',
  },
  count: {
    fontSize: fontSizes.sm,
    fontWeight: fontWeights.semibold,
    color: colors.textDark,
  },
  text: {
    fontSize: fontSizes.sm,
    color: colors.inputBlack,
  },
  actions: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.sm,
  },
  deleteButton: {
    height: '32px',
    padding: `0 ${spacing.sd}`,
    fontSize: fontSizes.sm,
    fontWeight: fontWeights.semibold,
    borderRadius: borderRadius.md,
    border: 'none',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: transitions.fast,
    minWidth: '72px',
    gap: spacing.xs,
    background: colors.badgeGray,
    color: colors.gray,
    '& img': {
      width: 16,
      height: 16,
    },
    '&:hover': {
      background: colors.badgeGray,
      color: colors.gray,
    },
  },
  matchButton: {
    height: '32px',
    padding: `0 ${spacing.sd}`,
    fontSize: fontSizes.sm,
    fontWeight: fontWeights.semibold,
    borderRadius: borderRadius.md,
    border: 'none',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: transitions.fast,
    minWidth: '72px',
    gap: spacing.xs,
    background: colors.lightGreen,
    color: colors.successGreen,
    '& img': {
      width: 16,
      height: 16,
    },
    '&:hover': {
      background: colors.lightGreen,
      color: colors.successGreen,
    },
  },
  closeButton: {
    position: 'absolute',
    right: spacing.sm,
    top: '50%',
    transform: 'translateY(-50%)',
    cursor: 'pointer',
    color: colors.textLight,
    fontSize: spacing.md,
    opacity: 0.8,
    transition: transitions.fast,
    padding: spacing.xs,
    '& img': {
      width: 20,
      height: 20,
    },
    '&:hover': {
      opacity: 1,
      color: colors.textDark,
    },
  },
});
