export const bulkCreateOrUpdateTranslationKeys = {
  title: {
    error: 'TITLE_FAILED_BULK_CREATION_RESULT',
    info: 'TITLE_PENDING_BULK_CREATION_RESULT',
    success: 'TITLE_SUCCESSFUL_BULK_CREATION_RESULT',
  },
  subtitle: {
    error: 'SUB_TITLE_FAILED_BULK_CREATION_RESULT',
    info: 'SUB_TITLE_PENDING_BULK_CREATION_RESULT',
    success: 'SUB_TITLE_SUCCESSFUL_BULK_CREATION_RESULT',
  },
  extra: {
    root: 'EXTERNAL_CUSTOMER_SERVICES_BULK_CREATION_RESULT_VIEWER_ALERT',
    button: 'BULK_CREATION_RESULT_VIEWER_UNMATCHED_MAIL_ADDRESSES_BUTTON',
    message: 'PROBLEM_WITH_BULK_CREATION_RESULT',
    label: 'SHOW_PROBLEMATIC_MAIL_ADDRESSES',
  },
  extraForGws: {
    root: 'EXTERNAL_CUSTOMER_SERVICES_BULK_CREATION_RESULT_VIEWER_ALERT_FOR_GWS',
    button: 'BULK_CREATION_RESULT_VIEWER_UNMATCHED_MAIL_ADDRESSES_BUTTON_FOR_GWS',
    message: 'PROBLEM_WITH_BULK_CREATION_RESULT_FOR_GWS',
    label: 'SHOW_PROBLEMATIC_MAIL_ADDRESSES_FOR_GWS',
  },
};

export const bulkInactivationTranslationKeys = {
  title: {
    error: 'TITLE_FAILED_BULK_INACTIVATION_RESULT',
    info: 'TITLE_PENDING_BULK_INACTIVATION_RESULT',
    success: 'TITLE_SUCCESSFUL_BULK_INACTIVATION_RESULT',
  },
  subtitle: {
    error: 'SUB_TITLE_FAILED_BULK_INACTIVATION_RESULT',
    info: 'SUB_TITLE_PENDING_BULK_INACTIVATION_RESULT',
    success: 'SUB_TITLE_SUCCESSFUL_BULK_INACTIVATION_RESULT',
  },
  extra: {
    root: 'EXTERNAL_CUSTOMER_SERVICES_BULK_INACTIVATION_RESULT_VIEWER_ALERT',
    button: 'BULK_INACTIVATION_RESULT_VIEWER_UNMATCHED_MAIL_ADDRESSES_BUTTON',
    message: 'PROBLEM_WITH_BULK_INACTIVATION_RESULT',
    label: 'SHOW_PROBLEMATIC_MAIL_ADDRESSES',
  },
  extraForGws: {
    root: 'EXTERNAL_CUSTOMER_SERVICES_BULK_INACTIVATION_RESULT_VIEWER_ALERT_FOR_GWS',
    button: 'BULK_INACTIVATION_RESULT_VIEWER_UNMATCHED_MAIL_ADDRESSES_BUTTON_FOR_GWS',
    message: 'PROBLEM_WITH_BULK_INACTIVATION_RESULT_FOR_GWS',
    label: 'SHOW_PROBLEMATIC_MAIL_ADDRESSES_FOR_GWS',
  },
};
