export const mockedConfigValueData = {
  data: {
    id: 5,
    type: 'warehouse_group',
    alias: '6214f3adf9aaea6020c01aea',
    key: '123',
    namespace: 'food',
    parentId: 3,
    value: {
      CHECKOUT_TO_DELIVER_DURATION_LIMIT: 1310,
      ORDER_WAITING_DURATION: 120,
      TASK_LIMIT: 8,
      POOL_COURIER_TASK_LIMIT: 4,
    },
    isCustom: false,
    customConfigs: [],
    parent: {
      id: 3,
      type: 'city',
      alias: 'Ankara',
      key: '5dd84c500000010003000000',
      namespace: 'food',
      parentId: 2,
      value: {},
      isCustom: false,
      customConfigs: [],
      parent: {
        id: 2,
        type: 'country',
        alias: 'Türkiye',
        key: '55999ad00000010000000000',
        namespace: 'food',
        parentId: 1,
        value: {},
        isCustom: false,
        customConfigs: [],
        parent: {
          id: 1,
          type: 'global',
          alias: 'GLOBAL',
          key: 'global',
          namespace: 'food',
          parentId: null,
          value: {
            OSRM_SCALE_FACTORS: {
              200: 1.314,
              400: 1.314,
            },
            CHECKOUT_TO_DELIVER_DURATION_LIMIT: 1300,
            ORDER_WAITING_DURATION: 100,
            TASK_LIMIT: 5,
            POOL_COURIER_TASK_LIMIT: 5,
            PRODUCT_COUNT_LIMIT: 25,
            BASKET_VALUE_LIMIT: 1200,
          },
          isCustom: false,
          customConfigs: [],
          parent: null,
        },
      },
    },
  },
};

export const mockedInheritedConfigValueData = {
  CHECKOUT_TO_DELIVER_DURATION_LIMIT: 1310,
  ORDER_WAITING_DURATION: 120,
  TASK_LIMIT: 8,
  POOL_COURIER_TASK_LIMIT: 4,
};

export const mockedDomainConfigSettingsData = {
  namespace: 'food',
  units: [
    {
      name: 'warehouse_group',
      config_set: [
        {
          field: 'CHECKOUT_TO_DELIVER_DURATION_LIMIT',
          type: 'integer',
          min: 1200,
          max: 3600,
          step: null,
          options: null,
        },
        {
          field: 'ORDER_WAITING_DURATION',
          type: 'integer',
          min: 0,
          max: 3000,
          step: null,
          options: null,
        },
        {
          field: 'TASK_LIMIT',
          type: 'slider',
          min: 1,
          max: 10,
          step: 1,
          options: null,
        },
        {
          field: 'POOL_COURIER_TASK_LIMIT',
          type: 'slider',
          min: 1,
          max: 10,
          step: 1,
          options: null,
        },
      ],
    },
  ],
  default_config_set: [
    {
      field: 'CHECKOUT_TO_DELIVER_DURATION_LIMIT',
      type: 'integer',
      min: 1200,
      max: 3600,
      step: null,
      options: null,
    },
    {
      field: 'ORDER_WAITING_DURATION',
      type: 'integer',
      min: 0,
      max: 3000,
      step: null,
      options: null,
    },
    {
      field: 'TASK_LIMIT',
      type: 'slider',
      min: 1,
      max: 10,
      step: 1,
      options: null,
    },
    {
      field: 'POOL_COURIER_TASK_LIMIT',
      type: 'slider',
      min: 1,
      max: 10,
      step: 1,
      options: null,
    },
    {
      field: 'PRODUCT_COUNT_LIMIT',
      type: 'integer',
      min: 1,
      max: 30,
      step: null,
      options: null,
    },
    {
      field: 'BASKET_VALUE_LIMIT',
      type: 'integer',
      min: 100,
      max: 3000,
      step: null,
      options: null,
    },
  ],
};
