import { createUseStyles } from 'react-jss';

export default createUseStyles({
  timeline: { fontSize: '14px' },
  tlHeader: {
    display: 'block',
    width: '12em',
    marginLeft: '2px',
    textAlign: 'center',
  },
  tlWrapBprimary: {
    display: 'block',
    padding: '15px 0 15px 20px',
    marginLeft: '6em',
    borderColor: '#5D3EBD',
    borderStyle: 'solid',
    borderWidth: '0 0 0 4px',
    '&:before': {
      content: ' ',
      position: 'absolute',
      bottom: 0,
      left: 50,
      width: '100%',
      height: '1rem',
      display: 'block',
      background: '#ffffff',
    },
  },
  tlDate: {
    position: 'relative',
    top: '10px',
    display: 'block',
    float: 'left',
    width: '4.5em',
    marginLeft: '-8.5em',
    textAlign: 'right',
    color: '#58666e',
  },
  tlContent: {
    border: '1px solid #dee5e7',
    paddingRight: '15px',
    paddingLeft: '15px',
    position: 'relative',
    display: 'inline-block',
    paddingTop: '10px',
    paddingBottom: '10px',
    backgroundColor: '#ffffff',
    maxWidth: '100%',
    overflowWrap: 'break-word',
  },
  tlContentBasket: {
    paddingRight: '15px',
    paddingLeft: '15px',
    position: 'relative',
    display: 'inline-block',
    paddingTop: '10px',
    paddingBottom: '10px',
    backgroundColor: '#ffffff',
  },
  textPrimary: {
    color: '#5D3EBC',
    fontWeight: '700',
    marginLeft: '3px',
    marginRight: '3px',
  },
  panelFooter: {
    backgroundColor: '#ffffff',
    borderRadius: '0 0 2px 2px',
    padding: '10px 20px',
    borderTop: '1px solid #edf1f2',
  },
  textAlignLeft: { textAlign: 'left' },
  ltItem: {
    display: 'block',
    '&:before': {
      display: 'table',
      content: ' ',
    },
  },
  ltWrap: {
    display: 'block',
    padding: '15px 0 15px 20px',
    marginLeft: '6em',
    borderColor: '#5D3EBD',
    borderStyle: 'solid',
    borderWidth: '0 0 0 4px',
  },
  orderButton: {
    backgroundColor: '#5D3EBD',
    fontSize: '12px',
    color: '#FFD10D',
    fontWeight: '700',
  },
  panelBody: {
    marginRight: '-15px',
    marginLeft: '-15px',
  },
  timelineIcon: {
    position: 'absolute',
    left: '-29px',
    background: '#ffffff',
    borderRadius: '100%',
    top: '50%',
    marginTop: '-5px',
  },
  muted: { color: '#697488', opacity: 0.6 },
  seperator: {
    width: '100%',
    borderTop: '1px solid #edf1f2',
  },
  dash: { '&::after': { content: '" - "' } },
  cancelTitleText: { color: 'red', marginBottom: 8, display: 'block' },
  cancelMessage: { textAlign: 'left' },
  gfBasket: {
    marginRight: '-15px',
    marginLeft: '-15px',
    borderTop: '1px solid #edf1f2',
    marginTop: '10px',
    padding: '10px 20px 10px 0',
  },
  agtMessage: { marginBottom: '0' },
  agtStatus: {
    listStyle: 'none',
    marginTop: 10,
    '& span': {
      color: '#5D3EBD',
      fontWeight: 600,
    },
  },
});
