export const COLLAPSE_LIST = [
  {
    index: 1,
    collapseName: 'Traffic KVI',
    categoryRole: 'Traffic',
    kviSegmentation: 'KVI',
    ruleName: 'traffic-kvi',
  },
  {
    index: 2,
    collapseName: 'Traffic FG',
    categoryRole: 'Traffic',
    kviSegmentation: 'FG',
    ruleName: 'traffic-fg',
  },
  {
    index: 3,
    collapseName: 'Traffic BG',
    categoryRole: 'Traffic',
    kviSegmentation: 'BG',
    ruleName: 'traffic-bg',
  },
  {
    index: 4,
    collapseName: 'Power KVI',
    categoryRole: 'Power',
    kviSegmentation: 'KVI',
    ruleName: 'power-kvi',
  },
  {
    index: 5,
    collapseName: 'Power FG',
    categoryRole: 'Power',
    kviSegmentation: 'FG',
    ruleName: 'power-fg',
  },
  {
    index: 6,
    collapseName: 'Power BG',
    categoryRole: 'Power',
    kviSegmentation: 'BG',
    ruleName: 'power-bg',
  },
  {
    index: 7,
    collapseName: 'Essential KVI',
    categoryRole: 'Essential',
    kviSegmentation: 'KVI',
    ruleName: 'essential-kvi',
  },
  {
    index: 8,
    collapseName: 'Essential FG',
    categoryRole: 'Essential',
    kviSegmentation: 'FG',
    ruleName: 'essential-fg',
  },
  {
    index: 9,
    collapseName: 'Essential BG',
    categoryRole: 'Essential',
    kviSegmentation: 'BG',
    ruleName: 'essential-bg',
  },
  {
    index: 10,
    collapseName: 'Basket Filler KVI',
    categoryRole: 'Basket Filler',
    kviSegmentation: 'KVI',
    ruleName: 'basket filler-kvi',
  },
  {
    index: 11,
    collapseName: 'Basket Filler FG',
    categoryRole: 'Basket Filler',
    kviSegmentation: 'FG',
    ruleName: 'basket filler-fg',
  },
  {
    index: 12,
    collapseName: 'Basket Filler BG',
    categoryRole: 'Basket Filler',
    kviSegmentation: 'BG',
    ruleName: 'basket filler-bg',
  },
];
