import { createUseStyles } from 'react-jss';

export default createUseStyles({
  returnTableWrapper: {
    '& .ant-table.ant-table-small .ant-table-thead > tr > th': {
      backgroundColor: 'rgba(26, 57, 96, 0.1)',
      color: 'rgba(27, 43, 65, 0.69)',
      fontSize: '14px',
      fontWeight: 700,
      lineHeight: '18px',
      height: 48,
    },
    '& .ant-table.ant-table-small .ant-table-thead > tr > th:before': { content: 'none !important' },
    '& .ant-table.ant-table-small .ant-table-tbody > tr > td': { height: 88 },
    '& .ant-table.ant-table-small .ant-table-footer': {
      backgroundColor: 'rgba(25, 59, 103, 0.025)',
      height: 48,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'flex-end',
    },
  },
  nameWrapper: {
    display: 'inline-flex',
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    marginLeft: '12px',
  },
  productImg: {
    border: '1px solid rgba(25, 59, 103, 0.05)',
    borderRadius: 4,
    width: 64,
    height: 64,
    '& img': { maxWidth: 'unset !important' },
  },
  tableFooter: {
    lineHeight: '24px !important',
    fontWeight: '400 !important',
    fontFamily: 'Open Sans',
    fontSize: 14,
    color: '#182739 !important',
    display: 'flex',
    alignItems: 'flex-end',
    boxSizing: 'border-box',
  },
  tableText: {
    fontFamily: 'Open Sans',
    fontWeight: 700,
    fontSize: 14,
    lineHeight: '18px',
  },
  productName: {
    color: 'rgba(24, 39, 57, 0.94)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    display: '-webkit-box',
    WebkitLineClamp: '2',
    WebkitBoxOrient: 'vertical',
  },
  productPrice: {
    color: '#5D3EBC',
    lineHeight: '24px',
  },
  productQuantity: {
    background:
      'linear-gradient(0deg, rgba(255, 62, 81, 0.2), rgba(255, 62, 81, 0.2)), #FFFFFF',
    borderRadius: 6,
    width: 27,
    height: 30,
    color: '#7C1E1E',
    fontFamily: 'Open Sans',
    fontSize: 12,
    lineHeight: '16px',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  returnPrice: {
    color: '#182739F0',
    lineHeight: '24px',
    width: 75,
    boxSizing: 'border-box',
  },
  returnText: {
    color: 'rgba(24, 39, 57, 0.94)',
    lineHeight: '24px',
    fontWeight: 400,
  },
  mr24: { marginRight: 24 },
  mt32: { marginTop: 24 },
  returnBtn: {
    width: 98,
    height: 56,
    borderRadius: 8,
    padding: '15px 24px',
    lineHeight: '20px',
    fontSize: 14,
    fontWeight: 700,
    fontFamily: 'Open Sans',
    color: 'white',

    '&-approve': { backgroundColor: '#5D3EBC' },
    '&-reject': { backgroundColor: '#E23737' },
    '&-cancel': {
      backgroundColor: 'rgba(25, 59, 103, 0.05)',
      color: '#5D3EBC',
    },
  },
  confirmText: {
    fontFamily: 'Open Sans',
    fontSize: 16,
    lineHeight: '22px',
  },
  tableTitle: { fontWeight: 600 },
  tabs: { '& .ant-tabs-tab-btn': { fontSize: 14 } },
});
