import { createUseStyles } from 'react-jss';

import { primary } from '@shared/components/GUI/styles/guiThemes';
import { colors } from '@app/pages/MarketProductChainManagement/styleVariables';

export default createUseStyles({

  body: {
    padding: '16px 24px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    background: colors.backgroundWhite,
    borderRadius: '8px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
    border: `1px solid ${colors.borderGray}`,
    boxSizing: 'border-box',
    width: '100%',
  },
  titleWrapper: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  backLink: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '32px',
    height: '32px',
    borderRadius: '8px',
    background: `${colors.purple}10`,
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    transition: 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
    '&:hover': {
      background: `${colors.purple}20`,
      transform: 'translateX(-2px)',
    },
    '&:active': { transform: 'translateX(0)' },
    '&:focus': {
      outline: 'none',
      boxShadow: `0 0 0 2px ${colors.purple}30`,
    },
  },
  backIcon: {
    width: '20px',
    height: '20px',
    transition: 'transform 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
  },
  title: {
    color: primary,
    fontSize: '22px',
    fontWeight: 700,
  },
  buttonWrapper: {
    display: 'flex',
    gap: '10px',
    '& .ant-btn': {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: '80px',
      height: '40px',
      padding: '8px 16px',
      fontSize: '14px',
      fontWeight: 600,
      lineHeight: '20px',
      borderRadius: '8px',
      gap: '6px',
      transition: 'all 0.2s ease',
      '&.ant-btn-primary': {
        backgroundColor: colors.purple,
        borderColor: colors.purple,
        color: '#ffffff',
        '&:hover': {
          backgroundColor: `${colors.purple}90`,
          borderColor: `${colors.purple}90`,
        },
      },
      '&.ant-btn-default': {
        backgroundColor: 'transparent',
        borderColor: colors.borderGray,
        color: colors.purple,
        '&:hover': {
          backgroundColor: `${colors.purple}08`,
          borderColor: colors.purple,
          color: colors.purple,
        },
      },
      '& span': {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '6px',
      },
      '& img': {
        width: '16px',
        height: '16px',
        display: 'inline-block',
      },
      '& .anticon': {
        display: 'inline-flex',
        alignItems: 'center',
      },
    },
    '& .ant-row': {
      boxShadow: 'none',
      height: 'auto',
      color: colors.purple,
      fontWeight: '700',
      fontSize: '14px',
      lineHeight: '20px',
      cursor: 'pointer',
    },
  },
  button: {
    display: 'flex',
    gap: '8px',
    minWidth: '80px',
    height: '40px',
    alignItems: 'center',
    justifyContent: 'center',
  },
  menu: {
    padding: '8px',
    minWidth: '280px',
    background: colors.backgroundWhite,
    borderRadius: '12px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.15)',
    border: `1px solid ${colors.borderGray}`,
    '& .ant-menu-item': {
      padding: '6px 12px',
      margin: '2px 0',
      borderRadius: '8px',
      cursor: 'pointer',
      transition: 'all 0.2s ease',
      '&:hover': {
        background: `${colors.purple}08`,
        '& .antIcon': {
          color: colors.purple,
          transform: 'scale(1.1)',
        },
        '& .menuText': {
          color: colors.purple,
          transform: 'translateX(4px)',
        },
      },
    },
  },
  menuItemContent: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    height: '36px',
  },
  antIcon: {
    fontSize: '16px',
    color: colors.iconGray,
    transition: 'all 0.2s ease',
    flexShrink: 0,
  },
  menuText: {
    flex: 1,
    fontSize: '13px',
    fontWeight: 600,
    letterSpacing: '0.1px',
    color: colors.textGray,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    transition: 'all 0.2s ease',
  },
  linkButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 12px',
    fontSize: '14px',
    fontWeight: 600,
    color: colors.purple,
    backgroundColor: 'transparent',
    borderRadius: '6px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    border: `1px solid ${colors.borderGray}`,
    outline: 'none',
    '& img': {
      width: '16px',
      height: '16px',
      opacity: 0.7,
      transition: 'opacity 0.2s ease',
    },
    '&:hover': {
      backgroundColor: `${colors.purple}08`,
      color: colors.purple,
      '& img': { opacity: 1 },
    },
    '&:focus': {
      backgroundColor: `${colors.purple}08`,
      boxShadow: `0 0 0 2px ${colors.purple}20`,
      '& img': { opacity: 1 },
    },
  },
  emojiAnimation: {
    animation: '$popAndSpin 1s cubic-bezier(0.4, 0, 0.2, 1)',
    transformOrigin: 'center',
  },
  '@keyframes popAndSpin': {
    '0%': { transform: 'scale(1) rotate(0deg)' },
    '20%': { transform: 'scale(1.3) rotate(-10deg)' },
    '40%': { transform: 'scale(1.2) rotate(10deg)' },
    '60%': { transform: 'scale(1.1) rotate(-5deg)' },
    '80%': { transform: 'scale(1.05) rotate(5deg)' },
    '100%': { transform: 'scale(1) rotate(0deg)' },
  },
  csvImporter: {
    '& .ant-modal-content': {
      borderRadius: '6px',
      padding: '20px',
    },
  },
});
