export const getExampleCsv = ({ externalCS, isSaleforceSSORequired, isCountryRequired = true }) => ({
  ...(isCountryRequired ? { country: 'TR / UK' } : undefined),
  fullName: 'Name Surname',
  email: `name.surname@${externalCS}.getir.com`,
  user: 'name.surname',
  firstName: 'name',
  lastName: 'surname',
  recoveryEmail: 'name.surname@getir.com',
  recoveryPhone: '+902133333636',
  mobilePhone: '+902133333636',
  displayName: 'name.s',
  outsourceFirm: externalCS,
  positionGeography: 'Turkey',
  payrollCountry: 'TR / UK',
  businessUnit: 'GetirFood / GetirMore',
  subDepartment1: 'Customer Services',
  title: 'Chat Advisor',
  profileName: 'Chat Team',
  teamLeadEmail: `team.lead@${externalCS}.getir.com`,
  secondManagerEmail: `second.manager@${externalCS}.getir.com`,
  permissionSet: 'Chat (Food)',
  ...(isSaleforceSSORequired ? { saleforceSSO: 'true / false' } : undefined),
});
